### ISSUE TITLE
Add folder for historical snapshots of CSVs

### ISSUE THREAD

**Issue by DGaffney** [nytimes/covid-19-data#1]
A huge subset of people that will be interested in working with this data will likely want to be able to look at the ways in which the cases develop over time in different locales. Right now, the only way to to this with the structure of the repository as it is would be to look at the git history, plucking out the changes at each commit. This would be overly cumbersome for everyone but the most technically sophisticated folks. Please add a folder within which you will add the files appended with an ISO datetime so that people will be able to quickly rip through the folder to generate dynamic representations of the data.

**Comment by j-f1** [comment]
It looks like all the historical data is in the CSV.

**Comment by DGaffney** [comment]
> It looks like all the historical data is in the CSV.

Phew. Should have looked closer through the readme first. It may be helpful to make it clearer about how to construct time-series examples from the dataset - my first quick glance at the readme had me assuming it was just cumulative to current point in time - if other people think the same they may wander off looking for something else during a quick scan for the best dynamic data without realizing it's right here.
