### ISSUE TITLE
Missing observation for Kansas City, Missouri

### ISSUE THREAD

**Issue by jlgallup** [nytimes/covid-19-data#101]
There is a missing observation for 2020-03-24 for Kansas City, Missouri. 2020-03-23 has 18 cases and 2020-03-25 has 50 cases.

Thanks for the great work by the NYT data team and Albert Sun for prompt and judicious replies.

**Comment by albertsun** [comment]
@jlgallup thanks for pointing this out, the row has been added. There were 30 cases on 3/24.
