### ISSUE TITLE
Created State and County Timeline Graphs

### ISSUE THREAD

**Issue by eventamplify** [nytimes/covid-19-data#104]
I see there may be others with similar idea but I created a simple visualization page for the state and county data to view the "curve" for each:  https://eventamplify.com/covid-curve

**Comment by waknapp** [comment]
Nice. Just finished the same.  Yours is prettier.  Thanks.

**Comment by pcardout** [comment]
Well done eventamplify -- I also made a visualizer using log-log plots to try to show when various states are starting to get off the exponential growth curve.    I started with NY, CA and WA and added NM (where I live).    You can see that WA is beginning to get control ... the other three states -- not yet.  
My code and plots are here:  
http://kestrel.nmt.edu/~rsonnenf/corona/corona_control.html
