### ISSUE TITLE
Joplin, Missouri

### ISSUE THREAD

**Issue by jlgallup** [nytimes/covid-19-data#106]
The Readme file says that the data for the city of Joplin, Missouri is reported separately from two counties which it spans, Jasper County and Newton County. However, I can't find any entry for Joplin, Missouri in the us-counties.csv file.

**Comment by jkua** [comment]
Joplin is a city, not a county, so there won't be an entry for Joplin. As you mention, the cases from Joplin show up in the entries for Jasper County and Newton County.

**Comment by jlgallup** [comment]
In that case, it should be removed from the section "Geographical Exceptions" in the README.md file. There it says, "Joplin, Mo.: Joplin is reported separately from Jasper and Newton Counties."

**Comment by jkua** [comment]
Sorry, I retract my statement. For some reason when I read the README, I interpreted it as saying that Joplin's cases were included in the counts from Jasper County and Newton County. Now I see it's saying the opposite. My apologies.

**Comment by albertsun** [comment]
Thanks folks - you're right. There is 1 case in Joplin, MO right now that we are including with Jasper County. We may continue to do that and will either add a Joplin row or update the README to clarify the situation.

**Comment by jlgallup** [comment]
Albert, Thanks again for the careful attention to these details. It makes the data much more valuable and useable.

I for one vote that you don't create an additional exception in Joplin to the County, State organization of the data. Most people using this data will have to create a special coding section just to deal with the Joplin exception, or explain at length in their help files. Distributing the data from Kansas City to its constituent counties (imperfectly) took me more than an hour of coding.

I know people think in terms of cities - a good solution to this is to merge in the County - Metropolitan Area (CBSA) crosswalk from the U.S. Census, but this requires a clean county dataset or kludges to correct each of the problems.

John

**Comment by albertsun** [comment]
@jlgallup in today's update we've removed Joplin from the geographic exceptions list and will be publishing their cases as part of the county totals.
