### ISSUE TITLE
add stay at home/shelter in place data?

### ISSUE THREAD

**Issue by mwaugh0328** [nytimes/covid-19-data#107]
From this map

https://www.nytimes.com/interactive/2020/us/coronavirus-stay-at-home-order.html

**Comment by MichaelKelleher** [comment]
I agree that creating and updating a county level list and/or a state level list of effective dates for shelter-in-place orders would be helpful in analyzing any effects of such an order.

From:
https://www.finra.org/rules-guidance/key-topics/covid-19/shelter-in-place
and
https://www.nytimes.com/interactive/2020/us/coronavirus-stay-at-home-order.html

I created this US state list of shelter_dates using the heuristic of selecting the date when at least half of a state's population was covered by such an order (I will update if I create this at the county level):
state,shelter_order_date
"Alaska","2020-03-22"
"Arizona","2020-03-23"
"California","2020-03-19"
"Colorado","2020-03-26"
"Connecticut","2020-03-24"
"Delaware","2020-03-24"
"District of Columbia","2020-03-24"
"Hawaii","2020-03-25"
"Idaho","2020-03-25"
"Illinois","2020-03-22"
"Indiana","2020-03-25"
"Kansas","2020-03-26"
"Kentucky","2020-03-27"
"Louisiana","2020-03-24"
"Maine","2020-03-26"
"Maryland","2020-03-26"
"Massachusetts","2020-03-24"
"Michigan","2020-03-24"
"Minnesota","2020-03-28"
"Montana","2020-03-28"
"Nevada ","2020-03-20"
"New Hampshire","2020-03-28"
"New Jersey","2020-03-22"
"New Mexico","2020-03-24"
"New York","2020-03-23"
"Ohio","2020-03-24"
"Oregon","2020-03-23"
"Pennsylvania","2020-03-19"
"Puerto Rico","2020-03-15"
"Texas","2020-03-25"
"Vermont","2020-03-26"
"Virginia","2020-03-23"
"Washington","2020-03-23"
"West Virginia","2020-03-25"
"Wisconsin","2020-03-25"
"Alabama","2020-03-27"
"Virginia","2020-03-30"
"Maryland","2020-03-30"
"North Carolina","2020-03-30"
"Rhode Island","2020-03-28"
"Tennessee","2020-04-01"
"Oklahoma","2020-03-29"
"Florida","2020-03-31"
"Georgia","2020-03-25"

**Comment by wescrockett** [comment]
> I agree that creating and updating a county level list and/or a state level list of effective dates for shelter-in-place orders would be helpful in analyzing any effects of such an order.

Thanks for this idea you two. Though I didn't add it directly in the data set that I am using for my project, I added it as a reference line (dealing with CA only).

**Comment by Fredo-XVII** [comment]
Yes, this is data that we are talking about, it would be great to have a source of truth. 

Thank you!!

**Comment by VictorRobellini** [comment]
Agreed! Having this data included would be a great data point.  Perferably county by county as well as state wide.

**Comment by brandomr** [comment]
I've been working on tracking policy interventions (such as shelter in place orders) at the city and county level. You can take a look here: [https://github.com/jataware/covid-19-data](https://github.com/jataware/covid-19-data).

These datasets are by no means complete or 100% accurate, but if it's of interest I could try to merge them with the NYT data.

**Comment by beetes-juice** [comment]
You can hit an esri service for this data:
https://services.arcgis.com/pGfbNJoYypmNq86F/ArcGIS/rest/services/COVID19_Public_Health_Status_by_County/FeatureServer/0

Field local_health_emg is a domain:
```
{
"name": "Declared Public Health Emergency",
"code": "Yellow"
},
{
"name": "Govt Directed Social Distancing",
"code": "Orange"
},
{
"name": "Govt Ordered Community Quarantine",
"code": "Red"
}
```

This is included in their Covid19 HUB site: https://coronavirus-disasterresponse.hub.arcgis.com/

**Comment by luca-martial** [comment]
Have any of you come across a curated, ready dataset for this at the county level? The ESRI service seems to be the best lead so far

**Comment by tiffehr** [comment]
I added this thread to our Additive Data collection on our Project board, along side other requests & discussions about augmenting our dataset with other needs.  Feel free to keep discussing, however!
