### ISSUE TITLE
Improper Death Count

### ISSUE THREAD

**Issue by wescrockett** [nytimes/covid-19-data#109]
Hello,

In a dashboard I built using this data, for relevant counties to my geographic area, it shows Tulare California with 3 deaths as of 3/31 (implying that 2 new deaths occurred in the county.) I have been unable to confirm two additional deaths and other county sources corroborate that there is still only 1 death reported in the county.

Thank you.

**Comment by bhbrantley** [comment]
On this note, file shows Chambers (AL) with a death count of 4 for 3/30 and then 3 for 3/31. But according to the [AL DPH](https://alpublichealth.maps.arcgis.com/apps/opsdashboard/index.html#/6d2771faa9da4a2786a509d82c8cf0f7) there are 4 confirmed deaths.

**Comment by albertsun** [comment]
@wescrockett thanks for pointing that out, you are correct and we will be amending Tulare to 1 death on 3/31 in the next data release.

@bhbrantley we are looking into this. Alabama has switched to reporting both "reported deaths" and "deaths from illness". I suspect what happened is sometime yesterday when they switched Chambers had reported deaths and 3 deaths from illness, before today confirming the 4th death from illness. We're currently being conservative and using the lower number but will look into how best to handle this.

**Comment by wescrockett** [comment]
Thanks @albertsun . I'm sure maintaining this thing is a bear!

**Comment by bhbrantley** [comment]
Thanks @albertsun -- this is tremendous work.

**Comment by wescrockett** [comment]
Closing issue
