### ISSUE TITLE
Is the data on sex and age available anywhere?

### ISSUE THREAD

**Issue by macrophyte** [nytimes/covid-19-data#11]

**Comment by Mantissa-23** [comment]
Also interested in this.

**Comment by CBG-63** [comment]
This will likely not be available, as it may violate HIPAA laws. While some of these have been temporarily waived for doctors to treat patients in other states, etc., it likely doesn't apply to the public.

**Comment by girlinamovie** [comment]
Agree with CBG-63

**Comment by sareeneng** [comment]
HIPAA identifiers - https://www.luc.edu/its/aboutits/itspoliciesguidelines/hipaainformation/18hipaaidentifiers/

Sex is not an identifier
Exact age is not an identifier **if <= 89 years old**. These patients could be all binned together as >89.
It cannot be linked to county-level data, but can be linked to state-level data.

Patient-level data is highly important. Right now we have no ways of risk-stratification (speaking as a PICU physician in New York), and all the data available is focused towards epidemiology which doesn't help us take care of patients.

**Comment by thoughtafter** [comment]
No one is releasing individual case data as far as I am aware. The issue for age is that states are binning ages differently so it's not very usable data.

**Comment by wesg52** [comment]
It would be worth joining this with census data by county to identify high risk clusters i.e. those counties with higher than average elderly populations.

**Comment by timriffe** [comment]
> No one is releasing individual case data as far as I am aware. The issue for age is that states are binning ages differently so it's not very usable data.

Can you give some pointers to states publishing cases and deaths in binned ages?

**Comment by thoughtafter** [comment]
> > No one is releasing individual case data as far as I am aware. The issue for age is that states are binning ages differently so it's not very usable data.
> 
> Can you give some pointers to states publishing cases and deaths in binned ages?

OR: https://govstatus.egov.com/OR-OHA-COVID-19
WA: https://www.doh.wa.gov/Emergencies/Coronavirus

**Comment by mymil** [comment]
There are line lists of individual cases with demographic information (as much as available) being compiled here: https://github.com/beoutbreakprepared/nCoV2019

**Comment by paoist** [comment]
> OR:
https://govstatus.egov.com/OR-OHA-COVID-19
> WA: https://www.doh.wa.gov/Emergencies/Coronavirus

Interesting, both have more female than male deaths. 

Seems important that aggregated gender statistics are made available nation wide.

**Comment by amcdavid** [comment]
I am also very interested in finding age-stratified data, especially of deaths. It seems almost negligent to compare incidence of death between time or place without this. The idea of joining to census data is interesting, and would be most appropriate if infection is independent of age. We know this isn't true on a micro level because nursing homes, etc, result in inhomogeneity. Any other ideas?

**Comment by paoist** [comment]
This link is a fairly updated and comprehensive with source references for most countries but since it’s in most cases are just aggregated data it’s far from as useful as it could be.  Some of the official sources listed provide time series in the native languages but only aggregated data on age, gender and preconditions which is frustrating. 
https://www.worldometers.info/coronavirus/#countries <https://www.worldometers.info/coronavirus/#countries>
One can only hope the WHO or someone in a centralised place get better data but if that’s the case they really ought to share much more publicly.

**Comment by Otteholt** [comment]
Thoughtafter states 
> No one is releasing individual case data as far as I am aware. The issue for age is that states are binning ages differently so it's not very usable data.

As a workaround to this issue it seems like the average age of a person’s assigned bin could be determined and then utilized.   These values could be obtained for patients in all states. 

Detailed age resolution would be lost, but the bins used in each state are similar enough to provide valuable insights. 

Could this be provided NYT?

**Comment by Dawnteach** [comment]
> No description provided.

Hi, not sure if this will help but Georgia is reporting actual age data, sex and even underlying conditions in general. Maybe that will clear the way for you to do the same in New York. Thinking of everyone since I have a daughter who lives in Manhattan! 

https://dph.georgia.gov/covid-19-daily-status-report

**Comment by timriffe** [comment]
Santa Clara county gives a dashboard with 10-year age groups for cases and deaths:
[https://www.sccgov.org/sites/phd/DiseaseInformation/novel-coronavirus/Pages/dashboard.aspx](https://www.sccgov.org/sites/phd/DiseaseInformation/novel-coronavirus/Pages/dashboard.aspx)

**Comment by shoffer** [comment]
It always fascinated me when people toss around a law or regulation like HIPAA or PIA and do not ever bother to read or understand it.
Thankfully, some of you do and correct for this.

The data is worthless without certain attributes.

Age and underlying conditions are critical to understanding what is going on. Without at least age, the reports are a meaningless list that does nothing but allow for panic or complacency. It fosters the extremes.
Here are some other attributes that are critical.
Duration of illness
Severity of symptoms
List of symptoms
Recovery
Recurrence number( per person)

Most reports are generalities that provide no value...just a map of giant red like blood as if the world is ending.

Glad some areas are being more transparent about it such as the references Santa Clara( I have not validated.

Rant over.
Stay well everyone.

**Comment by timriffe** [comment]
Ohio now posting data with sex, age groups, and even some other variables, very nice.
https://coronavirus.ohio.gov/wps/portal/gov/covid-19/home/dashboard

**Comment by brendantodaro** [comment]
I compiled some of the available state-level data (FL, GA, MI, NYC, OH, OR, WA) on death rates by age here: https://github.com/brendantodaro/US-COVID-deaths-by-age/blob/master/README.md

**Comment by shoffer** [comment]
Thanks for this information.

Steve

**Comment by shoffer** [comment]
Well done! Will be looking at this later today.

Steve

**Comment by shoffer** [comment]
Just another question: Has anyone done any side-by-side comparison of the details fo cases and deaths, with comprable demographic and associated data for SARS, Swine Flu, Bird Flu or any Seasonal Flu? Without context and comparison, it is hard to see/make judgement on where this pandemic lines up in contrast to others
