### ISSUE TITLE
JSON DataSet

### ISSUE THREAD

**Issue by cradaydg** [nytimes/covid-19-data#112]
It would be nice to have a JSON dataset available.

**Comment by BenRussert** [comment]
What's stopping you from converting to whatever you need?

**Comment by cradaydg** [comment]
Nothing in particular. JSON is the the most current format that exists ( I think, these things change so often.) and JQuery and other data access methods expect it.

csv has it's own issues, particularly with commas in text fields and the csv does not have texts delimiters.

As an aside, instructions to automate the download, if it is possible, would be nice too.

 It might be fun to build something to generate the JSON and publish it to your GitHub repo, but I'd need to know a schedule to try to automate it.
Helpful hints would be welcome too.

As another aside - I'm job hunting.


________________________________

**Comment by cipriancraciun** [comment]
I have built a derived dataset based on the NY Times data (and ECDC and JHU for that matter), that besides being available also as JSON, I have also augmented with various metrics:
* https://github.com/cipriancraciun/covid19-datasets

**Comment by cradaydg** [comment]
Thank you.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
