### ISSUE TITLE
Missing death data for King County, WA?

### ISSUE THREAD

**Issue by ndewind84** [nytimes/covid-19-data#113]
There were no new deaths reported in King County, WA on 3/31. Is that correct? It seems to be in conflict with numbers reported here:
https://www.kingcounty.gov/depts/health/communicable-diseases/disease-control/novel-coronavirus/data-dashboard.aspx

**Comment by albertsun** [comment]
Hi @ndewind84, around the end of March, Washington state seemed to have some blips in their case reporting system where some data might have been missed. We will investigate and see what historical revisions to make.
