### ISSUE TITLE
Knox County, TN `death_0` missing

### ISSUE THREAD

**Issue by kcavagnolo** [nytimes/covid-19-data#114]
The [first reported death](https://www.wbir.com/article/news/health/coronavirus/knox-co-confirms-its-first-coronavirus-related-death/51-9b2e0b8e-66cd-47be-ad5a-c70fc27b8cb2) in Knox County, Tennessee occurred on Mar 30 and is not reflected in the data. This is `death_0` and critical in modeling.

https://github.com/nytimes/covid-19-data/blob/baeca648aefa9694a3fc8f2b3bd3f797937aa1c5/us-counties.csv#L21394

**Comment by albertsun** [comment]
Hi, thanks for pointing this out.

We've gone back and looked at our original sources and in the next release we are going to amend the date at which Knox County first reports 1 death to be 3/31.

We know that that news article reports 3/30, but to be consistent with other areas, we're going to stay with 3/31 as the date, which is when we first heard about it from the health department authorities.

**Comment by kcavagnolo** [comment]
Awesome. Thanks. I appreciate having a hand-curated data set.
