### ISSUE TITLE
New Jersey with no county

### ISSUE THREAD

**Issue by chestnut2002** [nytimes/covid-19-data#115]
In the county file there are a lot of New Jersey cases with a null county. Any idea which county or counties they belong to?

I’m rolling this data up to the DMA (aggregation of counties) and would like to know where to put them. Guessing it is either New York City or Philadelphia.

Thanks,
John

**Comment by albertsun** [comment]
Hi @chestnut2002 unfortunately we don't know, that is the nature of the data. There are many cases in New Jersey that they have not yet ascertained which county the case should be assigned to.

**Comment by beaglesparks** [comment]
In NJ counties you have an unknown county. it is Warren County
