### ISSUE TITLE
Apr 1 Utah data is duplicate of March 31

### ISSUE THREAD

**Issue by mimconsulting** [nytimes/covid-19-data#116]
the case counts for all Utah counties are identical from March 31 to April 1st. Total cases (887) should be 1,012. Seems like a data error. 

By the way, thank you so much for providing this service!

![image](https://user-images.githubusercontent.com/33879754/78290071-65583f80-74e0-11ea-8d21-d4a40737e8fe.png)

**Comment by albertsun** [comment]
Hi @mimconsulting thanks for pointing this out. In today's release we updated the numbers for Utah for 4/1.

**Comment by aaronj84** [comment]
Thank you!!
