### ISSUE TITLE
Duplicate values for Travis County, TX

### ISSUE THREAD

**Issue by bjmarsh** [nytimes/covid-19-data#118]
There are a few instances in the data for Travis County, TX in which the same case counts
are repeated for multiple days, either replacing the correct values (from [Travis Co. dashboard](https://austin.maps.arcgis.com/apps/opsdashboard/index.html#/39e4f8d4acb0433baae6d15a931fa984)) or delaying them so that the values are 1 day offset (e.g. NYTimes has a count of 244 for 4/1, but this was the value on 3/31. It should be 305 for 4/1).

| Date | NYTimes | Travis Dashboard |
|--|--|--|
| 3/22 | 79 | 91 |
| 3/23 | 79 | 100 |
| 3/24 | 79 | 113 |
| 3/25 | 119 | 119 |
| 3/26 | 137 | 137 |
| 3/27 | 160 | 160 |
| 3/28 | 160 | 179 |
| 3/29 | 179 | 200 |
| 3/30 | 206 | 206 |
| 3/31 | 206 | 244 |
| 4/1 | 244 | 305 |

**Comment by albertsun** [comment]
Thanks, we're going to dive deeper into this, but for the moment I believe the difference is we are using numbers for Travis County reported through the Texas Department of State Health Services, and they may be somewhat behind Travis County in case counts. Our data would also be somewhat different, based on when cases are announced to the public, not the test report date to the department.
