### ISSUE TITLE
Issues in Virginia?

### ISSUE THREAD

**Issue by anon303030** [nytimes/covid-19-data#119]
I believe "James city" in Virginia should be listed as "James City" — since it is actually "James City County" (like "Charles City County") rather than an independent city.

https://en.wikipedia.org/wiki/James_City_County%2C_Virginia

Also Richmond County seems to have duplicated the 33 cases from Richmond city for April 1?

**Comment by albertsun** [comment]
You are correct. Teaches me not to trust my own assumptions about geographic names.

We will fix both of these in the next release.

**Comment by anon303030** [comment]
Virginia isn't easy for any of us, haha.

As others have said, many thanks for providing this data!
