### ISSUE TITLE
Make the data open ...

### ISSUE THREAD

**Issue by rufuspollock** [nytimes/covid-19-data#122]
Make the data open as per https://opendefintion.org/ - ie. free to use, build on and share *for anyone*.

In this situation it seems odd to add a non-commercial restriction - which restricts reuse (and would prevent reuse on e.g. wikipedia). The main value for NYT is on the nytimes website surely. No issue in sharing the raw data freely.

**Comment by lxgoodies2** [comment]
Thanks for publishing this detailed data, great source !! keep up the good work

**Comment by rufuspollock** [comment]
@albertsun any thoughts - you could just tweak to an attribution license of attribution share alike if really needed.

**Comment by albertsun** [comment]
@rufuspollock we're discussing internally, but not going to make any change at this moment. If you have a specific commercial use case you would like to pursue with the data please do email us at covid-data@nytimes.com. Many already have and we have been pretty broad about granting permission.
