### ISSUE TITLE
Kentucky revised its 4/1 numbers.  Not shown here.

### ISSUE THREAD

**Issue by chriskoch99** [nytimes/covid-19-data#127]
In his 4/2 press conference, KY governor Andy Beshear announced that they were revising the 4/1 case number down from 682 to 670, as they had identified some duplicates and people who were from out of state but tested in KY.

The NYT database has not been updated to reflect this change.

**Comment by albertsun** [comment]
Thanks @chriskoch99, at this point we're generally not changing historical data here for instances where a state or county has revised the numbers they've announced in the past. We're considering starting to do that but want to do it in a systematic manner if and when we do.
