### ISSUE TITLE
Source data for County/FIPS list?

### ISSUE THREAD

**Issue by bramscher** [nytimes/covid-19-data#128]
First, thanks for doing this!

Wondering if there is a reference source of every county with state and fips out there, or are you building that list as you get reports?  I would like to load that as a reference table as I assume there is not data for every county in the US if it has not had any reporting?  I think there is over 3000 county with fips out there, but can not find a good reference source.

Thank you!

**Comment by j-p-c** [comment]
https://www.census.gov/programs-surveys/popest/data/tables.html

https://www2.census.gov/programs-surveys/popest/datasets/2010-2019/counties/totals/co-est2019-alldata.csv

**Comment by bramscher** [comment]
Thanks JPC!   I am guessing somehow you need to coming state and county numbers into a string to create the county number like 010165 for Hale County Alabama from State code of 01 and county code 065.

**Comment by j-p-c** [comment]
Yeah, if SUMLEV is 040 then you have a state, and STATE is the FIPS. If SUMLEV is 050 then you have a county: just concatenate STATE and COUNTY to make the FIPS. For Hale County, Alabama, you get 01065.

**Comment by bramscher** [comment]
Thanks JPC!

**Comment by fullersr** [comment]
I have been using tl_us_2019_county shapefile.  Layout is as follows (after importing into geopandas)

-  0   STATEFP   3233 non-null   object  
-  1   COUNTYFP  3233 non-null   object  
-  2   COUNTYNS  3233 non-null   object  
-  3   GEOID     3233 non-null   object  
-  4   NAME      3233 non-null   object  
-  5   NAMELSAD  3233 non-null   object  
-  6   LSAD      3233 non-null   object  
-  7   CLASSFP   3233 non-null   object  
-  8   MTFCC     3233 non-null   object  
-  9   CSAFP     1255 non-null   object  
-  10  CBSAFP    1915 non-null   object  
-  11  METDIVFP  110 non-null    object  
-  12  FUNCSTAT  3233 non-null   object  
-  13  ALAND     3233 non-null   int64   
-  14  AWATER    3233 non-null   int64   
-  15  INTPTLAT  3233 non-null   object  
-  16  INTPTLON  3233 non-null   object  
-  17  geometry  3233 non-null   geometry

GEOID corresponds to the 5-char fips
I am probably going to use the METDIVFP to conflate areas such as NYC

A description of the layout can be found here
[TigerLine Shapefiles Tech Definition](https://www2.census.gov/geo/pdfs/maps-data/data/tiger/tgrshp2015/TGRSHP2015_TechDoc_Ch3.pdf)

**Comment by Gerardwx** [comment]
https://transition.fcc.gov/oet/info/maps/census/fips/fips.txt

**Comment by tiffehr** [comment]
@Gerardwx We'll be correcting this link in our documentation soon.  Thanks for the heads up.
