### ISSUE TITLE
Tompkins County NY Data Question

### ISSUE THREAD

**Issue by bdarfler** [nytimes/covid-19-data#130]
Thank you for this wonderful data source. I appreciate that the attempt here is to add value beyond simply tracking local county departments of health so there may be a simple answer to this. If that is the case I hope this isn't a waste of time.

However, the discrepancy I'm seeing between the Tompkins County data in this set and the DoH data from the county are so drastically different I felt compelled to bring it up in case there is an underlying issue.

As a resident and elected official in the county, I've been keeping a very close eye on the numbers and I believe I would have heard of any information that would lead to these discrepancies but I can't think of any.

To point out one example on 3/27 the data set for Tompkins County reads as follows

`2020-03-27,Tompkins,New York,36109,26,0`

However, on the same day, the count from the County DoH was nearly double at 48 positive cases. (source: https://twitter.com/TompkinsHealth/status/1243640578576916480/).

At first, I thought that maybe this was a date boundary issue, however, the County DoH number for 3/26 was 32 positive cases, still considerably higher (source: https://twitter.com/TompkinsHealth/status/1243268319286824969/)

This is made all the more curious by the fact that, as of yesterday, the count in this data had suddenly aligned with the County DoH data. On 4/2 both sources agreed on 87 positive cases

`2020-04-02,Tompkins,New York,36109,87,0`

https://twitter.com/TompkinsHealth/status/1245820115398070277

This is confusing since it seems highly unlikely that the count would be adjusted down and then back up by the NYT team (for good and valid reasons) in such a way that it precisely aligns back to the County DoH number.

Thank you for your time in reviewing this. I hope it has been helpful to the project and the quality of the data.

Note: the County DoH can be found at https://tompkinscountyny.gov/health but I have found that their Twitter feed is better for historical data digging.

Note: there was some confusion in the data around March 30/31st. This was covered by a local paper and more details can be found here - https://ithacavoice.com/2020/03/covid-19-confirmed-cases-rise-to-76-while-28-have-recovered/

**Comment by albertsun** [comment]
Hi @bdarfler ,

Thanks for the detailed issue. We're going to look into the case counts here.

Our ultimate source for this data is indeed that Tompkins County DoH site. It's possible there are some delays or missed updates in how we are recording and updating that data however.
