### ISSUE TITLE
Wrote python/numpy/pandas code to create filtered log-log plots to detect slope changes caused by social distancing

### ISSUE THREAD

**Issue by pcardout** [nytimes/covid-19-data#131]
**Way to go, New York Times and young Mr. Sun!**  
Inspired by Aatish Bhatia's methodology (and unable to really make out detail in his cramped plots)  I also made a visualizer using log-log plots to try to show when various states are starting to get off the exponential growth curve. I started with NY, CA and WA and added NM (where I live). **You can see that WA is beginning to get control ... the other three states -- not yet.**
My code and plots are here:
http://kestrel.nmt.edu/~rsonnenf/corona/corona_control.html

**Comment by tiffehr** [comment]
Moving this to Examples, in our Project board.  Thank you!
