### ISSUE TITLE
Whole Country Totals

### ISSUE THREAD

**Issue by dagostinelli** [nytimes/covid-19-data#132]
Request: Please provide a "whole USA by day" already-summed dataset.

**Comment by cberthiaume** [comment]
I thumbs downed this because this is the kind of basic work you should be able to do yourself but, I'm here and can copy/paste from my own work:

```python
import pandas as pd

df_state = pd.read_csv('../../covid-19-data/us-states.csv')
df_state.date = pd.to_datetime(df_state.date)
# group by date
df = df_state.groupby(['date']).sum()
```

**Comment by dagostinelli** [comment]
:laughing: I just got **datasplained**!

**Comment by albertsun** [comment]
We have now added a national level file us.csv

It is also true that it is the same as summing the state file.
