### ISSUE TITLE
Guam reporting significantly more cases

### ISSUE THREAD

**Issue by contextofislands** [nytimes/covid-19-data#133]
The data from this repository is reporting Guam's cases as almost double what their [Joint Information Center is reporting](https://ghs.guam.gov/coronavirus-covid-19), but Guam is not listed in the geographic exceptions.

**Comment by albertsun** [comment]
Hi @contextofislands, thanks for pointing this out. We are counting 130 cases among sailors on the USS Theodore Roosevelt among the total for Guam. You're right that we should list this in the geographic exceptions and we will update that today.

**Comment by aubreymoore** [comment]
albertsun, Thank you very much for including confirmed cases of USS Theodore Roosevelt in the Guam data. The Johns Hopkins data do not currently include these cases, which account for more than half of Guam's case load. I am using these data for simple modeling and will rewrite my software to pick up the raw data from this repo. See https://aubreymoore.github.io/Guam-Corona-Virus-Data/ and https://medium.com/@aubreymoore2013/fitting-curves-to-covid-19-data-from-guam-and-hawaii-4c6c116645c4.
