### ISSUE TITLE
Bexar county April 1, 2020 is listed as 0. 

### ISSUE THREAD

**Issue by gelfondjal** [nytimes/covid-19-data#136]
Local data disagrees.

**Comment by albertsun** [comment]
Hi @gelfondjal — our Bexar, Texas data has 207 cases and 9 deaths for April 1.

```
2020-04-01,Bexar,Texas,48029,207,9
```

**Comment by gelfondjal** [comment]
Hi @albertsun 
There are 0 new cases on that date:
23595 2020-03-31  Bexar Texas 48029   207      9
25810 2020-04-01  Bexar Texas 48029   207      9

**Comment by albertsun** [comment]
@gelfondjal I see what you mean now. We've investigated and pushed up new and improved data for Bexar county for that time period.
