### ISSUE TITLE
column for county population, please

### ISSUE THREAD

**Issue by charlesporter** [nytimes/covid-19-data#137]
would help many of us who's only tool is a spreadsheet if some more of the basic location values were included - most important is population. someone else mentioned recovered cases .   anyway: thanks for posting this data

**Comment by j-p-c** [comment]
For simpler analyses like this, feel free to download from [johncostella.com/covid-19/data/latest.csv](http://johncostella.com/covid-19/data/latest.csv) which includes estimated 2019 populations from the Census Bureau.

**Comment by charlesporter** [comment]
perfect. thanks.
