### ISSUE TITLE
so what? 

### ISSUE THREAD

**Issue by apheliar** [nytimes/covid-19-data#14]
why are you comparing counties? the population is different and smaller counties may gain false confidence due to low number of cases when it's simply because there's fewer people. 

a right and fair comparison would be #of cases per 1,000 people.

**Comment by codypiersall** [comment]
I think—and someone will correct me if I'm wrong—that this is how the data is presented in the upstream data providers (the state governments).

Someone could *use* the data provided by the NYT and some census data or something to create the data you're talking about.

**Comment by adrianhamins** [comment]
https://www.census.gov/data/datasets/time-series/demo/popest/2010s-counties-total.html

Merge the county dataset by FIPS to get population ratios.

**Comment by aaraney** [comment]
An issue template and wiki including questions like yours really needs to be made here in the near future.

**Comment by apheliar** [comment]
thanks for that. 

so can you tell me what i'm supposed to gain from this chart without having to inject assumptions of my own to make it mean something?

isn't it like comparing the number of cyclists in a populated city to the number of cyclists in a small town? of course there's more in a city. 

the only conclusion is its because there's more people. circling back to - so what?

**Comment by deto** [comment]
Not with NYT, but my interpretation is that this is a *resource* to use in other types of analyses.  You're not supposed to just look at this data and 'get' anything.  It's not even a plot, just a table.

A county by county plot would just reflect population and be meaningless.  So don't make that plot. Easy.

This is a tool for people to use, likely in conjunction with other data, to answer questions.

**Comment by apheliar** [comment]
ahh, yea i was referring to this:
![screen_shot_2020-03-27_at_12 16 01-1](https://user-images.githubusercontent.com/52557478/77784996-17939100-7021-11ea-97de-656483d17401.png)

**Comment by gavingolden** [comment]
Can you change the title to describe the problem and/or desired solution?

Do you want the county population to be included as a separate field?

I'd prefer to add the raw population rather than the ratio per 1000 because consumers can derive that on their own without losing the population stats (which could be useful on their own). Or provide both

**Comment by deto** [comment]
I think providing both total population as well as size (e.g. squared miles) would be useful to have in the dataset.  Both for states and counties.  Sure these are readily available, but would just be nice as a convenience to people who are going to poke around with this.

**Comment by apheliar** [comment]
i'm just unsure why we're comparing counties (or states). what do we gain from knowing Mass. has more cases than Rhode Island?

But if I saw that Rhode Island has only 30 cases per 1,000 (ex.) and Massachusetts has 50 per 1,000 - that's worth digging into to see why the #if cases in Massachusetts is so much more dense than Rhode Island. 

Seeing #of cases per state as numbers in a table is not the same as comparing them side by side on a chart, like this.

![screen_shot_2020-03-27_at_12 16 01-1](https://user-images.githubusercontent.com/52557478/77787555-588da480-7025-11ea-89d8-f60229f8d237.png)

**Comment by thoughtafter** [comment]
I disagree. There are differing datasets for population counts, and other metrics. I'd recommend each data set try to do 1 thing well. It's been difficult enough to get good data about covid-19 cases. What people need is a high quality source of raw data. What people choose to do with that data is another matter that can be addressed with those people.

**Comment by apheliar** [comment]
> I disagree. There are differing datasets for population counts, and other metrics. I'd recommend each data set try to do 1 thing well. It's been difficult enough to get good data about covid-19 cases. What people need is a high quality source of raw data. What people choose to do with that data is another matter that can be addressed with those people.

Can you tell me the benefit of comparing number of cases per state in a chart? Can you please tell me how this is helpful? Thanks.

**Comment by deto** [comment]
They didn't release a chart, they released a dataset.

You're the one who made that chart.  And that chart isn't very useful, I agree.  You should have downloaded population data and used it to make a better comparison.  If you don't know how to do that, or don't want to do that, then this dataset isn't meant for you.

**Comment by apheliar** [comment]
> They didn't release a chart, they released a dataset.
> 
> You're the one who made that chart. And that chart isn't very useful, I agree. You should have downloaded population data and used it to make a better comparison. If you don't know how to do that, or don't want to do that, then this dataset isn't meant for you.

ahhh, yea i didnt make this chart, it was referenced with NYTlink cited as the source. 

i appreciate that you've at least validated that i'm not crazy. thank you :))

**Comment by Kvit** [comment]
Here is a report that computes new daily cases, scaled by population and aligned by day of pandemic (say 1 is first day with 100+ new daily cases) . The report is updated daily from this data source
https://datastudio.google.com/u/1/reporting/1ZXKy_G6cFzqJCj9WpxDmwrvD953mQcAs/page/iJAKB

**Comment by apheliar** [comment]
> Here is a report that computes new daily cases, scaled by population and aligned by day of pandemic (say 1 is first day with 100+ new daily cases) . The report is updated daily from this data source
> https://datastudio.google.com/u/1/reporting/1ZXKy_G6cFzqJCj9WpxDmwrvD953mQcAs/page/iJAKB

thank you very much.
