### ISSUE TITLE
Aggregating FIPS in high intensity regions

### ISSUE THREAD

**Issue by codecae** [nytimes/covid-19-data#141]
While it is simpler to roll up numbers and ignore FIPS codes in regions that have them (such as new york), doing so makes it impossible to merge this data with other data sets.  Other available data, such as population could otherwise be used with this data to normalize calculations per capita to provide more relative scaling.  Without this ability, this data set is very difficult to use with other region/county-based data sets.

**Comment by j-p-c** [comment]
True, but that's how they started it, and it would break a lot of pipelines for them to now change it.

You can download processed data, including populations and normalized (per capita) counts, from [johncostella.com/covid-19/data/latest.csv](http://johncostella.com/covid-19/data/latest.csv). Let me know if anything looks wrong with it.

**Comment by gmillikan** [comment]
Hi J-P-C, May I ask where you got the 2019 population data?  Thanks, Geoff

**Comment by j-p-c** [comment]
Sure. I have all the details at the top of [johncostella.com/covid-19](http://johncostella.com/covid-19/), but it's [the U.S. Census Bureau](https://www.census.gov/programs-surveys/popest/data/tables.html).

**Comment by codecae** [comment]
I'm gonna close this, as I don't think anything else will come of it :)  Thanks for the help.

**Comment by codecae** [comment]
BTW j-p-c.. found some anomalies in your dataset.  Some counties are duplicated and have blank cumul numbers yet they have relative amounts -- ie: Bronx County on 4/4

Perhaps his is by design, but I'm just giving a little feedback at your request :)  Have a good one.

**Comment by j-p-c** [comment]
Yes, you need to read [the documentation for this repo](https://github.com/nytimes/covid-19-data#geographic-exceptions). The NYT folks combine the data for counties in New York City and those around Kansas City, Mo. It's therefore possible to get numbers relative to the overall population of those counties (and, for want of anything better, assign it to each of the aggregated counties), but it's not honest for me to assign integer counts to the individual counties. (If you need numbers in those cells, you could just multiply the relative proportion by the population of each given county, in the absence of per-county data, but in most cases you're likely to want per capita counts anyway.)

**Comment by codecae** [comment]
Ya I read the readme and understand the exceptions.  It should pretty simple to peanut butter spread and aggregate nyc and kansas city into single regions.  What is your methodology for Unknown counties?

**Comment by j-p-c** [comment]
Unknown counties can't be ascribed to particular counties, but they are included in the relevant State totals. (I originally created this dataset for the geomaps at [johncostella.com/covid-19](http://johncostella.com/covid-19/)—the county map only shows numbers ascribed to counties, and the state map shows numbers ascribed to states.
