### ISSUE TITLE
Map color scales should be continuous

### ISSUE THREAD

**Issue by jedwards1211** [nytimes/covid-19-data#143]
France (increasing every 8 days) currently has the same color as China (increasing every 157 days).  That's a huge difference.  There's not really any reason to use discrete color steps.

**Comment by Adam-Hoelscher** [comment]
This repo contains no maps and no data for any area outside the United States.

**Comment by jedwards1211** [comment]
I was hoping comments here would make their way to the people who maintain the maps on the NYT website heh
