### ISSUE TITLE
To save bandwidth...

### ISSUE THREAD

**Issue by gmillikan** [nytimes/covid-19-data#144]
Is there a way (without using Git) check file mod date before pulling the file?  Don't want to waste GitHub's bandwidth if we've already got the latest file....

Thanks,

--Geoff

**Comment by jtal** [comment]
Are you using a URL that looks like this?
https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv

If so you can use the normal HTTP headers to implement your favorite caching strategy.
Cache-Control
If-Modified-Since

**Comment by gmillikan** [comment]
Great thinking!  That's perfect!  Thanks so much @jtal!!   Best, Geoff
