### ISSUE TITLE
time-lapse per-capita county/metro/state maps

### ISSUE THREAD

**Issue by kmgwalker** [nytimes/covid-19-data#148]
Since others are using the issues tracker to publicize uses of the NYT data, I thought I would do the same: https://c19graphs.net .  Still a work in progress, but I have not seen many examples of the the time-slider+choropleth approach, so I thought I would share.  Does metro areas as well as counties and states.

**Comment by chadagreene** [comment]
Nice work @kmgwalker! I suspect it might be easier for the eye to pick out spatial patterns with a perceptually uniform colormap like [cmocean](https://matplotlib.org/cmocean/). My attempt to animate the data is [here](https://github.com/chadagreene/COVID19), but I don't have fancy sliders like yours.

**Comment by kmgwalker** [comment]
Thanks @chadagreene , those are nice colormaps.  I'll add user-selectable color maps/scales to my to-do list.

**Comment by daveroush** [comment]
Good stuff @kmgwalker

**Comment by jjbenes** [comment]
@kmgwalker The choropleths look nice. I did publish county per-capita results using a time slider and a choropleth a few days ago: https://first-principles.ai/covid-19/per-capita-map.html. The per-capita data points are ranked daily, so it's possible for a county's color to fade over time as another county gets more cases per-capita (see Northern California, for instance).

**Comment by SCHarris76** [comment]
@kmgwalker So glad you posted this! Your displays are wonderful. It is too bad that zooming interferes with UI (can't use arrow keys to advance date), but the overall presentation is excellent! It is very interesting to compare the state level view to the by-county view, especially for states like NY with areas that are hit hard and others that, so far, are minimally affected. You might give some thought regarding how to analyze data trends for rebound detection once social distancing restrictions begin to be lifted. Will require tracking dates for step-wise reductions in social distancing, hope these will be added to the NYT tracker.
