### ISSUE TITLE
Douglas County, Nebraska actually Diamond Princess?

### ISSUE THREAD

**Issue by miclugo** [nytimes/covid-19-data#149]
The us-counties.csv file shows an unexpectedly early start for COVID-19 in Douglas County, Nebraska: no cases on 2020-02-16, then 10 cases on 2020-02-17 and 2020-02-18.  The first case reported in Nebraska outside of Douglas County wasn't until 2020-03-12. 

Douglas County's [health department updates](https://www.douglascounty-ne.gov/covid-19-latest-updates) refers on 2020-03-08 to "the second and third cases in Nebraska, other than individuals who were brought to the Nebraska Biocontainment Unit from the Diamond Princess Cruise Ship."  The Biocontainment Unit is in Omaha, in Douglas County.

Should these cases be counted as belonging to Douglas County or should they be in some other geography?

**Comment by albertsun** [comment]
Hi @miclugo that is indeed what we are doing. We similarly are counting cases from the Grand Princess in Alameda and cases from the USS Theodore Roosevelt in Guam.

**Comment by miclugo** [comment]
@albertsun Thanks for adding the note about that to the readme.   I had been making some visualizations and was a bit confused about why there was an outbreak in Omaha that nobody else seemed to be reporting.
