### ISSUE TITLE
Last Update Datetime inclusion in README

### ISSUE THREAD

**Issue by aaraney** [nytimes/covid-19-data#15]
So users can quickly view the date time stamp for the latest data pushed without clicking on a file csv (this is assuming the repo was not cloned) can a date be included in header of the README displaying the last date and time for which data was push? Travis CI should be able to do this.

**Comment by patrickmj** [comment]
I'd prefer to see tags/releases on the data. It won't reflect the datetime of the data reported, only when the newly compiled data was all put in and deemed ready for sharing. But for purposes of citation, tracking, and versioning, that seems the most stable and coherent, and machine-readable.

**Comment by aaraney** [comment]
@patrickmj thats an excellent point, I agree that would be a better solution than the one I proposed.

**Comment by albertsun** [comment]
As this is dataset is cumulative counts for past days, the date column on each row should be the date you use for when that data is applicable to.

If you want to know when this repository of data was most recently updated, the timestamp of the most recent git commit would be your best reference.
