### ISSUE TITLE
GA Counties Death Error

### ISSUE THREAD

**Issue by dboneshc** [nytimes/covid-19-data#152]
Based on forward difference of cumulative death data, it would appear there is an error in deaths for Gwinnett and Fulton counties in GA. I wouldn't expect the differential of cumulative deaths with respect to time to be less than zero unless there was a fat finger error or incomplete revision to the data.

Fulton dates in question 3/28 - 3/29
Gwinnett dates in question 4/4 - 4/5

![image](https://user-images.githubusercontent.com/49176212/78830609-3c3f1f80-79b6-11ea-90ad-84262a77f0df.png)

**Comment by albertsun** [comment]
@dboneshc this happens with some regularity in this dataset.

Often counties do revise their case and death counts down in the future leading to a drop in the reported number. Sometimes we are able to revise this with knowledge of the correct historical data. More often we are not.

We are trying to develop methods to do it for more as health departments start to release more of their own historically corrected data, but in the meantime these drops will remain in this data set.
