### ISSUE TITLE
Data for 4/7/2020 in Pima County Arizona is not correct

### ISSUE THREAD

**Issue by msmaz** [nytimes/covid-19-data#154]
4/7/2020 data is the same as for 4/6/2020

According to the county  web site it should be:
464 cases
16 deaths

https://webcms.pima.gov/cms/One.aspx?portalId=169&pageId=527452

Likewise the Arizona State numbers are missing Pima county numbers and are also incorrect.

**Comment by albertsun** [comment]
Hi, so it looks like none of the sources for Pima were updated with the 464 number until 4/8 which is why we have that number for 4/8 and not 4/7.

**Comment by msmaz** [comment]
Albert,

Thanks for compiling these data -- it's a great resource!

It must be very hard to hunt down all the discrepancies that exist in a
data set with 2600 counties.

Thanks again.

Mike
