### ISSUE TITLE
4-9 County file Missing 4-9 Data

### ISSUE THREAD

**Issue by sledbury** [nytimes/covid-19-data#159]
Thanks for your efforts on this!!

Just wanted to make you aware that the 4-9 State file just posted has 4-9 data, but the 4-9 County file only has data through 4-8.

**Comment by albertsun** [comment]
Hi @sledbury how are you downloading the data? The latest us-counties.csv file in this repo does have 4/9 data at the end of the file.

**Comment by sledbury** [comment]
I went back after 30 minutes, and the 4-9 county file then had the 4-9 data, and noticed file date/time didn't change.  Strange.  I validated a few times before posting.  Maybe a caching issue?  But should have posted I was good to go.
