### ISSUE TITLE
Rockland County Deaths Data 4/7-4/9

### ISSUE THREAD

**Issue by bensilver95** [nytimes/covid-19-data#161]
4/7 deaths are 119, 4/8 deaths are 98, 4/9 deaths are 117.  The deaths column should be cumulative, no?

**Comment by albertsun** [comment]
@bensilver95 yes, generally. However, on 4/8 we switched from reporting New York state deaths based on place of residence to place of fatality. We are working towards revising the entire timeseries from the beginning to match that definition, but until then the deaths for 4/8 will be strange.
