### ISSUE TITLE
enriched nytimes-covid-19 data available, with county shapes, county center (lat, lons), 2019 census estimates, and per capita calculations

### ISSUE THREAD

**Issue by ringhilterra** [nytimes/covid-19-data#162]
I created some python scripts that enrich this dataset with additional information that can be useful for per capita and geospatial analysis.

data can be found here: https://github.com/ringhilterra/enriched-covid19-data

I hope it gives others a head start in their COVID-19 related analytic, modeling, and visualization efforts. I plan on updating the repo daily. 

I used the dataset to create this timelapse visualization found [here](https://www.reddit.com/r/dataisbeautiful/comments/fxqh6u/oc_covid19_us_timelapse_confirmed_cases_per/)

Thank you to New York Times for all the effort into collecting all of this valuable data!

**Comment by albertsun** [comment]
Thanks for sharing @ringhilterra

**Comment by ykzeng** [comment]
@ringhilterra thanks for sharing, it's critical to have more aspects of data on each county! I was also wondering, have u ever come across population density data on the fips-level? It's really a critical piece of data to consider in such an outbreak.

**Comment by ringhilterra** [comment]
@ykzeng, that is a good point, I will look into adding population density to the dataset, should not be too much work.

**Comment by ykzeng** [comment]
> @ykzeng, that is a good point, I will look into adding population density to the dataset, should not be too much work.

I actually found my data source from 2010 US census already, for population density.

Here is my data:
[https://github.com/ykzeng/covid-19/tree/master/data](https://github.com/ykzeng/covid-19/tree/master/data)

Like yours, it may contain some other "possibly" useful data from the census like population demographics, retail revenues, etc, so feel free to take whatever you feel might be needed :)

**Comment by ringhilterra** [comment]
@ykzeng I added the county population per square mile to my dataset. Thanks again. I referenced your repo under 'data sources' in the Readme.
