### ISSUE TITLE
Dallas county (Texas) spike on 2020-04-11?

### ISSUE THREAD

**Issue by ssdowd** [nytimes/covid-19-data#164]
us-counties.csv shows cases in Dallas,Texas (county) went from 1537 to 3269 and deaths from 25 to 66 between 2020-04-10 and 2020-04-11.  The Dallas Morning News reports 107 new cases for a total of 1644, with 2 new deaths for a total of 27.  See https://www.dallasnews.com/news/public-health/2020/04/11/tarrant-county-reports-four-more-coronavirus-deaths/

**Comment by albertsun** [comment]
Thanks @ssdowd we'll fix that. This was a metro area vs county mixup.

**Comment by albertsun** [comment]
@ssdowd fixed in the latest data update.
