### ISSUE TITLE
I made a video to show how to put the data into Excel and do simple analyses

### ISSUE THREAD

**Issue by RichardKCollins** [nytimes/covid-19-data#167]
NYTimes State and County Data in Excel
https://youtu.be/leYjzBStCZU

If you will tell me how to add the speadsheets to your covid-19-data project, I will do so.  I do cloned the project, but do not have write access to the master
[County Populations 2010 to 2019 co-est2019-alldata.xlsx](https://github.com/nytimes/covid-19-data/files/4467815/County.Populations.2010.to.2019.co-est2019-alldata.xlsx)

I am on GitHub but do not use it because I cannot see most of the text on most of the pages (too pale)

Here are the sheets I created in the video.  I added population from the Census for states and counties and calculated rates and ratios. I only had an hour or so, so there are things that could be done.  You offer the CSV, but that is not really easy to use or read.  Many people can get to Excel or Sheets.

Richard Collins, Director, The Internet Foundation
RichardCollins@TheInternetFoundation.Org

[NYTime State Report 12 Apr 2020.xlsx](https://github.com/nytimes/covid-19-data/files/4467810/NYTime.State.Report.12.Apr.2020.xlsx)
[NYTime County Report 12 Apr 2020.xlsx](https://github.com/nytimes/covid-19-data/files/4467811/NYTime.County.Report.12.Apr.2020.xlsx)

**Comment by ret394** [comment]
also try Google Docs or using https://www.libreoffice.org/discover/calc/

thanks. have a nice day. keep up the good work.

[ret394](https://github.com/ret394)
