### ISSUE TITLE
First Case of 2019 Novel Coronavirus in the United States was on January 20th, 2020

### ISSUE THREAD

**Issue by taschmitt** [nytimes/covid-19-data#168]
The latest research published on January 31, 2020 reports the first COVID-19 case in the U.S. occurred on January 20, 2020: https://www.nejm.org/doi/full/10.1056/NEJMoa2001191.

After the CDC's press release of the first COVID-19 case on the Janurary 21, 2019, the Washington State 2019-nCoV Case Investigation Team reported January 20, 2020 as the date of the first COVID-19 case.

**Notes**
CDC press release on first COVID-19 case: https://www.cdc.gov/media/releases/2020/p0121-novel-coronavirus-travel-case.html.

Wikipedia page on COVID-19: https://en.wikipedia.org/wiki/2020_coronavirus_pandemic_in_the_United_States

**Comment by albertsun** [comment]
Hi @taschmitt the data in this repo is all based on date of reported cases or announced cases. There are many different ways of dating cases — lab result date, symptom onset, specimen taken, etc but as we're relying on public data, we're using announced date.

**Comment by taschmitt** [comment]
@albertsun Didn't think of it as a press release announce date, but makes sense. For historical analysis I guess it could depend on the question(s) being asked.

Unless of course there is a huge amount of lag, and for disease proliferation tracking or research reasons that wouldn't be great. But mostly academic with 1 day at this point.

But I guess that's not our fault right now and pretty much says it all when the very first case date is not agreed upon across data aggregators. I've seen: 20th, 21st, and 22nd.

Thanks for more detail on your method of thinking. Very helpful for us and a great example of the vacuum left for collecting COVID-19 data.
