### ISSUE TITLE
State GA Cases 4/12 < 4/11

### ISSUE THREAD

**Issue by mgaslowitz** [nytimes/covid-19-data#169]
Cases for GA decreased from 4/11 - 4/12

|date|state|fips|cases|deaths|
|-|-|-|-|-|
|2020-04-11|Georgia|13|12261|432|
|2020-04-12|Georgia|13|12103|438|

**Comment by albertsun** [comment]
Starting on 4/12 Georgia started breaking out a set of cases for "Non-Georgia Resident". We're excluding these cases from our data because they are likely to already be counted in other states' numbers. These cases had previously been listed as Unknown county and you'll see that number drop significantly on 4/12 as well.

**Comment by ercbk** [comment]
You just can't change the "cases" definition for Georgia in the middle of your dataset. There needs to an adjustment to the case counts for the days prior.  Growth rates and doubling rates are jacked up now.

**Comment by albertsun** [comment]
Please believe me when I say we are as frustrated about changes as anyone else, or more so. However, the definition is different and we had to make a choice about which of inconsistent alternatives to go with. We'll look into revising case counts as we can but right now that data isn't available.

If you need a monotonically increasing case count you could do your calculation by excluding Unknown cases from Georgia for all days, though that has different drawbacks.

**Comment by ercbk** [comment]
Well, if this isn't resolved some other way, then there should be a section in the README explaining what happened and the date at which the change occurred.

**Comment by albertsun** [comment]
We've added a note in the readme for this.
