### ISSUE TITLE
Another COVID-19 dashboard [D3.js, open-source]

### ISSUE THREAD

**Issue by aryamanarora** [nytimes/covid-19-data#170]
Adding to the list of projects using this data: [@aryamanarora/coronavirus](https://github.com/aryamanarora/coronavirus)

Features:
* Choropleth map of cases on a logarithmic colour scale by U.S. county (and county-equivalent)
* Slider to see historical data
* Tooltip for number of cases and highlighting when hovering over a county
* Clicking on a county magnifies and focuses it, displaying an infobox to the right with case and death counts, and a graph of those over time
* Search bar to find a county or county-equivalent

**Comment by jcbowyer** [comment]
This is great.  I have worked on drill down maps (bubble and filled).  I would now like to make them time lapse.   I hope to find a way to reuse some of your code.  https://github.com/jcbowyer/d3-in-angular

**Comment by tiffehr** [comment]
Closing this issue, but it is listed within our collection of Examples on our Project board.  We'll point people that direction where possible.
