### ISSUE TITLE
South Dekota's death counts decrease on Apr 11

### ISSUE THREAD

**Issue by chrisjbillington** [nytimes/covid-19-data#171]
According to the dataset, South Dekota had 7 deaths on April 10th, but 6 deaths on April 11th.

If the 7th death was incorrectly reported, then the death number should be decreased from 7 to 6 for April 9 and April 10.

Presumably this data is from a particular county where the error will need to be corrected.

**Comment by albertsun** [comment]
Yes, those were the numbers reported by the state. We wouldn't simply assume that any day with 7 should be corrected to 6 without knowing if the death that was incorrectly reported occurred then or on an earlier date and earlier dates also need to be revised downwards, so in these instances we don't make a revision. We are looking into how to acquire and incorporate corrected historical data for situations like this.

**Comment by chrisjbillington** [comment]
Thanks for the explanation, it makes sense that you do not want to guess about how to correct it. Feel free to close this issue if you like!
