### ISSUE TITLE
NYC death toll jump

### ISSUE THREAD

**Issue by thegargiulian** [nytimes/covid-19-data#173]
I see that this story (https://www.nytimes.com/2020/04/14/us/coronavirus-updates.html?action=click&module=Spotlight&pgtype=Homepage) is the lead on the Times website right now. 

Do you know when the data will be updated here to reflect this? Will it be broken down by day or updated in one chunk?

**Comment by albertsun** [comment]
We're not going to include those additional deaths here as the methodology does not match what we're reporting for anywhere else. We're going to continue only counting deaths that have a lab confirmed positive Covid-19 test. If this counting method changes in enough places we may revisit.
