### ISSUE TITLE
New York Onondaga County Date is inaccurate 

### ISSUE THREAD

**Issue by ylzhang29** [nytimes/covid-19-data#177]
4/14: 537 confirmed  and 11 deaths
4/13: 537 confirmed  and 11 deaths
4/12: 481 confirmed  and 9 deaths
4/11: 456 confirmed 
4/10: 442 confirmed
4/9:  422 confirmed
4/8: 397 confirmed 
4/7: 377 confirmed 
Days prior to 4/7 were accurate

**Comment by albertsun** [comment]
Hi @ylzhang29 thanks for pointing this out, and sorry it's taken so long, but we'll look into this more closely
