### ISSUE TITLE
Alamance County, NC Incorrect Case Count

### ISSUE THREAD

**Issue by link2matt** [nytimes/covid-19-data#178]
According to Alamance County, there was an overcount of 21 cases on 4/13. Issue is explained on webpage below:

https://www.alamance-nc.com/healthdept/2020/04/14/update-on-alamance-county-covid-19-case-count/

Alamance states that the correct number of cases on 4/13 was 41 cases.  On 4/14, the case count was 42 cases, according to NCDHHS. This dataset seems to still include the 21 erroneously categorized cases in Alamance County's case count.

Thanks for providing this valuable resource.

**Comment by albertsun** [comment]
Hi @link2matt thanks for pointing this out, we've revised those two days in the latest update.
