### ISSUE TITLE
Possible Incorrect Data for Bucks County Pennsylvania

### ISSUE THREAD

**Issue by KathySunt** [nytimes/covid-19-data#182]
The data for Bucks County PA does not match what I see at these places: 
https://www.health.pa.gov/topics/disease/coronavirus/Pages/Cases.aspx
https://data.citizen-times.com/coronavirus/

Thank you for this information!!

Kathy

**Comment by albertsun** [comment]
HI @KathySunt our data comes from a combination of the PA State Health Department and Bucks County, which at times will report numbers in advance of the state. That's one reason it may not match.
