### ISSUE TITLE
RI data missing for 4/15 and 4/16

### ISSUE THREAD

**Issue by mcmcgrath13** [nytimes/covid-19-data#183]
Rhode Island case data is missing for 4/15 (and 4/16 based on ny times visuals).  They switched to using a [dashboard](https://ri-department-of-health-covid-19-data-rihealth.hub.arcgis.com/) to report data instead of the [google sheet](https://docs.google.com/spreadsheets/d/1n-zMS9Al94CPj_Tc3K7Adin-tN9x1RSjjx2UzJ4SV7Q/edit#gid=0).

**Comment by albertsun** [comment]
Thanks @mcmcgrath13 we've now updated this.
