### ISSUE TITLE
List of counties where previous day's cases/deaths greater than today's

### ISSUE THREAD

**Issue by seeess1** [nytimes/covid-19-data#185]
See attached file with two CSVs - one with list of counties where the previous day's case counts are greater than the following day's counts and list where previous day's death counts are greater than the following day's.

[previous_greater.zip](https://github.com/nytimes/covid-19-data/files/4494077/previous_greater.zip)

**Comment by albertsun** [comment]
Hi @seeess1,

Thanks, and unfortunately this is something we have to live with in the data. We've added a note to the README about this:

> In some cases, the number of cases or deaths for a state or county will decline. This can occur when a state or county corrects an error in the number of cases or deaths they've reported in the past, or when a state moves cases from one county to another. When we are able, we will historically revise counts for all impacted dates. In other cases, this will be reflected in a single-day drop in the number of cases or deaths.
