### ISSUE TITLE
Converted both .csv files to JSON format and updates every 4 hours

### ISSUE THREAD

**Issue by amishpr** [nytimes/covid-19-data#187]
My repo: https://github.com/amishpr/covid19-usa

# Description

This project checks [nytimes/covid-19-data](https://github.com/nytimes/covid-19-data) every 4 hours to see if the `us-states.csv` and `us-counties.csv` have been updated and then converts them to a JSON format and deploys it to a website for public use.

* Converted the `us-states.csv` file from [nytimes/covid-19-data](https://github.com/nytimes/covid-19-data) into a JSON file.

	* View JSON here: https://amishpr.github.io/covid19-usa/timeseries.json

* Converted the `us-counties.csv` file from [nytimes/covid-19-data](https://github.com/nytimes/covid-19-data) into a JSON file.

	* View JSON here: https://amishpr.github.io/covid19-usa/timeseries-counties.json

**Comment by tiffehr** [comment]
Closing this! It is listed in our Alternative Formats collection on our Project board. We'll point others to that collection if/when they ask about endpoints like these. Thank you!
