### ISSUE TITLE
Enrich with population density data on FIPS/County level

### ISSUE THREAD

**Issue by ykzeng** [nytimes/covid-19-data#188]
Hey everyone,

I am just wondering if any of you have missed the same piece of data like I did when doing analytics into the case data (big thanks for NYT for their hardwork in holding all this together). Specifically, among all other census data, I am looking for a centralized population density data on the FIPS/County-level. I believe this is critical for any analytics solutions. 

I have looked thru out github and google, came across a bunch of visualization from US 2010 Census like [this](https://www.census.gov/dmd/www/pdf/512popdn.pdf), which is already plotted on a map and I can't seem to find the original data anywhere.

In addition, we do have every county on Wikipedia, it is likely to build a crawler out of it, but the time and effort in validations and maintaining integrity would be tremendous considering the current time sensitivity. So does anybody has already a dataset for population density? Is it possible to enrich the NYT data with such a new dataset, in addition to population data?

**Comment by j-p-c** [comment]
https://www.census.gov/programs-surveys/popest/data/tables.html

I also have this NYT data joined with the 2019 population estimates available at http://johncostella.com/covid-19/data/latest.csv

**Comment by ykzeng** [comment]
> https://www.census.gov/programs-surveys/popest/data/tables.html
> 
> I also have this NYT data joined with the 2019 population estimates available at http://johncostella.com/covid-19/data/latest.csv

Thanks for the reply @j-p-c , I had the population data already, and already used it for getting "cases per million" estimation. But I am actually looking for population density data, which I believe may be another very important information. Highly populated counties in US central can have much less density comparing to the east, which may lead to less spreading.

**Comment by stevemarin** [comment]
Here's what I do to plot a statistic incorporating cases and population density...

```python
counties_geo_url = 'https://eric.clst.org/assets/wiki/uploads/Stuff/gz_2010_us_050_00_20m.json'
counties_geo = json.loads(urllib.request.urlopen(counties_geo_url).read().decode("ISO-8859-1"))
for county_geo in counties_geo['features']:
    county_geo['id'] = county_geo['properties']['GEO_ID'][-5:]    
```

and then

```python
demographics_dict = {}
demographics_dict['area'] = {county['id']: county['properties']['CENSUSAREA'] 
                           for county in counties_geo['features']}
```

I'm plotting with plotly.express which requires the id set as you see above.

**Comment by j-p-c** [comment]
Ah sorry @ykzeng; I misread your question.

**Comment by ykzeng** [comment]
> question

np, thanks for sharing!

**Comment by ykzeng** [comment]
> Ah sorry @ykzeng; I misread your question.

np, thx for sharing still

**Comment by ykzeng** [comment]
> Here's what I do to plot a statistic incorporating cases and population density...
> 
> ```python
> counties_geo_url = 'https://eric.clst.org/assets/wiki/uploads/Stuff/gz_2010_us_050_00_20m.json'
> counties_geo = json.loads(urllib.request.urlopen(counties_geo_url).read().decode("ISO-8859-1"))
> for county_geo in counties_geo['features']:
>     county_geo['id'] = county_geo['properties']['GEO_ID'][-5:]    
> ```
> 
> and then
> 
> ```python
> demographics_dict = {}
> demographics_dict['area'] = {county['id']: county['properties']['CENSUSAREA'] 
>                            for county in counties_geo['features']}
> ```
> 
> I'm plotting with plotly.express which requires the id set as you see above.

this is very good data! I actually found my own data source from 2010 US census. Did a cross comparison with your data and both our data looks good in terms of population density.

Here is my data:
[https://github.com/ykzeng/covid-19/tree/master/data](https://github.com/ykzeng/covid-19/tree/master/data)

Instead of geo coordinates, mine contain some other "possibly" useful data from the census like population demographics, retail revenues, etc.

**Comment by Prashavu** [comment]
@ykzeng I am looking for Population Density data, however the column "FIPS"  do not map. Is FIPS the concatenation of State+County
