### ISSUE TITLE
2020-04-15 worcester ma data seems incorrect

### ISSUE THREAD

**Issue by russellgoldenberg** [nytimes/covid-19-data#189]
You have deaths at 100, but I think it should be at 73. Assuming your source is https://www.mass.gov/doc/covid-19-cases-in-massachusetts-as-of-april-15-2020/download

If not I would be curious to see where the other ma data source is

**Comment by albertsun** [comment]
Hi @russellgoldenberg, yes we're using that and adding new deaths per county each day. How are you coming up with your 73 deaths number for April 15th?

**Comment by russellgoldenberg** [comment]
You have 56 on the 14th. There are 17 reported in that pdf I linked on the 15th. So that would put it at 73, not 100.

**Comment by russellgoldenberg** [comment]
Actually a few others look incorrect as well, for example you reported 0 deaths in Suffolk on the same day, though there were 27

**Comment by albertsun** [comment]
Thanks, we'll review this and see what's going on.

**Comment by albertsun** [comment]
Hi @russellgoldenberg, in today's update we revised our data for Massachusetts from 4/15 onwards. We are also looking at doing another revision from the beginning.

**Comment by russellgoldenberg** [comment]
Awesome. Just a quick note it looks like the deaths dipped lower on April 15 for Berkshire county (goes from 23 to 21).

**Comment by albertsun** [comment]
Sorry, yes, we just realized this and did a full revision again. Berkshire County should be 23 deaths on both 4/14 and 4/15. Bear with us as we get better at re-including historical data.
