### ISSUE TITLE
Texas Johnson County data inconsistent

### ISSUE THREAD

**Issue by furtip** [nytimes/covid-19-data#190]
On 4/7 Johnson County (fips 48251) reports 1 death and 33 cases
On 4/8 0 deaths and 33 cases
On 4/9 0 deaths and 30 cases
On 4/10 1 death and 30 cases
How can the data decrement? If it is due to incorrect earlier reporting, is it possible to fix the earlier dates?

**Comment by albertsun** [comment]
Hi @furtip yes, it's most likely due to cases earlier on that were amended later. We're only able in some cases to correct the earlier reporting. We'll look into this one.

**Comment by albertsun** [comment]
This data has now been adjusted
