### ISSUE TITLE
NY MSA Counties unchanged April 17 vs. April 16

### ISSUE THREAD

**Issue by dcthomas0518** [nytimes/covid-19-data#191]
Hi,
The below counties' death count did not change on April 17 vs. April 16, whereas they always changed in the past day over day:

Rockland, New York
Suffolk, New York
Westchester, New York
Nassau, New York
New York City, New York

Thanks,
dcthomas

**Comment by albertsun** [comment]
@dcthomas0518 Yes, unfortunately, New York State didn't release new numbers for 4/17. We are trying to figure out why and what they should be and will update the data if we are able to find the correct numbers.

**Comment by dcthomas0518** [comment]
Thanks for confirming.

Regarding New York deaths, does this project's numbers include NYC's probable deaths (e.g., deaths discovered at home) or only test confirmed deaths at hospitals per this article?

https://www.nytimes.com/2020/04/14/nyregion/new-york-coronavirus-deaths.html

**Comment by albertsun** [comment]
These numbers have now been updated as of 4/19.

We are not including probable deaths for New York at the moment.
