### ISSUE TITLE
Does New York City's deaths include probable or only test confirmed at hospitals?

### ISSUE THREAD

**Issue by dcthomas0518** [nytimes/covid-19-data#195]
Regarding New York deaths, does this project's numbers include NYC's probable deaths (e.g., deaths discovered at home) or only test confirmed deaths at hospitals per this article?

https://www.nytimes.com/2020/04/14/nyregion/new-york-coronavirus-deaths.html

**Comment by albertsun** [comment]
Those numbers only include lab confirmed deaths, whether they took place at a hospital or not.

As places move towards including probable cases we're evaluating what to do with those numbers.
