### ISSUE TITLE
GraphQL/RESTful access to the data

### ISSUE THREAD

**Issue by joshrotenberg** [nytimes/covid-19-data#196]
Thank you for making this data available to the public.

I put together a quick project to make the data available in other formats: https://github.com/joshrotenberg/covid_19_nyt_ex

Updates are checked for automatically so the data should almost always be up to date. It is a work in progress but most changes are additional and not breaking. Happy to take requests if anything finds it useful for a project.

**Comment by tiffehr** [comment]
Closing this, but it is added to our Alternative Formats collection on our Project board. We'll point others to that collection if/when they ask about endpoints like these.  Thank you!
