### ISSUE TITLE
Planned update frequency in README

### ISSUE THREAD

**Issue by axlekb** [nytimes/covid-19-data#2]
Hello! Thank you for providing this.

Would you be able to provide some guidance about when (e.g. 10a and 4p) and/or how often (e.g. 3x per day) you expect to update the data in the README?

**Comment by gavin20** [comment]
Possible workaround is to scrape the last update date listed via https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html

**Comment by jqnatividad** [comment]
I actually wrote a Selenium scraper that used the last update date by the byline this week and noticed that there are multiple updates throughout the day (typically 3-4x day).

It'd be great if this repository is updated whenever the article is updated, and have the full timestamp, so we can also see intraday changes in the data.

**Comment by girlinamovie** [comment]
Time stamp by county column? 
Kentucky Jeffersonville as of March 27 12PM Noon is 60 cases, it still says quantity of 1

**Comment by metasj** [comment]
@jqnatividad here's a project with intraday changes, explicit sources, and timestamps for each data point: https://github.com/COVID19Tracking

**Comment by gavin20** [comment]
Here's the NY source: https://github.com/nytimes/covid-19-data

**Comment by albertsun** [comment]
Hi folks, thanks for this and the interest.

Our goal is to update this data once a day, but for the moment it is still a manual process that includes human verification of the data. We're getting more automation up and running to speed things along. As we fall into a more regular cadence we will update the README with our expected cadence and the last update time. Thanks for the good idea.
