### ISSUE TITLE
I made a timelapse

### ISSUE THREAD

**Issue by Zoooook** [nytimes/covid-19-data#200]
One for each combination of [Total / Daily] x [Cases / Deaths] x [Raw / Per Capita]

[Youtube](https://www.youtube.com/watch?v=-TnuMcfLEjA)
[Reddit](https://www.reddit.com/r/dataisbeautiful/comments/g4xp27/oc_coronavirus_timelapse_daily_cases_per_capita/)
[Github](https://github.com/Zoooook/CoronavirusTimelapse)

**Comment by ArleneMaps** [comment]
That's great!   Did you make it in ArcGIS with a time slider?  I wanted to do an animation but haven't figured out how to arrange the fields. 
- Arlene

**Comment by Zoooook** [comment]
Thanks! No, all the frames were rendered in html with Selenium and assembled with ffmpeg. I grabbed the map from an old version of the NYTimes page, and found a file from them with county and state centroid positions. Python puts it all together.

**Comment by ArleneMaps** [comment]
Zoooook -that's cool!  I have color-shaded maps of each day, see  https://npscampus.maps.arcgis.com/apps/webappviewer/index.html?id=9075129191894cf2ad600314922d993e&fbclid=IwAR3JQV4rcX-ld24-FrUfir-kMcujnflnOEWwhb8WWWYWDa2CDVwyCFTO8uM

The cool thing is you click on the layer list so you can control which layers you see, and then click the Swipe tool (next to the print icon) and you can swipe back and forth to see the change between dates. Also, you can click on a county and get a graph of the cases over time.

**Comment by Zoooook** [comment]
Nice, that's a cool concept

**Comment by ArleneMaps** [comment]
Thanks!

**Comment by kolyarice** [comment]
This is great! Do you think you could do the same with the county-level hotspot map? This would let you see where the outbreaks are worsening or improving. 
Thanks for sharing your code

**Comment by ArleneMaps** [comment]
Kolyarice,
  Are you asking Zooook or me?  I've thought about how to do the change to identify hotspots, but not sure, maybe a 3-day moving average and then look at the difference between subsequent days?  What are your thoughts on this?

**Comment by j-p-c** [comment]
A static (updated daily) version of that is at [johncostella.com/covid-19](http://johncostella.com/covid-19/)

**Comment by kolyarice** [comment]
ArleneMaps, I was asking Zooook, but it doesn't really matter
I think color coding by doubling rate (as NY Times does) makes the most sense
![US-county-level-cv2019](https://user-images.githubusercontent.com/6494915/80027020-f5fabd80-8497-11ea-90c2-a3d3344171e3.jpg)

**Comment by Zoooook** [comment]
Hey thanks. For a static map I think color coding fits well for hotspots, with mine the idea is that you should see circles growing in hotspots, on the Daily Per Capita videos, which is what I posted to Youtube.
