### ISSUE TITLE
Error in Alabama death count - is not cumulative on 2020-04-18 

### ISSUE THREAD

**Issue by aolney** [nytimes/covid-19-data#201]
date | state | fips | cases | deaths
-- | -- | -- | -- | --
2020-04-19 | Alabama | 1 | 4903 | 160
2020-04-18 | Alabama | 1 | 4723 | 147
2020-04-17 | Alabama | 1 | 4572 | 151

Note that the cumulative drops from 151 to 147 before climbing to 160.

**Best guess is that 147 should be 157.**

**Comment by albertsun** [comment]
So, it seems that Alabama reported wrong numbers on 4/17 https://twitter.com/ALPublicHealth/status/1251531524958289920 which we will correct if/when we can get the right numbers.

**Comment by aolney** [comment]
I'm going to add a check to my data import code for any number that is less than the day before.

It seems that a check like this might also be helpful for vetting data here as well.
