### ISSUE TITLE
'confirmed' value anomaly for Snohomish County, WA

### ISSUE THREAD

**Issue by Spiderpig86** [nytimes/covid-19-data#204]
There seems to be a dip (-1) in confirmed cases from 3/27 to 3/28. Although minor, any reason why? Working on a project to display trends in the data.

| date         | county    | state      | confirmed |
|--------------|-----------|------------|-----------|
| 2020\-03\-27 | Snohomish | Washington | 913       |
| 2020\-03\-28 | Snohomish | Washington | 912       |
| 2020\-03\-29 | Snohomish | Washington | 1067      |

Anyway, thanks for the awesome work for keeping the data up to date daily. 🔥

**Comment by kolyarice** [comment]
see issue #26
