### ISSUE TITLE
[example]a real time data dashboard

### ISSUE THREAD

**Issue by mayaa6** [nytimes/covid-19-data#205]
I made a data dashboard with data from NYTIMES.

It read data and update every two minutes.

Here is the youtube live: [youtube](https://youtu.be/i8I0s3EwyNc)

Help me improve it

**Comment by sbulen** [comment]
@albertsun - I suggest an "examples" (or similar) label to allow easy querying of issues in GitHub.  To easily include/exclude data uses from issues.   Just a thought.

**Comment by mayaa6** [comment]
good suggestion

**Comment by albertsun** [comment]
Thanks @sbulen that's a good idea.
