### ISSUE TITLE
Pennsylvania confirmed vs probable

### ISSUE THREAD

**Issue by Pedro-McM** [nytimes/covid-19-data#207]
The readme page says that Pennsylvania is combining confirmed and probable deaths and cases.  However, this page reports both confirmed and probable deaths and cases:
https://www.health.pa.gov/topics/disease/coronavirus/Pages/Cases.aspx

**Comment by albertsun** [comment]
Yes you're right. We're gong to clarify the README to be clear that while they have the confirmed-only number at the state level, they do not at the county level, so therefore we're using probable+confirmed numbers for Pennsylvania.

We're seeing a broader trend towards states reporting probable+confirmed as their total number.

**Comment by albertsun** [comment]
Clarified this in the README now.

**Comment by Pedro-McM** [comment]
Okay.  Thanks!

 

Sorry.  I submitted that same thing again when I didn’t see it in the list of issues.  I thought maybe I had forgotten to hit Submit.

 

It would be wonderful if you could give a time series of both probable and confirmed deaths.

 

Pete
