### ISSUE TITLE
FIPS code for Unknown county should be 000, not 999

### ISSUE THREAD

**Issue by cswingle** [nytimes/covid-19-data#21]
I noticed that some of the data where the county is listed as "Unknown" has a FIPS code ending in `999`. I think those should end in `000`. For example, there are two records for Maine, Unknown with a FIPS code of `23999`. If you look in the Census Bureau's FIPS spreadsheet, the state of Maine by itself has a state code of `23` and a county code of `000`, or `23000`. In other words, I think FIPS uses `0` to indicate NULL/Unknown, for each sub-level rather than `9`.

Maybe this was a deliberate choice so you didn't wind up with FIPS matches for these records, but in that case, maybe leaving the FIPS column blank would make more sense than populating it with a value that doesn't exist in the FIPS reference data.

**Comment by MarypatM** [comment]
@cswingle I was noticing this as well. I found what I think might be an older reference, https://www.census.gov/prod/techdoc/cbp/cbp95/st-cnty.pdf, where the statewide value is `999`, as in `23 999 Statewide` for Maine. Newer references use `000` for the generic state, as you mention (e.g.  https://www.census.gov/geographies/reference-files/2018/demo/popest/2018-fips.html).

Maybe this is an example of inconsistent data gathering giving the varying methods? Definitely a good candidate for data cleansing.

**Comment by albertsun** [comment]
Hi @cswingle thanks for pointing this out! In the latest revision of the data and going forward all Unknown counties will have the FIPS code field blank.
