### ISSUE TITLE
Issue downloading/opening us-counties.csv

### ISSUE THREAD

**Issue by mfcarrasco** [nytimes/covid-19-data#210]
500 internal server error.

**Comment by mhaynes001** [comment]
Same.  I thought perhaps the link changed but navigated manually and found the: 
`500 internal server error.`

**Comment by albertsun** [comment]
Github appears to be having some issues with their servers https://www.githubstatus.com/incidents/2y6v4ltq26g7 - this is preventing us from updating data as well, but I guess, not preventing the creation of issues.

**Comment by mhaynes001** [comment]
Ahh, I should have checked there.  I noticed issues the other day and had checked that.  Thanks!  It just looked like a different error as if maybe it was a blank file.  Thanks for the quick update!

**Comment by albertsun** [comment]
Going to close this, please follow along with the Github status page issue if you're still having trouble. It seems to be working for me now.
