### ISSUE TITLE
issue accessing raw data from us.csv

### ISSUE THREAD

**Issue by jlbriney** [nytimes/covid-19-data#211]
a 500 internal server error appears when I try to get the raw data from us.csv file - please fix!

**Comment by albertsun** [comment]
Github appears to be having some issues with their servers https://www.githubstatus.com/incidents/2y6v4ltq26g7 - this is preventing us from updating data as well, but I guess, not preventing the creation of issues.

**Comment by albertsun** [comment]
Going to close this, please follow along with the Github status page issue if you're still having trouble. It seems to be working for me now.
