### ISSUE TITLE
Basic question about gaps in series...

### ISSUE THREAD

**Issue by sbulen** [nytimes/covid-19-data#215]
Sorry if this was answered somewhere else, I may have missed it...

Question:  If there is a gap in a series for a particular county, i.e., no record for a date, does that mean ZEROES apply for that county for that date?  or NO CHANGE to prior values?

I have been assuming zeroes.  The problem is that, for many counties, it looks far more like they didn't send an update in.  Assuming zeroes causes the series to bounce back & forth between a clean series & zero.  Assuming no change will drive up the totals.  (This also impacts any attempt to calc new cases & new deaths on any particular day.  Unknown counties are most dramatically impacted.)  

Again, thanks for the outstanding work.  You dudes are brave.

**Comment by albertsun** [comment]
If there is no record for a date, that means there were zero cases or deaths. The only time that should really happen is for Unknown counties where all those cases or deaths would have been reassigned to another county.

If there are other examples where that is happening in a way that seems wrong please let us know.

**Comment by sbulen** [comment]
Most are unknown counties, but not all.  Of non-unknowns, most are from the early days. 

Here are a few examples.  Many of these are the start of multi-day ranges of gaps:
Alabama, Geneva, 2020-04-09
Alabama, Perry, 2020-04-07
Alabama, Perry, 2020-04-08
Idaho, Boundary, 2020-04-13
Illinois, Logan, 2020-03-26
Illinois, Mason, 2020-04-02
Indiana, Benton, 2020-04-02
Indiana, Vermillion, 2020-04-02
Louisiana, Caldwell, 2020-03-31
Missouri, Marion, 2020-04-02
Nebraska, Hamilton, 2020-03-30
North Carolina, Jackson, 2020-03-26
Pennsylvania, Union, 2020-03-28
Virginia, Charles City 2020-04-01
...etc., etc....

(A warning for folks who attempt to calculate new cases/deaths by calc'ing the difference from the previous record for that county...)

**Comment by albertsun** [comment]
Hi @sbulen, I believe what's happening in most of these cases is that they are counties where a case was reported and then on a subsequent day reassigned to another county or found to be reported in error, leading to that county's count dropping back to 0.

We'll investigate further and likely remove the erroneous first case in some of these instances.

**Comment by sbulen** [comment]
No problem.  

You answered my question - zero - so I'll close this out.  

Data is just that - data.  It's never perfect...
