### ISSUE TITLE
Total cases vs. Active cases - the need for data

### ISSUE THREAD

**Issue by jdkromkowski** [nytimes/covid-19-data#216]
Total cases is no longer as useful a metric.  What people need to know about now is active cases.

Active Cases = (total cases) - (total deaths) - (recovered). 

How will data scientists or anybody actually be able to measure a "DECLINE".   As long as there are new daily cases that is not a decline unless the new daily cases is less than (daily deaths plus daily recovered).

**Comment by albertsun** [comment]
Hi @jdkromkowski,

For this data release we focused on consistent, nationwide county-level data for cases and deaths. Most other data about Covid-19, including active and recovered cases, is not available consistently across states and counties. We hope it becomes more so over time.

**Comment by jdkromkowski** [comment]
Well, https://www.worldometers.info/coronavirus/country/us/ seems to be able to have data on "active cases" by state -  which it is getting from Hopkins/CDC.  So maybe this github starts with the State level data?

**Comment by jdkromkowski** [comment]
PS  
Puerto Rico 04-20 vs 04-21 isn't that reflecting active case change?
