### ISSUE TITLE
Two Texas counties decrememted data

### ISSUE THREAD

**Issue by furtip** [nytimes/covid-19-data#217]
4/22/20 | Hunt | Texas | 48231 | 38 | 2
4/23/20 | Hunt | Texas | 48231 | **37** | 2

4/22/20 | Johnson | Texas | 48251 | 61 | 2
4/23/20 | Johnson | Texas | 48251 | 61 | **1**

**Comment by albertsun** [comment]
Johnson county was an errant death that was counted from out of state. We've removed that now in the latest update.

The Hunt county case is a state revision where it's unclear where the case was reassigned to so we are not able to resolve that.
