### ISSUE TITLE
American Samoa has 60 cases in states file, but no counties record

### ISSUE THREAD

**Issue by ddenenberg71** [nytimes/covid-19-data#222]
Hi, I noticed American Samoa has 60 cases reported in the states file, but no records in the counties file.  Should it at least have an 'unknown' record in the counties file like other territories?  

I found this while incorporating territory statistics as supplemental data into my Virginia-centric site covid19va.net.  

Thanks and keep up the good work!  

Thanks,
David

**Comment by albertsun** [comment]
Hi @ddenenberg71,

American Samoa continues to have 0 cases. It was our error to include it in the datafile since we do not intend to include areas with 0 cases or deaths. (That 60 you are seeing is the FIPS code.)

**Comment by ddenenberg71** [comment]
@albertsun Thanks for the explanation.  Yeah, I looked too quickly at the '60' and thought it was a case number, but it was really the existence of the record in the states file without any records in the counties file that has caught by my charting engine.  Thanks for explaining.
