### ISSUE TITLE
Anomalous data entry in us_counties.csv

### ISSUE THREAD

**Issue by peterdaytx** [nytimes/covid-19-data#224]
Row | date | county | state | fips | cases | deaths
77765 | 4/21/2020 | Bucks | Pennsylvania | 42017 | 2067 | 116
80556 | 4/22/2020 | Bucks | Pennsylvania | 42017 | 2067 | 126
83357 | 4/23/2020 | Bucks | Pennsylvania | 42017 | 2197 | 118

Row 80556, reported Deaths value is unlikely!

**Comment by albertsun** [comment]
Hi @peterdaytx thanks for flagging this for us. The number of deaths for 4/23 was too low due to a data entry error and we've revised it upwards.
