### ISSUE TITLE
Testing Data

### ISSUE THREAD

**Issue by madbiker1** [nytimes/covid-19-data#225]
Does anyone have data that shows the number of tests administered per day by state?   I'd like to incorporate that into my analysis.  If it has positive and negative test results, even better.

**Comment by albertsun** [comment]
Our data set has focused on providing comprehensive counts of cases and deaths by county. Data on positive and negative tests is rarely available at the county level. The [COVID Tracking project](https://covidtracking.com/) seems to be doing a good job of tracking that at the state level though, and we’ve used their data in at least one of our articles [here](https://www.nytimes.com/interactive/2020/03/17/us/coronavirus-testing-data.html).

**Comment by madbiker1** [comment]
Thanks.   That site will work for what I need.
