### ISSUE TITLE
Add population data

### ISSUE THREAD

**Issue by kristynf** [nytimes/covid-19-data#226]
Could you add population data?

**Comment by j-p-c** [comment]
You can get population data from https://www.census.gov/programs-surveys/popest/data/tables.html. I have it joined in at http://johncostella.com/covid-19/data/latest.csv.

**Comment by Zoooook** [comment]
Also here: https://github.com/nytimes/covid-19-data/issues/180

**Comment by EllieLockhart** [comment]
I'd be interested in taking this on if the issue is still a concern for the project.

**Comment by tiffehr** [comment]
We are not adding population data to these files.  But more than a few users of this data have offered up their own additions or pointers to population figures.  We have been collecting them in [the Project board on this repo, in a column called Additive Data](https://github.com/nytimes/covid-19-data/projects/1), among others.
