### ISSUE TITLE
Data posted 4/26 mislabeled as including data through 4/26; actually through 4/25

### ISSUE THREAD

**Issue by cfhp1** [nytimes/covid-19-data#228]
The release notes from 4/26 mis-label the data set as including data through 4/26 rather than 4/25. On 4/26, this is easily spotted, but may create confusion on the morning of 4/27 when people are checking to see if the new data set has been posted.

**Comment by albertsun** [comment]
You're right, typo on my part. Sadly there is nothing to be done about it without rewriting the git history, which would cause even more problems.

**Comment by cfhp1** [comment]
I appreciate what you're doing for us, @albertsun!
