### ISSUE TITLE
Daily count

### ISSUE THREAD

**Issue by alexgenaud** [nytimes/covid-19-data#23]
Could it be possible to show the confirmed cases and deaths (new or cumulative) by date?

... like the Johns Hopkins data. For example:

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

**Comment by thoughtafter** [comment]
Are you suggesting a new dataset or a change to an existing dataset?

**Comment by cullylarson** [comment]
The dataset already includes cumulative cases and deaths. To get new cases, just subtract the difference between days. Or am I misunderstanding the request?

**Comment by cipriancraciun** [comment]
@cullylarson the original poster asks for a pivoted table (i.e. a single location is a single row, and each the dates are columns).  NY Times provides a "normal' (SQL like) data table.

@alexgenaud I have been working with the JHU dataset for a week now, and I can say that the pivoted table format is a mess, thus I hope NY Times team doesn't make the same mistake as JHU did...

**Comment by albertsun** [comment]
@alexgenaud the data we've released already has one row for each date and each geography.

If you are indeed asking for it to be formatted with individual dates as columns, then @cipriancraciun's suggestion is correct, you could create that format by creating a pivot table in your favorite spreadsheet tool.
