### ISSUE TITLE
Unpivoted case-level data with outcomes

### ISSUE THREAD

**Issue by yuryatin** [nytimes/covid-19-data#233]
Thank you so much for your very good and convenient data source. Are you aware of any source of anonymized _unpivoted_ case-level dataset with basic demographics, i.e., age, sex, and with the outcome (death vs. survival)?

**Comment by albertsun** [comment]
I'm not aware of any publicly available data source such as that. Certain states have released that data for cases that have died.

**Comment by yuryatin** [comment]
Thank you for your response. Much appreciated.
