### ISSUE TITLE
Methodology for calculated metro-level data?

### ISSUE THREAD

**Issue by mtdukes** [nytimes/covid-19-data#234]
Wanted to see if y'all could provide some details on how you're generating metro-level data for the upshot's reporting here:

https://www.nytimes.com/interactive/2020/04/23/upshot/five-ways-to-monitor-coronavirus-outbreak-us.html#next-hotspots

We've only been able to get county-level data so far, and the numbers generated don't seem to match up with what we're seeing on the local level. Thanks in advance.

Tyler Dukes // Reporter, WRAL News
tdukes@wral.com // 919.696.1935

**Comment by albertsun** [comment]
Hi Tyler,

Sorry to not get to your email earlier. That story is using Metropolitan Statistical Areas https://www2.census.gov/geo/maps/metroarea/us_wall/Jul2015/cbsa_us_0715.pdf which are composed of counties, so the data for any given area is just the sum of the county level data we have.

**Comment by mtdukes** [comment]
Thank you, much appreciated. On the hotspot identification that y'all are doing here, are you accounting for the small starting numbers at all? Some of the jumps we're seeing in NC highlighted in the story seem to be largely because they started low (3 or 4) and jumped up to 30ish.

**Comment by jharrison** [comment]
I've been working on metro-level analysis using a similar method, matching the counties to the metropolitan statistical areas defined in [this spreadsheet](https://hub.arcgis.com/datasets/47c5474c19cb4f4d9f102a84b4b8e462_2). One problem I've encountered is that there's a lot of data in the NYT set with "Unknown" as the county. Have you found a way to address that?

**Comment by kpq** [comment]
Hi Tyler –

I'm not certain which NC metro you're talking about, but we do have some floors for population and cases to make it into the tables: "Limited to areas with more than 250 cases and 50,000 people. The table showing the average daily growth of the death rate is limited to areas with more than 20 deaths."

Hope this helps. _KQ

**Comment by armsp** [comment]
@kpq @jharrison @albertsun @mtdukes Is there a mapping from counties to metropolitan statistical areas so that if we have the county level data we can aggregate them to get the same for metropolitan statistical areas?

**Comment by albertsun** [comment]
@armsp those mappings would be available from the U.S. Census Bureau.
