### ISSUE TITLE
Granville County, NC data inconsistency

### ISSUE THREAD

**Issue by cfhp1** [nytimes/covid-19-data#235]
Granville County, NC, shows 107 new cases on 4/27 that are not in the 4/28 count nor removed from the 4/27 count. Was this a reporting error that should be restated for 4/27? Thanks.

**Comment by albertsun** [comment]
@cfhp1 thanks for pointing this out. That was the number we got from the state that day. We're not sure why but we'll look into it.

**Comment by cfhp1** [comment]
Thanks.

**Comment by cfhp1** [comment]
The data is now consistent. The 107 extra cases on 4/27 were removed.
