### ISSUE TITLE
Dates off by one?

### ISSUE THREAD

**Issue by lematt1991** [nytimes/covid-19-data#237]
Looking at the us-counties.csv data, I see:

```
date,county,state,fips,cases,deaths
...
2020-04-28,Albany,New York,36001,1009,45
...
2020-04-29,Albany,New York,36001,1067,47
```

However, on the [New York State's website](https://health.data.ny.gov/Health/New-York-State-Statewide-COVID-19-Testing/xdss-u53e/data), these dates seem to be off by one:

```
Test Date,County,New Positives,Cumulative Number of Positives,Total Number of Tests Performed,Cumulative Number of Tests Performed
...
04/29/2020,Albany,98,1165,439,10310
04/28/2020,Albany,58,1067,351,9871
04/27/2020,Albany,30,1009,197,9520
```

Can you clarify what the dates correspond to in the CSV files?  I see in the README:

> For each date, we show the cumulative number of confirmed cases and deaths as reported that day in that county or state. All cases and deaths are counted on the date they are first announced.

But unless I'm misunderstanding, this doesn't seem to be the case.  Thanks!

**Comment by lwaananenjones** [comment]
The numbers that New York reports each day reflect the previous day's total. So the numbers publicly announced on the New York state website today, 4/30, are labeled as 4/29 in their own dataset.

**Comment by tiffehr** [comment]
We'll document this in our Wiki pages with frequently asked questions, which is coming soon.
