### ISSUE TITLE
Can we compare "normal" death rates to COVID death rates?

### ISSUE THREAD

**Issue by knwpsk** [nytimes/covid-19-data#238]
Curious whether anyone has done the work to compare "normal" vs COVID rates of death.  Please point out any "good data sources" if you know of them.

(Context: there are, or will be, arguments from some sides that COVID-19 isn't causing significantly larger numbers of deaths than would be the norm.... etc.  Clearly in some places such as NYC, where the hospitals and morgues are overflowing, one can argue on plain sight that this isn't true.  But can the data further support or refute this argument globally?)

**Comment by Nicole58** [comment]
CDC Wonder is where I’ve pulled data on death rates by age in the past. https://wonder.cdc.gov/ucd-icd10.html

Great question

**Comment by ericmock** [comment]
I have posted some a few graphs showing this on Facebook.  And will be posting more on my blog soon.

Here are the deaths per capita averaged over a one week period up until April 21. The yellow/orange bottom slices are heart disease deaths for reference.

![94171004_257086169013239_994789922688729088_n 2020-05-02 19_03_45](https://user-images.githubusercontent.com/25640/80894288-b5751e00-8ca7-11ea-913a-06bf079f8b7c.gif)

**Comment by knwpsk** [comment]
Eric that's cool.  Link to your blog?

**Comment by ericmock** [comment]
http://www.unstablefocus.com/wordpress
