### ISSUE TITLE
Am I wrong or is there no (death rate) data change for new york... somewhere around 87 days after january 21st?

### ISSUE THREAD

**Issue by andrew-luhring** [nytimes/covid-19-data#239]
I made this https://github.com/andrew-luhring/covid-differential-grapher

based on this data set. I'm trying to figure out why there's no change in death rate on day 87 and 88. Is that an anomaly in the data? Is the data wrong? Or am I just wrong somewhere in my processing of it. I'm pretty sure I'm processing it correctly; I'm kinda working under the assumption that NY ran out of tests or something. I vaguely remember that being a thing that happened... but I figured I'd ask.

<img width="965" alt="ny" src="https://user-images.githubusercontent.com/1039350/80840247-846eed80-8bc2-11ea-8107-2d33a801f29f.png">

**Comment by albertsun** [comment]
Hi @andrew-luhring,

If you take a look at the README, you'll see a note there describing how New York State didn't report any data on new deaths for those two days in April. It wasn't a lapse in testing, just a lapse in the announcement of new data.

**Comment by donovanrichardson** [comment]
@andrew-luhring On April 18, NYS deaths all seem to be accounted for in “Unknown” county. This is the last day that has cases or deaths assigned to unknown county. In the state-by-state file, new deaths reported for April 18 without the issue of having an unknown county. 
If you need county-level data, this might be an issue, but the statewide data seems fine as long as you’re accounting for unknown county or using the state-by-state file. ![Unknown county](https://user-images.githubusercontent.com/50427582/80869018-ed5e7000-8c6b-11ea-9598-d5e13c29acb7.png)
