### ISSUE TITLE
Is the Dataset used in this NYT Video Available?

### ISSUE THREAD

**Issue by trisongz** [nytimes/covid-19-data#24]
[YouTube Video Link - How China Is Reshaping the Coronavirus Narrative](https://youtu.be/LwqhvRcBrK4)

I'm working on building a model around classification of information that is spread around the internet about covid-19, as a growing number of actors are using the topic to further their personal agendas. The dataset and method for labeling the data would be extremely helpful.

Great reporting on the video!

**Comment by albertsun** [comment]
Hi @trisongz, we're glad that you enjoyed the video. We are not planning to publicly release that dataset. Best of luck on your research. More work there is certainly necessary.
