### ISSUE TITLE
Data reporting inconsistency (South Carolina)

### ISSUE THREAD

**Issue by philipmnelson** [nytimes/covid-19-data#240]
It's not a huge issue, and definitely not the Times' fault, but on [April 29 South Carolina](https://www.scdhec.gov/index.php/news-releases/dhec-conducts-cross-analysis-death-certificates-confirmed-covid-19-cases) reported an additional 29 deaths that had not been included in their running total until that day. If you are working with this data you might notice that this looks like a spike in deaths on that day but it's not. 

Here's a graph showing what looks like a peak
[
![combinedDeaths](https://user-images.githubusercontent.com/12937257/80852344-d0875580-8bf5-11ea-9715-702d6c84a063.png)
](url)

The dataset does not reflect this but SC DHEC also posted the dates of these deaths in [a file](https://www.scdhec.gov/sites/default/files/media/document/COVID-19-Additional-Deaths-4.28.2020.pdf) and counties in which the deaths occurred on their site. If needed, I can submit a PR but I realize this might not be wanted.

**Comment by albertsun** [comment]
Thanks @philipmnelson, this is certainly a gotcha people should be aware of, but it's actually not inconsistent within the overall data set. Our methodology is to use the date of death reported, not date of death. While date of death may be more intuitive, if we were to switch over we would attempt to do so consistently across all geographies.

We've noted this case for a potential future revision but will not be backdating those deaths at the moment.
