### ISSUE TITLE
Data Issue:  No new cases or deaths in Connecticut for 3 May

### ISSUE THREAD

**Issue by ArleneMaps** [nytimes/covid-19-data#246]
### Describe the issue:
- [x ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
Looks like Connecticut took the day off from reporting.   There is no change in cases or deaths for any of the counties I checked.

**Comment by albertsun** [comment]
Hi @ArleneMaps yes, that is indeed the case. They said that they are taking the day off to change over their own data collection process and the update today (tomorrow for us) will have all new cases lumped in.

Unfortunately there's not much we can do to provide data if the state has not done so.
