### ISSUE TITLE
Connecticut 5/3/2020 data unchanged.

### ISSUE THREAD

**Issue by mgbyrnes** [nytimes/covid-19-data#247]
Connecticut 5/3/2020 State and County data the same as 5/2/2020.
One exception is the Unknown County data -- for both cases and deaths -- has been reduced:

$ diff -c 2020-05-02 2020-05-03
*** 2020-05-02	2020-05-04 13:02:38.000000000 -0400
--- 2020-05-03	2020-05-04 13:01:37.000000000 -0400
***************
*** 5,9 ****
  New Haven,Connecticut,09009,8024,565
  New London,Connecticut,09011,623,43
  Tolland,Connecticut,09013,461,39
! Unknown,Connecticut,,371,2
  Windham,Connecticut,09015,211,2
--- 5,9 ----
  New Haven,Connecticut,09009,8024,565
  New London,Connecticut,09011,623,43
  Tolland,Connecticut,09013,461,39
! Unknown,Connecticut,,312,1
  Windham,Connecticut,09015,211,2

**Comment by lwaananenjones** [comment]
Connecticut did not announce new cases on 5/3. The health department included this note in its daily report:

> NOTE: The Connecticut Department of Public Health is transitioning to a new process to make the daily collection of data more sustainable. To facilitate this shift, the report issued today (Sunday, May 3) only contains data on hospitalizations and fatalities. The next full report will be issued on the afternoon of Monday, May 4, and will contain combined data from both Sunday and Monday.

https://portal.ct.gov/-/media/Coronavirus/CTDPHCOVID19summary5032020.pdf

**Comment by mgbyrnes** [comment]
Thanks for the response and the doc pointer!
