### ISSUE TITLE
Data Issue:  4/23 - 4/24 Alameda County Death Count

### ISSUE THREAD

**Issue by caryhz** [nytimes/covid-19-data#250]
### Describe the issue:
- [X] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
If 'deaths' in the us-counties file is meant to be a cumulative count, then there may be a typo on 4/23's Alameda County (California) death count. It's currently at '53' when 4/24's death count is '48'. 4/22's count was '43' for reference. 4/23 may be a simple typo and may have meant to be '43' again, with it decreasing up to '48' on 4/24. 

Please let me know if that's the case or if i'm interpreting 'death's incorrectly. 
<img width="339" alt="Screen Shot 2020-05-04 at 9 27 02 PM" src="https://user-images.githubusercontent.com/12985315/81035035-058de500-8e4e-11ea-828c-eb24b03a447e.png">

**Comment by albertsun** [comment]
Hi @caryhz, we've amended this number in today's update.
