### ISSUE TITLE
Question: JHU CSSE or NYTimes Discussion?

### ISSUE THREAD

**Issue by briancpark** [nytimes/covid-19-data#257]
### Do you think there is an error in the data?
I was primary using https://github.com/CSSEGISandData/COVID-19 provided by JHU CSSE, a database that many are probably using right now because it updates international data. 

### Do you have a question about the LICENSE or permission to use this data?
Please email us at covid-data@nytimes.com

### Your question
What databases are you guys relying on for US data? There are many complaints on the JHU CSSE that the data isn't accurate or isn't updated regularly?

**Comment by albertsun** [comment]
@briancpark this data is pulled from our own database compiling case counts from state and county health departments through a combination of automated scrapers and human reporting. You can read more about how we collect the data in the [README.md](https://github.com/nytimes/covid-19-data)

**Comment by tiffehr** [comment]
If you would like a comparison of sources, peers of ours at OpenNews wrote up a summary of some frequent data sources:  https://source.opennews.org/articles/comparison-four-major-covid-19-data-sources/

**Comment by briancpark** [comment]
@tiffehr Thank you for the link. A lot of university students are probably involved with doing COVID-19 related projects. So it's important to know how the data is collected and how it differs from other sources, especially in a field like data science or information science.
