### ISSUE TITLE
Enhancement:folks Population and Land Area

### ISSUE THREAD

**Issue by drwiremore** [nytimes/covid-19-data#258]
It was hard for me to find, but I've added 2019 population, and land area by county.  It is based on your good work, and as an xlsx, it is attached.  Nothing flashy - populations from the USCensus, and land area constructed from US Census tiger files by fips.

This allows people to see, by county, and land area where there is indeed a high death rate.

While well received, the CISO community tracking this report asked for how many have been tested, and how many recovered.  At the county level, this would be most helpful.

I know your busy, but I'm seeing your data not as current as it used to be.  The pull from today says it is 20 hrs old, but it is data from 5/5, and today is 5/7.  It is older than that.  Let me know if I can help.

Here is your data organized with population and land area to paint a picture by county of deaths / population density.  The hot spot isn't NYC.
[COVID counties by pop density 20200507.xlsx](https://github.com/nytimes/covid-19-data/files/4593126/COVID.counties.by.pop.density.20200507.xlsx)

drWireMORE

**Comment by tiffehr** [comment]
Thank you!  You might consider collaborating or consolidating with #180, too.

**Comment by drwiremore** [comment]
The uscensus tiger files have the fips for all counties, parish, boroughs in the usa including Puerto Rico. While the population numbers are 3019, the land area is the same

By combining uscensus population by counties and land area , 

~jff
