### ISSUE TITLE
Data Issue:  May 6 data is 

### ISSUE THREAD

**Issue by Laza77** [nytimes/covid-19-data#259]
### Describe the issue:
- [x] Incorrect number of cases or deaths
- [x] Suspicious number of cases or deaths

![Screenshot 05-07-2020 13 45 58](https://user-images.githubusercontent.com/50716446/81327367-22eacb00-9069-11ea-985c-b8531484742d.png)

- [ ] Missing time-series information
- [ ] Other

### Fuller details
I've been using this data for my visualizations for more than a month.  For some reason numbers for May 6 are enormously high.   (see attached image)

**Comment by albertsun** [comment]
Hi, our May 6 data currently includes probable deaths in NYC whereas our May 5 and prior data does not. We plan to revise the historical data to include probable deaths as well.

We've now added a more extensive note about this change here https://github.com/nytimes/covid-19-data/blob/master/PROBABLE-CASES-NOTE.md

**Comment by guzhiling** [comment]
Hi Albert,

Thank you so much for your hard work and updates on this.

**Comment by albertsun** [comment]
As of the update we published yesterday, there is no longer this large single day spike.
