### ISSUE TITLE
Jump in Wyoming number of cases?

### ISSUE THREAD

**Issue by brianocliff** [nytimes/covid-19-data#260]
Thank you for all your efforts gathering and publishing this information. It's wonderful to have these data so easily available and so often updated. Sorry if I missed an explanation elsewhere, but I don't understand the rather large jump in the number of cases for Wyoming in today's release. May I ask what caused that? Thanks again!

**Comment by ke4roh** [comment]
https://www.gillettenewsrecord.com/news/wyoming/article_72463d30-fba9-5af1-affa-9b0d104f064a.html

They reported/detected a lot more.  It is the fastest-blooming state in the Union today.  See also my fork which includes a map of the rate & saturation: https://github.com/ke4roh/covid-19-data

**Comment by brianocliff** [comment]
Hi ke4roh,
Thanks. I also saw that article. The Gillette News Record (that you referenced) reported an increase of 27 cases. These data have a one day increase of 179 cases. That seemed to be a significant difference.

**Comment by brianocliff** [comment]
Hi ke4roh,
Thanks. I also saw that article. The Gillette News Record (that you referenced) reported an increase of 27 cases. These data have a one day increase of 179 cases. That seemed to be a significant difference.

**Comment by albertsun** [comment]
Hi, yes, part of the jump in Wyoming is from that true increase, but part of it is also because the data for 5/6 includes probable cases and the data for 5/5 does not. Our plan is to update the data for past day's to include the probable cases as well.

**Comment by albertsun** [comment]
There's some more detail about the tradeoffs involved and our decision to start including those probable cases here https://github.com/nytimes/covid-19-data/issues/261#issuecomment-625533999
