### ISSUE TITLE
Data Issue: Indiana data spiked up on 5/6, but I'm not seeing that reported anywhere.  

### ISSUE THREAD

**Issue by tljthree** [nytimes/covid-19-data#263]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [x] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
Indiana data for May 6 indicates an additional 164 deaths. This is over double the number of deaths that Indiana has experienced on any other day. Also, the number of new cases jumped to a new daily record that was over 30% higher than the previous daily record in Indiana.

Of course, this could just mean that someone was correcting a past undercount in the data.

**Comment by albertsun** [comment]
Hi, our May 6 data currently includes probable deaths in Indiana and elsewhere, whereas our May 5 and prior data does not. We plan to revise the historical data to include probable deaths as well.

We've now added a more extensive note about this change here https://github.com/nytimes/covid-19-data/blob/master/PROBABLE-CASES-NOTE.md

**Comment by tljthree** [comment]
Thanks. I appreciate your work.
I'm curious why you wouldn't just add new categories for "probable" cases and deaths, instead of mixing probable and confirmed in the same data? That would let us manage those 2 types of data separately, adding them together when we need to, and keeping them separate when we don't. It would seem to allow richer analysis possibilities.
Thanks again.

**Comment by ke4roh** [comment]
tljthree, they aren't listed separately because states aren't reporting them separately.  As nice as it would be to have the two sets, it's not available.

**Comment by tljthree** [comment]
Thanks for your service and your help. 
I saw the spike on May 6, but haven't seen cases sustain at that level since. 
Is the daily data for Indiana including probable cases every day since May 6, or are they just periodically "leveling up" probable cases on a single day (e.g. May 6)?
Also, if there is a resource that explains the different state methodologies for reporting probable cases, I'd be glad to read that.
Thanks again. I appreciate what you do.

**Comment by amyswalk** [comment]
Hi @tljthree, thanks for your question. Indiana posts a cumulative probable death count that is separate from the lab-confirmed death figure. The state says it does not include probable deaths in its confirmed death totals. The state has been collecting these figures and officially began reporting them on its dashboard on April 24. As the state continues to gather information on past probable deaths, that cumulative number could jump.
