### ISSUE TITLE
Example: US COVID-19 Cases Timelapse by Counties (Suggestions welcome)

### ISSUE THREAD

**Issue by briancpark** [nytimes/covid-19-data#264]
### Describe the project
Made a timelapse of COVID-19 cases by US counties using the FIPS metadata and plotly geo json mappings. All written in Python in Jupyter Notebooks.

Right now, the next steps are to tune the parameters because the cases are maxed out at 1000. Please give suggestions for better max cases or better color gradients. 

If you are interested in using the code or timelapse, please make sure to credit me.

### Have a URL or images of the project?
[GitHub Repository](https://github.com/briancpark/COVID-19-Visualizations)

[`.gif` Version](https://github.com/briancpark/COVID-19-Visualizations#covid-19-cases-in-the-united-states-of-america)

[Video Download](https://github.com/briancpark/COVID-19-Visualizations/raw/master/timelapses/us_confirmed_timelapse.mp4)

![gif](https://github.com/briancpark/COVID-19-Visualizations/raw/master/timelapses/us_confirmed_timelapse.gif)

EDIT: Fixed gif compression bugs!

**Comment by knwpsk** [comment]
I like your work Brian.
Suggestion: The video needs some explanatory captions.  What's the date range?  Do the blocks represent counties?

If/when the video gets shared, it loses the context of your github page etc.

**Comment by tanimislam** [comment]
Hello, I have done something similar as well. Demonstrations are located at my Github repo, https://github.com/tanimislam/covid19_stats.

**Comment by briancpark** [comment]
@knwpsk Thanks for the suggestions! 

I update this repo everyday, so it's dependent on how fast the NYTimes updates their databases. I implemented your suggestions and they can be found under the same link or [here](https://github.com/briancpark/COVID-19-Visualizations/raw/master/geo/geo_us/us_cases_timelapse.mp4).

**Comment by briancpark** [comment]
@tanimislam Thanks for sharing! I looked at it. May I ask what libraries you used, especially for plotting the maps? I mainly used plotly and then Selenium to screen capture the plotly graphs. It's a very brute force way and takes a long time to compile, but I couldn't find any other cleaner way.

I really like how you matched the COVID-19 curve with a pointer and matched it with the corresponding plethora map!

**Comment by tanimislam** [comment]
@briancpark I heavily used [matplotlib](https://matplotlib.org) for the plotting, and [Basemap](https://matplotlib.org/basemap/) for the geographic features, specifically in a way where I don't have to pop up the canvas on-screen.

If you are interested, we can continue this discussion elsewhere!

**Comment by briancpark** [comment]
@tanimislam Yes! I'm interested in learning more about your methods. My email is [briancpark@berkeley.edu](mailto:briancpark@berkeley.edu)
