### ISSUE TITLE
Enhancement: Growth Rate Color Charts

### ISSUE THREAD

**Issue by DrKarner** [nytimes/covid-19-data#266]
The doubling-rate colored-bar charts would be improved by changing from cumulative cases to cases from the prior week. Presently, nearly every geographic area has colors implying longer doubling times (less disease). This is because cumulative cases have become so much larger than new cases that even new highest rates of infection will yield longer doubling times.

**Comment by jdkromkowski** [comment]
"Cumulative cases have become so much larger than new cases that even new highest rates of infection will yield longer doubling times."

This is another reason why RECOVERED cases needs to be tracked so that ACTIVE cases can be reported.  Its the doubling rate of active cases that is the more important metric.

**Comment by tiffehr** [comment]
@DrKarner Could you please clarify which charts you mean?  Perhaps with a URL or screenshot?  

If you mean a visualization submitted by the public using the data available in this repository, could you please provide a pointer to that Issue?  

(We have started [a collection of the public's examples here](https://github.com/nytimes/covid-19-data/projects/1), in the column labelled `Examples`.)

**Comment by DrKarner** [comment]
I mean the NYT's "Case Growth Rate" chart which is color scaled based on the doubling rate (fastest in red= 3 days, whereas slowest in white = more than 30 days). Figure attached. My point is that after 30 days of cumulative cases (let's say the cumulative cases is 30,000, so 1,000 per day average), if the daily new case count on day 31 is below the average new cases of the preceeding 30 days (i.e. below 1,000) it would be shown as the lowest color option (white). 
If cumulative cases have accrued over a longer period of time (say it's 90 days, and total cases = 90,000, so the daily average still is 1,000), then day 91's new case load would need to exceed 3,000 to register above the lowest color rank  because case doubling is based on cumulative total cases. Consequently, all the "Case Growth Rate" entries are headed towards white, even though daily new cases may be at record highs (see second figure for same time period).
![Screenshot_20200508-175011_NYTimes](https://user-images.githubusercontent.com/65095879/81751916-45b02180-9465-11ea-89c4-eada10b24dff.jpg)
![Screenshot_20200508-174923_NYTimes](https://user-images.githubusercontent.com/65095879/81751957-5496d400-9465-11ea-951c-8addc79ff4c9.jpg)

**Comment by tiffehr** [comment]
Is this a Data Issue or an Enhancement? I understand the methodology points but I'm unclear what you want this public data set to do.

**Comment by iancsf** [comment]
From what I've read, most states and localities are not reporting either active-cases or recovered cases in a consistent manner that could be incorporated into the database.  However, a reasonable estimate of active-cases can be made with a little math.  
Usual Recovery time is reportedly approximately just over 3 weeks:  "The average time for recovery and hospital discharge was a little over 22 days." (non-hospitalization recovery closer to 2 weeks).
https://www.webmd.com/lung/news/20200331/covid-19-death-rate-drops-still-deadly-to-seniors
https://www.webmd.com/lung/covid-recovery-overview#1

Thus if we assume everyone with Covid-19 from 3 weeks ago is either recovered or has died, a simple estimate of active cases would be:
     
active_cases = sum(3-weeks_daily_cases) - sum(3-weeks_daily_deaths)

where daily cases can be derived from the NYT data simply by differencing the cumulative counts reported in the NYT data.

**Comment by tiffehr** [comment]
@iancsf We are not likely to calculate this type of figure, or include it in this data set where it is missing.  In a [related request](https://github.com/nytimes/covid-19-data/issues/269#issuecomment-627521778_), my colleague @albertsun explained
> [...] Many states seem to report "Recovered" as an inferred metric, where any case past a certain number of days is assumed to be recovered unless they've died. My feeling is the data is just not that reliable.

We have been selective about when we collect or tally it — only when we can confirm how the location's methodology.

**Comment by iancsf** [comment]
I agree.  While it would be useful to know both active and recovered numbers,  in the absence of testing previously positive cases to track recovery, any published figure would just be an approximate figure.  I had intended this as a suggestion for those requesting the enhancement:  if you want an estimate of that figure, here's how you can calculate it easily from the data.  But as I stated above, this would merely be an estimate.   

Apologies for not making that clear.

**Comment by DrKarner** [comment]
tiffehr: Sorry for delayed response. My comments were geared towards graphics enhancement. The doubling rate color scale (from white to red) loses its effectiveness as the pandemic marches on because the Doubling rate = cumulative cases / today's cases. Today's cases will always represent a smaller fraction of the cumulative cases, so the doubling rate, even when the daily caseload is constant, will take longer.
Example: With new cases is a constant 1,000 per day. 
At day 2:
Cumulative cases / new cases 
equals
2,000 / 1,000 = 2 days.
Color select
5,000 / 1,000 = 5 days. 
Color selection= orange.
Reader's impression: It's
At day 30:
30,000 / 1,000 = 30 days.
Color selection= white.

**Comment by iancsf** [comment]
DrKarner's comments seem to refer to a calculation using all data, rather than looking at the  slope of the log of the last few data points.   Using the last 2-weeks gives a better estimate of the current trend.
In my calculations and figures, doubling/halving rate is calculated using the log-linear slope of the most recent 14 days.   Specifically, I fit a straight line to the last 14 points of log(counts) .  With that, the doubling rate is given as:
     doubling_rate = log(2)/slope(14 points)

This is, of course, more susceptible to noisy data, so is more valid for states and countries than for individual counties, except for counties with very high counts.

 The figures give 3 rates for cases:
     doubling rate for total cases
     doubling/halving rate for estimate of active cases
     doubling/halving rate for daily (7-day) average # of cases
And 2 rates for deaths:
     doubling rate for total deaths
     doubling/halving rate for daily (7-day) average # of deaths.

**Comment by tiffehr** [comment]
@DrKarner, @iancsf :  I have relayed your comments to the NYT editors who are working on our visualizations.  That work is separate from this data set, which is focused on data collection and normalization.  We are not augmenting this data set with NYT's internal analysis/classifications, so the methodology of what we offer here should be largely unchanged and reliable.
