### ISSUE TITLE
Enhancement: case cluster data (as used in NYT stories) as a public data set here

### ISSUE THREAD

**Issue by bfeldman89** [nytimes/covid-19-data#267]
### Describe the feature you would like to see
The NYT [data on the largest clusters](https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html#clusters) in the country is what I rush to when checking the NYT website for updates. It’d be amazing if that data were shared here!

![64C9750D-B3BC-4F74-BDFE-3BA8B57E7994](https://user-images.githubusercontent.com/26087892/81489248-ea015080-9238-11ea-8ed2-dbecc124ba8c.png)

### Describe alternatives you've considered
An additional feature could be categorizing the cluster sources  (e.g., meat processing plant, ship, correctional or detention facility, or long-term care facility). I think it’d really help communicate the extent of the crisis in prisons in jails. 

[![231D9CD4-2D5A-4FB1-8603-FFE370E1CCA8](https://user-images.githubusercontent.com/26087892/81489990-da3a3a00-9241-11ea-82e3-4ffdd521efb5.jpeg)](https://twitter.com/davidminpdx/status/1259318025351659521)

___
btw, THANK YOU! 🙏

**Comment by joelmiller** [comment]
Just reupping this.  I'm looking for exactly this data set.
