### ISSUE TITLE
Android Application 

### ISSUE THREAD

**Issue by chasefarmer2808** [nytimes/covid-19-data#268]
I have released an Android Application to the Play Store to show this data.  It is currently under review and pending approval.  Apparently, Google has become more strict about C-19 apps they are allowing to be published on the Play Store, so we'll see what happens.  

The app is called COVID Hero, and its purpose is to give the user personalized information and resources based on their location and community.  In this first release, it does this by displaying this amazing county data set.  The user can see the latest case and death counts, and see the trend over time in a histogram chart.  The bars in the chart are conditionally colored; red if the count went up compared to the previous day, and blue if it stayed the same or went down.  That way, the user can quickly see upward and downward trends in the data.

If this gets approved, I will expand the app in future releases to show the state and US data.  Hope you like it!

![Screenshot_1589118052](https://user-images.githubusercontent.com/6749277/81500828-bbb85b00-92a2-11ea-9d06-4a69e9780a5a.png)
![Screenshot_1589118056](https://user-images.githubusercontent.com/6749277/81500829-bc50f180-92a2-11ea-8b3a-4467f9e4edb2.png)
![Screenshot_1589118081](https://user-images.githubusercontent.com/6749277/81500830-bc50f180-92a2-11ea-9cfe-4e4c6552e015.png)
![Screenshot_1589118085](https://user-images.githubusercontent.com/6749277/81500831-bc50f180-92a2-11ea-8364-6cba7bc4ec15.png)
![Screenshot_1589118192](https://user-images.githubusercontent.com/6749277/81500833-bce98800-92a2-11ea-8510-7a8f51bd517f.png)
![Screenshot_1589118033](https://user-images.githubusercontent.com/6749277/81500834-bce98800-92a2-11ea-88c8-7af9a8088696.png)

**Comment by chasefarmer2808** [comment]
This unfortunately, but understandably got rejected by Google today.

**Comment by briancpark** [comment]
@chasefarmer2808 Sorry to hear that. If this app is written in React Native, you could try the iOS App Store, given if you already paid the $100 developer account. But please note that Apple will probably also reject the app. Apple and Google are trying their best to avoid misinformation, and the best way to do that is only approve apps by approved health organizations. Other than that, it's a good idea and app!

**Comment by steliokontos** [comment]
Is there an APK available?

**Comment by chasefarmer2808** [comment]
@briancpark thanks for this!  Yes I was a little disappointed because this is my first app I've tried to publish.  But I understand Google's decision.  And I agree, I don't think Apple will be anymore flexible.

@steliokontos I have not made the APK available.  I assume this would be through some CDN?  Maybe even a cloud storage link?  This is my first time distributing an Android app, so I'm unsure if this is even wise/good practice.  Open to discuss.

**Comment by tiffehr** [comment]
This lives within our Examples collection on our Project board.  Closing, though you're welcome to continue discussion.
