### ISSUE TITLE
Enhancement: Will a recovered dataset ever be added to this database?

### ISSUE THREAD

**Issue by briancpark** [nytimes/covid-19-data#269]
### Is your feature request related to a data problem?
No recovered patients show in this database.

### Describe the feature you would like to see
A recovered dataset if possible. I understand that the data collection of this is another big task and it has to be accurate if it were to be done by counties. But first, a recovered dataset by state for now would be a good start.  

### Describe alternatives you've considered
I've already read #248. But the collaborator of the database never stated if there are plans in the future to include it. Just curious if the NYTimes is working on collecting data at the moment. If not, other databases seem to include it (for example [JHU CSSE](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data)).

**Comment by albertsun** [comment]
@briancpark we're not collecting it right now and have no plans to include it. Many states seem to report "Recovered" as an inferred metric, where any case past a certain number of days is assumed to be recovered unless they've died. My feeling is the data is just not that reliable.

**Comment by MyklClason** [comment]
@albertsun In order words, it may be better to just create our own recovered data if that is basically how it's going to work anyway? 

IE: Start at the day 1 data (first confirmed cases), set those as the "active cases" then each day drop the active cases by 1/x (assuming the average case recovers after X days after infected, this is probably anywhere from 0.5X to 2X, so the accuracy is roughly a factor of 2) and then add the new cases minus deaths that day to get the active cases for that day. Repeat for each day to get the current active cases for that day (recovered is then cases - active cases - deaths). A bit hacky, but might be accurate enough for rough estimation purposes of current active cases. Active cases should be stored as a float, but displayed as ceil. If below 1/Xth of case, then count it as 0 active cases.

**Comment by tiffehr** [comment]
@MyklClason If you need these figures and are fine with current caveats about how they're determined by localities, I recommend looking at the [COVID Tracking Project's data](https://covidtracking.com/data).  They include recovery figures for a number of locations, though the same questions apply about methodology.  I would not recommend deriving this number in the manner you describe.  That could very well compound methodological problems.

**Comment by MyklClason** [comment]
@tiffehr Fair enough, not an overly accurate method to do it exactly as mentioned, seeing the flaws, though it does seem to be within the expected margin of error compared to the recovered totals there. However, that margin of error was quite high (factor of 2). Anyway, won't be using that.

**Comment by albertsun** [comment]
@MyklClason I would not recommend that you do that. While an epidemiologist may choose to infer or derive such a metric for a specific analysis they are doing (I don't know if they would, I am not an epidemiologist), if you are doing this in order to add a number to a public-facing website displaying Covid-19 statistics, I would strongly urge you to consider not showing a recovered number at all. While there may be a "best number you can get", it is still worth considering if that best is good enough, compared to not showing a number at all, and fully considering the potential downsides if that number is wrong. There is so much still unknown about this disease.

**Comment by MyklClason** [comment]
@albertsun Agreed. Not adding a public website, more did out of curiosity (again, expected margin of error too high to be useful, publicly). Will use one of the above links for recovered if I end up displaying it at all.
