### ISSUE TITLE
Add Pending Test Column

### ISSUE THREAD

**Issue by s7726** [nytimes/covid-19-data#27]
Please add a column for pending tests.

**Comment by thoughtafter** [comment]
This would be good. However, I don't think most states have been reporting this and getting access to historical data may be an issue.

**Comment by adrianhamins** [comment]
https://github.com/COVID19Tracking/covid-tracking-data/tree/master/data

There are other data sources attempting to track pending cases as of a timestamp each day.

**Comment by s7726** [comment]
Not updated very often, and not down to county level.
If we're just going to point to other resources to get a complete dataset, why not contribute to the other source instead of making another source.
