### ISSUE TITLE
Data Issue:  May 10 counties data

### ISSUE THREAD

**Issue by ArleneMaps** [nytimes/covid-19-data#270]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [x ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
I don't see the May 10 data in the counties data that was just posted for May 10. Thanks.

**Comment by briancpark** [comment]
It shows for me. Please make sure you pulled correctly.

**Comment by ArleneMaps** [comment]
Thanks, you're right, I refreshed the page with the links, but not the
actual data page.
Arlene
