### ISSUE TITLE
Data Issue:  FIPS 31043

### ISSUE THREAD

**Issue by seeess1** [nytimes/covid-19-data#272]
### Describe the issue:
- FIPS 31043 had 1407 cases between 5/8 and 5/10. Seeing the same numbers from other scrapers so there probably isn't an issue with NYT method. Probably more of an issue with how this county is reporting their data. Might require follow up with their health department.

**Comment by albertsun** [comment]
@seeess1 yes, it appears the county had no update on new cases over the weekend. We're seeing more places moving towards somewhat less regular reporting.

**Comment by seeess1** [comment]
Oh, interesting (and frustrating/saddening).
