### ISSUE TITLE
Enhancement: Testing by Day Provides real insight into case growth #s

### ISSUE THREAD

**Issue by rht6rht** [nytimes/covid-19-data#275]
I don't see the number of tests by day available anywhere, those data points will give true power to the new cases number.  Provides invaluable perspective and context.

**Comment by tiffehr** [comment]
We are not tracking testing data.  Data is inconsistently defined and irregularly available.  In previous requests like this, we explained:

> Our data set has focused on providing comprehensive counts of cases and deaths by county. Data on positive and negative tests is rarely available at the county level. The [COVID Tracking project](https://covidtracking.com/) seems to be doing a good job of tracking that at the state level though, and we’ve used their data in at least one of our articles [here](https://www.nytimes.com/interactive/2020/03/17/us/coronavirus-testing-data.html).

_Originally posted by @albertsun in https://github.com/nytimes/covid-19-data/issues/225#issuecomment-619586551_

**Comment by rht6rht** [comment]
@Tiff
Thank you, very helpful!
