### ISSUE TITLE
Question:  How Frequent Will the Live Directory Be Updated?

### ISSUE THREAD

**Issue by briancpark** [nytimes/covid-19-data#276]
### Your question
I've read the updated commits and README, but nowhere it states how often the `live/` directory will be updated? Once, twice, three times per day? Or as soon as information is received? That would equate to a lot of commits. 

Is the `live/` just a place holder for number of cases on the unfinished day it was committed and pushed to? Or is it actually really "live" data? There seems to be ambiguity in the term "live" that I and some other users might mistake it for. Apologies if how frequent the directory or database will be updated is already stated elsewhere.

**Comment by albertsun** [comment]
Hi @briancpark, it's hard for us to make guarantees on how often. The best we can say now is several times a day.

It's more "live" than the historical data is all.
