### ISSUE TITLE
Data Issue: Municipality-level data for Puerto Rico

### ISSUE THREAD

**Issue by seeess1** [nytimes/covid-19-data#277]
Municipality-level data exists for Puerto Rico and can be scraped here:

https://bioseguridad.maps.arcgis.com/apps/opsdashboard/index.html#/3bfb64c9a91944bc8c41edd8ff27e6df

The raw data includes FIPS codes that align with the county-level FIPS codes in other states.

**Comment by seeess1** [comment]
I'm seeing data for Puerto Rico with FIPS codes now in live/us-counties.csv, which is great. But in the historical timeseries us-counties.csv file, it looks like all the Puerto Rico data is still being recorded with "Unknown" for the FIPS code.

**Comment by albertsun** [comment]
@seeess1 yes, we have not added them there because unfortunately we do not have the complete timeseries for the municipios. We don't have data for them early on in the outbreak.

**Comment by seeess1** [comment]
Ah I see
