### ISSUE TITLE
Jupyter notebook to get people started?

### ISSUE THREAD

**Issue by tnovikoff** [nytimes/covid-19-data#28]
You may want to consider including a sample Jupyter notebook in your repo to help people get started with this data even more easily. Best of luck and let me know if I can help in any way!

-Tim Novikoff
PM for [Colab](https://colab.research.google.com/notebooks/intro.ipynb)

**Comment by gbriddick** [comment]
I second this suggestion.  I have little experience with Jupyter Notebooks, otherwise I’d try my had at it.

**Comment by albertsun** [comment]
@tnovikoff our plan is to keep this repo plan and simple with just the data - but it looks like someone else has in fact created such a notebook here: https://github.com/nytimes/covid-19-data/pull/30

While we do like seeing so many people already using this data to learn data analysis and visualization, and we are huge fans of Jupyter Notebooks here at the Times, we really do hope that it is of the most use to professional epidemiologists and those experienced with working with disease incidence data.

**Comment by jsirott** [comment]
For anyone interested, you can get the sample notebook from my forked respository at https://github.com/jsirott/covid-19-data. I've also added some census data with county population data as well.
