### ISSUE TITLE
Massachusetts data

### ISSUE THREAD

**Issue by Pedro-McM** [nytimes/covid-19-data#281]
### Describe the issue:
- [x] Incorrect number of cases or deaths

There is a big inconsistency between the New York Times data and the official Massachusetts data.  Just curious why.

I noticed that when I used the NYT data to calculate new deaths for 5/12, I got 33.  But Massachusetts reported 105 (stated as confirmed; not sure about probable).  Then I noticed that the official Massachusetts cumulative deaths numbers are somewhat different than those of the NYT.

[https://www.mass.gov/info-details/covid-19-response-reporting](https://www.mass.gov/info-details/covid-19-response-reporting)

For example (cumulative deaths):
Date   Mass   NYT
5/11   5408   5108
5/12   5513   5141
5/13   5513   5315
5/14   5679   5482

**Comment by lwaananenjones** [comment]
In our data, all cases and deaths are counted on the date they are first announced. Some states are using other methods for their historic data, such as date of death, which is what Massachusetts does in its DateofDeath.csv file. Massachusetts also has an [archive of previous daily reports](https://www.mass.gov/info-details/archive-of-covid-19-cases-in-massachusetts), which includes the counts announced each day.

Deaths are usually not announced until a day or two after the death occurred, and in some instances there is a delay of weeks or even months. So the adjusted historical counts are usually higher than the count announced on that day.

**Comment by Pedro-McM** [comment]
Thanks!
