### ISSUE TITLE
Data Issue:  Colorado May 15

### ISSUE THREAD

**Issue by WilliamBrotherton** [nytimes/covid-19-data#282]
### Describe the issue:
- [X] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
On May 15th Colorado changed its method of reporting, and the way I see it listed may be messing with your script creating an inconsistency in data. I live in Colorado, so I only monitor data from Colorado. 

For example May 16th data shows:
Deaths: 1192 (in red)
Then displays
Death among cases (878 due to COVID-19)

I suspect May 15th data to show:
Deaths: 1150*
Deaths among cases (878 due to COVID-19)

**Comment by albertsun** [comment]
@WilliamBrotherton thanks for letting us know. We're taking the higher total number of deaths in Covid-19 cases.
