### ISSUE TITLE
NM data?

### ISSUE THREAD

**Issue by shott** [nytimes/covid-19-data#283]
Hello New York Times:

Thank you for this tremendous resource. And I expect that none other than Edward Tufte would be impressed with your graphical data representation. Bravo tutti!!!

For many weeks, the state and county data for New Mexico matched what I could see from the NM Department of Health. Over the past few days I have noticed that the NYT number of cases is about 40 higher than that reported by NMDOH and several of the counties have several more cases in the NYT listing than that reported by NMDOH. I’ve been unable to find an explanation in various README files a and an uncertain if this is a difference in probable vs confirmed cases that showed up in the last week or so. 

Thanks for your consideration and your monumental effort in collecting this data. 

John

**Comment by lwaananenjones** [comment]
Hi John, thank you for following so closely. There are two different explanations for the discrepancies you noticed:

1) Over the weekend, New Mexico updated county-level numbers in daily press releases, but not on the NMDOH interactive dashboard. We used the press release updates for [5/16](https://cv.nmhealth.org/2020/05/16/updated-new-mexico-covid-19-cases-now-at-5847/) and [5/17](https://cv.nmhealth.org/2020/05/17/updated-new-mexico-covid-19-cases-now-at-5938/).

2) We had a tabulation error in the 5/17 data that resulted in the 40 extra cases you noticed reported in the statewide cases total. We're in the process of correcting that, and thank you for bringing it to our attention.

**Comment by shott** [comment]
Thank you for your explanation and for promptly addressing the data issue.
