### ISSUE TITLE
Data Issue:  Bourbon, KS

### ISSUE THREAD

**Issue by ke4roh** [nytimes/covid-19-data#287]
### Describe the issue:
- [X] Incorrect number of cases or deaths

### Fuller details
Bourbon Co., KS has never had 7 cases, which us-counties shows for April 7-22, then back to 6. Refer to https://www.facebook.com/sekmchd/photos/a.634597113394972/1408772555977420/?type=3&theater

**Comment by albertsun** [comment]
Thanks, while they did report 7 cases earlier on it appears that one was reassigned to Woodson County so we've updated our data to reflect that.
