### ISSUE TITLE
Analysis Request: Analyze US Corona Virus Daily New Case and Death Rate Cyclicality

### ISSUE THREAD

**Issue by BBorSC** [nytimes/covid-19-data#288]
The cyclicality of the US and most state data (both daily new cases and deaths) follows a 7 day cycle resulting in peaks for new cases on Thursdays which given a 5 day average incubation time means that Saturday is when social distancing breaks down across the country resulting in increased deaths.  Not only is this true for the US as a whole but also most states.

Someone should further research and publish the results because this would clearly support the impact of social distancing translated into a specific death rate increase.

**Comment by ke4roh** [comment]
There are other factors driving weekly cycles.  Fewer tests tend to be taken or completed on the weekends, and tests have historically taken a long time from sampling to result.

**Comment by BBorSC** [comment]
Yes but then why is the death rate following the same 7 day cycle (but not on Thursday’s) if it was an anomaly of testing.   Also the individual states are following the trend on Wednesday or Thursday.   Alabama suffered its largest single day increase in cases 4 days after a significant increase in mobility this past weekend.    I think there is something to this – we’ll see after Memorial Day weekend.   My prediction is come Thursday or Friday of next week we will see the largest single day spike in many southern states.

Regards,

Bryan Moore

**Comment by ke4roh** [comment]
I don't mean to suggest that your hypothesis, "Case rates spike on Thursday because of Saturday breakdown of distancing," is wrong (or right).  I mean to say that there are other factors at play which may make it harder to assess than just looking at days of the week and the peak.  Contact tracing and cell phone data also provide relevant insights to the idea of postulated Saturday breakdowns of distancing.

**Comment by BBorSC** [comment]
Agree.   The hypothesis is only one of many potential factors which might explain the data.   If weekend reduction of social distancing is an important driver of case spikes and subsequently increased deaths through those same spikes then we ought to see a large spike come next Thursday and Friday due to Memorial Day weekend celebrations.   Appreciate the back and forth.   Stay safe.

Regards,

Bryan Moore

**Comment by tiffehr** [comment]
This data set is focused on cumulative counts of coronavirus cases & deaths at the state and county level.  The data is public and ready for whatever uses you would like to pursue.  The NYT has our own work from it; we read these comments for feedback and questions that we could clarify in our work.

However, this request for analysis is not directly tied to this data set nor is this the best one to drive it, I don't believe.  This is a good discussion and I recommend you continue it.  But I'm going to close the issue.

**Comment by ke4roh** [comment]
Here's a peek with today's data.  The busiest day just looking at reported cases is Friday.  

 dow | new cases | diff from mean
-- | -- | --
Sunday | 197995 | -11%
Monday | 200417 | -10%
Tuesday | 212177 | -5%
Wednesday | 229894 | 3%
Thursday | 237252 | 7%
Friday | 245723 | 10%
Saturday | 235852 | 6%

**Comment by BBorSC** [comment]
OK – thanks for the consideration.

Regards,

Bryan Moore
VP Operations

AlphaPet Inc
(A wholly-owned subsidiary of Indorama Ventures Pcl)
1301 , Finley Island Rd
Decatur , AL 35601  , USA
Work:  +1 (256) 308 1180 ext 2206
Cell: +1 (803) 370-1363
www.indoramaventures.com<http://www.indoramaventures.com/>
E mail: Bryan.Moore@US.Indorama.net<mailto:Bryan.Moore@US.Indorama.net>

Our vision: To be a world-class chemical company making great products for society.

"Important: This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error we would request you not to copy, store or forward the email. Please return the message to the sender and delete it immediately thereafter"
