### ISSUE TITLE
Enhancement: show cities at lower zoom on website

### ISSUE THREAD

**Issue by Jmuccigr** [nytimes/covid-19-data#290]
It would be nice to see the cities in the various states at a lower zoom level. For those of us not familiar with their geographies.

**Comment by tiffehr** [comment]
Thank you for this feedback.  We'll relay it to the journalist who work on our maps.  As this is not about our public data set, I'm going to close this issue.

**Comment by Jmuccigr** [comment]
> Thank you for this feedback. We'll relay it to the journalist who work on our maps. As this is not about our public data set, I'm going to close this issue.

Thanks. No problem. I didn't know if there was another place for such comments.
