### ISSUE TITLE
Examples: Figures of NYT state & county data, and for other countries

### ISSUE THREAD

**Issue by iancsf** [nytimes/covid-19-data#291]
Plots of the NYT's US, state, and county Covid-19 data, along with equivalent plots for 212 countries are available at the URL below.   The plots show daily cases & deaths, along with cumulative, 7-day averages and trends, and an estimate of active cases.  Additional tables give approximate doubling/halving times.  US data is taken from the NYT database;  country-level data is  from "Our World In Data" (OWID) GitHub page (see below).

![image](https://user-images.githubusercontent.com/3203128/82609958-2a3ec800-9b83-11ea-9910-191fdb97c22f.png)

My figures, tables, documentation and source code (matlab) are available at
https://tinyurl.com/icsf-covid19-figures

which redirects to:
https://texastechuniversity-my.sharepoint.com/personal/ian_scott-fleming_ttu_edu/_layouts/15/onedrive.aspx

OWID's raw nation-level Covid-19 data (csv files, etc.) is available at https://github.com/owid/covid-19-data/tree/master/public/data

**Comment by tiffehr** [comment]
Added this to our collection of Examples, on our Project board.
