### ISSUE TITLE
Kansas City, Missouri Counties?  

### ISSUE THREAD

**Issue by fullersr** [nytimes/covid-19-data#293]
### Your question
I must have missed a stitch.  Based on the data exceptions note, I have been conflating Jackson, Clay, Platte and Cass counties when associating the data with other county data.  But I just realized those counties now each have a line of their own.  Is that a recent change?  Related to this, how should we understand the postings for Kansas City -- those that have no fips code?

**Comment by fullersr** [comment]
Ah.  My bad.  I read the explanation more carefully.   It does indeed explain that there are data posted for the parts of each of those counties not considered to be withing Kansas City, MO city..

**Comment by tiffehr** [comment]
Kansas City is an independent city, which is commonly mapped as an entity on par with the other counties of Missouri.  We do indeed have geographies across the intersection of Kansas City to Cass, Platte and Clay counties.  We have tried to be diligent about how we assign those cases and account for partial cases, including talking with the counties.  We continue to evaluate this as cases increase, for now, in each county/city.

**Comment by fullersr** [comment]
Have you come up with methods to determine cases per unit of population for the outlying parts of the counties?

**Comment by tiffehr** [comment]
No, that is not the aim of this data set.  The counties have their own distinct reports, which we take but account for how they separately describe KCMO residents. I recommend looking at each of the four county sites and how they break out city residents.
