### ISSUE TITLE
Data Issue:  

### ISSUE THREAD

**Issue by nnnagle** [nytimes/covid-19-data#295]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [X] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
The new cases number for Knox county, Tennessee have diverged from the official statistics for the last week by a total of 9 cases, starting 5/16/20.    State statistics are here:  https://www.tn.gov/content/dam/tn/health/documents/cedep/novel-coronavirus/datasets/Public-Dataset-Daily-Case-Info.XLSX

**Comment by lwaananenjones** [comment]
Starting 5/16, our data for Knox County comes from directly from the [Knox County health department](https://covid.knoxcountytn.gov/case-count.html). 

Counties often report ahead of the state in Tennessee and elsewhere, which is one reason the number is higher. The other reason is that Knox County reports "probable" cases, which we include. The state reports a total number of probable cases, but does not include it in the county-level data.

**Comment by nnnagle** [comment]
I can't get it to match with that page either. First, that page is foul! You have to hover over a chart to see this historical number.  But I am attaching the number on the County page vs the NYT numbers.
[NYTvsCounty.xlsx](https://github.com/nytimes/covid-19-data/files/4674528/NYTvsCounty.xlsx)

**Comment by lwaananenjones** [comment]
To their credit, most counties don't have historical data posted in any format :)

It looks like this is the difference of the probable cases, which are included in our total but not in the county's chart. I added a column breaking out the probable count for each day. 
[NYTvsCounty-withProbable.xlsx](https://github.com/nytimes/covid-19-data/files/4674577/NYTvsCounty-withProbable.xlsx)

**Comment by nnnagle** [comment]
Thank you for the clarification. At University of Tennessee/Oak Ridge National Laboratory, we've been using your data to nowcast the trends for every county in the US. We've found these data to be reliable for this. Here is a simple visualization of the nowcast:  http://quetelet.geog.utk.edu/covid-nowcast

**Comment by nnnagle** [comment]
Are you scraping the most recent number? So if a day is later updated, it wouldn't show up in NYT data on the day of the correction, but rather as a change in total count on the most recent day scraped?

**Comment by tiffehr** [comment]
@nnnagle That is correct. We don't pull the entire timeseries again, since MOST places don't provide it.  We spot-check when +/- counts draw our attention.  For some that provide timeseries (intentionally or not) we try to double-check our day-by-day historical record.

**Comment by nnnagle** [comment]
Thank you!
