### ISSUE TITLE
Example: Visualize the case data with time lapse and census information overlays

### ISSUE THREAD

**Issue by seanchen7** [nytimes/covid-19-data#296]
# COVID19-TRACKER

Hi everyone, I wanted to share a website I recently developed an app/website to help track and map the #covid19 cases in the U.S. The app can be accessed from here: [COVID19 Tracker].

![covidapp](https://user-images.githubusercontent.com/9141617/82839830-aa746e80-9e9e-11ea-9154-bb95dd2bbeca.png)

*Updated 5/23:*

Additional interactive charts have been added to this app to visualize county-level case growth statistics. The underlying data is also being automatically updated twice daily via connection to this NYT GitHub repository.

![covidapp2](https://user-images.githubusercontent.com/9141617/82839833-acd6c880-9e9e-11ea-8fc7-95a317981b14.PNG)

You can find the underlying code in this [GitHub repository](https://github.com/seanchen7/COVID19-TRACKER)

[COVID19 Tracker]:      http://covidtracker.schen.org

**Comment by briancpark** [comment]
I like this website! May I ask what web tools you are using? I'm trying to build my own reactive website using my own [visualizations](https://github.com/nytimes/covid-19-data/issues/264), preferably through GitHub pages. But I really lack skills in pure HTML/CSS.

**Comment by seanchen7** [comment]
Thanks Brian! I am not very proficient with HTML myself so I leverage the R Shiny package, which you can read more about here: https://shiny.rstudio.com/
Currently this website is hosted on an Ubuntu server on AWS, but RStudio also provides free hosting service if you are interested in exploring.

**Comment by tiffehr** [comment]
This is collected in our Examples column in the Project board, so I closed the issue.  Nice work!
