### ISSUE TITLE
Question:  Is the zip code level data available for NYC?

### ISSUE THREAD

**Issue by Jmuccigr** [nytimes/covid-19-data#298]
Is the zip-code level data for NYC that data you provide on the website available somewhere easy to download (like in a repo)? Thanks.

**Comment by tiffehr** [comment]
We use the city's zipcode data, provided free to all in their [nychealth repo]( https://github.com/nychealth/coronavirus-data ): https://github.com/nychealth/coronavirus-data/blob/master/data-by-modzcta.csv
