### ISSUE TITLE
Data Issue:  Bronx, Queens and Kings 

### ISSUE THREAD

**Issue by hamedkhe** [nytimes/covid-19-data#299]
Hello, 
how i can access to data of these Bronx, Queens and Kings?

**Comment by tiffehr** [comment]
If you're seeking data for three of the counties in New York City, the city itself provides that information free to all in their [nychealth repo]( https://github.com/nychealth/coronavirus-data ): https://github.com/nychealth/coronavirus-data/blob/master/data-by-modzcta.csv
