### ISSUE TITLE
COVID-19 Drill Down mapping tool( filled and bubble) with multiple scales

### ISSUE THREAD

**Issue by jcbowyer** [nytimes/covid-19-data#300]
### Describe the project
COVID-19 project that shows how to build interactive maps and charts inside an Angular 9 application using the D3 JavaScript framework.

### Have a URL or images of the project?
![GitHub Preview](https://github.com/jcbowyer/d3-in-angular/raw/master/images/preview.png)

Click [here](https://medium.com/@johncbowyer/covid-19-maps-in-angular-9-using-d3-js-b14843795a0c) to view application overview.

Click [here](https://jcbowyer.github.io/d3-in-angular/) to view the demo app.

**Comment by tiffehr** [comment]
Thank you.  Added to our Examples collection on our Project board.
