### ISSUE TITLE
Question: Is there a dataset containing number of tests administered on a county level in the US? 

### ISSUE THREAD

**Issue by s-eley** [nytimes/covid-19-data#301]
### Do you think there is an error in the data?
Please submit a Data Issue so it can be easily routed to the correct people.

### Do you have a question about the LICENSE or permission to use this data?
Please email us at covid-data@nytimes.com

### Your question
Please check to make sure your question is not answered in the README. It may have been updated since you first read it.

**Comment by tiffehr** [comment]
We would point you to https://source.opennews.org/articles/comparison-four-major-covid-19-data-sources/, which has a matrix of the different data points offered by ourselves and other case-gathering efforts.
