### ISSUE TITLE
Data Issue: Milledgeville recent death data disagrees with public data

### ISSUE THREAD

**Issue by gwhammett** [nytimes/covid-19-data#303]
### Describe the issue:
- [x] Suspicious number of cases or deaths

### Fuller details
Milledgeville, GA is listed in the article
https://www.nytimes.com/interactive/2020/04/23/upshot/five-ways-to-monitor-coronavirus-outbreak-us.html
(Updated May 29, 2020, 9:23 A.M. E.T.) as the worst in the country in new deaths per capita over the past two weeks.  (Milledgeville is treated in the NYT article as a "micropolitan" area that covers Baldwin County and Hancock County.)  I looked into the Times raw data in
https://github.com/nytimes/covid-19-data/blob/master/us-counties.csv
and found it agrees with the data at the Georgia Department of Public Health (DPH) data in
https://dph.georgia.gov/covid-19-daily-status-report
on the cumulative total deaths of 48 (in Baldwin plus Hancock counties).  However, the Times data claims that 32 of these occurred in the past 2 weeks (May 15-28), 14 in Baldwin County and 18 in Hancock, while the Georgia DPH data indicates that only 12 occurred during the past two weeks, 7 in Baldwin and 5 in Hancock.

It seems that a likely source of error is that deaths were incorrectly recorded in the csv file on the day the deaths were reported, while the deaths actually occurred on earlier days.  This would mean that the Georgia DPH data seems more likely to be correct than the NYT data.  But it would be good if someone can track down the source of the NYT data to be sure.  (It's also good to double check outliers anyway, since they are more likely to have errors...)

(I took an interest in this case because I went to high school in Milledgeville many years ago.)

A data detail: I don't know how to see the raw data from the Georgia DPH, but one can select the county at the https://dph.georgia.gov/covid-19-daily-status-report web page andd make the following plots, and then count the dots in the past 14 days.  (Data for the past 14 days does not have lines connecting them, but they can still be seen, and the totals add up correctly.)

<img width="947" alt="Baldwin County Deaths over time" src="https://user-images.githubusercontent.com/874326/83318734-7635e080-a205-11ea-8834-ea9f1cebc03b.png">
<img width="959" alt="Hancock County Deaths over time" src="https://user-images.githubusercontent.com/874326/83318739-7d5cee80-a205-11ea-8866-4175fdf14d63.png">

**Comment by gwhammett** [comment]
A possible source of this error is the following:
The Georgia Department of Public Health for central Georgia has a Facebook page where they have daily reports of the cumulative totals of covid-19 deaths in various counties, including Baldwin and Hancock County:
https://www.facebook.com/NCHD52/
If one subtracts the data on May 14 from the data on May 28, one gets the NYT result of 32 new deaths in those two counties.  But apparently most of these deaths actually occurred before May 14, as indicated in the https://dph.georgia.gov/covid-19-daily-status-report data, but just weren't reported until after May 14.

**Comment by albertsun** [comment]
@gwhammett you are correct about the source of the discrepancy here. Our ultimate data source is in fact the Gerogia DPH. However, our data on cases and deaths are based on when cases and deaths are reported. Georgia here in their historical curve is showing deaths based on date of death. However, they have incomplete data for the most-recent 14 days because not all deaths may have been recorded.

Most states and localities have not published historical data as Georgia has, and so purposes of consistency, the dataset here assigns deaths based on the date they are reported.

**Comment by gwhammett** [comment]
@albertsun thanks for looking into this, and confirming that the data the New York Times is reporting for Milledgeville GA is incorrect.  

I think the NYT needs to correct the article at
https://www.nytimes.com/interactive/2020/04/23/upshot/five-ways-to-monitor-coronavirus-outbreak-us.html
which as of today (May 31) claims there have been 33 deaths in the past 2 weeks in the Milledgeville micropolitan area, while the Georgia DPH historical data indicates there have been only 9 deaths in those 2 weeks.  Thus the death rate of 0.62 per thousand that the NYT article claims should be reduced to 0.17, and Milledgeville would no longer appear in this table of the worst places in the country:
<img width="668" alt="NYT covid recent deaths 2020 05 31_error" src="https://user-images.githubusercontent.com/874326/83366638-61308d00-a37e-11ea-82f6-4d06b8c9bc0c.png">

I know this is a relatively small thing compared to lots of other things going on right now, but I think it is important to fix known errors that are prominently reported in important news sources like the New York Times.  This affects how policy makers make decisions and how the public evaluates the situation.  The NYT article about Milledgeville is being repeated by other news outlets, such as:
https://www.albanyherald.com/news/milledgeville-growing-into-a-covid-19-hot-spot/article_c321c18a-a10f-11ea-8cc3-cb80319e3de4.html
https://www.wrdw.com/content/news/I-TEAM-One-rural-portion-of-GA-now-leading-the-nation-in-new-COVID-10-deaths-570806611.html

(P.S.: the NYT article now says it was "Updated May 31, 2020, 10:17 P.M. E.T.", but that can't be right because it is only 8:27 P.M. E.T. now).

**Comment by albertsun** [comment]
Our data is not incorrect.

Milledgeville does have the most newly announced deaths by population in the most recent two weeks. In order to describe hotspots nationwide we need to use a consistent methodology for counting nationwide. It would be incorrect to apply one methodology to Georgia and another everywhere else.

We believe this is the best way of identifying hotspots across the country. Since no one has perfect data on this pandemic, there will be no perfect way to do this, but we are constantly trying to improve both the data we have and the way we identify hot spots.
