### ISSUE TITLE
Data Issue:  FYI data files just posted only have most recent day

### ISSUE THREAD

**Issue by philipncohen** [nytimes/covid-19-data#305]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [x] Missing time-series information
- [ ] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources.

**Comment by albertsun** [comment]
Hi apologies,

I accidentally copied files into the wrong place. This is now corrected and the historical data is restored.
