### ISSUE TITLE
Data Issue:  historical data just vanished

### ISSUE THREAD

**Issue by cory** [nytimes/covid-19-data#306]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [X] Missing time-series information
- [ ] Other

### Fuller details
Historical data vanished with today's commit.

**Comment by ddenenberg71** [comment]
Looks like the live file may have accidentally overwritten the historical file.

**Comment by cory** [comment]
Yes. that's clearly what happened, just wanted to let them know :)

**Comment by cory** [comment]
thank you, @albertsun
