### ISSUE TITLE
Data Issue:  

### ISSUE THREAD

**Issue by chem-geek** [nytimes/covid-19-data#308]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [x ] Missing time-series information
- [ ] Other

Incorrect files deposited for 5/30. (Appear to be duplicates of live data files, not the historical data files.)

**Comment by albertsun** [comment]
Apologies,

I accidentally copied files into the wrong place. This is now corrected and the historical data is restored.
