### ISSUE TITLE
Question:  Handling of MA 6/1 data

### ISSUE THREAD

**Issue by vigneshv59** [nytimes/covid-19-data#309]
Massachusetts seems to have started reporting probable deaths starting from the data on 6/1, which caused a giant spike in the number of reported deaths today, at least on the live data. It seems like the official state reporting assigned the probable deaths to the day they occurred, but it doesn't seem like there's anything similar on a county level -- are there any plans to historically revise the 6/1 data on either a county or a state level or do you anticipate that the spike in the data will remain in the daily reports as well?

**Comment by albertsun** [comment]
Hi @vigneshv59 yes we've noticed this too. We're discussing to see what's possible as far as backdating this data.

**Comment by PatrickDRusk** [comment]
Massachusetts daily provides a Zip of data that includes a `DateOfDeath.csv` that allocates every confirmed and probable death to the date it occurred, with corrections made as far back as 45 days at time. It would be super-helpful to use that to correct your dataset on a routine basis.

**Comment by tiffehr** [comment]
We currently download MA's .zip about every 15min to extract the cumulative totals from its `Cases.csv`, `DeathsReported.csv` and `County.csv` files.  We have been doing this since June 2nd, which includes all of their probable cases as provided per day.  Our dataset provided here should be up to date historically with those figures.

**Comment by PatrickDRusk** [comment]
Massachusetts' `DateOfDeath.csv` is substantially more accurate than their `DeathsReported.csv`. Wouldn't it help your trend analysis to know the date on which people have died, versus the date on which it was reported? I've attached a two-week stale version of a graph I used to maintain showing just how different they are (even with smoothing).

![image](https://user-images.githubusercontent.com/17709454/86624155-d81a0080-bf90-11ea-84c8-2bd41d2b902e.png)

**Comment by PatrickDRusk** [comment]
Please note that Massachusetts already has a `CasesByDate.csv` to record the date on which people were tested, rather than the date it was reported. Again, more accurate.

**Comment by lwaananenjones** [comment]
We watch these other sources and agree that it's useful for certain types of trend analysis. Fewer than half the states consistently provide this type of data at the state level, and very few provide it at the county level. Even among states that provide this information, there are a variety of methods for dating cases, such as date of symptoms onset, date diagnosed, and date reported to the state. So far, there is no way to use this data in a consistent way nationwide, and users who only need the data for Massachusetts can get it directly from the state.

**Comment by tiffehr** [comment]
This public data set is just part of what NYT staff uses for our own analysis.  For our published charts and maps -- like our trend analysis -- we published a Methodology or Sources description that explains our use of data beyond what is open-sourced here.

**Comment by PatrickDRusk** [comment]
Thanks. I appreciate all that you have made available publicly.
