### ISSUE TITLE
Doña Ana, NM missing FIPS

### ISSUE THREAD

**Issue by keyonvafa** [nytimes/covid-19-data#31]
Hi,
First of all, thank you for making this amazing data set available. 
The FIPS code for Doña Ana, NM is 35013, but the FIPS fields are missing in the database whenever Doña Ana is listed (probably because of some ASCII merging error). 
Thanks!
Keyon

**Comment by albertsun** [comment]
Hi @keyonvafa thanks for noticing this. We've fixed this in the most recent release and Doña Ana will have its FIPS code going forward.
