### ISSUE TITLE
Question:  Michigan Data from 6/1

### ISSUE THREAD

**Issue by sarah1340** [nytimes/covid-19-data#310]
For the NYT Michigan data, there appears to be a spike of 1,000+ new cases on June 1, yet on June 1 the state reported only 135 new cases. There also appear to be more discrepancies over the last couple of days in the total number of cases being reported (NYT: 58680, COVID Tracking and Michigan.gov: 57731. 

Can you provide any information on what is causing the spikes in the NYT data or discrepancies with official state counts (e.g. probable cases, etc.)?

**Comment by albertsun** [comment]
Hi @sarah1340, in Michigan starting on June 1st we began recording probable cases and deaths reported by county and regional health districts and adding those cases and deaths to the statewide confirmed totals.
