### ISSUE TITLE
County-level data for Rhode Island is not consistently reported

### ISSUE THREAD

**Issue by wisselbd** [nytimes/covid-19-data#311]
While the state-level data for Rhode Island comes in relatively consistently, there have only been two updates to the county-level data in the last four weeks. Those updates took place on 5/11 and 5/27.

Johns Hopkins does not even release county-level data in Rhode Island, so I am guessing the state just does not do a good job reporting it.

Of course there is not much The Times can do about this, but is there a mechanism to note which county-level data may be less reliable or less consistently reported? 

I helped launch a [web-based dashboard](https://covid19watcher.com/) that displays The Times' data, and one of our users noted that the data for Providence, RI seemed off. I am hoping that there is a way to note which data need caution in interpreting so that people are not misled by the results.

Thanks for all of your work!

**Comment by albertsun** [comment]
@wisselbd yes, Rhode Island updates its county level data much less regularly than their statewide totals.

One thing you could potentially look at to identify this is the Unknown county figure. We put the difference between the old county sum and the state total into that row. So states that have a large number of Unknown cases or deaths would generally be considered to have less reliable data.

**Comment by wisselbd** [comment]
@albertsun that is very clever, thank you for the suggestion!
