### ISSUE TITLE
What's going on with the once-a-day file today?  ETag has changed several times

### ISSUE THREAD

**Issue by gmillikan** [nytimes/covid-19-data#312]
We watch the ETag on the header, when it changes we pull the file.  ETag usually changes once daily around noon.  It's changed like 5 times today.  Everything ok?

Thanks,

--Geoff Millikan

**Comment by gmillikan** [comment]
Here's the current headers for https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv  Problem is the ETag changing frequently (10+ times today) instead of only when the file has been modified.

Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Cache-Control: max-age=300
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 1903244
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: text/plain; charset=utf-8
Date: Thu, 04 Jun 2020 23:16:13 GMT
**ETag: W/"0fb8d5140f7816cbaa33518713897a6ebd92ee36d22be02f7f0020daef1a0ea8"**
Expires: Thu, 04 Jun 2020 23:21:13 GMT
Source-Age: 186
Strict-Transport-Security: max-age=31536000
Vary: Authorization,Accept-Encoding
Via: 1.1 varnish (Varnish/6.0)
Via: 1.1 varnish
X-Cache: MISS, HIT
X-Cache-Hits: 0, 1
X-Content-Type-Options: nosniff
X-Fastly-Request-ID: 1fa9c161dcdda8749e5d950dec7f37f36ff83eaf
X-Frame-Options: deny
X-GitHub-Request-Id: CA78:2619:44282:4E43C:5ED97EBA
X-Served-By: cache-bur17546-BUR
X-Timer: S1591312574.991055,VS0,VE3
X-XSS-Protection: 1; mode=block
`

**Comment by albertsun** [comment]
@gmillikan we are not specifically doing anything with the ETag for that file and we did only update it once today. Perhaps something is going on with the Github server.

**Comment by gmillikan** [comment]
Thanks @albertsun!  It's GitHub issue then.  Just don't want to mess up your account at GitHub by downloading it 100 times a day.  We'll figure it out.  Thanks for the awesome data!  BTW, we gave you guys a good shout out at the 2 links below:

https://www.cvleaderboard.org/partners.php

https://www.cvleaderboard.org/data.php

Thanks again,

--Geoff Millikan
