### ISSUE TITLE
Data Issue:  Michigan 06-05 Infect and Death Jump

### ISSUE THREAD

**Issue by guzhiling** [nytimes/covid-19-data#313]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [x] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
Michigan State Infect & death has a big jump on 06-05. The government confirmed counts are 58,525 & 5,613 (https://www.michigan.gov/coronavirus/0,9753,7-406-98163_98173---,00.html) while nyt data is 63,744 & 5,854. is it due to the jump in probable cases?

**Comment by albertsun** [comment]
Hi @guzhiling on June 5, Michigan started reporting probable cases and deaths for the first state. We include those in our totals which is why the total increases so much.

**Comment by guzhiling** [comment]
> Hi @guzhiling on June 5, Michigan started reporting probable cases and deaths for the first state. We include those in our totals which is why the total increases so much.

Thank you, Albert, for your timely reply. That solves my question. I want to confirm that right now there is no double-counting of probable cases from county level and state level, is it right?

**Comment by albertsun** [comment]
Yes, that's right. They are not double counted, but there are still some counties that report more probables than the state, in which case we use the number from the county instead of the number from the state.

**Comment by guzhiling** [comment]
I see. In that case, we use the county with the highest probable cases to represent the state-level probable cases, i.e. max(counties_i, state). That makes sense to me. 

Thank you for your explanation and hard work!

**Comment by mbauman** [comment]
Oakland County specifically looks off, but perhaps they were just _really_ bad at confirming cases?  53% of all new cases in Michigan on June 5 are attributed to Oakland County alone.  It's a jump of nearly 30% over that county's prior cumulative total, representing 0.2% of its population.

It's simply a huge outlier from all the other Michigan counties.

**Comment by albertsun** [comment]
@mbauman this is a limitation of the way this data is reported. Michigan added all their probable cases, including all those probable cases in Oakland county, on one day, even though many of those cases took place in the past. Our dataset primarily represents the total number of cases on any given day. Normally that would lead easily to a computation of new cases, but in this case, unfortunately, it doesn't.

**Comment by tgskiman** [comment]
> Hi @guzhiling on June 5, Michigan started reporting probable cases and deaths for the first state. We include those in our totals which is why the total increases so much.

Are you using this backlog of data added on the 5th in your graphs on the main page to show which states are increasing vs decreasing? This is what it looks like and seems to misrepresent the data and trajectory of the state. I worry others may not dig in to the data to understand. Is my assumption correct, or am I misinterpreting the data? If this is the case it would be nice to add a footnote to the graphs when this change occurs. Thanks.

**Comment by westmich** [comment]
The spike from one county on one day is making the overall data for the state rather useless.  Please fix - I thought that was the whole point of this site with a day delay was to correct these sorts of issues.

**Comment by mbauman** [comment]
> Michigan added all their probable cases, including all those probable cases in Oakland county, on one day, even though many of those cases took place in the past

Yes I fully understand that limitation.  My point is that — even considering the temporal backlog — there is additionally a big _geographic_ outlier in where these cases occurred.  But that very well may be true to the differences in how aggressively the counties are assigning probable cases.

I see you have nicely documented this in https://github.com/nytimes/covid-19-data/blob/master/PROBABLE-CASES-NOTE.md.  Thanks for all your hard work in collecting this data!
