### ISSUE TITLE
Data Issue:  NYC Jails and cluster data

### ISSUE THREAD

**Issue by yovinny** [nytimes/covid-19-data#314]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources.

**Comment by yovinny** [comment]
The most recent [data ](https://www1.nyc.gov/assets/boc/downloads/pdf/News/covid-19/Public_Reports/Board%20of%20Correction%20Daily%20Public%20Report_6_05_2020.pdf)from the city's Board of Corrections indicates that there are 1408 corrections staff, 196 health staff, and 340 incarcerated people with confirmed COVID tests in city jails, and yet NYC jails don't appear on the list of "cluster" sites along with other facilities with lower numbers.  Why is that and should it be corrected.  The Board of Corrections publishes updates daily at the link I included, usually a day or two old.

**Comment by albertsun** [comment]
@yovinny NYC has many different jail facilities, and the city has not provided a breakdown of cases by facility, so we have not been able to add them to our list of clusters. We do include these cases in our topline total numbers for the city.
