### ISSUE TITLE
Question:  How are the 'hover' numbers on the county hot spot map calculated ?

### ISSUE THREAD

**Issue by jazz788** [nytimes/covid-19-data#315]
Hi,
Has anyone ran into an issue on this? No matter how I try, I am not able to come up with the same numbers. 

Worked examples here - using the NYT county data, and census population data. There may be some small differences in census population data, but not enough to throw the numbers off as badly as I'm seeing.  In many cases it's close, but its wrong often enough to assume i'm doing something wrong, but I can't see what it is.

Example 1.

![image](https://user-images.githubusercontent.com/66713895/84229231-aeafa700-aaae-11ea-8edf-d951cba834c2.png)

Example 2. 

![image](https://user-images.githubusercontent.com/66713895/84229448-2f6ea300-aaaf-11ea-824f-b701642ae9fb.png)

**Comment by GordonLElliott** [comment]
> 1. Your column for "7 days prior" appears to be using an 8-day range.

That would correspond to the average over 7 days of the individual day to day differences or daily new cases. (Intermediate terms cancel and only the end day terms are left, mathematically. Daily increases are so noisy that they are difficult to follow on a graph.) A span of one day difference would have 2 day records, so 7 day difference will involve 8 records (8-day range) when done correctly.

@albertsun has commented on another thread that NYT has switched to the [County Population Totals: 2010-2019](https://www.census.gov/data/datasets/time-series/demo/popest/2010s-counties-total.html) for per capita reporting.

I'm interested in that population data edited to have identical county names (or codes) so they can be directly joined with the main tables here to get the population value needed for per capita report. I think I can clean (edit) tha census data to conform to the county names here but I have not see how large a job that will be. Most is just removing the extraneous " county" in the county names to match these datasets.
