### ISSUE TITLE
How do you determine new cases that are "About the same" in the world map?

### ISSUE THREAD

**Issue by armsp** [nytimes/covid-19-data#316]
With reference to the [world chloropleth map](https://www.nytimes.com/interactive/2020/world/coronavirus-maps.html), you have divided the color scheme to -
* Falling
* Rising - 3 levels
* About the same

I want to know how exactly is **About the same** category calculated.

**My attempt**
I tried to reverse engineer this from the *popup* information but I don't think I can do that.
**Why?**
Cause for Australia, the *new cases* now are less than that of 2 weeks ago and it's categorized as **Falling** which makes sense.

We see the same trend for Russia, its *new cases* is less now than it was 2 weeks ago, but its marked as **About the same**.
Similarly, the gap in the *new cases* and that of two weeks ago for **About the same** category seems to vary a lot from one country to another, which leads me to believe that it's not based on absolute values.

Also, while you are at it, could you please tell me how do you categorize the 3 **Rising** levels - what rate is used for the 3 colors in **Rising** category?

**Comment by armsp** [comment]
@tiffehr @albertsun or any of the maintainers, it would be great if you could clarify this. It would help understand how you determine if the cases are **About the same**

**Comment by tiffehr** [comment]
@armsp Do you see issues with the classification that we should look into?  This graphic is derived from the specific data set we offer here for public use, so that is our main duty here.  The NYT's own work based on this data is not contained in this repo — we are not adding it on top of what is presented here.

**Comment by armsp** [comment]
@tiffehr  I suppose not, because the calculations for the categories are done using the data that you provide...which itself looks okay. The only issue is the gap in understanding how **About the same** category is decided. It has examples of counties (and countries for the world map) where the cases now and that of two weeks ago, increase AS WELL AS decrease. The graphics cleverly obscures the fact by showing just the results. I was hoping if you would have any idea how they determine the margin of error to say that the cases are **About the same** even though the weekly averages may increase or decrease.

https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html

**Comment by albertsun** [comment]
Hi @armsp,

The map you linked to, is, as Tiff said, independent of the data set here, though derived from the same underlying data. It is also frequently updated and liable to change as we continually tweak the map and other elements on that page to try and communicate the state of the outbreak clearly to our readers. We think most scientific users should not try to simply recreate the maps we've already made, but to come up with their own analysis and measures based on the raw underlying data.

That said, at this moment, the scale on the map is based on the change in the 7-day trailing average number of cases compared to two weeks ago.

The thresholds for that change are:
Blue:  < -15%
Yellow: > -15% and < +15%
Light orange: >+15% and <+100%
Mid orange: >+100% and <+200%
Dark red: >+200%

**Comment by armsp** [comment]
@albertsun thank you so much for the clarifications. I understand the idea to come up with our own analysis...but I have recently just started loving Data Viz because of you folks, and I am using this as a learning period to get better at it. I have been working on something that can perhaps be added to your Examples list.

**Comment by armsp** [comment]
@albertsun if possible, could you also tell me how and why did NYT decide upon number 15. I mean is there any mathematical reasoning behind it?

**Comment by bsaunders23** [comment]
Hey @albertsun , know that we've closed this but looks like color scales are now referring to per-capita counts. Any idea on the thresholds for these? Appreciate the advising on not trying to replicate the classifications since they're often changing but unfortunately need to have parity with the color scales for a current project :(

![image](https://user-images.githubusercontent.com/28548757/87734654-1f21a600-c788-11ea-8f37-4bb3d82dcc31.png)

**Comment by albertsun** [comment]
@bsaunders23 those scales are going to be somewhat dynamic now. And we are likely to keep changing them. That chart is so small the color is really just intended to be a quick visual indicator for people, not something to analyze closely.

What project are you working on and why does it require parity with our color scale? Maybe we can advise on some alternate solution than trying to keep up with that?

**Comment by bsaunders23** [comment]
Thanks for the quick response @albertsun, We're hoping to leverage some general rules of thumb around interpretation of per capita values, which is where we'd hope to build on how NYT is already classifying. The general ask on parity was from business teams to match what had been done historically, and I think we're fine to relax constantly updating our logic to match. In this case given the indicator itself has changed, it'd still be a big help to at least understand how you're grouping at present from which we can adjust as needed.

Thanks!

**Comment by albertsun** [comment]
@bsaunders23 thanks. If you take a look at the U.S. map page now you should see that the color scale for the Hot spots map at top is labeled with the per capita case thresholds.

The charts in the state and county table use a similar scale, though at the state and county level the actual numbers are different. These scales are dynamically adjusted based on the overall data range so the actual thresholds will fluctuate over time.

**Comment by bsaunders23** [comment]
@albertsun Thanks for the quick response here, makes sense!
