### ISSUE TITLE
Basic cartographic principles for mapping case count and case ratio 

### ISSUE THREAD

**Issue by manishverma09** [nytimes/covid-19-data#318]
### Describe the project
Some basic principles to discretize the case count and case ratio (counts relative to population), and create static and web maps in R. The focus is on using elementary cartographic principles and develop an objective approach to map development. You will have to knit the two R Markdown files to see the output. Consult the text in the Markdown files and the associated slides. 

Thanks to NYTIMES for making the data available and providing rich and complete metadata.

### Have a URL or images of the project?
https://github.com/manishverma09/Mapping-COVID-19

**Comment by tiffehr** [comment]
Added to our Project board, which is collecting Examples.  Thank you!
