### ISSUE TITLE
Data Issue: Seven day average for Pierce County in Washington State looks inaccurate

### ISSUE THREAD

**Issue by voxel-eyes** [nytimes/covid-19-data#319]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [x] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

Why do you show a huge jump in cases for Pierce County, Washington? The case count listed on the Tacoma-Pierce County Health Department shows that cases have remained about the same over the time frame you're referencing: https://www.tpchd.org/healthy-people/diseases/covid-19-pierce-county-cases/

Around 11 cases per day average, not 51.4.
<img width="335" alt="Screen Shot 2020-06-12 at 11 00 05 PM" src="https://user-images.githubusercontent.com/66861598/84561573-638dd200-ad02-11ea-80df-dc9207d5e136.png">

**Comment by voxel-eyes** [comment]
The issue appears to have been corrected today. Thank you!
<img width="380" alt="Today" src="https://user-images.githubusercontent.com/66861598/84585096-ec6b4300-adc0-11ea-8261-2c8f58c64403.png">

**Comment by albertsun** [comment]
Hi, yes, Pierce County data on probable cases was available so we've added those to our case counts. Those are now backdated to when probable cases were first identified instead of when we first realized the data was there.
