### ISSUE TITLE
Question:  If Johns Hopkins updates its time series data for a few days ago, will your data also be updated?

### ISSUE THREAD

**Issue by Jelfff** [nytimes/covid-19-data#320]
The Johns Hopkins 'readme' for their time-series data states:
"This folder contains daily time series summary tables, including confirmed, deaths and recovered. All data is read in from the daily case report. The time series tables are subject to be updated if inaccuracies are identified in our historical data. The daily reports will not be adjusted in these instances to maintain a record of raw data."

If NYT is using Hopkins as a data source, then what happens when Hopkins updates its time-series data for a few days in the past?  Does NYT make a corresponding tweak to its data?

**Comment by tiffehr** [comment]
@Jelfff We are not using Johns Hopkins as our data source. We pull their numbers alongside our own collection, to compare and contrast.  But this data set is not subject to their changes.
