### ISSUE TITLE
Data Issue: Rhode Island unchanged since 12 June

### ISSUE THREAD

**Issue by kcannon3** [nytimes/covid-19-data#322]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [x] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
Cases and deaths for RI have remained static since 12 June (reporting this on 14 June) at 15947 cases and 833 deaths. It seems unlikely no new cases or deaths have been reported in that time.

**Comment by albertsun** [comment]
Hi @kcannon3, unfortunately this is in RI DOH's hands and they do not update any of their numbers over the weekend. Tomorrow's update will have new numbers.
