### ISSUE TITLE
Mapbox Tiles request

### ISSUE THREAD

**Issue by jazz788** [nytimes/covid-19-data#323]
Hi, 

What is the source for the mapbox tiles for the  NYT charts - are they publicly available ? I am interested in getting the county,  state and 'county clipped' if possible. I think they are these files: 

https://a.tiles.mapbox.com/v4/nytgraphics.596eyqgf/
https://a.tiles.mapbox.com/v4/nytgraphics.anzki7b9/
https://a.tiles.mapbox.com/v4/nytgraphics.csrp4dba/
https://a.tiles.mapbox.com/v4/nytgraphics.183yay8f/

Thanks

J

**Comment by albertsun** [comment]
The tilesets are our custom design work and are not publicly available.

**Comment by jazz788** [comment]
Got it thanks @albertsun
