### ISSUE TITLE
Example: https://flattenthecurve.wellifi.com

### ISSUE THREAD

**Issue by bramscher** [nytimes/covid-19-data#325]
### Describe the project
We gave added the ability for users to track specific regions or areas of particular interest to the user, share with family and friends and comment on observations. So a bit of a social network based on the amazing work of the NYT data. 

The charting has a simple algorithm for tracking trending of new cases as we believe

 this is the most critical view of the data.  

### Have a URL or images of the project?
https://flattenthecurve.wellifi.com/

![Screen Shot 2020-06-16 at 1 24 16 PM](https://user-images.githubusercontent.com/7459837/84861788-b0391c00-b026-11ea-9c18-aacaa48d92a5.png)

**Comment by tiffehr** [comment]
Added to our Examples collection!
