### ISSUE TITLE
Are antibody positive results included in the 'New Cases' metric? 

### ISSUE THREAD

**Issue by sarawr29** [nytimes/covid-19-data#326]
Are positive antibody test results reflected anywhere in this data? They are technically 'lab-confirmed' results, as your definition of 'new cases' states. Just wondering how you are/could represent this data as antibody testing becomes readily available and trusted. Maybe set up a separate chart/tracker to indicate those results? There wouldn't be a date dimension for those to be measured against - besides testing date.

**Comment by albertsun** [comment]
@sarawr29 positive antibody results are not directly included. However we do include "probable" cases and deaths in our total counts. One part of the definition of "probable" includes a positive antibody test. You can read more about that methodology here: https://github.com/nytimes/covid-19-data/blob/master/PROBABLE-CASES-NOTE.md
