### ISSUE TITLE
Question:  Live Data is behind historical data

### ISSUE THREAD

**Issue by chris-ruskai** [nytimes/covid-19-data#328]
### Do you think there is an error in the data?
Please submit a Data Issue so it can be easily routed to the correct people.

### Do you have a question about the LICENSE or permission to use this data?
Please email us at covid-data@nytimes.com

### Your question
Please check to make sure your question is not answered in the README. It may have been updated since you first read it.

Why is the live data behind the historical data?

**Comment by albertsun** [comment]
@chris-ruskai not too sure what you mean by that, could you please be more specific and show us an example of what you see where the live data is behind?

**Comment by chris-ruskai** [comment]
At the time of writing, the last update for the historical data was more recent than the last update for the live data.
