### ISSUE TITLE
Question:  

### ISSUE THREAD

**Issue by monoteos** [nytimes/covid-19-data#329]
Hi, I'm trying to understand what is clipped counties is (data_regions_clipped-1dzkrj)
this link 

https://a.tiles.mapbox.com/v4/nytgraphics.anzki7b9/page.html (access token removed from url)

it looks like counties, but clipped to some data, can you explain what is it?

![image](https://i.imgur.com/Ju2fWKt.png)

**Comment by albertsun** [comment]
The issues on this repo really are intended for data questions about the files in this repo, not general questions about what the NYTimes publishes. But... our maps there are dasymetric maps designed to put less visual emphasis on sparsely populated areas.
