### ISSUE TITLE
Data inconsistency: Cumulative data between us-counties.csv and us-states.csv are not equal

### ISSUE THREAD

**Issue by lRn2Win** [nytimes/covid-19-data#33]
If you sum the deaths and cases between each of your sets, they aren't equal. Why?

**Comment by dannguyen** [comment]
State and county agencies don't act or report in lockstep. Some/many states likely don't have a centralized reporting system, which leaves counties to report their own unaudited numbers that will later get reconciled.

Here's a good write up by the Texas Tribune, which talks about the various issues, including different methodologies:

https://www.texastribune.org/2020/03/24/coronavirus-cases-in-texas-why-the-numbers-are-different-everywhere/

> One reason for the previous discrepancies between state and county numbers was that different methodologies were being used.

> Until Tuesday evening, the state tracked cases by county of residence. This meant that if a University of Texas student who lived in Houston contracted the new coronavirus and was tested and treated in Austin, the tally appeared as a positive case in Harris County.

> Many counties, on the other hand, have been reporting anyone who tested positive in their jurisdictions. DSHS’s new method will use tallies directly from counties.
