### ISSUE TITLE
Data Issue:  

### ISSUE THREAD

**Issue by curiouspeat** [nytimes/covid-19-data#330]
### Describe the issue:
- [x] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources.

In Marin county California the number of cases reported on 6/8 is 625 but the number reported by Marin county on that day is 611.

I caught this problem because the number of new cases on the following day was negative 5.  It would be good to run a sanity check like that on your data to make sure that the new case numbers are always non-negative.

Thank you so much for providing and publishing the data.  We use it in the tools section of the phoenixdataproject.org website.

Cheers,
Peter Khoury

**Comment by JazabC** [comment]
I can look into this

**Comment by lwaananenjones** [comment]
Hi Peter, thank you for raising this issue. It looks like Marin County [added cases from San Quentin Prison on 6/8](https://coronavirus.marinhhs.org/covid-19-status-update-06082020), then [stopped including those cases in the total a day later](https://coronavirus.marinhhs.org/covid-19-status-update-06092020), resulting in the decrease. It's fairly common for states and counties to omit prisoners from their total, but our data includes prisoners when possible. We will update Marin County data to include the San Quentin cases. That will result in 625 cases on 6/8 and 635 cases on 6/9.

**Comment by curiouspeat** [comment]
BTW I know that its an absolute pain to keep up a high quality data set that is consistent.  Thank you so much for doing so.  It’s really appreciated.

Take care and stay healthy,
Peat


On Jun 20, 2020, at 10:09 PM, lwaananenjones <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Peter, thank you for raising this issue. It looks like Marin County added cases from San Quentin Prison on 6/8, then stopped including those cases in the total a day later, resulting in the decreas
Caution (External, notifications@github.com<mailto:notifications@github.com>)
Sensitive Content   Details<https://shared.outlook.inky.com/details?id=Y29tbXNjb3BlL3BldGVyLmtob3VyeUBjb21tc2NvcGUuY29tLzhjODQxYTllMzY3Y2JkNDZlNzI5MTgwZGI1MmVjMjA4LzE1OTI3MTYxOTQuOTE=#key=6602ec0981ad738a59f3aad9186d3dc6>
Beware of COVID-19 phishing scams. Click here to visit the CDC website with the latest authoritative information on the Coronavirus COVID-19 pandemic.<https://www.cdc.gov/coronavirus/2019-ncov/index.html>
Report This Email<https://shared.outlook.inky.com/report?id=Y29tbXNjb3BlL3BldGVyLmtob3VyeUBjb21tc2NvcGUuY29tLzhjODQxYTllMzY3Y2JkNDZlNzI5MTgwZGI1MmVjMjA4LzE1OTI3MTYxOTQuOTE=#key=6602ec0981ad738a59f3aad9186d3dc6>  FAQ<https://www.inky.com/banner-faq/>  Protection by INKY<https://www.inky.com/>



Hi Peter, thank you for raising this issue. It looks like Marin County added cases from San Quentin Prison on 6/8<https://secure-web.cisco.com/1CaQ_sypspSxcVD_TpF7ScuSOsbHQnq46_2xNttH67PtttjjEOTRD7p674MTS9amg2PZCuYHs4r3mWQaDE5JYhLnPuM94_-dRi-o4XpsMuvWCqFtHTUS_QxUWFpmS4EkzuWxzQ6mQQkDHWcvQ7P5gvLL656J98dp92AgjNmWFV5CTzt0Jl_2ucoxN3rEajB50O6R3diRxpZ_HkqM84d2uJGKH0Rfc_Ralhla-SXrhERV8VNLGXBDrT3lOs7sRuBPImTvbTRw7ytBIyhsyJQZpoeWwBcM0sblFKBy33Bma6E8CQ8MlK95e_Zurp8KFD9NLaKAgKYHpM-0DFphu9wQdFA/https%3A%2F%2Fcoronavirus.marinhhs.org%2Fcovid-19-status-update-06082020>, then stopped including those cases in the total a day later<https://secure-web.cisco.com/1PMhINtauCmYTj47yz_wylxjoj6lIKSv5aM0Hs5bZ2Y2e8fUCSQxceXRl3H412v4zuaZcoNEOQTZplfXAmsJ1sJenbcLhky92LIXuEU6gT7X8D9ilGQwJIjRdVKMOGYWgV9a4P7NhZTwQ_1K8qlR_I_vl_Y1YgVfBgkc-BSFpjmuDxmIOA-kYAFZtrIxekj0qyUWSUC0QsA7cbuqPCfx6Fb0Z_5UkUbKMcyQRtqFzdBP3cZ2RoVcrXAiYCBfZSIDzRgqF2BVzz6yg_Pd4hrMBk9abi3sgF7ZtAhehd8180F2iOZphGGXo03-vT8lbaottoYbJXVk1mg7X59xHmGgDVQ/https%3A%2F%2Fcoronavirus.marinhhs.org%2Fcovid-19-status-update-06092020>, resulting in the decrease. It's fairly common for states and counties to omit prisoners from their total, but our data includes prisoners when possible. We will update Marin County data to include the San Quentin cases. That will result in 625 cases on 6/8 and 635 cases on 6/9.

**Comment by albertsun** [comment]
Thanks @curiouspeat, this data is now updated btw.
