### ISSUE TITLE
Enhancement: Mortality %

### ISSUE THREAD

**Issue by DrKarner** [nytimes/covid-19-data#332]
### Describe the feature you would like to see

Deaths / Cases x 100 = % Mortality

Rationale: County-level mortality rates vary from over 10% to less than 1%. High mortality % indicates something irregular has occurred there, raising caution and warranting investigation.

In map view, I would like to see a button next to "hotspots" which when activated will  display the % mortality using a color-based scale.

**Comment by gmillikan** [comment]
Understand this is a request for NYT but our site has that at the link below on a state-by-state and county-by-county basis - we don’t have “hot spots” yet). Good feature request!

https://www.cvleaderboard.org/USA/new-jersey/#FatalityRate

**Comment by tiffehr** [comment]
This public repository is focused on the raw data NYT has collected, maintained and shared with the public, according to our [stated methodology](https://github.com/nytimes/covid-19-data#methodology-and-definitions). It does not include additional calculations or visualizations the NYT itself may draw from the data.  

Unless this request is about augmenting this dataset with a uniquely valuable figure, we are not including such figures in what we offer.  This one seems like a fairly direct calculation that can be done by those using this dataset for their own purposes.

**Comment by gmillikan** [comment]
Thanks @tiffehr, y’all rock. Thanks for the amazing dataset, really appreciate all the work you and the team are doing.
