### ISSUE TITLE
Data Issue:  June 1 2020 Baltimore City cumulative cases show decrease

### ISSUE THREAD

**Issue by jessicahladd** [nytimes/covid-19-data#334]
### Describe the issue:
- [x] Incorrect number of cases or deaths
- [x] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
When looking up the county "Baltimore City", the cumulative case data shows 

2020-05-30: 5572 cases
2020-05-31: 5672 cases
2020-06-01: 5612 cases
2020-06-02: 5696 cases

All other dates / cases in Baltimore make sense. I suspect a data entry error happened on 2020-05-31 or 2020-06-01.

**Comment by lwaananenjones** [comment]
Thank you for bringing this up. Those numbers accurately reflect what the state reported each day for Baltimore City, and local media at the time noted the decrease of 60 cases on June 1. It's common for county-level counts to decrease as cases are reassigned to a different county, found to be duplicates, etc. We try to find out more about these decreases, but rarely get enough information to make accurate revisions, so in the vast majority of decreases we preserve the counts as originally reported.
