### ISSUE TITLE
Example: How to auto-connect to this data from Excel

### ISSUE THREAD

**Issue by knwpsk** [nytimes/covid-19-data#337]
Forgive me if this is redundant but I searched and couldn't find the answer.  Also had a hard time figuring it out, so I'm sharing.

If you want to automatically connect from Excel to these data files, and refresh them periodically, this is how (Excel 2016, Office Pro version):

- Open Excel, open a new file or tab
- Click cell A1
- Click Data tab in the ribbon (menu)
- Click "New Query" (this was the confusing part -- DON'T use "new Connection")
- Enter the URL for the "Raw" file in Github

The rest is pretty obvious.

Now you can manage the properties of the connection under the Connections button in Data tab (in the Ribbon).
You can choose to auto-refresh the data when you open the Excel file -- I recommend NOT doing this.  Instead, I click "Refresh All" (Data tab) after opening the file.

I have several pivot tables based on the imported data.  My pivots do not auto-update when I update the data/connection.  I have to right-click in the pivot table, and choose "refresh" to accomplish that.  Same for pivot charts.

**Comment by tiffehr** [comment]
Thank you for the instructions!  I added this to our Collection of Alternative Formats, alongside other efforts to turn this into broader formats.
