### ISSUE TITLE
Data Issue:  records missing for 5 counties in New York: Bronx, Kings, Queens, New York and Richmond

### ISSUE THREAD

**Issue by KYZhang20** [nytimes/covid-19-data#338]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [x] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details

I don't see records in the data file for 5 counties in New York state: Bronx, Kings, Queens, New York and Richmond, please help check it. Thank you.

**Comment by KYZhang20** [comment]
The data has New York City, however, New York city can not be show at county level

**Comment by tiffehr** [comment]
In which .csv in this public data set are you expecting to see those records?

**Comment by KYZhang20** [comment]
Us-counties.csv

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by albertsun** [comment]
@KYZhang20 if you take a look at the README, the section about New York City explains that we provide a single value for all of New York City rather than breaking it out by those 5 counties.
