### ISSUE TITLE
Example: Simple state-level graph visualization with sortable tables of national information

### ISSUE THREAD

**Issue by CrossEye** [nytimes/covid-19-data#340]
### Describe the project
A simple table containing the national and state data with daily, weekly, monthly and overall totals as well as trend and per capit
a figures, all for both cases and deaths.  Also charts per state of daily and rolling average figures as well as cumulative figures, again for both cases and deaths.

This was simply a set of tools I wanted for myself.  But others may find them useful.

### Have a URL or images of the project?
https://crosseye.github.io/covid/

**Comment by tiffehr** [comment]
Thank you!  Added to our Collection of Examples, for the public to peruse.
