### ISSUE TITLE
Example: Tabular Data and Graphs for Counties, States, Metro/Micro Statistical Areas, and Combined Statistical Areas

### ISSUE THREAD

**Issue by LeboRefugee** [nytimes/covid-19-data#341]
### Describe the project
To put it simply, I take the data compiled by the NY Times and produce tables showing cases & deaths through time, including weekly rate of increase and the number of cases for every 100,000 people over fourteen days for a given area.  It also shows how the top ten areas of various metrics have changed through time, shows the numbers and populations living in areas with low, increasing, or decreasing case rates, and when and at what level various areas saw their peak rates.  It essentially shows the sort of info I wanted to see in a not-flashy package.

### Have a URL or images of the project?
http://radunzel.com/wp/covid-19-counties/

**Comment by tiffehr** [comment]
Thank you!  Added to our Collection of Examples.
