### ISSUE TITLE
Data Issue:  06-25 New Jersey Death Jump

### ISSUE THREAD

**Issue by guzhiling** [nytimes/covid-19-data#342]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [x] Other

There is a jump from 06-24 to 06-25 for death in New Jersey. Is it due to the inclusion of probable death since 06-25? 

As of 26 June noon, the government website shows 13,018 + 1,854 deaths. (see the screen shot below)

![image](https://user-images.githubusercontent.com/37173670/85882704-64644080-b7a5-11ea-955f-7e0b818a2aef.png)

**Comment by albertsun** [comment]
Yes that's it exactly
