### ISSUE TITLE
Data Issue:  

### ISSUE THREAD

**Issue by JamesH-Lantern** [nytimes/covid-19-data#343]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [X] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources.

It seems New Jersey just had a huge spike in number of deaths and new cases yesterday without any news heralding these spikes... The number of new deaths went from 46 on 6/24 to 1877 on 6/25..   The number of new cases went from 158 cases to 2,158..   

Its suspicious in that it was not following a trend, and the new cases was such a perfect round number..  Also there was not really any New Cases in the last week to support such a big positive jump in deaths and new cases.

![image](https://user-images.githubusercontent.com/58083868/85886507-3f2afe80-b7b4-11ea-8098-e1875e873bfa.png)

![image](https://user-images.githubusercontent.com/58083868/85885048-ad21f680-b7b1-11ea-92df-2886bc67e642.png)

Thank you so much for doing this report - it has been very helpful to me....

**Comment by albertsun** [comment]
This is mentioned here https://github.com/nytimes/covid-19-data/issues/342 as well as in our commit message and an update to the README today.

New Jersey started reporting probable deaths for the first time today and released them in bulk without backdating.

**Comment by JamesH-Lantern** [comment]
Thank you Albert - Will check the Readme next time :)
