### ISSUE TITLE
Data Issue:  

### ISSUE THREAD

**Issue by lberke** [nytimes/covid-19-data#344]
### Describe the issue:

- [x] Suspicious number of cases or deaths

### Fuller details
The new cases and new deaths calculated for NJ between 6/24 and 6/25 do not look correct based on total cases and total deaths between earlier report dates.

44006New Jersey | 6/24/2020 | New Jersey | 34 | 169892 | 12995 | **158 | 46**
-- | -- | -- | -- | -- | -- | -- | --
44007New Jersey | 6/25/2020 | New Jersey | 34 | 172050 | 14872 | **2158 | 1877**

The 6/25 data doesn't seem reasonable based on this site:
https://nj.gov/health/cd/documents/topics/NCOV/COVID_Confirmed_Case_Summary.pdf

**Comment by lwaananenjones** [comment]
On 6/25, New Jersey started reporting probable deaths, which resulted in a one-day increase for cases and deaths. The state doesn't include probable data in its daily PDF report (yet), but it is labeled separately on the [state dashboard](https://covid19.nj.gov/). We add notes to the readme file when there are unavoidable data reporting anomalies like this: 

> On June 25, New Jersey began reporting probable deaths, adding 1,854 probable deaths that may date back to earlier in the outbreak to their total.

A new feature this week on our [state tracker pages](https://www.nytimes.com/interactive/2020/us/new-jersey-coronavirus-cases.html) is that spikes from data anomalies are labeled directly on the charts.

![nj-probables](https://user-images.githubusercontent.com/47159046/85930175-0bf97580-b86f-11ea-8236-111974d22ffe.png)
