### ISSUE TITLE
Data Issue:  pk

### ISSUE THREAD

**Issue by Pkannetwork-pk** [nytimes/covid-19-data#346]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources. Please check the README and recent commit messages for updates to see if your issue is addressed.

**Comment by tiffehr** [comment]
I don't see a report of any issue, just our Issue template.  Closing.  Please open a new GitHub issue if you have questions about our data, with a full description of the problem.
