### ISSUE TITLE
Importing the data into a Google Sheet

### ISSUE THREAD

**Issue by JohnDovey** [nytimes/covid-19-data#348]
### Describe the project
After seeing the example on how to import the data into MS Excel, I thought I’d share how to do so into Google sheets (https://github.com/nytimes/covid-19-data/issues/337#issue-645562260)
Paste the url for the CSV file into cell A1
https://github.com/nytimes/covid-19-data/blob/master/us.csv
In cell A2 put: =IMPORTDATA(A1)

**Comment by tiffehr** [comment]
Added to our Alternative Formats collection!  Thank you.
