### ISSUE TITLE
Question:  criteria for "falling", "rising", "about the same"

### ISSUE THREAD

**Issue by louking** [nytimes/covid-19-data#351]
### Your question
It's possible i missed this, but I don't see anywhere what criteria you're using to deem a state as "rising", "falling", or "about the same". I *think* you're comparing the 7 day average from today with the 7 day average from 14 days ago, but don't see what the delta is to trigger the category.

Is this documented anywhere, and if not should it be?

**Comment by louking** [comment]
For instance, it's not clear to me why today (6/28/20)  MA and CT are shown as mostly the same, and why PR, NH, VT are shown as decreasing

**Comment by tiffehr** [comment]
This dataset is `.csv` files with our collected counts.  It does not include NYT's own work to use this data for charts or maps.  That custom work is not included in this repository nor its methodology.

This [previous inquiry](https://github.com/nytimes/covid-19-data/issues/316) may be of some help, however.  And the methodology we have with our rising/falling bar charts clarifies a good deal as well.
![image](https://user-images.githubusercontent.com/60173/85960157-6548ce00-b96f-11ea-98dd-9c1c7eb1fc4d.png)
