### ISSUE TITLE
Data Issue:  Pecos County, TX on 20-06-09

### ISSUE THREAD

**Issue by adam-a-smith** [nytimes/covid-19-data#352]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [X] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
In your us-county data, Pecos County, TX has suspicious numbers:

2020-06-08 | Pecos | Texas | 48371 | 105 | 0
2020-06-09 | Pecos | Texas | 48371 | 27 | 0
2020-06-10 | Pecos | Texas | 48371 | 107 | 0

It looks like maybe a typo? Or did someone really intend for the number of cases to drop 78 in one day, only to raise by 80 on the next?

**Comment by tiffehr** [comment]
Our [Methodology](https://github.com/nytimes/covid-19-data/blob/master/README.md#methodology-and-definitions) explains our sourcing, all of which is publicly available for you to examine yourself.  

Our figures for Pecos County are provided via the state heath department, Texas Health & Human Services.  Texas HHS provides [this dashboard](https://txdshs.maps.arcgis.com/apps/opsdashboard/index.html#/ed483ecd702b4298ab01e8b9cafc8b83) with both state and county figures, including Pecos County.  The state's figures for Pecos County come from the county itself, though they provide [very little to corroborate local cases](https://www.co.pecos.tx.us/covid19/).  

However by looking up Texas HHS's publicly available [Trends by County](https://tabexternal.dshs.texas.gov/t/THD/views/COVIDExternalQC/COVIDTrends?:isGuestRedirectFromVizportal=y&:embed=y), it shows Pecos County's figures with a large change and a correction, around the dates you mention.

![image](https://user-images.githubusercontent.com/60173/85976325-56cad880-b9a8-11ea-8793-be6b4609ae4b.png)

With zero fatalities to confuse the data entry (like flip-flopping data entry), we cannot assume anything about this pattern.  To me it does not read as a typo.  But it is a correction all the same, from the county or state itself.
