### ISSUE TITLE
Data Issue:  Data for Hunterdon county NJ for 6/25/2020 through 6/28 seems incorrect

### ISSUE THREAD

**Issue by sesamler** [nytimes/covid-19-data#355]
Hunterdon's own site for 6/28 has 1,072 cases and 68 deaths for 6/28.  This file has 1129 and 123 respectively for 6/28.
I've emailed Karen Demarco @ Hunterdon as well.  thanks

**Comment by lwaananenjones** [comment]
On 6/25, the [New Jersey state dashboard](https://covid19.nj.gov/) began including probable deaths as well as lab-confirmed deaths. Our data includes probable cases and deaths when available, which accounts for the differences you're seeing. 

<img width="401" alt="hunterdon-nj-0629" src="https://user-images.githubusercontent.com/47159046/86045393-5f4efd80-ba00-11ea-8ef0-f8696ed01e5a.png">
