### ISSUE TITLE
Data Issue:  Missing updated data for Dallas Texas 6/28

### ISSUE THREAD

**Issue by furtip** [nytimes/covid-19-data#356]
### Describe the issue:
- [x] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

Counties data missing updated from Dallas Texas
Dallas reported 20165 cases and 352 deaths as of 2020-06-28
https://www.keranews.org/post/covid-19-live-updates-dallas-county-reports-record-572-cases
They also have released number for 6/29 which aren't in the live file, but I don't know when your sweep takes place, but the live file is still showing 6/27 totals for 6/29

**Comment by lwaananenjones** [comment]
Thank you for bringing this up. Our data for Dallas County gets pulled automatically from the [county dashboard](https://www.dallascounty.org/departments/dchhs/2019-novel-coronavirus.php), and there was no new data in that location for 6/28. It's common for county websites to be updated Monday-Friday, so missing data on the weekends does not always get flagged as an issue. We can revise this data after verifying with the county.

**Comment by albertsun** [comment]
As of this morning's update Dallas County data for that date has been updated.
