### ISSUE TITLE
Data Issue:  High number of deaths on 06/25 (2,437 deaths USA)

### ISSUE THREAD

**Issue by jrtonin** [nytimes/covid-19-data#357]
Why the 2,437 deaths reported on 6/25 from USA, and that number is not seen in other opened databases?

**Comment by lwaananenjones** [comment]
On 6/25, New Jersey added probable deaths to its public data dashboard. Our data includes probable cases and deaths when available. We add notes to the readme file when there are unavoidable data anomalies such as this:

> On June 25, New Jersey began reporting probable deaths, adding 1,854 probable deaths that may date back to earlier in the outbreak to their total.

We've also started adding notes on the [United States charts](https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html) when data from one state affects the national total to clarify those anomalies. 

![usa-nj-deaths](https://user-images.githubusercontent.com/47159046/86061763-3472a280-ba1c-11ea-9f0f-8a6e7d0112da.png)
