### ISSUE TITLE
Enhancement: Add positivity or total tests taken

### ISSUE THREAD

**Issue by etietje** [nytimes/covid-19-data#358]
It would be amazing if you could share a postivity rate, or the total tests taken (so I could calculate my own rate). Any chance of that happening?

**Comment by afischer** [comment]
Hi @etietje, testing information is not included in our dataset, and while we have seen testing data become more widely available, it still isn't reported consistently across states at the level of detail required for accurate tracking.

We do include "probable" cases and deaths in our counts, which include positive antibody tests. You can read more about that methodology here: https://github.com/nytimes/covid-19-data/blob/master/PROBABLE-CASES-NOTE.md
