### ISSUE TITLE
Data Issue:  MI data for June 5 is way too high

### ISSUE THREAD

**Issue by etietje** [nytimes/covid-19-data#359]
### Describe the issue:
- [X ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
Cases and Deaths skyrocketed in MI on 6/5. It looks like maybe a factor of 10x?

**Comment by amyswalk** [comment]
Hi @etietje, Michigan started reporting probable cases and deaths on that date. The spike that's now showing on 6/5 includes cases and deaths likely going back months, but we don't have date information for those added cases unless the state provides it. We add notes to the [readme](https://github.com/nytimes/covid-19-data/blob/master/README.md) file when there are unavoidable data reporting anomalies like this.

We are also labeling data anomalies like this on the [state pages](https://www.nytimes.com/interactive/2020/us/michigan-coronavirus-cases.html). 

<img width="574" alt="Screen Shot 2020-06-30 at 9 23 05 AM" src="https://user-images.githubusercontent.com/19143079/86131203-5703ca80-bab3-11ea-8f24-74f73c0c2699.png">
