### ISSUE TITLE
Request: Provide date and time the data was collected

### ISSUE THREAD

**Issue by lRn2Win** [nytimes/covid-19-data#36]
Cross validating data with JHU/WHO show discrepancies which might be attributed to differences in the time when data was collect via your source. Can you provide the exact times when the data for a given county is collected? 

For example, JHU for New York City on 3/25 show 17857 cases and 199 deaths and your data shows 20011 cases and 280 deaths.

**Comment by dannguyen** [comment]
The 199 deaths in NYC on 3/25 was a number that was reported at 9 AM: http://web.archive.org/web/20200325232018/https://www1.nyc.gov/assets/doh/downloads/pdf/imm/covid-19-daily-data-summary.pdf

The 5:30PM report later that day has  the 20,011 cases and 280 deaths: http://web.archive.org/web/20200326120314/https://www1.nyc.gov/assets/doh/downloads/pdf/imm/covid-19-daily-data-summary.pdf

**Comment by albertsun** [comment]
Not all of our case and death counts are sourced from a single source like scraping a government website. Particularly in the early days, many lines of data were combined from multiple sources at different times which were combined together and revised. As we go forward and move more towards a system powered by scraped data we may consider adding this information.
