### ISSUE TITLE
Example: CV Leaderboard

### ISSUE THREAD

**Issue by gmillikan** [nytimes/covid-19-data#360]
Easy-to-understand charts comparing new cases, fatality rate with every state and county normalized "per 100,000" for easy comparison. In fact, each of the 3,000 counties are compared to neighboring counties to make it easy to see if we're doing better or worse.  The mission of the site is simply to make the numbers easy to see and understand to empower us to make knowledgeable decisions.  We very much thank the NY Times in many places for their awesome work in making this data available (for example see "Data" page at link below).

### Have a URL or images of the project?
- The main page comparing states (click the bars to drill down).  https://www.cvleaderboard.org/USA/coronavirus-cases-by-state/   Note these charts are friendly for color blind people as they can see the bar lengths.  In other words the red/green is for cosmetic enhancement only, not crucial for the use of the site. We did that on purpose.

- Here's a state page (California): https://www.cvleaderboard.org/USA/california/  Will be adding new cases per capita as soon as we come up for air.

- County level page for Harris County, TX. Click the "16 weeks" link at top of page for long term trend view.  https://www.cvleaderboard.org/USA/texas/harris-county/

- The data from every chart can be downloaded as CSV or Excel -  just click the menu icon in the right hand corner of each chart. Here's the link to the "data" page where we highlight New York Times: https://www.cvleaderboard.org/data.php

- We've invested a lot of technology in the site to be able to handle millions of requests. We're using Cloudflare as our front end and collocated in the huge One Wilshire facility in Los Angeles on a gigabit Ethernet connection hosted by CoreSite.

- We'll have email alerts for all 3,000 United States counties, boroughs and parishes tomorrow.  We're in our final beta testing today.  Here's the link if you'd like to give a test before we go public. Would appreciate your feedback. 
 https://www.cvleaderboard.org/alert/

Thanks so much to the NY Times for making this data available, it's a huge service to us all.  I doubt many people will know how much good you are doing.  Much respect and appreciation to the team.

Respectfully,

--Geoff Millikan

**Comment by tiffehr** [comment]
Thank you for sharing!  I added this to our Collections, under Examples.  We appreciate the extra effort put into the data-sourcing credits, too.  👍
