### ISSUE TITLE
Example: Mobile-friendly interface for navigating the top COVID datasets

### ISSUE THREAD

**Issue by bcunning** [nytimes/covid-19-data#361]
### Describe the project
RonaViz is a fast, mobile-friendly interface for the Times' dataset. I wanted to build a quick way to check in on friends and family in other states and counties to see how things are doing there. I found it especially useful to supplement the Times' data with hospitalizations and testing data to get as clear picture as possible of where things are at. The design is built for quickly navigating different levels of hierarchy in the country. You can quickly tap on states, and zoom into specific counties. If you're interested in a more holistic perspective of the country, the table at the top works great for that too.

The data is always current and updates to use live data as soon as a significant chunk of it is reported. The supplemental data comes from the COVID Tracking Project and Google Community Mobility Reports.

Massive thank you to the Times for making this dataset available. It's a true national resource and makes me proud to be a subscriber.

The code that powers the site is available on [github](https://github.com/bcunning/CoronaViz).

### Have a URL or images of the project?
The site is available at [ronaviz.com](https://ronaviz.com)

Here are a few screenshots of the project:

<img src="https://user-images.githubusercontent.com/507749/86278492-7af40880-bba6-11ea-90f8-5b7ab55b509e.png" width="300">  

_Selecting a state to see which counties have seen the most new cases._

<img src="https://user-images.githubusercontent.com/507749/86278515-80515300-bba6-11ea-9108-b7e6444ed5bd.png" width="300">  

_Comparing case growth in a region over time._

<img src="https://user-images.githubusercontent.com/507749/86278540-8c3d1500-bba6-11ea-885d-902352ed25b1.png" width="300">  

_Monitoring the national test positive rate_

<img src="https://user-images.githubusercontent.com/507749/86278680-cc9c9300-bba6-11ea-9c00-9fffb3acf5eb.png" width="300">  

_Viewing current hospitalizations for a region of the country_

<img src="https://user-images.githubusercontent.com/507749/86278549-8fd09c00-bba6-11ea-887b-03f739fb283d.png" width="300">

_Examining retail visitation behavior as it compares to the national average_

**Comment by gmillikan** [comment]
That's so great it works well on mobile. That's such a needed thing and so hard to do.  Thanks for doing that.  I hope it gets a lot of traction because so many other sites don't work well or are confusing with lines everywhere.

**Comment by tiffehr** [comment]
Thank you for sharing! This looks great. I added it to our Collections (a Project board) under Examples.

**Comment by Nicole58** [comment]
This is fabulous! thanks for sharing. one of the best I've seen

**Comment by bcunning** [comment]
Thank you! I love interactive data viz. The Times (and Mike Bostock while he was there) are a big source of inspiration to me.

**Comment by tiffehr** [comment]
🙂
