### ISSUE TITLE
Data Issue:  The files for today are mislabeled/mistitled shows 7/30 and s/b 6/30

### ISSUE THREAD

**Issue by BAR-B-Q** [nytimes/covid-19-data#362]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [x] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources. Please check the README and recent commit messages for updates to see if your issue is addressed.

**Comment by ddenenberg71** [comment]
Where is this observed?  Which file?  Thanks.

**Comment by albertsun** [comment]
Hi @BAR-B-Q thanks, this was my mistake with a typo in the commit message. The data files are correct and have data for 6/30, it's only the commit message that says 7/30.

Sadly I think the only way to fix it now is with a force push to the repository but that will mess up anyone who has already pulled. Unfortunately just have to live with it.

**Comment by BAR-B-Q** [comment]
Yes - guess that would have helped to include (sorry) 
see:  https://github.com/nytimes/covid-19-data <https://github.com/nytimes/covid-19-data> 

the US, state, county, and ReadMe csv files

**Comment by BAR-B-Q** [comment]
I sort of guessed that might be the situation - I noticed the data on the file are correct!  Thanks for the response.

Barb

**Comment by gmillikan** [comment]
Thanks for not committing again because yeah, we could handle it but would re-time stamp all out “update” times on our charts and could be confusing to users thinking that the underlying data changed, when it hasn’t. Thanks again.
