### ISSUE TITLE
Question:  What is the logic for skipping a week when calculating 'falling, rising, about the same' classifications:

### ISSUE THREAD

**Issue by jazz788** [nytimes/covid-19-data#363]
### What is the logic for skipping a week when calculating 'falling, rising, about the same'  classifications:

As mentioned by @albertsun  before 

> "the scale on the map is based on the change in the 7-day trailing average number of cases compared to two weeks ago."

Practically this means for example today (July 1st) the classification is calculated based on:

- 7 days to Jun 31st, compared to 
- 7 days to Jun 17th

What is the logic in ignoring the preceding week (in this case the 7 days to June 24th).  It does not feel intuitive, but I'm sure there is some thinking behind it, so it would be great to hear it

Many thanks.

**Comment by bsaunders23** [comment]
Reference to earlier ticket defining logic for NYT thresholds if anyone's looking for it https://github.com/nytimes/covid-19-data/issues/316#issuecomment-643779708

**Comment by albertsun** [comment]
Hi @jazz788 and others, we don't think of the comparison specifically as "skipping a week", though your framing of it that way is not inaccurate I suppose. It's simply meant to show how the current situation has changed from a time in the recent past that is long enough ago to show a meaningful difference, but close enough ago that it is still timely.

**Comment by jazz788** [comment]
Thanks @albertsun  helpful, greatly appreciated.
