### ISSUE TITLE
Question:  The current dataset for Counties is at 291760 records. 

### ISSUE THREAD

**Issue by mrolfer** [nytimes/covid-19-data#365]
Is it possible to publish a version with perhaps the last 30 days? Excel is starting to choke on this many records when I open the CSV.

**Comment by samboy** [comment]
Here’s a version with county data for 2020-06-10 to 2020-07-12 
[data-101011lines.zip](https://github.com/nytimes/covid-19-data/files/4917050/data-101011lines.zip)

Here is where I mutter darkly about Wirth’s law. 

But, it’s possible to ignore Wirth’s law. Let’s take Lua, a 120 kilobyte sized scripting engine, which, among other things, powers every single Roblox game out there. This 120k program can be told to load the *entire* NYtimes county dataset, puts it in memory, copies that dataset twice, one for cases, another for deaths, has in memory detailed cases, population, and death statistics, then can make an entire 200 megabyte website with that information, in under 90 seconds using well under a gigabyte of memory.

**Comment by cj2001** [comment]
As this dataset gets larger, you might want to consider moving over to a tool or programming language that can handle all of that.  Excel is really not designed for this.  I might recommend Python or R.

**Comment by mrolfer** [comment]
Thanks but for some reason this dataset started opening in Excel in a fairly short amount of time.

Regards,
Michael

**Comment by albertsun** [comment]
Glad to hear that @mrolfer 

I'll close this issue out then
