### ISSUE TITLE
Data Issue: Harris county data is missing for 7/3

### ISSUE THREAD

**Issue by bcunning** [nytimes/covid-19-data#369]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [X] Missing time-series information
- [ ] Other

### Fuller details
Live data for 7/3 is missing both Harris County and Los Angeles county. These are two of the biggest counties in the country in terms of # of cases. I’m not sure about LA but it seems like Harris should definitely have data for the day. The totals without these counties are being displayed live on the Times’ site.

**Comment by albertsun** [comment]
Hi @bcunning I don't think we see what you are seeing. From looking back through each commit, the datafiles always had rows for Los Angeles,California and Harris,Texas.

**Comment by bcunning** [comment]
Hey @albertsun sorry, I should’ve been more specific. The values are there but haven’t changed from 7/2. It looks like LA county isn’t being reported elsewhere but it seems at least like state totals elsewhere have numbers that reflect about what you’d expect from those counties recently.

Could be some counties not reporting due to the holiday? Just threw me off because the new cases for TX and CA seem like an undercount relative to how they’re tracked elsewhere.

**Comment by albertsun** [comment]
Yes, that's right, many counties and states are reporting data less regularly due to the holiday.

**Comment by albertsun** [comment]
It turns out we did miss an update of the number for Harris County. We've now updated the data for 7/3 with the higher number.

**Comment by bcunning** [comment]
Ah ok. That’s what it looked like. Thanks Albert!
