### ISSUE TITLE
Data Issue:  Harris County TX not updated for 7/3.  Coorect enries (from County website) are 35,316 & 395.

### ISSUE THREAD

**Issue by MirrorCola** [nytimes/covid-19-data#370]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources. Please check the README and recent commit messages for updates to see if your issue is addressed.

**Comment by albertsun** [comment]
We did originally miss the update for Harris County, but have updated Harris County's numbers for 7/3 now.
