### ISSUE TITLE
Add section for projects that use this data

### ISSUE THREAD

**Issue by lodenrogue** [nytimes/covid-19-data#371]
I've created a command-line tool for using and performing operations on this data: https://github.com/lodenrogue/covid-cli

I think it would be a good idea to add a section in the README where we can list projects using this data

**Comment by tiffehr** [comment]
We have a Project board collecting such info, specifically the column marked as Examples.  https://github.com/nytimes/covid-19-data/projects/1

**Comment by lodenrogue** [comment]
Sorry Id didn't see that. How can I add my project there?

**Comment by tiffehr** [comment]
Use our "Examples" Issue type, please!
