### ISSUE TITLE
Data Issue:  Problems with daily totals of Utah counties

### ISSUE THREAD

**Issue by jsutah** [nytimes/covid-19-data#374]
- [ ] Incorrect number of cases or deaths

I have been reviewing the daily numbers for counties throughout Utah. At first, the data seemed to be consistent with that reported, but later I have found dramatically high numbers for individual counties. For instance, the most recent report on July 4 for Salt Lake County, the case count for that day reads 12,435 and there are many other instances where this appears in the spreadsheet prior to this date. The reason I feel this data is incorrect is that for Utah as a whole, we have not experienced a day in which the total has exceed 700.

Can you help me understand where these totals are derived from as there seems to be something drastically wrong with the totals being reported in the dataset?

Thank you!

**Comment by jsutah** [comment]
Follow-up to my comment...are the daily values the total number of current cases within each county or are these the total number of new cases reported for the day? I believe this is where I am seeing problems and it may just be the interpretation of the data values.

Thanks!

**Comment by lwaananenjones** [comment]
All our data represents cumulative counts, so the 12,435 figure matches the total cases listed on the [Salt Lake County data dashboard](https://slco.org/health/COVID-19/data/). (This is different from the charts on our [state pages](https://www.nytimes.com/interactive/2020/us/utah-coronavirus-cases.html) that do show new cases by day.)

With the repeated value for Salt Lake County, you're seeing a common quirk in health department data reporting schedules. We compare the numbers published by the state and the county, and counties often report ahead of the state. But many counties do not update on the weekends, which means the case count doesn't change unless the state catches up and reports a higher number.
