### ISSUE TITLE
Please time the update of the historical files with the rolling of the "live" file

### ISSUE THREAD

**Issue by PatrickDRusk** [nytimes/covid-19-data#375]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [X] Missing time-series information
- [ ] Other

### Fuller details
I programmatically access your historical files and tack on the "live" file to create a complete data set. However, I have noted that the "live" file rolls forward to a new day hours before the historical files get updated for the prior day. So there is a time gap where I can see (today) data through June 4, and preliminary data for June 6, but no data for June 5, notwithstanding that I had a pretty good picture of June 5 just hours before.

Any chance you could coordinate the commits that update the historical files with the rolling of the live file?

**Comment by albertsun** [comment]
Hi @PatrickDRusk that's a good point. We're working on better automating the updates of this data, and the new method should update the files all together to avoid this gap.

**Comment by albertsun** [comment]
We've retooled our workflow and this date gap issue should no longer happen.
