### ISSUE TITLE
Data Issue:  Louisiana data 6/17-19: number of cases increase, then decrease, then increase.

### ISSUE THREAD

**Issue by cph015** [nytimes/covid-19-data#377]
### Describe the issue:
- [X] Incorrect number of cases or deaths
- [x] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources. Please check the README and recent commit messages for updates to see if your issue is addressed.

See suspicious data below:

us-states.csv:

6/17/20 | Louisiana | 22 | 48746 | 3062
6/18/20 | Louisiana | 22 | 49506 | 3069
6/19/20 | Louisiana | 22 | 48627 | 3084
6/20/20 | Louisiana | 22 | 49497 | 3104
6/21/20 | Louisiana | 22 | 49890 | 3105

**Comment by lwaananenjones** [comment]
This decrease on 6/19 is the result of a state data adjustment to remove duplicate cases and nonresidents. Here is the note from the state on that day:

> LDH has implemented a new process for improved de-duplication and parish assignment of data received from labs around the state. In doing so, LDH identified a total of 1,666 existing duplicate cases as well as cases of out-of-state residents. These have been removed in the updated case count today.
