### ISSUE TITLE
Data Issue:  San Diego county cases not matching the county dashboard

### ISSUE THREAD

**Issue by gkarthik** [nytimes/covid-19-data#378]
### Describe the issue:
- Data inconsistency

### Fuller details

The cases in the NYT dataset do not match the data from the [San Diego county dashboard](https://www.arcgis.com/apps/opsdashboard/index.html#/96feda77f12f46638b984fcb1d17bd24). Seems to be consistently different ~~lower and deliberate~~. I was wondering if there was a specific reason for this. 

I've listed some dates as an example below, 

NYT data
```
2020-06-29,San Diego,California,06073,13895,361
2020-06-30,San Diego,California,06073,14212,365
2020-07-01,San Diego,California,06073,14686,372
2020-07-02,San Diego,California,06073,15270,377
2020-07-03,San Diego,California,06073,15759,387
2020-07-04,San Diego,California,06073,15761,387
2020-07-05,San Diego,California,06073,16789,387
```

Cumulative cases from San Diego county dashboard,

```
2020-06-29,14149
2020-06-30,14623
2020-07-01,15207
2020-07-02,15696
2020-07-03,16164
2020-07-04,16726
2020-07-05,17000
```

Thank you for all your effort in creating and maintaining this resource!

**Comment by lwaananenjones** [comment]
There are two factors that explain the differences you're seeing:

1. We include 63 cases from the USS Kidd, which arrived San Diego in late April so infected crew members could be treated there. The county does not include these cases.
2. The county backdates by a day, so the data reported by the county on 7/5 is labeled as 7/5 in our data and 7/4 in the county data. That's because each day they announce the previous day's total. We use the date it was announced.

**Comment by gkarthik** [comment]
Thank you for clearing that up @lwaananenjones. I had one last question, the increase in cases on `2020-07-04` from `2020-07-3` is `2` according to the NYT dataset. However it is, `274` in the county dataset (considering the backdating difference will be `2020-07-05` - `020-07-04`). This is quite a significant difference. Is this an artifact? Thank you once again.

**Comment by lwaananenjones** [comment]
It looks like this is because the county didn't update its dashboard on the holiday, so our data for 7/4 came from the state dashboard instead. We can update that to use the county number for 7/4. That adjustment will show up soon.
