### ISSUE TITLE
Data Issue: TX Death Toll Data appears slightly overstated 

### ISSUE THREAD

**Issue by ecebulski** [nytimes/covid-19-data#379]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths

### Fuller details
The number of deaths as of 7/6 for TX appears to be 2655 according to the dashboard data on  [https://www.dshs.state.tx.us/coronavirus/](url), [https://www.cdc.gov/covid-data-tracker/#cases](url) while cumulative data within this data set states the number of deaths as 2726 as of 7/6.

**Comment by amyswalk** [comment]
Hi @ecebulski, we collect data from the states and the counties. Some counties report cases ahead of the state, and this is true in Texas. Some Texas counties also report probable cases per CDC's recommendation. The state does not, though has said previously that it will share these publicly in the future. You can find more details about probable cases in our note [here](https://github.com/nytimes/covid-19-data/commit/b14a9b8dd14114cf2ecb4a943c7c5051ac94212a).
