### ISSUE TITLE
Great podcast on "The Daily" featuring the NYT data team (link below)

### ISSUE THREAD

**Issue by knwpsk** [nytimes/covid-19-data#380]
Interview with Rob Gebeloff, head of the NYT data team, who curates this data.  Figured a lot of users might enjoy listening to it.  Good show, Rob!

https://player.fm/series/the-daily-1354914/counting-the-infected

**Comment by guzhiling** [comment]
Thank you for sharing! It was very informative. I cannot thank NYT data team more for their commitment and professionalism in dealing with the pandemic data during this difficult time.

**Comment by tiffehr** [comment]
Very glad you like the episode of our podcast.  This data set didn't have an explicit mention but our data-collection process did. Rob did a great job representing the work and what flows from it in other NYT coverage. 

The story Rob co-bylined, [The Fullest Look Yet at the
Racial Inequity of Coronavirus](https://www.nytimes.com/interactive/2020/07/05/us/coronavirus-latinos-african-americans-cdc-data.html), acquired data from the CDC.  This public data set provided a baseline, but we did not have historically comprehensive race v. impact.  The CDC's data augments this nicely, for county by county analysis.

**Comment by knwpsk** [comment]
@tiffehr will you be posting the CDC data here too?  Would be very interesting.

**Comment by tiffehr** [comment]
@knwpsk No, as mentioned in the podcast episode, the story and in other Issues here, we're still in discussions with the CDC about getting more data and backfilling information in what they have provided so far.  Ideally, they would release it themselves, to all.
