### ISSUE TITLE
Question:  Data from article on racial inequalities

### ISSUE THREAD

**Issue by MP1285** [nytimes/covid-19-data#381]
Hello, would the data from this article -- tracking Covid incidence by race - be uploaded on the Github repository: https://www.nytimes.com/interactive/2020/07/05/us/coronavirus-latinos-african-americans-cdc-data.html

Is there a way to gain access to the data used for the article? Many thanks.

**Comment by albertsun** [comment]
Hi @MP1285, we are not releasing the raw underlying data from the CDC at this time, as discussions and legal matters with the CDC proceed over what additional data they will publish continue.

The underlying source data for the map published on that page _is_ available in the source code of the page if you snoop around here: https://static01.nyt.com/newsgraphics/2020/06/17/coronavirus-race/b3a7a35bf5974b44b7fba2fd4a22c036a136deae/data.csv

**Comment by MP1285** [comment]
Thank you ! This is super helpful !

**Comment by GShotwell** [comment]
Is there somewhere we can suggest research questions for you to look at? 

There was a great paper which showed that the racial covid gap increased with latitude during the spring, which is an excellent argument for vitamin D's involvement. I think your dataset could probably provide a better answer as to whether this is actually the case. https://nutrition.bmj.com/content/early/2020/05/20/bmjnph-2020-000096

Here's some commentary on the paper: https://shotwell.ca/posts/2020-05-23-race-and-covid/

**Comment by loweas** [comment]
Is there an end date for the data you provided above (https://static01.nyt.com/newsgraphics/2020/06/17/coronavirus-race/b3a7a35bf5974b44b7fba2fd4a22c036a136deae/data.csv) ?

Like is it cumulative from Jan 1. 2020 -Jun 30th 2020?

**Comment by albertsun** [comment]
Please consult the methodology section from the original article for any questions about that data file. As we're not releasing it here we are not going to be able to say much more about it on Github.

**Comment by loweas** [comment]
> Please consult the methodology section from the original article for any questions about that data file. As we're not releasing it here we are not going to be able to say much more about it on Github.

Thank you for the quick response!

**For any academics looking to use this data note - Methodology says end of May but map pictures say May 28th 2020.**
