### ISSUE TITLE
Enhancement: Note inclusion of probable cases/deaths

### ISSUE THREAD

**Issue by mbauman** [nytimes/covid-19-data#382]
### Is your feature request related to a data problem?

No, but it would help resolve [_many_ data issues](https://github.com/nytimes/covid-19-data/issues?q=probable).

### Describe the feature you would like to see

Not all states/counties are including probable cases, and when they begin including them, this leads to a large day-over-day increase — and it results in spurious data issues here.  It'd be nice to include a column in the primary dataset that notes which rows include probable data and which rows do not in their cumulative totals.  While this could simply be a boolean noting that _some_ probable cases are included, it would be more capable of representing the situation on the ground if it were a bit more complicated.

For example, it could be an integer noting a probable inclusion policy "version number".  A value of 0 would mean no probable cases/deaths are included, with each successive increment would simply note that there's been a change in how the probable cases/deaths are included (potentially noting the new inclusion of a batched re-evaluation of historical cases/deaths).  This would allow data users to automatically identify and triage discontinuities, while simultaneously allowing them to accurately label data that are wholly "confirmed" vs. those that are "confirmed and probable."

### Describe alternatives you've considered

This information could be encoded in many forms.  An alternative form could be a column that notes that _date_ from which probable cases are included in the cumulative total.  This would be a missing value for states that have not yet included probable cases, then become populated with a recent date once they begin including recently-diagnosed probable cases, and would jump backwards if they go back to add historical probable cases.  The downside with this formulation is that it doesn't support noting batched inclusion of successive historical analyses over the same date-ranges.

Another alternative would be a completely separate table that simply notes dates of policy changes in the reporting within particular jurisdictions.  This would be easily extensible with a few more columns to detail _how_ things changed.

In an ideal world, it'd be nice to completely separate the probable + confirmed numbers into two columns, but I understand that's not possible due to the anemic data reporting in some jurisdictions.  While it'd help some with batched historical discontinuities from probable re-analysis (as they'd be limited to the probable column), data users would still be blind to the cause of the discontinuity.  Proposed enhancements like #230 would go farther to address this, but are even less likely to be possible nationwide.

**Comment by albertsun** [comment]
HI @mbauman, apologies for the much delayed response and thank you for proposing this idea. We don't currently have enough information even internally to do what you're proposing. One of the biggest challenges we face is figuring out what methodology the state and local health departments we gather data from are themselves using.

We would definitely like to give everyone a better picture of probable vs confirmed cases as they are reported though and are continuing to think about how best to do that.
