### ISSUE TITLE
Data Issue:  New Mexico case numbers don't reflect data corrections

### ISSUE THREAD

**Issue by russbiggs** [nytimes/covid-19-data#383]
### Describe the issue:
- [x] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
The statewide case numbers reflect the totals as reported each day but with each daily reporting the NMDOH issues corrections for the previous day's total. Corrections don't happen everyday but more often than not some correction is released, generally around non-residents incorrectly reported as residents, test cases that were false positive, double counted tests etc. They often aren't a huge difference but have been up to 10% off in the new cases count. e.g.:

| Date  | reported  | corrected |diff |
|---|---|---|---|
| 2020-07-03  | 12776  | 12772  | -4 |
|  2020-07-04  | 13063  |  13053 | -10 | 
|  2020-07-05  |  13256 |  13254 | -2 |
| 2020-07-06 |  13507 |  13506 | -1 |
| 2020-07-07 | 13727  |  13727 | 0 |

The corrected historical numbers are not updated on the site but *are* used in charts and in talking points by state officials. I'm happy to assist in how the corrections can be incorporated from the data provided on the site.

**Comment by lwaananenjones** [comment]
Thank you for bringing this up. Several states report this type of daily correction, though New Mexico does an especially good job of including it consistently and with the affected counties identified. However, I don't think we can confidently assume the corrections only affect the previous day's data; a case removed as duplicate may have been included for days or weeks before the state corrected the error. 

In general, if there is any uncertainty about historical corrections we are leaving the data as it was reported. We may eventually be able to revisit this, but so many states and counties routinely make small adjustments that we don't currently have the capacity to revise on a daily basis as long as the data accurately reflects what was announced each day.

**Comment by russbiggs** [comment]
@lwaananenjones Thanks for following up and your policy on data corrections definitely makes sense given the volume of data you're working with. You are correct that my current method in "correcting" makes a pretty big assumption that the difference all falls on one day, my goal was to simply remove the duplicates which stack up pretty quick (~150 in the past month and a half). I'll keep my eye on this and hopefully there might be a more detailed method I can throw your way to better pinpoint the corrections.

**Comment by tiffehr** [comment]
Thanks very much, @russbiggs!  We'll keep an eye on New Mexico's , knowing you are as well.  🙂
