### ISSUE TITLE
Data issue: NYC Death severely undercounted on Jun 29 and severely overcounted on Jun 30

### ISSUE THREAD

**Issue by dcthomas0518** [nytimes/covid-19-data#385]
Source: us-counties.csv

Why is daily death count in New York City only 1 on Jun 29 and 625 on Jun 30? 

625 on June 30 is about three weeks worth of deaths, according to the recent trend. Where did the >600 deaths come from in one day in NYC?

NYC Deaths | Cumulative | Daily (derived)
26-Jun | 21,893 | 37
27-Jun | 21,913 | 20
28-Jun | 21,940 | 27
29-Jun | 21,941 | 1
30-Jun | 22,566 | 625
01-Jul | 22,574 | 8
02-Jul | 22,593 | 19
03-Jul | 22,610 | 17

Thanks

**Comment by albertsun** [comment]
We use data from both the NYC health department and the New York State health department. On June 29, the city health department did not announce any new deaths. Please take a look at the README for the explanation of June 30 — the city announced a large number of new deaths from the past in bulk.

**Comment by dcthomas0518** [comment]
I don't see the explanation of June 30 in the README since below is all I see regarding New York in README is for April, not June 30:

New York

All cases for the five boroughs of New York City (New York, Kings, Queens, Bronx and Richmond counties) are assigned to a single area called New York City. There is a large jump in the number of deaths on April 6th due to switching from data from New York City to data from New York state for deaths. We are not currently including the probable deaths reported by New York City.

For all New York state counties, starting on April 8th we are reporting deaths by place of fatality instead of residence of individual. There were no new deaths reported by the state on April 17th or April 18th.
