### ISSUE TITLE
Data Issue:  Lenawee County in Michigan is definitely wrong.

### ISSUE THREAD

**Issue by lyrrael** [nytimes/covid-19-data#386]
### Describe the issue:
- [X] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
https://www.lenawee.mi.us/931/COVID-19-Case-Testing-Information

Lenawee County Health Department reports 242 known cases and 36 probables, not ~1000.

**Comment by tiffehr** [comment]
Our source for Lenawee County is the [states' health department](https://www.michigan.gov/coronavirus/0,9753,7-406-98163_98173---,00.html), specifically their ["Cases and Deaths by County"](https://www.michigan.gov/documents/coronavirus/Cases_and_Deaths_by_County_2020-07-12_696192_7.xlsx) XLSX file.  We rely on them to report what Lenawee in turn reports to them.  

That spreadsheet currently reports
![image](https://user-images.githubusercontent.com/60173/87258813-854eb600-c474-11ea-96ca-cf5f8ec4f81c.png)

Our last few collections of that data from the XLSX file show a steady ~240 probable cases.
* 263 on 7/10/2020
* 275 on 7/11/2020
* 278 on 7/12/2020

We have no history from the source of a spike.

But I do see the incorrect figure for 7/11/2020 in our [County CSV](https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv):
![image](https://user-images.githubusercontent.com/60173/87259040-59343480-c476-11ea-9f18-e938c26f82a0.png)

We'll figure out where that came from and correct it.

**Comment by lyrrael** [comment]
Excellent! Thank you!

**Comment by lwaananenjones** [comment]
This is a common question about Michigan counties — we include prison cases in the county where the correctional institutions are located, to be consistent with how prison cases are included in most other states. Michigan instead lists prison cases as a separate category. In this case it's Gus Harrison Correctional Facility, which adds 730 cases. Those cases are listed on [this page maintained by the Michigan Department of Corrections](https://medium.com/@MichiganDOC/mdoc-takes-steps-to-prevent-spread-of-coronavirus-covid-19-250f43144337) in an image. This is a good example of the manual updates and reporting we do to make the data more comprehensive and consistent from state to state.

**Comment by lyrrael** [comment]
Oh wow, that’s fascinating. Thank you for taking the time to look and to explain it to me. Sorry to have taken your time!

**Comment by tiffehr** [comment]
Ah, thank you @lwaananenjones!
