### ISSUE TITLE
Example: New cases & deaths vs SIP dates

### ISSUE THREAD

**Issue by sbulen** [nytimes/covid-19-data#387]
### New cases & deaths vs SIP dates
My humble Excel analysis of new cases & deaths vs SIP dates, using this data.  I am sharing mainly because I don't think I've seen this emphasized enough or visualized in a way that demonstrates the effectiveness of SIP.  Top ten states are depicted, 7 day rolling average, log scale.  But instead of using dates as the horizontal axis, I used a calculation for days-since-statewide-SIP-order.

Now...  Maybe we need a similar chart for the recent spate of re-openings...

### The chart:
![image](https://user-images.githubusercontent.com/23568484/87256487-f3c94f00-c447-11ea-8e12-199432f02801.png)

The NY, NJ & Delaware recent adjustments really stand out, even with 7-day rolling averages...

Sources for SIP dates:
https://www.finra.org/rules-guidance/key-topics/covid-19/shelter-in-place
https://www.nytimes.com/interactive/2020/us/coronavirus-stay-at-home-order.html

**Comment by tiffehr** [comment]
Very nice, thank you!  This is an interesting way to rework state-level shelter in place markers. 

Added to our Collection of Examples, on our Project board!
