### ISSUE TITLE
Beautiful and easy to use site that shows how cases and deaths have progressed per county over time

### ISSUE THREAD

**Issue by david-l-weitz** [nytimes/covid-19-data#388]
### Describe the project
I could find no site that shows the progression of Covid by county, so I decided to build one using React and Firebase :)

### Have a URL or images of the project?
https://50statescovid.com/CA

**Comment by gmillikan** [comment]
Nice! Works pretty good on mobile too!  

BTW, our site has it all by county - below is weeks of Los Angeles County. 

https://www.cvleaderboard.org/USA/california/los-angeles-county/?days=56

**Comment by david-l-weitz** [comment]
> Nice! Works pretty good on mobile too!
> 
> BTW, our site has it all by county - below is 8 weeks of Los Angeles County.
> 
> https://www.cvleaderboard.org/USA/california/los-angeles-county/?days=56

**Comment by david-l-weitz** [comment]
Nice job Geoff!

**Comment by david-l-weitz** [comment]
One concern: I think the fatality rate chart you show is misleading. I see you have a disclaimer addressing how testing affects fatality rate. However, what in my mind can cause a bigger issue is the lag between cases and the deaths resulting from those cases. If you have a large spike in cases, but the deaths as a result of those cases have not occurred for example, your fatality rate will be deflated and will misrepresent the actual status of Covid in an area.

**Comment by tiffehr** [comment]
Thank you.  Added to our collection of Examples, on our Project board.  Please continue the conversation about this specific piece, but I'll close the issue.
