### ISSUE TITLE
Data Issue: Louisiana Information-> Discrepancy between Website and Readme File 

### ISSUE THREAD

**Issue by guzhiling** [nytimes/covid-19-data#389]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [x] Other

There is a minor discrepancy in the **June 19 & 20** updates. 
- In Readme
![image](https://user-images.githubusercontent.com/37173670/87316187-13658380-c4eb-11ea-9df8-1f6bf0a9073e.png)

- On [NYT website](https://www.nytimes.com/interactive/2020/us/louisiana-coronavirus-cases.html)
![image](https://user-images.githubusercontent.com/37173670/87316478-722afd00-c4eb-11ea-82fa-81c7d0299bca.png)

Also, I am wondering how the team track the period that the backlogged cases belong? I find this information is very difficult to find.

**Comment by albertsun** [comment]
Hi @guzhiling thanks for pointing this out. We've updated the notes on our article to reflect that those cases were removed on June 19 not June 20.

We don't always know the periods of backlogged cases. We track this by following the press releases and public dashboards of each state and territory and making notes of significant things when we find them.
