### ISSUE TITLE
Direct Data from County Officials?

### ISSUE THREAD

**Issue by hottweelz** [nytimes/covid-19-data#39]
From your list of sources, would you want direct contributions FROM local County EMA's?  As a member of mine, ours brought it up... you'd need some sort of validation.

For example, our County, Camden County, GA is listed as 1 case, whereas we do have 6

**Comment by dannguyen** [comment]
If anything, it'd be interesting to have an example of how/why these discrepancies exist. This [news article from yesterday](https://www.news4jax.com/news/georgia/2020/03/25/8-covid-19-cases-in-southeast-georgia-among-1247-statewide/) (along with others earlier in the week), mention the official tally of Camden having 1 case of Covid-19. Which county official is now reporting 6 cases?

**Comment by hottweelz** [comment]
I"ll confirm WHEN we identified 6, but I'm in direct talks with our County Admin who I help with EMA

**Comment by hottweelz** [comment]
Also you've identified another issue right there, we are Camden County, GA but RELY on Florida News because we are a Jacksonville FL Metro Area.... it's a mess.
