### ISSUE TITLE
In theory using the NYTimes API, could I plot new CV-19 cases per day using ggplot in R?

### ISSUE THREAD

**Issue by Montana** [nytimes/covid-19-data#393]
Thanks for this data New York Times, the thread title is my question, the example I present you with would look something like: 

```R
df %>% mutate(Orig_cases = ifelse(row_number()==1, sumCase, sumCase - lag(sumCase)))

 date cases cumCase Orig_cases
1  2020-01-01    88      88         88
2  2020-01-02    49     137         49
3  2020-01-03    14     151         14
```

**Comment by albertsun** [comment]
@Montana Yes, I'm not an R expert, but if that is subtracting the count on the previous day from the current day, that should give you the number of new new daily cases. Please read the README carefully, particularly the section on declining counts to understand the possible complications in interpereting the data that way.

**Comment by cj2001** [comment]
I have done it in [this](https://cj2001.shinyapps.io/summit_covid_dashboard/) open source dashboard via Shiny.  The source code is available both on the dashboard as well as [my repo](https://github.com/cj2001/summit_county_covid).

**Comment by Montana** [comment]
Thank you both! I really appreciate it @cj2001 and @albertsun!
