### ISSUE TITLE
Data Issue:  Large jump in NJ deaths from 6/24/20 to 6/25/20

### ISSUE THREAD

**Issue by ssmithClimate** [nytimes/covid-19-data#394]
There is a large jump in NJ deaths from 12,995 on 6/25 to 14,872 on 6/26. Was there some sort of reporting backlog? There is a similar jump in New York from 6/29/20 (31,143) to 6/30/20 (31,776).

https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv

**Comment by amyswalk** [comment]
Hi @ssmithClimate, please take a look at the README for the explanation for New York on June 30 — the city announced a large number of new deaths from the past in bulk.

On 6/25, New Jersey added probable deaths to its public data dashboard. Our data includes probable cases and deaths when available. We add notes to the readme file when there are unavoidable data anomalies such as this:

On June 25, New Jersey began reporting probable deaths, adding 1,854 probable deaths that may date back to earlier in the outbreak to their total.

We've also started adding notes on the United States charts when data from one state affects the national total to clarify those anomalies.

![nj probable jump](https://user-images.githubusercontent.com/19143079/87558987-b6eb9b00-c687-11ea-97b8-434f51ff0542.png)

**Comment by ssmithClimate** [comment]
Thank you!
