### ISSUE TITLE
Will Trump's order to bypass the CDC affect this data?

### ISSUE THREAD

**Issue by knwpsk** [nytimes/covid-19-data#396]
If hospitals follow the new order from the Trump Admin to bypass the CDC, and report their CV data directly to the white house -- will this affect NYT's ability to gather and curate this data? 
(I hope not!  It will be all the more important to have a reputable, reliable, independent source to check against any politicized numbers!)

Also - does NYT have a view on whether the hospitals are required to follow this new "order" ?

**Comment by Nicole58** [comment]
I've been wondering/worrying about this exact same thing!

**Comment by virtadpt** [comment]
I've been concerned about someone getting this repo pulled down.  That's why I've been keeping local copies of it.

**Comment by amyswalk** [comment]
Hi all, the new order should only affect hospitalization data (which used to appear on C.D.C.'s site [here](https://www.cdc.gov/nhsn/covid19/report-patient-impact.html)). You can see the full list of data that the administration is asking for [here](https://www.hhs.gov/sites/default/files/covid-19-faqs-hospitals-hospital-laboratory-acute-care-facility-data-reporting.pdf) (scroll down). Current reporting on this seems to indicate that states will still share hospitalization related data on their dashboards (though not all states currently do so). We are not tracking hospitalization data here. The Covid Tracking Project shares hospitalization data among states that report it.

**Comment by knwpsk** [comment]
<relief>
Thanks, Amy
