### ISSUE TITLE
Enhancement: Adding in ratio of positive to negative tests

### ISSUE THREAD

**Issue by cj2001** [nytimes/covid-19-data#397]
### Is your feature request related to a data problem?
No.

### Describe the feature you would like to see
It would be helpful to see the case data, broken down at the county level, on the ratio of the positive to negative tests.  We have seen that this ratio is increasing at the state level, but I am hoping to find that ratio aggregated at the county level and the existing NYT data set is the best I have seen for county-level data.  So I am just hoping to see another column of test positive ratio in `us-counties.csv`, based on date.

### Describe alternatives you've considered
My data exploration has revolved around certain counties within Colorado.  I have been through the CDHPE data stores and not been able to find it there.  I have also Googled on it to no avail.

**Comment by amyswalk** [comment]
Hi @cj2001, unfortunately data on negative tests is not consistently available at the county level. For Colorado, I'd look to the county (or city) public health departments to see if they report negative cases. [Denver](https://storymaps.arcgis.com/stories/50dbb5e7dfb6495292b71b7d8df56d0a) has negative cases on its dashboard, for example.
