### ISSUE TITLE
Data Issue:  Incorrect number of cases in Massachusetts

### ISSUE THREAD

**Issue by smach** [nytimes/covid-19-data#399]
### Describe the issue:
- [X ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
Your [Massachusetts map](https://www.nytimes.com/interactive/2020/us/massachusetts-coronavirus-cases.html) is showing 303 new cases for July 14. The [Massachusetts Dept of Public Health reported 203 new cases on July 14](https://www.mass.gov/doc/covid-19-dashboard-july-14-2020/download). 
![MA1](https://user-images.githubusercontent.com/3394160/87601477-3054af00-c6c3-11ea-9721-268319553592.png)
![MA2](https://user-images.githubusercontent.com/3394160/87601490-35b1f980-c6c3-11ea-940b-77aacefbd187.png)

**Comment by amyswalk** [comment]
Hi @smach, per C.D.C. and the Council of State and Territorial Epidemiologists we include probable cases in our case counts, as well as confirmed cases (in blue in your screenshot). You can learn more about these in the readme file. Massachusetts reports probable cases (and deaths) on page 21 of the [daily PDF dashboard](https://www.mass.gov/doc/covid-19-dashboard-july-15-2020/download) and offers definitions in the footnote.

**Comment by smach** [comment]
OK thank you.
