### ISSUE TITLE
FIPS needs definition	

### ISSUE THREAD

**Issue by ereinecke** [nytimes/covid-19-data#4]
Request that README include a definition, or link to a definition, of the FIPS code and what it means in this context.

**Comment by tunaboy** [comment]
Not sure, but I'd say Wikipedia is your friend here:

https://en.wikipedia.org/wiki/Federal_Information_Processing_Standard_state_code

**Comment by drPeteD** [comment]
Census publishes [County FIPS in csv](https://www2.census.gov/geo/docs/reference/codes/files/national_county.txt), or in a [PDF list](https://www.census.gov/prod/techdoc/cbp/cbp95/st-cnty.pdf).

**Comment by josh-byster** [comment]
I just published a new repo mapping FIPS to a central lat/long to plot on a map, see #51 for more info. Hope that's helpful! :)

**Comment by albertsun** [comment]
Thanks for pointing this out, we've updated the README to clarify FIPS codes.
