### ISSUE TITLE
Data Issue:  Rhodes Island Providence County Daily New Cases Higher than State level

### ISSUE THREAD

**Issue by guzhiling** [nytimes/covid-19-data#400]
### Describe the issue:
- [x] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

- Providence County Level Daily New Cases = 530
![F4F2A167-0F7E-4D12-A1CA-B64BBC61AD1B](https://user-images.githubusercontent.com/37173670/87699298-42cdf780-c75a-11ea-97d2-76bb83c71b69.jpeg)

- State Level Daily New Cases = 148
![4F8B7ADC-4211-4D67-B1A1-D5E6F0A3D45F](https://user-images.githubusercontent.com/37173670/87699301-43ff2480-c75a-11ea-9d1b-b1734d43606d.jpeg)

Is it due to probable cases at county level but not state level?

**Comment by albertsun** [comment]
Rhode Island updates its county level data much less frequently than its state level data. Because of that, when there is no county level data we assign new statewide cases to Unknown county. When new county level data is available, we update the counties and remove cases from Unknown county.

**Comment by guzhiling** [comment]
I see! Thank you for the explanation!
