### ISSUE TITLE
Question: How will transfer of data collection from CDC to HHS impact this collection?

### ISSUE THREAD

**Issue by sbulen** [nytimes/covid-19-data#401]
### Your question
It's all in the title...

**Comment by tiffehr** [comment]
This has been asked in a few other Issues, like #396.  As Amy replied:

> Hi all, the new order should only affect hospitalization data (which used to appear on C.D.C.'s site [here](https://www.cdc.gov/nhsn/covid19/report-patient-impact.html)). You can see the full list of data that the administration is asking for [here](https://www.hhs.gov/sites/default/files/covid-19-faqs-hospitals-hospital-laboratory-acute-care-facility-data-reporting.pdf) (scroll down). Current reporting on this seems to indicate that states will still share hospitalization related data on their dashboards (though not all states currently do so). We are not tracking hospitalization data here. The Covid Tracking Project shares hospitalization data among states that report it.

_Originally posted by @amyswalk in https://github.com/nytimes/covid-19-data/issues/396#issuecomment-659002096_

**Comment by sbulen** [comment]
Thanks...  Sorry missed that.  Should remember to look at closed issues for questions & examples...
