### ISSUE TITLE
Example: Google Colab Notebook

### ISSUE THREAD

**Issue by rchurt** [nytimes/covid-19-data#403]
### Describe the project
This Jupyter Notebook will import the dataset into a Pandas DataFrame so it can be manipulated in Python. This will let users get up-and-running using this data with just a couple clicks. It's also implemented in Google Colab, which allows users to run it on a virtual machine through their browsers, with no need to install any kernel or packages locally.

https://github.com/rchurt/rchurt.github.io/blob/master/covid_19_data.ipynb

**Comment by tiffehr** [comment]
Thank you!  Added to our Project board, which collects Examples for other data set users.
