### ISSUE TITLE
Data Issue:  South Carolina death data change in reporting

### ISSUE THREAD

**Issue by philipmnelson** [nytimes/covid-19-data#406]
### Describe the issue:
- [x] Incorrect number of cases or deaths

### Fuller details
So this is similar to an issue I filed previously (#240), but with more data involved and a change in the way SC reports deaths. DHEC [reported yesterday](https://www.scdhec.gov/news-releases/dhec-provides-new-data-individuals-dates-death-latest-covid-19-update-july-16-2020) 71 additional deaths that [occurred from June 26 - July 15](https://www.scdhec.gov/sites/default/files/media/document/COVID19-Deaths_by_date_of_death_and_county-7.16.2020.pdf). 
I don't know if the county level dataset could be updated to reflect the actual death dates. It wasn't last time, and I've had to manually account for this in my visualizations and the Times'. 

According  to DHEC's news release, they are going to start reporting deaths with dates of death when they are able to verify the dates of deaths, which to my understanding means that some of their previously reported numbers are completely meaningless. 

For example, on July 8, DHEC acknowledged that the reported number of deaths did not reflect the number of deaths from the previous day but they did not provide any sort of clarification of what counties or days these deaths occurred in/on. 
![Deaths on July 8](https://user-images.githubusercontent.com/12937257/87757471-b1519a80-c7d8-11ea-9077-89e1507d777f.png)

I just wanted to make everyone here aware of the change in reporting.

I know that when something like this is reported it usually isn't fixed because historical corrections are a little difficult but this definitely changes the way the deaths for SC appear. Hence why I'm reporting again.

 [Additonal deaths reported on July 16th with Dates and Counties PDF](https://github.com/nytimes/covid-19-data/files/4936168/COVID19-Deaths_by_date_of_death_and_county-7.16.2020.pdf)

**Comment by albertsun** [comment]
Hi @philipmnelson thanks for linking those specific documents. We'll look into it, but at first glance, it is unlikely we would make that change. This dataset across all states will record deaths based on when deaths are reported, not necessarily when they occur. The hope is that those are always the same day but we know that it very frequently is not.

**Comment by philipmnelson** [comment]
Alright. Thank you!

**Comment by philipmnelson** [comment]
Reopening so you all can find that data easily later.

**Comment by tiffehr** [comment]
We know where to find this.  Thank you again for the report.
