### ISSUE TITLE
Data Issue:  Erroneous death reported for California, Napa County (FIPS 06055) on 7/15/2020

### ISSUE THREAD

**Issue by gmillikan** [nytimes/covid-19-data#407]
Napa County Officials are telling me there was no fatality July 15 and the last COVID19 fatality was June 17, 2020.

California state dateset confirms 4 deaths (screenshot and link below) and not 5 deaths in the NYT dataset.

![image](https://user-images.githubusercontent.com/63218226/87795387-cf30f680-c7fc-11ea-86ab-a58c13db9767.png)

https://data.ca.gov/dataset/covid-19-cases

**Comment by albertsun** [comment]
Napa's official coronavirus report website here shows 5 deaths: https://legacy.livestories.com/s/v2/coronavirus-report-for-napa-county-ca/9065d62d-f5a6-445f-b2a9-b7cf30b846dd/

That's where our number comes from.
