### ISSUE TITLE
Data Issue:  us-counties/us-states updates for July 17 data?

### ISSUE THREAD

**Issue by ddenenberg71** [nytimes/covid-19-data#409]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [X] Missing time-series information
- [ ] Other

### Fuller details
Will updates be published today for July 17 data?  As of 3PM ET the non-live files haven't been updated yet.  The updates almost always happen by 2PM ET on weekends.  Thanks!

**Comment by david-c-hill** [comment]
I'm having the same issue. July 17 data would normally be available by now.
Thanks much!

**Comment by cfhp1** [comment]
Same here. A few days ago the bot posted at 7:20 p.m., and there was another update around 11:30 the next morning, I think, so I was letting this ride a bit, but there is still no update with all 7/17/20 data.

**Comment by bcunning** [comment]
Seconding this.

**Comment by cfhp1** [comment]
@albertsun  You knew the status last time this happened. Do you perhaps know what we should expect this time? Thanks!

**Comment by Pedro-McM** [comment]
Yes, also looking for data for 7/17/20.

**Comment by ssoloway** [comment]
Does this have something to do with the sidelining of the CDC's data collection?

**Comment by cfhp1** [comment]
@ssoloway No, it should not. Hospital data collection may be a greater challenge, but that is not included in this data set. The [Covid Tracking Project](https://covidtracking.com/) is a good place to seek that data. There are some closed issues about this impact.

**Comment by edsuom** [comment]
Same here, about to do a blog post on the COVID-19 situation and it's a bit frustrating to be waiting and hoping for the data to get updated to the post is as current as possible.

**Comment by albertsun** [comment]
Hi. Apologies all. This data is now updated.

Clearly we have some work to do still in our consistency so we’ll be taking a look at that this week.

Do note, the update has data for 7/18 already, but those counts are still incomplete and will be revised tomorrow with additional places that have not yet reported.

**Comment by cfhp1** [comment]
Very glad to have it. We appreciate that you compile this for us. I'm hopeful that you can solve the update frequency challenge in short order.

**Comment by edsuom** [comment]
Many thanks! I will be posting a link to this blog post ("Balancing Harms: Why our teenagers won't be on their high school campus this Fall.") in the right place here to show how one citizen is using this info to make an important parenting decision. The work you put into providing this data to the public every day is much appreciated.

**Comment by Pedro-McM** [comment]
Thanks, Albert.

 

No worries.  I can’t really complain very much, as the data is available for a very reasonable price!  Little glitches are bound to happen once in a while.  I’m sure more than a few of us were worried that this might have something to do with Donald Trump, but I assumed it was just that someone was out sick or on vacation and it fell through the cracks.

 

Pete

**Comment by bcunning** [comment]
Thank you Albert. I really appreciate all the work you do supporting this effort.
