### ISSUE TITLE
Update frequency?

### ISSUE THREAD

**Issue by mvanmidd** [nytimes/covid-19-data#41]
First of all, thanks for providing this data! The covid dataverse is getting kind of crowded, and I hope the various efforts will begin to consolidate their efforts and collaborate. That said, publishing is always better than not publishing. Unless maybe you bait and switch like JHU, constantly changing the format with little warning... but I digress.

What's the expected frequency and timing of updates to this dataset?

(This would be a good thing to include in an FAQ, per https://github.com/nytimes/covid-19-data/issues/38 )

**Comment by jasonlally** [comment]
I understand if you all want to push updates as needed. We are just automatically checking each 30 minutes for updates, but something that just clarifies the regularity or even irregularity of data updates would help others know how to interpret latest data.

Also, might be useful to have a column that just has the as_of_datetime or something like that so it's just row level data. Then you don't have to worry about things being irregular, it's just a datetime that gets appended to all rows before your push.

**Comment by nnagata** [comment]
Seconding what @jasonlally says. 

I think something similar to the ["States Current" tab](https://docs.google.com/spreadsheets/u/2/d/e/2PACX-1vRwAqp96T9sYYq2-i7Tj0pvTf6XVHjDSMIKBdZHXiCGGdNC0ypEU9NbngS8mxea55JuCFuua1MUeOj5/pubhtml#) in the spreadsheet maintained by the [COVID-19 Tracking Project](https://covidtracking.com/) world be great! 

Or collaborate with them? They also document how they try to handle differences between states and their health reporting systems.
