### ISSUE TITLE
Question:  

### ISSUE THREAD

**Issue by ssoloway** [nytimes/covid-19-data#410]
### Do you think there is an error in the data?
Please submit a Data Issue so it can be easily routed to the correct people.

### Do you have a question about the LICENSE or permission to use this data?
Please email us at covid-data@nytimes.com

### Your question
Please check to make sure your question is not answered in the README. It may have been updated since you first read it.

**Comment by ssoloway** [comment]
Is the count of cases different from the count of positive tests?  In other words, is there any attempt to weed out instances in which someone was diagnosed post-mortem without a test, someone was tested twice, etc?  (I suspect the difference would be small.)

**Comment by lwaananenjones** [comment]
This dataset includes diagnosed cases of Covid-19, with each case representing an individual person. That is reported consistently across all states and territories. There are some differences in how states report testing numbers, with some states reporting the total number of tests, which could include multiple tests for the same person. Testing numbers are not included in this dataset. 

If someone is diagnosed without a test based on symptoms and exposure to person who tested positive, this is considered a "probable" case according to the [Council of State and Territorial Epidemiologists definition](https://cdn.ymaws.com/www.cste.org/resource/resmgr/2020ps/Interim-20-ID-01_COVID-19.pdf) adopted by the CDC. Similarly, a coroner or medical examiner can list Covid-19 on a death certificate based on medical evidence even if the person wasn't tested, and this is considered a probable death. More than half the states report probable cases and/or probable deaths, and those are included in this dataset when available.

Occasionally we do see officials remove cases or deaths that are duplicates. We also routinely see deaths added weeks or months after the date of death as officials catch up and reconcile different records systems. We've also seen some states and counties go back and remove deaths from the official count if the death certificates indicate an unrelated cause of death, such as overdose. This [story about probable deaths](https://www.nytimes.com/interactive/2020/06/19/us/us-coronavirus-covid-death-toll.html) explains more about that record-matching process, and this [story about fax machines](https://www.nytimes.com/2020/07/13/upshot/coronavirus-response-fax-machines.html) explains why this process can take so long.
