### ISSUE TITLE
Logistic Growth Model with Multiple Growth Regimes and Weekly Periodicity

### ISSUE THREAD

**Issue by edsuom** [nytimes/covid-19-data#413]
### The Model

My “logistic growth with multiple growth regimes model” is a naive curve-fitting model that fits the past 11 weeks of U.S. reported cases to within 2% maximum error using just ten parameters:

- The number of reported cases of COVID-19 in the U.S. is following a logistic growth model with L (the ultimate upper limit) fixed at 1/4 of the U.S. population,

- but with three separate growth regimes (3 parameters) having smooth transitions between them (4 parameters),

- and with a sinusoidal component that imposes a weekly variation (2 parameters) on the current growth rate for each day,

- plus, finally, with a fixed number of new cases per day (1 parameter), to allow the model to only account for reported cases on or after May 1.

### Balance of Harms: Why our teenagers won’t be on their high school campus this fall.

[An essay](http://blog.edsuom.com/2020/07/balancing-harms.html) I posted on my blog July 19 with the then-latest curves produced by the model using the New York Times dataset.

**Comment by tiffehr** [comment]
Thank you!  Added to our collection of Examples, for work people have done with this data set.  Much obliged!
