### ISSUE TITLE
Data Issue:  Missing FIPS for three counties including NYC County

### ISSUE THREAD

**Issue by zgarsh** [nytimes/covid-19-data#414]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [x] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
In reviewing data from 7/22/2020, I find 29 counties which lack a FIPS code. The majority of these are "Unknown County, <State>", but the following named counties are included:
- Joplin County, Missouri
- Kansas City County, Missouri
- New York City County, New York

I'm new to using this kind of data but believe that New York City County's FIPS should be 36061 [source](https://data.ny.gov/Government-Finance/NY-Municipalities-and-County-FIPS-codes/79vr-2kdi)

Data for NYC County:
![image](https://user-images.githubusercontent.com/25714869/88369109-2aef0880-cd44-11ea-95db-83fcfc58ef99.png)

All counties missing FIPs:
![image](https://user-images.githubusercontent.com/25714869/88369137-3e9a6f00-cd44-11ea-94c5-49db01f81b77.png)

**Comment by albertsun** [comment]
HI @zgarsh,

Those three cases are described in the Geographic Exceptions section of the README. In each case they are a custom non-county geographic area. For example our New York City figures include the 5 counties that are the boroughs of New York City. FIPS code 36061 is the FIPS code for New York County which is only the borough of Manhattan.

Joplin and Kansas City are city areas that partially overlap other counties and do not have their own county-equivalent FIPS codes.

**Comment by zgarsh** [comment]
Apologies for missing that. Thanks!
