### ISSUE TITLE
Data Issue: Modoc County, California is missing

### ISSUE THREAD

**Issue by ityllux** [nytimes/covid-19-data#416]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [X] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
Data and a map outline are missing for Modoc County, CA in the Northeast corner of California.

**Comment by lwaananenjones** [comment]
Modoc County is not showing up on the map or in the dataset because the state and county report zero cases so far. If cases are reported, it will show up at that time.
