### ISSUE TITLE
Data Issue:  San Bernardino County, CA Case Count Error

### ISSUE THREAD

**Issue by kyleh195** [nytimes/covid-19-data#417]
The current case count for San Bernardino County is incorrect. As of 7/26 the file has cumulative cases at 29,265 but the published total from the county is 27,992. 

The source for the official case count is https://sbcovid19.com/

I believe the data diverged during the past 7 days, so one or more days of case increases was in late July may have been recorded incorrectly and the error has resulted in an overage in the cumulative total?

**Comment by albertsun** [comment]
Hi @kyleh195 in this instance the number we are reporting for San Bernardino comes from the state of California data, not the county provided data. The state dashboard is here https://public.tableau.com/views/COVID-19CasesDashboard_15931020425010/Cases?:embed=y&:showVizHome=no

Both the county and the state publish cumulative totals and each day the figure we include is the higher of those two.
