### ISSUE TITLE
Data Issue:  Texas deaths overstated by 10% starting 7/27

### ISSUE THREAD

**Issue by fbtoc** [nytimes/covid-19-data#419]
Per the Texas health website, due to changes in counting deaths, the cumulative death count showed a daily increase of 675 on 7/27/20.  The us_states.csv file showed a daily increase of 1202 for the same date.  JHU and Worldometer pretty much track the Texas health website.

**Comment by albertsun** [comment]
Hi @fbtoc, the reason our count is higher than the state of Texas here is because we use counts from counties that continue to report more deaths than the state. There is an explanation in a tweet thread here: https://twitter.com/albertsun/status/1288921345728876548
