### ISSUE TITLE
Data Issue:  Data for 7/30 and 7/29 for Contra Costra Counties / California seems off.

### ISSUE THREAD

**Issue by ATP015** [nytimes/covid-19-data#421]
### Describe the issue:
- [X] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
Data for 7/30 and 7/29 for Contra Costra Counties / California seems off.
Daily cases change is negative.

**Comment by lwaananenjones** [comment]
Several counties in California, including Contra Costa, reported a large increase in cases on July 29 and then revised the count down on July 30. The explanation we've received is that it was an error with the state's reporting system. We will revise our data if the county can provide the correct number of cases for 7/29, though this is not always possible. Contra Costa is today reporting some additional problems with the state data, so there may be other fluctuations until that's resolved.

> July 31, 2020 Note: We have been informed that the State is experiencing issues with electronic lab reporting of test results. As a result, the case and testing numbers may experience an increase once the issues have been resolved.
