### ISSUE TITLE
Question:  problems loading page without errors on Safari iPhone browser

### ISSUE THREAD

**Issue by shott** [nytimes/covid-19-data#422]
### Do you think there is an error in the data?
Please submit a Data Issue so it can be easily routed to the correct people.

### Do you have a question about the LICENSE or permission to use this data?
Please email us at covid-data@nytimes.com

### Your question
Please check to make sure your question is not answered in the README. It may have been updated since you first read it.

**Comment by tiffehr** [comment]
@shott Would you mind sharing the URL that you're talking about, please?

**Comment by shott** [comment]
Sorry. The specific error message and the URL is:

A problem repeatedly occurred on “https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html”.

Thanks for checking this out. 

John

**Comment by tiffehr** [comment]
Relayed to the folks who are focused on updates (and performance) for our pages.  Thanks for the report!

**Comment by charliesmart** [comment]
@shott Would you mind sharing which iPhone model you're using so we can better diagnose the issue? Thanks!

**Comment by shott** [comment]
This is an iPhone SE 2-3 years old running iOS 13.3.1. I have restarted it and cleared the Safari history and data cache … but that didn’t resolve the issue. 

Thanks so much,

John

**Comment by charliesmart** [comment]
Thanks, we're looking into it!

**Comment by shott** [comment]
Super!  Your team is fantastic!!! Something is wrong if you all don’t get a Pulitzer for this monumental, but so vital, effort!

**Comment by shott** [comment]
As of early evening (mountain time) on Monday, things seem to be loading again. I won’t close this case because I don’t know what may have been done to resolve this issue … but things seem to be working for me once again. 

Thank you all!!’

John

**Comment by shott** [comment]
While I don’t know what the issue was, it is fixed now. Thank you N.Y. Times!!!
