### ISSUE TITLE
Incorrect number of deaths for St. Croix County, WI, see: https://scccdd.maps.arcgis.com/apps/opsdashboard/index.html#/859b5b36d25e47ec8512e86356ca8ac2 

### ISSUE THREAD

**Issue by macthecat** [nytimes/covid-19-data#423]
### Describe the issue:
- [x] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources. Please check the README and recent commit messages for updates to see if your issue is addressed.

**Comment by lwaananenjones** [comment]
Thank you for pointing this out. Our data for St. Croix County is currently from the state and reflects the numbers reported on the [state website](https://www.dhs.wisconsin.gov/covid-19/county.htm). We use county data when it improves the dataset, prioritizing counties in states that report less reliably and then counties with large populations or outbreaks. We continue to add county data sources after verifying the county's definitions and reporting schedule, so we'll look into adding this.

**Comment by gmillikan** [comment]
Visualization of current St. Croix data here:

https://www.cvleaderboard.org/USA/wisconsin/st.-croix-county/
