### ISSUE TITLE
Question: Deaths in New York State

### ISSUE THREAD

**Issue by Pedro-McM** [nytimes/covid-19-data#426]
I read the write-up about the changes that were made with respect to the reporting of deaths in New York State, but there's one thing I don't understand.

As a result of today's changes to the handling of New York deaths, the total number of deaths in New York State decreased by 137 (from 32,431 reported for 8/5/20 to 32,294 reported for 8/6/20).

Were those deaths moved to a different state?

Or did that decline occur because NYT still needs to figure out in what county to assign those deaths?

Or some other reason?

Sincerely,
Peter McManus

**Comment by albertsun** [comment]
Hi, the first is right. Some deaths that were out of state residents are no longer being counted. It's possible that those were being double counted with another state but we don't have a breakdown of where they possibly overlapped with.

**Comment by Pedro-McM** [comment]
Thanks!  In other words, they were subtracted from New York State but they weren't added to other states.

**Comment by tiffehr** [comment]
They may have already been counted in other states. We have no way to know.

**Comment by Pedro-McM** [comment]
Perfect. I just wanted to confirm that they weren't specifically added to the other states.  I wrote a program for looking at the NYT data and the program has a way to hide big jumps like that.  I would handle it differently if you had moved those deaths to other states.
