### ISSUE TITLE
Data Issue:  August 10 updates for us-states/us-counties?

### ISSUE THREAD

**Issue by ddenenberg71** [nytimes/covid-19-data#428]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [X] Missing time-series information
- [ ] Other

### Fuller details
Hi, were August 10 updates for us-counties.csv and us-states.csv accidentally missed or just delayed?  No updates appear to have been committed for August 10 as of 7:20AM ET.  I realize there is no set time for the updates but lately they seem to occur around 1-3AM ET unless there is some significant reporting change.  Thanks!

**Comment by albertsun** [comment]
There should be an update within the next hour.

**Comment by ddenenberg71** [comment]
Got it.  Thanks.
