### ISSUE TITLE
Enhancement: Positivity rates for tests

### ISSUE THREAD

**Issue by cjhseq** [nytimes/covid-19-data#431]
Could you make available the source data for the positive test rates used in this opinion article - https://www.nytimes.com/interactive/2020/08/14/opinion/politics/covid-school-reopening-guidelines.html

Ideally it would be just an additional column matched with the "us-counties.csv" file that has the total test count you are using to calculate percent positive or just the percent positive if you are not calculating the value yourselves. Thanks so much, really appreciate all the data being made available via this resource.

**Comment by cfhp1** [comment]
I saw the source for county-level positivity test rates on that tool listed as state governments. If you happen to have compiled those from feeds, it would be truly excellent to have them in the same place. I realize this is unlikely as the data seems so hard to come by. If it were reasonably doable, presumably it would be provided by the Covid Tracking Project, which says it updates state level test data by hand. Even if we only have the one snapshot, I'm grateful that you provided it.

**Comment by cfhp1** [comment]
If anyone else is looking for these, I'm providing a [link to the list of websites used by the Covid Tracking Project](https://docs.google.com/spreadsheets/u/2/d/e/2PACX-1vRwAqp96T9sYYq2-i7Tj0pvTf6XVHjDSMIKBdZHXiCGGdNC0ypEU9NbngS8mxea55JuCFuua1MUeOj5/pubhtml#) to manually compile state level data.

**Comment by cjhseq** [comment]
Thanks @cfhp1 for the link. It would still be nice to know the actual numbers used by the Times for the opinion piece above as they seem slightly off for my home state (WA) as compared to county level data as well as the state-level aggregate used by the Covid Tracking project among others. Hard to know what could be driving the difference without knowing the exact data used for the opinion piece. Thanks again.

**Comment by monkeywithacupcake** [comment]
Times interactive graphics have # Tests by day for states and the US (not by county). Perhaps if the data that fill in those graphs could be added, people could calculate the positivity rate?

**Comment by tiffehr** [comment]
These sources are not ours to share, nor fold into our open data sources provided here.  As the graphics note:
>  Sources: Harvard Global Health Institute (case data, state-level positivity test rates); the Centers for Medicare and Medicaid Services (county-level positivity test rates)
