### ISSUE TITLE
Data Issue:  Arkansas Cases Count Drop by 400

### ISSUE THREAD

**Issue by BAR-B-Q** [nytimes/covid-19-data#432]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [X] Other

### Fuller details
Not sure what caused a 400 case count drop on the 8/15/2020 data for Arkansas.

**Comment by lwaananenjones** [comment]
We've asked the state about this and will hopefully get more information today. The decrease was almost entirely from the category of "unknown" cases that had not been assigned to a county, so it should not affect county numbers. One possibility we've seen before is the removal of nonresident cases after the state verifies addresses and transfers them to other locations.

**Comment by lwaananenjones** [comment]
Here's the response from the health department:

> Two important changes are reflected in the data update on Saturday. We have worked to validate our records, and have removed cases that were found to be out-of-state residents or duplicates. We have also corrected an issue that affected testing data from one private lab and added records that had been missing. This is why the cumulative numbers are lower.
