### ISSUE TITLE
Data Issue:  incorrect number of cases & deaths - several MA counties: Norfolk, Suffolk, Essex, Middlesex - totals have not changed in several days

### ISSUE THREAD

**Issue by Arcazares** [nytimes/covid-19-data#434]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources. Please check the README and recent commit messages for updates to see if your issue is addressed.

**Comment by Arcazares** [comment]
The total number cases and deaths in several Massachusetts counties including: Norfolk, Suffolk, Essex, Middlesex have not been updated in several days.  There have been cases and deaths in those counties in the last several days, however, the totals in the database remain unchanged.

**Comment by tiffehr** [comment]
Yes, Massachusetts has removed their daily county data.  But it continues to include it in a weekly report.  Our county data will now only update weekly, unless the state chooses to return to the daily reporting methodology.
