### ISSUE TITLE
Enhancement: Cases per million people

### ISSUE THREAD

**Issue by neelm00** [nytimes/covid-19-data#439]
A helpful column of data would be to find the total case count per million in each state to see get a better idea of how dense the case count is in varying states to understand more which states are struggling most regardless of the population of the state.

**Comment by tiffehr** [comment]
The challenge with adding per-capita calculations and keeping it up to date is WHICH population figures to use.  A number of past Issues and comments here in this repo have requested population-related figures against varying sources.  As this can be calculated fairly easily from the cumulative figures per locality, we have not included per-capita calculations here.

I recommend [seeing whether some of the additive data sets (like population) offered by other users](https://github.com/nytimes/covid-19-data/projects/1#column-9013481) may fit the bill.
