### ISSUE TITLE
Question:  Is it possible to include college/university data?

### ISSUE THREAD

**Issue by beckchel** [nytimes/covid-19-data#445]
Hello!

Would it be possible to include the data set used to build this article? 

https://www.nytimes.com/interactive/2020/us/covid-college-cases-tracker.html

Tracking college cases internally would be hugely helpful to my institution.

Thank you for the consideration!

**Comment by albertsun** [comment]
Hi @beckchel,

Basically all the data we have and are confident in is already on that page directly.

We're open to the idea of publishing it in some other format or way, but curious to hear more about specific use cases you or others would have for the data.

**Comment by beckchel** [comment]
Thanks for getting back to me! I work for Michigan State University, and
we're trying to compare ourselves to other similar universities in our own
internal dashboards. A CSV or other tabular format would be super helpful
(with citation of course!).

**Comment by tiffehr** [comment]
We do expose the data under the hood for that interactive page, if you want to grab a globally exposed JSON object and filter it to your specifications.  That implies scraping our page source, however.

![image](https://user-images.githubusercontent.com/60173/91501002-a89dbb00-e892-11ea-8541-68539938dcd4.png)

**Comment by beckchel** [comment]
Thank you! I'll send this to my data science counterparts.

**Comment by EllieLockhart** [comment]
I have pretty extensive academic experience and am proficient in scraping - if this is something consistent with the goals of the project, I would be happy to start looking into building some sort of data harvesting framework for universities.

**Comment by austinvhuang** [comment]
Seconding this request. It would be useful for modeling and researching local characteristics of outbreaks in conjunction with other data.

**Comment by jimfenton** [comment]
Also seconding this request. My daughter, a student at CU Boulder, would like to be able to compare her school to others on a per capita basis. Having the data here rather than scraping it would also facilitate analysis of growth rates.

**Comment by PatrickMartinK** [comment]
Bumping this request, I'm the director of a student-run think tank at Florida State University and this data would be absolutely crucial to our data analysis efforts. We're trying to compare FSU stats to our peer institutions and state university system, and using this database is the best way to do that. If anyone has figured out how to scrape it, or if a collaborator has compiled it into a CSV, I would greatly appreciate a response.

**Comment by tiffehr** [comment]
Yep, thank you, all.  We are very aware of the interest and we are working on it.  There are more challenges to the decision than you might imagine.  I'll update this thread once we have a decision either way.

**Comment by briancpark** [comment]
I am following this thread and also bumping this request. I'm a university student, and it would be beneficial to share well formatted datasets among peers and professors to bring upon more awareness. Some professors at my university have been giving relevant COVID-19 datasets for data science projects and assignments. I would be happy to pass this down to my university community if this dataset does become publicly available. I know trying to formulate a new time series dataset for a specific group is more work, but I really appreciate what NYTimes has been doing so far with other COVID-19 data such as mask usage and county specific US data.

**Comment by tiffehr** [comment]
Thank you.  No need to bump the thread.  We are very aware of the interest and inquiries, here on GitHub, via email, Tweets, reader comments, etc.

**Comment by lwaananenjones** [comment]
Hi everyone, raw data from the college tracker is now available with the most recent update: https://github.com/nytimes/covid-19-data/tree/master/colleges
