### ISSUE TITLE
Data Issue:  Racine County, WI data incorrect since August 27th

### ISSUE THREAD

**Issue by jbsaff** [nytimes/covid-19-data#446]
### Describe the issue:
- [X] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
Racine County, Wisconsin data is incorrect from August 27th on when compared with official reporting from WI DHS. 
https://data.dhsgis.wi.gov/datasets/covid-19-historical-data-table/data?orderBy=DATE&orderByAsc=false&where=GEO%20%3D%20%27County%27%20AND%20NAME%20%3D%20%27racine%27

On August 26th, data is listed as 3897 positive cases. On the 27th, this repository jumped to 4362 positive cases, but the DHS is reporting 3931. The data is still incorrect through August 30th.

**Comment by albertsun** [comment]
Hi @jbsaff,

The difference is we are including probable cases as reported by Racine County in their Covid-19 updates here: https://www.racinecounty.com/residents/covid-19-updates

Originally we had only recorded these cases starting August 27 but have now updated the data set with all reported probable and confirmed cases for Racine dating back to late April.
