### ISSUE TITLE
New York Death Count Drops 8-6

### ISSUE THREAD

**Issue by Oren-T** [nytimes/covid-19-data#448]
The New York data for August 6th seems to show a decrease of deaths by 102 as compared to the 5th. In particular, I noticed that Westchester county deaths from Aug 6th minus Aug 5th shows _-132_. I was wondering if you could provide insight into this drop?

**Comment by lwaananenjones** [comment]
This change on Aug. 6 reflects a methodology change on our part for the sake of greater consistency across geographies. [This note more fully explains](https://github.com/nytimes/covid-19-data/blob/master/NEW-YORK-DEATHS-METHODOLOGY.md) the reasons for that change, as well as the effects.

**Comment by Oren-T** [comment]
Thank you so much for the insight.
