### ISSUE TITLE
Data Issue: "cases" jumped unexpectedly for Orange County, CA (fips 06059) on 2020-09-06

### ISSUE THREAD

**Issue by mikelehen** [nytimes/covid-19-data#449]
### Describe the issue:
- [X] Incorrect number of cases or deaths
- [X] Suspicious number of cases or deaths

### Fuller details

Based on the us-counties.csv file, Orange County went from 49,509=>50,749 (+1,240 new cases) on 2020-09-06.  This is a much larger delta than normal (they were averaging ~150 cases/day) and is a higher cumulative case count than https://occovid19.ochealthinfo.com/coronavirus-in-oc or https://public.tableau.com/views/COVID-19CasesDashboard_15931020425010/Cases?:embed=y&:showVizHome=no reports for Orange County.  And [searching Google News](https://news.google.com/search?q=orange%20county%20covid&hl=en-US&gl=US&ceid=US%3Aen) I'm not able to find any confirmation or explanation for a large increase in cases in Orange County.

> $ csvcut -c 4,2,1,5 us-counties.csv | grep "^06059" | tail -3
> 06059,Orange,2020-09-05,49509
> **06059,Orange,2020-09-06,50749**
> 06059,Orange,2020-09-07,50864

Where is NYT pulling the cumulative cases from?  Can you double-check there hasn't been a mistake?

**Comment by lwaananenjones** [comment]
This is related to the addition of probable cases in Orange County. Last week, Orange County started reporting cases from positive antigen tests, which are considered probable cases based on updated guidance from the [Council of State and Territorial Epidemiologists](https://cdn.ymaws.com/www.cste.org/resource/resmgr/ps/positionstatement2020/Interim-20-ID-02_COVID-19.pdf). California state data only includes confirmed cases, which are based on PCR/molecular testing. On 9/3, the total number of confirmed cases in Orange County decreased after the removal of antigen cases incorrectly categorized as confirmed. This is the note the county shared at the time:

> NOTES: Today, Orange County's cumulative case count was reduced due to the exclusion of 496 COVID-19 antigen positive test results that were inadvertently counted as confirmed cases. CDPH only considers persons with PCR positive test results as confirmed cases. However, in order to better mitigate COVID-19 community spread, HCA is also tracking and conducting contact tracing on persons with antigen positive test results. To date, 822 Orange County residents with antigen positive test results have been identified. Antigen positive test counts will be tracked separately on the sidebar of the dashboard.

This dataset includes probable cases where possible, so we began including those cases on 9/6 after verifying that they are unique individuals (no overlap with confirmed cases). We're attempting to get revised numbers for last week to avoid the abrupt decrease and increase as the county adjusted its methodology, but if there is any uncertainty the numbers will continue to reflect what was announced each day.

**Comment by mikelehen** [comment]
@lwaananenjones This is very helpful.  Thank you!

**Comment by mikelehen** [comment]
Would it be possible to share:
1. What was the number of antigen tests that you newly included on 9/6?  (or feel free to point me to the data source and I can look it up)
2. When will you know if you can revise the numbers to avoid the abrupt decrease / increase?

We're trying to decide if/how to adjust things on https://covidactnow.org/us/ca/county/orange_county

Thanks!

**Comment by lwaananenjones** [comment]
The breakdown for 9/6 was 1,017 antigen probable cases + 49,732 confirmed cases = 50,749 total. This comes from the [county dashboard](https://ochca.maps.arcgis.com/apps/opsdashboard/index.html#/cc4859c8c522496b9f21c451de2fedae), the two cumulative numbers in the top left.

We will likely revise 9/3-9/5 by the end of this week, which would eliminate the decrease and move the increase a few days earlier. Before 9/3, the county did not publicly share the antigen case count, but we're seeing whether it's possible to obtain that for earlier dates.

**Comment by lwaananenjones** [comment]
The Los Angeles Times open data project is continuing to use the confirmed-only case count for Orange County at this point, so that may be useful for comparison or consistency: https://github.com/datadesk/california-coronavirus-data

**Comment by lwaananenjones** [comment]
This is now revised back to 9/3 include probable cases starting when the county first announced them.

**Comment by mikelehen** [comment]
I saw that.  Thank you!  I'll go ahead and close the issue.

**Comment by mikelehen** [comment]
Actually, one minor follow-up question.  Is there any way I could have found out about this reporting change without filing a github issue?

We would like to be able to immediately detect anomalies like this since it throws off our "new cases per day" calculation when a bunch of old cases appear overnight. 😁

**Comment by lwaananenjones** [comment]
That's a good question. This is probably the best way for now :) We've got a consistent system for annotating state-level methodology changes and anomalies on our state tracker pages, but that doesn't cover county-level changes like this one. It often takes us a couple of days to check with the county and make sure we're interpreting changes correctly, so that's another limitation –  we're typically reacting to unpredictable data source changes. It's our goal to be as transparent, so we'll consider what's possible. You may already have this, but it may be useful to build in a threshold that flags the "new cases per day" as potentially unreliable for users if it deviates substantially from the trend. These changes unfortunately still throw off the calculations even once we know the cause.

**Comment by albertsun** [comment]
Yea, opening an issue and asking is probably the best way.

For this specific change, or changes where the methodology change is the inclusion of probable cases for the first time, you can also see by looking at the change history of the files in the live/ folder. For instance, in this update https://github.com/nytimes/covid-19-data/commit/74932e8385139d38a83443c84bd2152b0aceac7b#diff-7144fff6223018e7309841f6ba31317cR216 you can see that Orange, California has a value for probable cases for the first time.
