### ISSUE TITLE
Add data provenance

### ISSUE THREAD

**Issue by 4d55397500** [nytimes/covid-19-data#45]
Seeing as how the csv files stored here are going into high-profile maps, medium blogs, twitter, etc., and then in fact affecting critical policy decisions can you try to add some provenance information: for a given case count in the CSV, where did the data come from? There will almost certainly be discrepancies and incorrect reporting; better to not take it upon yourselves as a newspaper to resolve them. Additionally, reporting the data source will make clear to the public holes in statistics given at the state and local level.

Keep up the good work!

**Comment by jeichstaedt** [comment]
seconded! And thanks NYT!

- Johannes Eichstaedt (faculty at stanford)

**Comment by albertsun** [comment]
Hi @4d55397500 thanks for your comment. As @jeichstaedt has said, we've tried to be as clear as possible about the provenance, but there are truly many, many sources. If the provenance of any individual data point becomes an important issue we are happy to dig in further.
