### ISSUE TITLE
Data Issue:  St. Louis-related data seem off

### ISSUE THREAD

**Issue by yagni** [nytimes/covid-19-data#452]
### Describe the issue:
- [x] Suspicious number of cases or deaths

### Fuller details
I'm subtracting case counts on adjacent days from covid-19-data to get new cases. For example, to get new cases on June 2, I compute (June 2 cases - June 1 cases). When I do that and compare both St. Louis city and St. Louis county official numbers with covid-19-data, they seem quite a bit different.

You can see the St. Louis county dashboard [here](https://data.stlouisco.com/app/st-louis-county-covid-19-cases-dashboard). The general shape of the graph is different and I spot checked a few points. For example, June 7 in covid-19-data lists 243 new cases, whereas the official dashboard has only 30 new cases. Also July 30 reports a spike of 530 while the official dashboard only shows 253. These are not small discrepancies.

Similarly, the St. Louis city dashboard [here](https://www.stlouis-mo.gov/covid-19/data/) has differences. In covid-19-data, May 3 shows 118 new cases while the official dashboard lists only 4. Then covid-19-data reports 0 new cases on May 4, while the official count shows 36 new cases. The highest covid-19-data spike is on July 30 (175 new cases), where the official dashboard shows a downward trend at that time (there the highest new case count is on July 8, at only 111). The covid-19-data chart is also missing some general trends found on the official dashboard.

Did you exclusively use St. Louis city and St. Louis county data for their respective case counts, or were other sources involved? Is this a difference between diagnosis date and reported date?

**Comment by albertsun** [comment]
Hi, these differences are due to how the date of a case is assigned. The totals in the database published here are based on the number of total cases as reported each day. The numbers on those dashboards are based on the date a case was diagnosed or a specimen was collected or some other date assigned after the fact. That means that the health departments are retroactively changing the counts for past days and that the number of "new cases" for the most recent days are incomplete.

See the notes as below:

> These data reflect cases entered into Missouri’s communicable disease surveillance database and are subject to change as we receive more current information. Data for the most recent days is incomplete; numbers will change as the database is updated.

> Case count totals shown in this graph represent specimen collection date, in other words, the day the individual was tested for COVID-19. There is a lag between when an individual is tested and when results are available, therefore the data is subject to change as new information becomes available. This also explains why recent dates do not have many (or any) cases listed, because cases that the DOH learns about are shown on the graph in previous days - when the person went for testing. Learn more.

**Comment by yagni** [comment]
Thank you. Does this also mean your data source will be influenced by backlog clearing? So e.g. if they added some cases today that were collected a week ago, they would show up in your chart as being counted today rather than a week ago?

**Comment by albertsun** [comment]
Yes, in general that is how all cases are recorded in this dataset. Nearly every newly reported case has some amount of lag time from when the specimen was collected.
