### ISSUE TITLE
Question:  Daily County Case Number in Massachusetts

### ISSUE THREAD

**Issue by zshe3** [nytimes/covid-19-data#454]
It seems that Massachusetts Department of Public Health does report daily county case number in their dashboard (https://www.mass.gov/info-details/archive-of-covid-19-cases-in-massachusetts#september-2020-).

However, in this anomaly notes (https://www.nytimes.com/interactive/2020/us/massachusetts-coronavirus-cases.html#anomaly-notes), it states that "As of Aug. 12, Massachusetts updates the number of cases and deaths by county once a week. The state previously updated these counts each day".

**Comment by lwaananenjones** [comment]
Thank you for pointing this out. Massachusetts announced Aug. 12 that cases and deaths by county would be updated only once a week, and fortunately that decision was reversed the following week. There is a gap in county updates from Aug. 12-17, and we'll update the note to reflect that.

**Comment by zshe3** [comment]
Thank you for the prompt response!
