### ISSUE TITLE
Data Issue:  Why is Harrisonburg, VA (a city) listed in "us-counties.csv"?

### ISSUE THREAD

**Issue by philipshirk** [nytimes/covid-19-data#455]
Harrisonburg, Va is a city in Rockingham County. Why is Harrisonburg listed in "us-counties.csv"? Presumably as a result of this, Harrisonburg shows up on the list of "Hot spots: Counties with the highest number of recent cases per resident" on https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html.

**Comment by ddenenberg71** [comment]
Virginia is unique in that it has several "independent cities" that are separate and distinct from counties.  They have their own FIPS codes.  Please see:  https://en.wikipedia.org/wiki/Independent_city_(United_States)

**Comment by ddenenberg71** [comment]
OK, technically not unique in that only 38 of the 41 independent cities in the US are in the Commonwealth of Virginia, but two (Baltimore, St. Louis) of the three  outside of Virginia are sufficiently large enough to escape notice.  In any case, what you are observing is accurate.  And here I will throw in a shameless plug for my site http://covid19va.net/ which aims to show day-by-day trends in cases/deaths/hospitalizations/testing on a locality-basis focusing on the localities and regions of Virginia.

**Comment by tiffehr** [comment]
Ah, thank you, @ddenenberg71. That's exactly it. NYT has historically grouped independent cities with counties for projects showing geographic distribution, like this data set.

**Comment by ddenenberg71** [comment]
Just FYI as another means of explanation, the Virginia independent cities are listed here as "county equivalents": https://en.wikipedia.org/wiki/List_of_United_States_counties_and_county_equivalents
