### ISSUE TITLE
Data Issue:  County "cumulative" totals decrease on subsequent days about 2% of the time.

### ISSUE THREAD

**Issue by mhfaust** [nytimes/covid-19-data#456]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [x] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
I've been parsing and transforming the data to get it ready for a visualization app I'm writing. I intend to store daily new infections, so I'm calculating those as one day's running total minus the previous day's, for each county. Using this approach, I obtain negative values for new infections 12,741 times (as of this evening). 

Example:

| date | county | state | fips | cases | deaths |
| ------ | ------ | ------ | ------ | ------ | ------ | 
| 2020-08-20 | Glascock | Georgia | 13125 | 32 | 1 |
| 2020-08-21 | Glascock | Georgia | 13125 | 31 | 1 | 

...so by my method of calculating daily new infections, I arrive at -1 for Glascock County, Georgia on August 21.

I am attaching a .csv log (renamed to .txt so github will accept it) of these "anomalies" with rows containing the date's count and the next date's count. 

[cumulationAnomalies.txt](https://github.com/nytimes/covid-19-data/files/5253650/cumulationAnomalies.txt)

How should we interpret this pattern?

**Comment by tiffehr** [comment]
Local health officials revise cases & deaths downward at their discretion.  We know of two routine patterns:
1. correcting cases that previously were thought to be covid-19 cases but later proven to not be so
1. correcting cases if they report by date of onset ([looks like parts of GA do this](https://twitter.com/GaDPH/status/1308142738580418560)), if that wasn't clear in the initial case/test data  
1. backdating cases that previously were all announced to the public on a single day (smoothing out a spike-like increase)

They can do this with or without a public announcement, depending on how they display their data.  In many cases, it is hard for us to catch backdating or revisions (or which case it may be).  Negative values between daily new infections are likely, even with our efforts to track the data to be as truthful as we can be.

Many localities post their daily new cases figures directly, even as a timeseries.  However, Glascock rolls up under the [East Central Health District](https://covid19.ecphd.com/), which only reports cumulative figures per county, so it's hard to see the fluctuation over time in their own site.
