### ISSUE TITLE
Data Issue:  Death count for Puerto Rico

### ISSUE THREAD

**Issue by robincrlee** [nytimes/covid-19-data#457]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [x] Suspicious number of cases or deaths
- [x] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
The cumulative death counts for Puerto Rico (for all counties) are 0 after the data get broken into counties level. 
If there aren't data available, it might be better to code those as unknown or missing data rather than 0. 
https://bioseguridad.maps.arcgis.com/apps/opsdashboard/index.html#/3bfb64c9a91944bc8c41edd8ff27e6df

**Comment by tiffehr** [comment]
Puerto Rico has not provide deaths for municipalities/counties at any point in our data collection, starting mid-March 2020. Without a local health department breakdown, we have no reliable method to allocate deaths among the counties.  

For other states or territories, we show cases and deaths at the county level where we can, or empty entries otherwise. I would encourage you to check your own usage.  In our CSV, the deaths columns are blank not zero.
![image](https://user-images.githubusercontent.com/60173/93845543-350f8380-fc6f-11ea-9e66-6cb6a18b82aa.png)

**Comment by mbauman** [comment]
There are literal zeros for the Puerto Rican municipios in the [us-counties](https://github.com/nytimes/covid-19-data/blob/2843249e6d3842f03c41ed684f7a8002d2f00247/us-counties.csv) CSV.  Is that intended?  E.g.,

```csv
2020-11-26,Villalba,Puerto Rico,72149,473,0
2020-11-26,Yabucoa,Puerto Rico,72151,565,0
2020-11-26,Yauco,Puerto Rico,72153,728,0
```

**Comment by tiffehr** [comment]
@mbauman Are you pointing to the specific dates is question?  Or the persistence of zeros for where we do not have data from the source?

**Comment by mbauman** [comment]
There are zeros in the main us-counties CSV file for all dates since May 9.  Given your prior comment I expected them to be missing — but that seems to only be the case in the `live` dataset.

**Comment by tiffehr** [comment]
Please check the file again and confirm you no longer see zeros in `us-counties`?

**Comment by ddenenberg71** [comment]
I think the bigger confusion here is that the death counts (in **uscounties**) appear to completely disappear for Puerto Rico on May 9.  On May 8, "Unknown" shows 107 deaths.  On May 9, "Unknown" has 0 (now null/blank) and it remains zero/blank.  Net effect is that cumulative Puerto Rico deaths go from 107 to 0 on May 9 and stay at zero forever.   Wouldn't it be more clear to keep accumulating the deaths in Unknown?

**Comment by mbauman** [comment]
> Please check the file again and confirm you no longer see zeros in us-counties?

Confirmed, thank you!

> Wouldn't it be more clear to keep accumulating the deaths in Unknown?

This would be great!

**Comment by tiffehr** [comment]
Puerto Rico has not provided deaths for subgeographies since early in the pandemic. They removed the data set early on, before May if I recall correctly.  We manually kept an early figure as the Unknown county until we confirmed their reporting methodology. We removed all subgeography deaths from our records for Puerto Rico once that became clear.

**Comment by ddenenberg71** [comment]
There is general expectation that the county rows tally to the state row for a given state/territory.  This does not occur for Puerto Rico.  If there is some justification for deviating from this for Puerto Rico, then we'll keep coding around it.   But based on my 8 months of working with these data sets (thank you) this does seem like a big deviation from the way "Unknown" has been used before, especially in the first few months of the pandemic when we knew that "Unknown" counts could fluctuate (based on efforts to retroactively attribute to counties) but would always reasonably tally with the known county counts to the state.  Thanks.

**Comment by ddenenberg71** [comment]
us-counties rows:

> ...
2020-04-30,Unknown,Puerto Rico,,1537,92
2020-05-01,Unknown,Puerto Rico,,1573,94
2020-05-02,Unknown,Puerto Rico,,1755,95
2020-05-03,Unknown,Puerto Rico,,1806,97
2020-05-04,Unknown,Puerto Rico,,1875,97
2020-05-05,Unknown,Puerto Rico,,133,99
2020-05-06,Unknown,Puerto Rico,,140,99
2020-05-07,Unknown,Puerto Rico,,140,102
2020-05-08,Unknown,Puerto Rico,,153,107
2020-05-09,Unknown,Puerto Rico,,153,
2020-05-10,Unknown,Puerto Rico,,127,
2020-05-11,Unknown,Puerto Rico,,131,
2020-05-12,Unknown,Puerto Rico,,134,
2020-05-13,Unknown,Puerto Rico,,137,
2020-05-14,Unknown,Puerto Rico,,147,
2020-05-15,Unknown,Puerto Rico,,157,
2020-05-16,Unknown,Puerto Rico,,156,
...

us-states rows:

> ...
2020-04-30,Puerto Rico,72,1537,92
2020-05-01,Puerto Rico,72,1573,94
2020-05-02,Puerto Rico,72,1755,95
2020-05-03,Puerto Rico,72,1806,97
2020-05-04,Puerto Rico,72,1875,97
2020-05-05,Puerto Rico,72,1924,99
2020-05-06,Puerto Rico,72,1968,99
2020-05-07,Puerto Rico,72,2031,102
2020-05-08,Puerto Rico,72,2156,107
2020-05-09,Puerto Rico,72,2173,108
2020-05-10,Puerto Rico,72,2198,111
2020-05-11,Puerto Rico,72,2256,113
2020-05-12,Puerto Rico,72,2299,114
2020-05-13,Puerto Rico,72,2329,115
2020-05-14,Puerto Rico,72,2427,117
2020-05-15,Puerto Rico,72,2542,122
2020-05-16,Puerto Rico,72,2589,122
...

**Comment by albertsun** [comment]
Puerto Rico's data is different than other places in a bunch of ways, but we'll look into this.

However, as general guidance we would really recommend that if you want a state or territory level count for a figure that you use the us-states.csv file rather than summing the us-counties.csv file. Yes, it generally should sum up to the state count, but that is not going to be as reliable. Our manual data checking processes are focused on making sure the top-line numbers for each state are as accurate as possible, and the way the Unknown row is handled can definitely be a little inconsistent.

**Comment by ddenenberg71** [comment]
@albertsun Thanks.  Yes, agreed for any pure state-level use/presentation we should use the states file, but hopefully you can see why this different interpretation of "Unknown" for Puerto Rico is a problem for any usage of the counties file.  I believe I speak for most when I say we interpret the "Unknown" counts as "_not yet attributed to any county or county-equivalent_" which seems to be exactly the situation for Puerto Rico.  I realize there is a more nuanced definition in the README.  But based on the explanation here, it sounds like the only consistent approach to arrive at the unattributed counts would be to just completely disregard the Unknown rows and calculate the unattributed by subtracting the sum of the true county-level counts from the state counts.

**Comment by tiffehr** [comment]
I would be cautious about calling anything in this data set an expectation. The README's history underscores that. We do not have a requirement on our end for our own graphics that summing Unknown + all other counties must match their parent geography total.  Subtracting would be the most reliable mechanism if you absolutely need them to match, particularly working from the counts in us-states.csv. 

We'll consider PR's Unknown county history.  But even if we do add the value that does not set the expectation that math will be reliable.

**Comment by albertsun** [comment]
The files are now updated and the Unknown row for Puerto Rico has death counts matching the territory total.

I would still reinforce Tiff's comment about over interpreting the data for the Unknown row. The data is messy and that particular data point for each place is the messiest.
