### ISSUE TITLE
8/22 14,000 incremental cases for Harris County, TX over 8/21! 123,817 to 137,946... Typo or real?

### ISSUE THREAD

**Issue by peterdaytx** [nytimes/covid-19-data#458]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources. Please check the README and recent commit messages for updates to see if your issue is addressed.

**Comment by albertsun** [comment]
Hi,

This is not a typo in the dataset here. Yesterday, Harris County, and Texas more generally, released a large backlog of old cases that bumped up their total number of cases.

Only a small number of those are ones they call "recent" (within last 14 days), see here: https://twitter.com/hcphtx/status/1308223067714445313
