### ISSUE TITLE
Data Issue:  Delayed case reporting in Aiken and Edgefield county of South Carolina

### ISSUE THREAD

**Issue by zshe3** [nytimes/covid-19-data#459]
The recent jump in cumulative case number in Aiken and Edgefield county of South Carolina seem to be caused by the delayed reporting of case number back to March by AU Health System. (See https://www.augustachronicle.com/news/20200922/south-carolina-dhec-au-health-delay-in-reporting-15000-test-results-in-covid-19-cases-spike-in-aiken-and-edgefield)

Can you confirm that? 

Thanks!

**Comment by lwaananenjones** [comment]
Yes, that's correct from what we know. The [state press release](https://scdhec.gov/news-releases/dhec-updates-numbers-delayed-results-out-state-lab-latest-covid-19-update-september) did not name counties, but that is where we saw the most significant effect.
