### ISSUE TITLE
Data Issue:  Joplin County, MO, and Kansas City, MO are lacking FIPS codes. 

### ISSUE THREAD

**Issue by svadivazhagu** [nytimes/covid-19-data#460]
### Describe the issue:
The FIPS codes in the /master/live/us-counties.csv for Joplin County, MO, and Kansas City, MO are missing. Upon research, they don't have an assigned FIPS code, but are cities that are made up of other counties which are present in the dataset. Therefore, these 2 are repetitive and should be removed.

**Comment by albertsun** [comment]
Hi @svadivazhagu please take a look at the README, these are specifically called out as areas that report data separately from the counties overlapping them.

**Comment by svadivazhagu** [comment]
Thanks Albert!
