### ISSUE TITLE
Question:  is there any change for data updating schedule?

### ISSUE THREAD

**Issue by guzhiling** [nytimes/covid-19-data#461]
Hi,

I noticed the us-counties.csv, us-states.csv, and us.csv have not been updated. Are they still under review, or is there any change for the data updating schedule?

Thank you!!

**Comment by david-c-hill** [comment]
I'm waiting for county data as well...
Thank you nyt!

**Comment by cfhp1** [comment]
Bated breath here too! We appreciate the service you provide!

**Comment by cfhp1** [comment]
@albertsun , tagging you since you've had info before when something went awry with the updates in case you may know what's up this time. Thanks.

**Comment by chem-geek** [comment]
Yep. Unusual for the update to be this late...hoping to update my daily data and projections...

**Comment by Pedro-McM** [comment]
Just want to add my name to the list of people waiting for the data.

Thanks, NYT, for providing the Covid data.

**Comment by cfhp1** [comment]
NYT, my data science intern is speculating that the government has shut you down for the tax expose. He needs to know if the revolution has begun, please. ;)

**Comment by albertsun** [comment]
Hi folks, apologies, our auto-updating process has started to have some problems as the data has gotten larger. We're going to update it now.

**Comment by cfhp1** [comment]
@albertsun Thank you!

**Comment by guzhiling** [comment]
> Hi folks, apologies, our auto-updating process has started to have some problems as the data has gotten larger. We're going to update it now.

Thank you so much!

**Comment by albertsun** [comment]
Data is now updated and we'll keep a closer eye on it.

Thanks for flagging this everybody.
