### ISSUE TITLE
Data Issue:  For state-wise data, there is an issue with Massachusetts data

### ISSUE THREAD

**Issue by kmair** [nytimes/covid-19-data#462]
### Incorrect number of cases:
The daily cases decrease for the state of Massachusetts after Sep 1st as:

2020-09-01    128888
2020-09-02    121131
2020-09-03    121546
2020-09-04    121758
2020-09-05    122196
. . . .
2020-09-20    127540
2020-09-21    127796
2020-09-22    127969
2020-09-23    128512

**Comment by khorton** [comment]
How does this issue differ from [Issue #447](https://github.com/nytimes/covid-19-data/issues/447)?

**Comment by albertsun** [comment]
Yes this is in fact the same issue as described there. See the explanation here: https://github.com/nytimes/covid-19-data/issues/447#issuecomment-687164349
