### ISSUE TITLE
Data Issue:  North Carolina case jump on 9/25

### ISSUE THREAD

**Issue by zshe3** [nytimes/covid-19-data#463]
NC had a more than 6,000 case jump on 9/25. The state’s Department of Health and Human Services said that it was due to "including the results of antigen tests that backdate to May 20. "

https://www.newsobserver.com/news/coronavirus/article246028760.html

**Comment by david-c-hill** [comment]
I saw that jump  as well in UNCC's 14 county region explorer:
https://dchill.shinyapps.io/ui_region_covid-19_app/

**Comment by lwaananenjones** [comment]
Yes, that's the reason for the North Carolina increase on 9/25. In its [FAQ press release about this change](https://files.nc.gov/covid/documents/dashboard/Antigen-Testing-Frequently-Asked-Questions.pdf), the state included a breakdown of how many cases and deaths are the result of including cases identified through antigen testing.

**Comment by zshe3** [comment]
Thanks!
