### ISSUE TITLE
Data Issue:  Alabama case jump on 9/25

### ISSUE THREAD

**Issue by zshe3** [nytimes/covid-19-data#464]
"Alabama sees 1,600+ jump in probable COVID cases due to older data"

https://www.al.com/news/2020/09/alabama-sees-1600-jump-in-probable-covid-cases-due-to-older-data-798-new-confirmed-cases.html

**Comment by albertsun** [comment]
Thanks @zshe3 we've noted this on our Alabama page https://www.nytimes.com/interactive/2020/us/alabama-coronavirus-cases.html#anomaly-notes as an anomalous reporting day.
