### ISSUE TITLE
Data Issue:  non-live us-counties/us-states not updated

### ISSUE THREAD

**Issue by ddenenberg71** [nytimes/covid-19-data#465]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [X] Missing time-series information
- [ ] Other

### Fuller details
Are the non-live us-counties/us-states updates stuck again?  The files haven't been updated in ~30 hours.  Thanks!

**Comment by albertsun** [comment]
Those files should be updated within the next half hour or so.

**Comment by ddenenberg71** [comment]
Files have been updated.  Thanks.
