### ISSUE TITLE
Data Issue: Instances where sum of county cases doesn't equal state cases

### ISSUE THREAD

**Issue by mkfreeman** [nytimes/covid-19-data#469]
### Describe the issue:
- [x] Incorrect number of cases or deaths
I believe there are 207 observations (each representing a state on a given date) where the sum of the cases from the [county level data](https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv) does not equal the number of cases from the [state level data](https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv) (mostly in the Virgin Islands). 

### Fuller details
I've attached a .csv file containing these observations, and posted the R code below I used to generate them. At most, the difference is 263 cases. 

```r
# Inconsistent totals between counties and state

# Load the tidyverse package for data manipulation
library(tidyverse)

# Load the *state level* data 
states <- read.csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv")

# Load the *county level* data 
counties <- read.csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv")

# Aggregate the county data by state and date
aggregated_county_data <- counties %>% 
  group_by(state, date) %>% 
  summarize(sum_county_cases = sum(cases))

# Join this onto the state data to show the discrepancy 
# (only keep where inconsistent)
combined_data <- states %>% 
  left_join(aggregated_county_data, by=c("state", "date")) %>% 
  mutate(diff = sum_county_cases - cases) %>% 
  filter(diff != 0) %>% 
  select(state, date, sum_county_cases, cases, diff)

# Write it out to a csv file
write.csv(combined_data, "inconsistent_totals.csv", row.names = F)
```
[inconsistent_totals.xlsx](https://github.com/nytimes/covid-19-data/files/5337833/inconsistent_totals.xlsx)

**Comment by tiffehr** [comment]
We take county data vs. state based on 
1. clarity of reporting methodology
2. speed of reporting
3. We don't county tallies exactly equal state totals -- they are often two separate reporting entities (local health dept. vs. state health reps).  

They may provide their tallies by different methodology as well, based on size and staffing.  We choose which is fastest and clearest, in terms of reporting cases and deaths.  We do not enforce these total up under states in any tidy manner.  The Virgin Islands, in specific, are a good example of the differences between subregion and state totals, not necessarily the only exception.  Many of the U.S. territories choose to break out cases as they see fit for their populations, not based on sums.

**Comment by mkfreeman** [comment]
Thanks for letting me know!
