### ISSUE TITLE
Data Issue: Kansas City, MO

### ISSUE THREAD

**Issue by chris-prener** [nytimes/covid-19-data#470]
The current number of cases in the NYTimes data for Kansas City, MO is 11,387. Both the [State of MO](https://showmestrong.mo.gov/public-health-county/) and [the City itself](https://covid-19-response-in-kcmo-kcmo.hub.arcgis.com) are reporting more than 12,000 cases. The NYTimes data for Kansas City also hasn't been updated, it seems, since 2020-09-29. Thanks for looking into this!

**Comment by albertsun** [comment]
It seems the city dashboard is only updating once a week now. In our latest data, for yesterday, we are publishing 12,116 cases for Kansas City based on the city dashboard. We're going to look further into the difference between city and state numbers and whether we can have a more up to date number.

**Comment by chris-prener** [comment]
Thanks @albertsun - I just realized that now - the state numbers are being updated on a more regular basis, I believe.

**Comment by lwaananenjones** [comment]
As of 10/8, the numbers in our data for Kansas City, Jefferson County and Platte County are from the state. We decided this was the best option for daily updates without the risk of double-counting across jurisdictions. The total number of cases in the Kansas City area remained the same, but this means there are some one-time adjustments for the county/city numbers.
