### ISSUE TITLE
Question:  Is it possible to publish historic college COVID data?

### ISSUE THREAD

**Issue by m-s-j** [nytimes/covid-19-data#473]
Would it be possible to publish a CSV with past college COVID data from the past few months? This would be extremely helpful because it would allow for studying trends in the data over time.

Thanks

**Comment by albertsun** [comment]
Hi @m-s-j, at this point we're not publishing historical data for this. It's simply changed too much and been revised too many times for the historical record to be reliable. Going forward it may be possible to construct a sparse historic data set from the file we have published.

**Comment by andrewjohnston99** [comment]
I am using the data for a project at school right now. It is displayed online [here](https://www.nytimes.com/interactive/2020/us/covid-college-cases-tracker.html) and can be manually found in the past [here](https://web.archive.org/web/*/https://www.nytimes.com/interactive/2020/us/covid-college-cases-tracker.html).
