### ISSUE TITLE
New York City Zip Code Data

### ISSUE THREAD

**Issue by architverma1** [nytimes/covid-19-data#474]
I was wondering if the New York City cases by zip code raw data (cases per zip code per day) was available? I can't find a such a file from the NYC DOH github either, so alternatively is there some processing you're doing on their data? Thanks!

**Comment by avias1459** [comment]
I am also interested in this data.  We need it to help understand progress in the red zones.

**Comment by albertsun** [comment]
The New York City zip code level data is available directly from the NYC Health department Github repo here: https://github.com/nychealth/coronavirus-data

They have a file data-by-modzcta.csv. As it's a git repo you can traverse the history of the file for historical counts.

We are not planning to republish that data here.
