### ISSUE TITLE
Enhancement: Prison/Jail Case Counts

### ISSUE THREAD

**Issue by geoffreylarnold** [nytimes/covid-19-data#475]
On the [main story](https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html) the NYT has a list of prisons and their number of cases. Including this as part of the dataset with a column on most recently update dated would be very helpful, if possible estimated population of the prison/jail would make this even better.

**Comment by tiffehr** [comment]
We have no plans to break out penal system cases from regular cases.  We would refer you to [The Marshall Project for that data](https://www.themarshallproject.org/2020/05/01/a-state-by-state-look-at-coronavirus-in-prisons) and their methodology.
