### ISSUE TITLE
Data Issue:  data not loaded for 10/18 as 830 EST; usually updated by 2am EST.  

### ISSUE THREAD

**Issue by neodavid04** [nytimes/covid-19-data#476]
- [x] Missing data for 10/18/2020

No data for 10/18 yet (https://github.com/nytimes/covid-19-data/blob/master/us-counties.csv).  Hoping it gets updated soon.  Please let us know.  Thanks!

**Comment by albertsun** [comment]
An update should be coming within the next hour or so.

**Comment by neodavid04** [comment]
Thanks!
