### ISSUE TITLE
Data Issue:  us-counties data for Orleans County Vermont is now all zeroes

### ISSUE THREAD

**Issue by cpsource** [nytimes/covid-19-data#478]
### Describe the issue:
- [x] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources. Please check the README and recent commit messages for updates to see if your issue is addressed.

**Comment by albertsun** [comment]
@cpsource I see Orleans county Vermont with 27 cases on Oct 22 in the us-counties.csv data file. Where are you seeing zeroes?

**Comment by tiffehr** [comment]
@cpsource Do you have further details about what you are seeing?
