### ISSUE TITLE
Data Issue:  Date on college data not updated on last commit

### ISSUE THREAD

**Issue by andrewjohnston99** [nytimes/covid-19-data#479]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [x] Missing time-series information
- [x] Other

### Fuller details
For the college case data, the last commit (e9946d3ebbe298d90e7b69f98ff78b27c4270a7e) updated the case values but not the date values. Latest date for values on [webpage of data](https://www.nytimes.com/interactive/2020/us/covid-college-cases-tracker.html) states 10/22, date in repo still says 10/8 but was updated with latest case numbers.

**Comment by albertsun** [comment]
🤦 you're right. Thanks for pointing that out, we'll get it fixed.
