### ISSUE TITLE
Data Issue: San Diego Deaths are wrong for Oct 16 & 17

### ISSUE THREAD

**Issue by pruggia** [nytimes/covid-19-data#480]
### Describe the issue:
- [x] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
us-counties file show the following entries for San Diego
2020-10-15,San Diego,California,06073,51533,847
2020-10-16,San Diego,California,06073,51844,865
2020-10-17,San Diego,California,06073,52045,869
2020-10-18,San Diego,California,06073,52418,853

Notice how there is a jump in deaths for Oct 16 and 17 only for that to come back down later.

The following site shows those counts to actually be 853 for both 10-16 and 10-17: https://www.arcgis.com/apps/opsdashboard/index.html#/96feda77f12f46638b984fcb1d17bd24

I think the wrong 865 and 869 numbers may have come from the reported ICU numbers instead?

**Comment by albertsun** [comment]
Thanks, it does look like the wrong number was picked up for two days there. We'll publish a revision to reset the numbers to what the California DPH was publishing at that time for those two days — 847 and 850 deaths.

**Comment by tiffehr** [comment]
@pruggia Confirm you seen the correction?

**Comment by pruggia** [comment]
Yes, I see the correct numbers now, thanks!
