### ISSUE TITLE
Data Issue: Jump in GA cases 2020-10-05  

### ISSUE THREAD

**Issue by bjb100** [nytimes/covid-19-data#481]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [x ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details

There is an unreasonable one-day jump in cases in GA (reflected also in at least some GA county data) on 2020-10-05. This jump is new -- it appeared in the data posted on10/25/20 but was not present in previously posted data.

If this is real, can you offer an explanation?

Thank you for maintaining this data base!

**Comment by zshe3** [comment]
In this webpage (https://www.nytimes.com/interactive/2020/us/georgia-coronavirus-cases.html#anomaly-notes), NY Times said that "Oct. 5: Georgia began including probable cases identified through antigen testing. The number of probable cases is updated once a week on Mondays".

However, I would also like to NY Times only updated this change in the data posted on 10/25/20, which means that it changed some historical data before 10/25 and after 10/05.

**Comment by lwaananenjones** [comment]
Yes, this is correct. On Oct. 5, the Georgia Department of Health began including probable cases identified through antigen testing in [weekly reports](https://dph.georgia.gov/county-indicator-reports) linked from the state's main dashboard. It took us some time to confirm the report definitions and consistent weekly format, so those probable cases were added Oct. 24 with retroactive revisions back to Oct. 5, when the state data was first available.

**Comment by bjb100** [comment]
Thanks very much for the explanation.
