### ISSUE TITLE
What's the source of Utah County cases?

### ISSUE THREAD

**Issue by GiorgiLomaia** [nytimes/covid-19-data#485]
I know Utah doesn't report data at county level and wanted to see what source NYTimes is using to continue reporting at county level in Utah. Thank you

**Comment by tiffehr** [comment]
Utah does provide county data, including breakdowns even for regional roll-ups like the Tricounty area:  https://coronavirus-dashboard.utah.gov.
![image](https://user-images.githubusercontent.com/60173/97658107-1d2adc80-1a31-11eb-98c5-57840a278c29.png)
![image](https://user-images.githubusercontent.com/60173/97658268-87438180-1a31-11eb-8921-ec967d0bebb2.png)

We extract county figures from their client-side/javascript data layer for that URL.  They display the 14-day rate and case count, but to do that math they include actual case counts in the underlying data.  

However, we don't solely use that source for Utah's counties.  We also collect figures from the individual health-district sites, e.g. https://tricountyhealth.com/local-covid-update/.  In our public data set, you see our best source for each county with the state's figures as the backbone.
