### ISSUE TITLE
Data Issue: Random jumps in data for Georgia Counties

### ISSUE THREAD

**Issue by perinita** [nytimes/covid-19-data#486]
### Describe the issue:
- [X] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
Many Georgia counties have a jump in cases on Oct. 5/6. The jump is greatly disproportional to any reasonable number of reports, so this appears to be pure error in some form. Counties include Fulton, Gwinnett, and many more.
![image](https://user-images.githubusercontent.com/32721163/97759531-9aa92800-1ad7-11eb-8c60-5c34aa181e83.png)
![image](https://user-images.githubusercontent.com/32721163/97759553-a3016300-1ad7-11eb-969d-fb5f65562918.png)

**Comment by khorton** [comment]
See issue [#481](https://github.com/nytimes/covid-19-data/issues/481) for the explanation of this jump.

**Comment by tiffehr** [comment]
Yep, confirming that's the correct explanation.

@lwaananenjones [wrote](https://github.com/nytimes/covid-19-data/issues/481#issuecomment-716271889):
> Yes, this is correct. On Oct. 5, the Georgia Department of Health began including probable cases identified through antigen testing in [weekly reports](https://dph.georgia.gov/county-indicator-reports) linked from the state's main dashboard. It took us some time to confirm the report definitions and consistent weekly format, so those probable cases were added Oct. 24 with retroactive revisions back to Oct. 5, when the state data was first available.

**Comment by perinita** [comment]
﻿Thank you!!
