### ISSUE TITLE
Data Issue:  Harris County, Tx shows zero incremental cases from 10/29 to 10/30, county site shows 629. (161,613 total).  Don' know if this propagates to Texas & US totals?

### ISSUE THREAD

**Issue by MirrorCola** [nytimes/covid-19-data#487]
### Describe the issue:
- [x] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources. Please check the README and recent commit messages for updates to see if your issue is addressed.

**Comment by lwaananenjones** [comment]
Thank you for flagging this. We found the problem and revised Harris County for 10/30, so that will show up here in the next data update. It does result in an increase for the Texas and U.S. totals as well.
