### ISSUE TITLE
Question:  My calculated daily counts seemed to take an unusual jump. When I compared the state totals to another site, some states, AR, IL, IS, MD, MI, NE, took an unusual very high variance. Is a correction pending? Will it be announced?

### ISSUE THREAD

**Issue by bobket45** [nytimes/covid-19-data#489]
### Do you think there is an error in the data?
Please submit a Data Issue so it can be easily routed to the correct people.

### Do you have a question about the LICENSE or permission to use this data?
Please email us at covid-data@nytimes.com

### Your question
Please check to make sure your question is not answered in the README. It may have been updated since you first read it.

**Comment by tiffehr** [comment]
Could you provide the numbers you see for those states, as well as your contrasting data source?  Without that, we don't understand what you're seeing.

**Comment by bobket45** [comment]
Question #489

Your Git Hub data by was compared to
www.worldometers.info/coronavirus/country/us/ and most states totals nearly
or exactly matched but AR, IL, IA, MD, MI and NE were high by quite a bit
the total difference was +9590. If not that most closely matched and just a
small number were too high by hundreds, I would have thought I was working
with the wrong day. Of course, I understand that the NY Times GitHub
project is at the mercy of those that are reporting. My source was the NY
Times GitHum project data by county. I converted to EXCEL and ran af few
formulas to calculate the daily cases, deaths, 5 day average and the sum of
active cases over 15 days.I then copied 11/01 data to a new sheet to a
pivot data where I captures the state totals. Although somewhat bulky, I
could send the entire sheet if needed.


Regards,
Bob Ketterer
bob@BOBKET.NET <http://bobket.net/> LLC

**Comment by tiffehr** [comment]
I have never heard of worldometers.info, but reading their somewhat thin data-collection methodology, I have more open questions than answers.  They lack detail about how they interpret different descriptions of cases.  They reference their "Latest News" subsection for most recent sources for U.S. data, but it is quite a mix and the applied definition or coercion is unclear.

[Our README published here](https://github.com/nytimes/covid-19-data/blob/master/README.md#methodology-and-definitions) has a lot of information about our domestic sources, as well as the definitions of how we interpret case rates into normalized figures.  I would guess that is the difference you see, specifically in the area of _probable_ case definitions.  It is unlikely that two sources would sum to the exact same figures, _due_ to these definition interpretations.

**Comment by bobket45** [comment]
Tiff,

My issue appears to be unclear. As I indicated I used your raw county data
and summarized by state. I later used your state data and found substantial
differences for the listed states.

It may be a data corruption problem so I'll reload the data and charge the
states in question.

Thanks for your consideration. I'll reply when I have a clearer picture.

Regards,
Bob Ketterer
bob@BOBKET.NET <http://bobket.net/> LLC

**Comment by tiffehr** [comment]
Spot-checking yesterday's data for Arkansas, all counties exactly equal the state-level total we report between the two CSVs.

## Our state CSV:
![image](https://user-images.githubusercontent.com/60173/98303362-370d7780-1f7b-11eb-82cd-5472a19c3938.png)
 
## County CSV, copied to Sheets, and summed using their internal tool (some counties out of view):
![image](https://user-images.githubusercontent.com/60173/98304393-20682000-1f7d-11eb-9ed4-695b7c5b0eb9.png)

Our Arkansas data source is https://experience.arcgis.com/experience/c2ef4a4fcbe5458fbf2e48a21e4fece9 and we make no changes on their data except to remap a "Missing County Info" to our "Unknown" county in Arkansas.

Are you excluding the Unknown counties in various states, in your comparison?

**Comment by bobket45** [comment]
Tiff,

Looking at the county, there are "unknown" counties and I noticed that
unknown took a big jump.
May indicate a data entry or reporting problem(s). Preceding the election
was a bit unlucky timing.

[image: Unknown.png]

Regards,
Bob Ketterer
bob@BOBKET.NET <http://bobket.net/> LLC

**Comment by tiffehr** [comment]
@bobket45 I would refer you again to our README, which details per-state reporting challenges, our data definitions and how we use artifacts like Unknown counties.  I am still unclear where you think there is an error.
