### ISSUE TITLE
New York City: by County

### ISSUE THREAD

**Issue by InformationForHumans** [nytimes/covid-19-data#49]
Hi - first off, thank you for this source. Is there a breakout by Queens, Kings, Bronx, Staten Island, New York?

**Comment by brycemcd** [comment]
The [README](https://github.com/nytimes/covid-19-data#geographic-exceptions) indicates that all counties (boroughs) in NYC are combined into one and do not have an assigned FIPs code.

**Comment by InformationForHumans** [comment]
Thank you @brycemcd
