### ISSUE TITLE
Data Issue:  Incorrect zero-case day in Massachusetts 11/5

### ISSUE THREAD

**Issue by joshua-nugent** [nytimes/covid-19-data#490]
### Describe the issue:
- [X] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
Hampshire, Franklin, and Hampden counties (maybe more?) in the state of MA are showing zero new cases on 11/5, but the mass.gov site shows non-zero cases. Can you fix this?

**Comment by tiffehr** [comment]
Looking into it.
