### ISSUE TITLE
Data Issue: Discrepancy between Illinois State and Cook County for 11-05 and 11-06

### ISSUE THREAD

**Issue by chrwang** [nytimes/covid-19-data#491]
### Describe the issue:
- [X] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
From 2020-11-05 to 2020-11-06, Illinois had an increase in deaths of 78 (from 10334 to 10412), but Cook County had an increase of 268 (from 5574 to 5742). The [Cook County Medical Examiner's page](https://maps.cookcountyil.gov/medexamcovid19/) also seems to suggest that there have only been  5657 total deaths. Could you clarify if this was expected or if there was an error? Thanks!

**Comment by lwaananenjones** [comment]
This is the result of a change in how the Illinois Department of Health is reporting their data. Before 11/6, the state provided total statewide counts for probable cases and deaths, but did not split that total by county. The state [made a few changes to their data structure on 11/6](http://dph.illinois.gov/news/public-health-officials-announce-10376-new-confirmed-cases-coronavirus-disease?fbclid=IwAR1xsXAmTJowQ9446_LeJBbuv1NIW0kIrBaLZUmUMf7ERw5QBmp402GBLn0), and one change is that [probable](https://www.nytimes.com/interactive/2020/06/19/us/us-coronavirus-covid-death-toll.html) deaths are now assigned by county. 

It's our methodology to include probable cases and deaths where available. So the increase accurately reflects what the state is reporting now, but it's likely that many of those deaths happened months ago.

**Comment by chrwang** [comment]
Makes sense, thanks for the info!
