### ISSUE TITLE
Data Issue:  

### ISSUE THREAD

**Issue by PatMinot** [nytimes/covid-19-data#493]
### Describe the issue:
- [ ] Incorrect number of cases at county level vs. dataset for state level data. 

example code below. sum the columns to see variance of aggregates at county vs. state datasets.

df_RawData = pd.read_csv('https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv')
df_covidNtl = pd.pivot_table(df_RawData, values='cases', index=['county'], columns=['date'])
df_covidNtl = df_covidNtl.fillna(0)
df_covidNtl.to_excel('test.xlsx')

df_covidState=pd.read_csv('https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv')
df_covidState = pd.pivot_table(df_covidState, values = 'cases',index=['state'], columns=['date']) 
df_covidState.to_excel('test2.xlsx')

**Comment by albertsun** [comment]
Closing this since you have made two issues https://github.com/nytimes/covid-19-data/issues/494
