### ISSUE TITLE
Data Issue: Oklahoma State Department of Health day-shifting data

### ISSUE THREAD

**Issue by HiDrNick** [nytimes/covid-19-data#495]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [X] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [X] Other

### Fuller details
During the weekend of 2020-11-07, Oklahoma skipped a whole day of reporting data. 

Rather than catch up, on Monday OSDH officials announced that COVID-19 new case reporting would be delayed by an additional 24 hours. See [this Tweet from a local health reporter](https://twitter.com/KassieMcClung/status/1325860662891909121), for example. This changes the definition of "date" in their report. Their intention is to remain perpetually a day behind.

The NYT data set does not currently reflect that. In Oklahoma, on Saturday 2020-11-07, 4771 cases are assigned to FIPS 40000. The following day, those cases are redistributed to the correct counties, with a few duplicates removed, but the new cases for Saturday (which would usually be reported on Sunday) were not reported. Instead, the Saturday cases were reported on Monday, the Sunday cases Tuesday, and so on.

A dataset user looking at Oklahoma would conclude that the new cases reported for Oklahoma on 2020-11-04 through 2020-11-10 are 7 days of case data, but they'd be wrong. It only covers 6 days. In the short term, trajectory calculations that compare this week's new cases to last week's new cases will fail.

This issue might be addressed in several ways. I'm not sure what your usual practice is. You might
- Keep the date consistent: Ignore the 2020-11-07 OSDH update, and backdate all future updates 1 day, or
- Adopt the new date definition: Ignore the 2020-11-07 OSDH update, and move every previous date forward of 1 day.

Either approach will address the issue with week-over-week comparisons.

Thank you very much for your work creating and maintaining this data set. I've worn it out trying to keep out hospitals in Oklahoma City from overflowing.

Cheers, 
**Nick Brooke**
Brooke Insights

**Comment by albertsun** [comment]
@HiDrNick thanks for the detailed issue.

In general our policy is to take numbers based on the day they are published and ignore the day the health department claims the data is for. This has been the best way to be consistent nationally and to update on a regular schedule. So, we're not going to do any backdating going forward or any mass back-dating of data that Oklahoma has published in the past.

However, for 11/7 and 11/8 specifically we will be making some revisions. The original numbers for 11/7 came from this press release: https://coronavirus.health.ok.gov/articles/situation-update-covid-19-11072020 That gave a statewide number but not a county breakdown for new cases.

On 11/8 Oklahoma updated their county level data and also removed duplicates from the number they published on 11/7. We're going to backdate those county level numbers and total to 11/7 and leave the current numbers for 11/8 unchanged. After our upcoming revision, both 11/7 and 11/8 will have 136258 cases.

From 11/9 onwards we will be back to our regular methodology of assigning the numbers released by Oklahoma to the current day.

It's true as you point out that this means the weekly number is going to be based on only 6 not 7 days worth of data. It may be worth adding to whatever analysis script you are using some error handling for days like this and just doing a 6 day average if there is a day with a 0.

Hope that helps.

**Comment by HiDrNick** [comment]
Having the 7th and the 8th match will help call attention to the skipped day, thanks.
