### ISSUE TITLE
Data Issue: Audrain County, Missouri has not shown increase in cases since Oct. 22

### ISSUE THREAD

**Issue by Kirkman** [nytimes/covid-19-data#498]
### Describe the issue:
- [x] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
The NYT Covid-19 historical county dataset shows [no increase in cases after Oct. 22](https://user-images.githubusercontent.com/761387/99289347-6b4a2900-2802-11eb-8688-ddf4fd55e3c2.png) in Audrain County, Missouri, where the total given on that date is 896.

In contrast, a screenshot on the [Audrain Co. health department website](http://www.audraincountyhealth.org/) shows a steady progression from 462 to 721 over the period of Oct. 31 - Nov. 13:

![screenshot](http://www.audraincountyhealth.org/sitebuilder/images/ACHD_COVID_Dashboard_111320-1005x575.png)

Similarly, the [Missouri state health department](https://results.mo.gov/t/COVID19/views/StatewideDashboards-MOBILETEST/COVID-19inMissouriPhone?:isGuestRedirectFromVizportal=y&:embed=y) today shows a 7-day new case count of 96, and shows the total number of cumulative cases as 865:

![Screen Shot 2020-11-16 at 11 07 06 AM](https://user-images.githubusercontent.com/761387/99284589-0e4b7480-27fc-11eb-8ec4-28bcb52fc9b7.png)

![Screen Shot 2020-11-16 at 11 13 03 AM](https://user-images.githubusercontent.com/761387/99285226-e7417280-27fc-11eb-97d5-5b23f1de51fb.png)

**Comment by Kirkman** [comment]
I have been scraping Missouri's new state dashboard since Oct. 20. If it's helpful, here are the "total cases" and "total deaths" figures I have scraped for Audrain each day:

date | cases | deaths
---- | ----- | ------
2020-10-20 | 535 | 7
2020-10-21 | 535 | 7 
2020-10-22 | 553 | 7
2020-10-23 | 560 | 7
2020-10-24 | 563 | 11
2020-10-25 | 571 | 11
2020-10-26 | 577 | 11
2020-10-27 | 586 | 11
2020-10-28 | 588 | 10
2020-10-29 | (failed to scrape)
2020-10-30 | 622 | 10
2020-10-31 | 639 | 10
2020-11-01 | 654 | 10
2020-11-02 | 664 | 10
2020-11-03 | 680 | 11
2020-11-04 | 681 | 11
2020-11-05 | 695 | 10 
2020-11-06 | 708 | 10
2020-11-07 | 718 | 10
2020-11-08 | 734 | 10
2020-11-09 | 745 | 10
2020-11-10 | 763 | 11
2020-11-11 | 777 | 11
2020-11-12 | 791 | 11
2020-11-13 | 812 | 11
2020-11-14 | 836 | 11
2020-11-15 | 849 | 11
2020-11-16 | 865 | 11

**Comment by lwaananenjones** [comment]
Thank you for asking about this — it took us a while to implement a solution after the county [stopped reporting inmate cases](https://www.facebook.com/permalink.php?story_fbid=3314488645253194&id=190086631026760) in late October. We use county data in many places if the county is reporting ahead of the state, and Audrain County data dropped from 896 on 10/22 to 500 on 10/26 after the county stopped including inmate cases from the Women's Eastern Reception, Diagnostic and Correctional Center, which had a substantial outbreak in September and October. Our dataset includes prison cases when we can verify methodology and location. We've now revised the data to use the county's updates combined with the prison cases, using figures from the state's [corrections dashboard](https://results.mo.gov/#/site/DOC/views/CovidDashboard_Public/Public).

**Comment by Kirkman** [comment]
That makes a lot of sense. Thanks for revising!
