### ISSUE TITLE
Data Issue:  Mask data - state/county data gaps when mapping with highcharter

### ISSUE THREAD

**Issue by houstonhaynes** [nytimes/covid-19-data#499]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [x] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
I just pulled this data to sniff around a bit and found that AK, CA, AZ, CO, AK, AL, CT and the odd county are missing data. I'm pulling the county-based JS map from highcharts through the R wrapper library. See sample and screen shot below. Thanks for any advice on how/whether to remediate.

`library(highcharter)

mask_URL <- "https://raw.githubusercontent.com/nytimes/covid-19-data/master/mask-use/mask-use-by-county.csv"

maskdata <- read.csv(mask_URL)

hcmap("countries/us/us-all-all",
      data = maskdata,
      value = "ALWAYS",
      joinBy = c("fips", "COUNTYFP")) `

![Screenshot 2020-11-16 110126](https://user-images.githubusercontent.com/8174976/99296798-2b804300-27fc-11eb-8673-b074fde62b02.png)

**Comment by houstonhaynes** [comment]
I'm embarrased - forgot to pad the values... - see updated 

`mask_data <- 
  mask_data %>%
  mutate(COUNTYFP = str_pad(COUNTYFP, 5, side = 'left', pad = '0'))`

**Comment by tiffehr** [comment]
Looking into this one.  Thanks for drawing our attention to it!
