### ISSUE TITLE
Data marked March 27 should be March 26

### ISSUE THREAD

**Issue by ritchiewilson** [nytimes/covid-19-data#5]
Right now it is early on March 27, but these .csv files have all the data for the 27th. That doesn't make sense, because the day hasn't happened yet. The files are also almost totally missing data from March 26. It looks like the data marked for March 27 should have actually been for March 26. I think that also explains why this chart looks like it missing a days worth of day: https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html#g-cases-over-time

![image](https://user-images.githubusercontent.com/296062/77762656-3d646a00-7010-11ea-89ec-9f0422af0faf.png)

That chart is missing data from yesterday, but does have data for today, which hasn't really happened yet.

Can you confirm this data is correct?

**Comment by albertsun** [comment]
Hi @ritchiewilson, thanks for flagging this issue for us. The chart issue there was an error with how the data was rendered in the chart on our maps page specifically. That's been fixed now.

<img width="647" alt="Screen Shot 2020-03-27 at 10 12 13 AM" src="https://user-images.githubusercontent.com/382862/77764697-74884a80-7013-11ea-949c-d52242362c35.png">

The data files in this repo are correct, but the last day of data available here is 3/25. We have not yet published data for 3/26 or 3/27, but will be adding that data over time.

**Comment by ritchiewilson** [comment]
Perfect. Thanks for you work on this
