### ISSUE TITLE
Data Issue:  ND Cases are daily diff not total for dates

### ISSUE THREAD

**Issue by CovidCountyUSA** [nytimes/covid-19-data#500]
Ignore

**Comment by CovidCountyUSA** [comment]
Accidental issue submission.

**Comment by tiffehr** [comment]
👍

**Comment by CovidCountyUSA** [comment]
County level dataL Graphic showing spread from Jan 2020 to Nov 23, 2020 ,,,
thanks to NYT.  From what I understand, the Gray Lady is the only one
gathering this information...thank you.

https://youtu.be/meswiMV8q1A

**Comment by tiffehr** [comment]
Thank you for sharing!
