### ISSUE TITLE
Data Issue: Looking at just USA data. Missing data for several counties for certain timeframes

### ISSUE THREAD

**Issue by Nk2845** [nytimes/covid-19-data#501]
For Example, Autauga county in Alabama state and Logan county in Arkansas State have data missing from 01/21/2020 to 03/23/2020 and from 01/21/2020 and 04/05/2020 respectively.

But, when I use this Tableau Dashboard published at,
https://public.tableau.com/profile/covid.19.data.resource.hub#!/vizhome/COVID-19Cases_15840488375320/COVID-19GlobalView
This publisher somehow has the complete dataset including the missing data like I mentioned above. 

Currently, your dataset has 748,500 records approximately and the above publisher has 991,300 records.

Could you please check the issue and comment where I can find the full dataset?

Thank you,
NK

**Comment by albertsun** [comment]
@Nk2845 we don't publish a row for any place on days where there were 0 cases and 0 deaths. The first row for each of those places are when the first case was reported. You can assume that in the date range you mention they have 0 cases and 0 deaths.

**Comment by Nk2845** [comment]
Great. Thank you for a quick response. I checked and looks like still there are 6,465 records with Positive Cases count and 1748 records with Death count.

Kindly check into the issue.

[Data for NY Times.xlsx](https://github.com/nytimes/covid-19-data/files/5575484/Data.for.NY.Times.xlsx)



Please look at the attachment below

**Comment by tiffehr** [comment]
@Nk2845 I'm not following what you want us to check about #s of records. The attachment you reference looks like a translation of our data.  Different data providers are going to have different numbers of records, based on methodological variation.  So it's unclear what you are trying to report.
