### ISSUE TITLE
Data Issue: Incorrect data for Washita County, OK. on 2020-11-07?

### ISSUE THREAD

**Issue by JonasHogman** [nytimes/covid-19-data#502]
### Describe the issue:
- [X] Incorrect number of cases or deaths
- [X] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
The number of cumulative deaths in Washita County, OK. (FIPS 40149) in the historical dataset spikes up from 1 to 43 on 2020-11-07, and then goes back down to 2 the day after.

**Comment by lwaananenjones** [comment]
Thank you for pointing this out. This was a day we had to manually update the data after Oklahoma issued corrected day the following day, and a few counties were inadvertently transposed. That will be corrected in the next update.
