### ISSUE TITLE
Data Issue:  Inaccurate Case numbers for Santa Barbara County

### ISSUE THREAD

**Issue by mwehmer** [nytimes/covid-19-data#505]
### Describe the issue:
- [X ] Incorrect number of cases or deaths

### Fuller details
The reported case counts for Santa Barbara County are incorrect. The 7-day averages are pretty close, but as one of the Epidemiologists that maintains the Santa Barbara County Dashboard found here: https://experience.arcgis.com/experience/030e625c69a04378b2756de161f82ef6 and is part of the team that generates the local numbers, the Santa Barbara data on your site is inaccurate.

For example: On 11/24 - Santa Barbara reported 100 cases vs the 220 that I am seeing on the NYT dashboard.

**Comment by lwaananenjones** [comment]
Thank you for getting in touch about this. (And thank you for your work! We sincerely appreciate all the work that goes into regularly updated county dashboards.) The number we display for new cases is the difference between the cumulative totals from day to day, and the Santa Barbara dashboard is typically our source. Our system pulls in the total number of cases from the dashboard if everything is working correctly, and occasionally uses the state's number on weekends. Here's a comparison for the past several days:

| Date | Current SB dashboard | Data pulled from dashboard | NYT data |
| ------------- | ------------- | ------------- |
| 11/24 | 11166 | 11166 | 11166 |
| 11/23 | 11067 | 10934 | 10946 (state) |
| 11/22 | 11013 | no update | 10922 (state) |
| 11/21 | 10934 | no update | 10839 |
| 11/20 | 10839 | 10839 | 10839 |
| 11/19 | 10768 | 10768 | 10768 |
| 11/18 | 10702 | 10702 | 10702 |
| 11/17 | 10612 | 10612 | 10612 |

So I see two reasons the daily new cases may be different:

1. The Santa Barbara dashboard doesn't update on weekends, is that correct? If the weekend numbers are added retroactively, that doesn't get pulled into our system, though it's possible we could also make a retroactive revision.
2. This most recent Monday, 11/23, the counts do not match. After checking with other sources, I'm confident our system pulled in the number correctly on that day, but if 11,067 is correct we can update that.

The 11/23 number is the main reason for the difference in the number of new cases. If you can confirm that 11,067 is correct for 11/23, we can change that in our data.

**Comment by mwehmer** [comment]
Thank you for the quick response. 
1. The Santa Barbara County dashboard does not update on weekends or holidays, but retroactively updates the following business day around 4pm PST.
2. 11,067 is the correct number of newly reported cases to the public health department on 11/23/20. But the issue is the calculation that the your system is using to calculate Santa Barbara County numbers will generally be off because subtracting from the day before will not produce the newly reported cases of that day. Our epidemiology team constantly clean data and will on occasion remove a case that was later to be out of jurisdiction, a duplicate case, or not a case at all due to changing lab algorithms that had been reported on a previous date.

I appreciate you taking the time to discuss these data issues.

**Comment by lwaananenjones** [comment]
Just circling back to confirm we revised the 11/23/20 count to 11,067. Thank you!
