### ISSUE TITLE
Data Issue:  Blanks for Puerto Rico deaths

### ISSUE THREAD

**Issue by dgglynn** [nytimes/covid-19-data#507]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ x] Other

### Fuller details
For current us-counties.csv (as of 11/29/2020) lines 117488 to 117562, covering Puerto Rico for 2020-05-05 have trailing commas that are inconsistent with the format of the rest of the lines in the csv file.

The 11/26/2020 version of us-counties.csv does not have these trailing commas for the entries for Puerto Rico starting at line 17488.

Cursory inspection seems to indicate that entries in the current us-counties.csv for Puerto Rico seem to have the trailing commas for other dates after 2020-05-05 lines. I did not confirm that it is all entries for Puerto Rico listed in current

2020-05-5 entries for Puerto Rico are the first ones that have a "county" entry(earlier entries for Puerto Rico appear to be aggregate data and the county field is labeled unknown).

This difference in line formatting broke importing of the csv file into my influxdb instance.

**Comment by SomervilleTom** [comment]
The change to simply DROP "deaths" data for PR is a breaking change. that breaks the ingestion process of my site as well.

I suggest that it would be better to remove ALL the municipio data for PR than to include data that is consistent with the rest of the file. Having a header that includes a field (`deaths`) and then providing a few hundred rows that end with the field separator (out of 776,197) is not acceptable. Either that or provide a distinguished value (such a "-1") for the missing field.

**Comment by albertsun** [comment]
Hi folks, apologies for the change breaking ingestion processes. The trailing commas indicates that the value for deaths for all Puerto Rico municipios is blank, which should be distinct from "0". We do generally use blanks for missing values rather than a -1 or anything like that. Missing FIPS codes are handled the same, as is the live/us-counties.csv file.

This change was requested in this other issue https://github.com/nytimes/covid-19-data/issues/457

We can't remove all the municipio data for Puerto Rico as the cases values are all still valid.

**Comment by SomervilleTom** [comment]
First, let me just express my appreciation to the entire NYT team for providing this invaluable resource.

I guess there's just no good way around the issue -- if the data isn't there, it isn't there. I'll refactor my ingestion process to be more robust. I appreciate the quick response to my earlier cfomment.

**Comment by gnewman7** [comment]
NYTimes this data is a great resource. Thank you for sharing. I too ran into the same ingestion issue with the Puerto Rico entries. I will correct my MySQL Load scripts if the death values are going to stay as blanks.

**Comment by mhowe0422** [comment]
I've already made the load change. Thanks for the data, keeping us busy doing our own tracking.

Mark
Pittsburgh PA
________________________________

**Comment by albertsun** [comment]
Appreciate you all for bearing with us through the format change.
