### ISSUE TITLE
Data Issue:  Our you using Moving Average i.e. Rolling Mean for cases and deaths?

### ISSUE THREAD

**Issue by davidjayjackson** [nytimes/covid-19-data#508]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [* ] Missing time-series information
- [ ] Other

### Fuller details
Our you using Moving Average i.e. Rolling Mean for cases and deaths?

Thanks,
David Jackson

**Comment by albertsun** [comment]
The data files in this repository are only raw counts. The files do not contain any rolling means or moving averages.

**Comment by davidjayjackson** [comment]
Thanks for the clarification.

David
