### ISSUE TITLE
Is the data being refreshed at midnight everyday?  

### ISSUE THREAD

**Issue by Nk2845** [nytimes/covid-19-data#511]
I saw the data refreshed at around 6:30 am yesterday. Can we expect the data to be consistently refreshed at midnight everyday?

**Comment by albertsun** [comment]
It will usually be updated each night by around 2am ET, but sometimes not until the morning. It's a combination of automated and human done steps so hard to guarantee an exact time. The schedule of updates as they stand now should give a good picture of the overall cadence.
