### ISSUE TITLE
CoWiz: An Interactive Dashboard for analyzing and visualizing the COVID-19 spread in the US

### ISSUE THREAD

**Issue by ABSantra** [nytimes/covid-19-data#512]
### Project Description - CoWiz
Ever wondered - "Which geographical regions showed a downward trend similar to the lockdown period during extended long weekends?" OR "Are the regions with an uptick caused by the rallies with mass gatherings?"

We at Information Technology Lab (ITLab) from the University of Texas at Arlington announce the launch of Covid Wizard or CoWiz - The interactive Covid-19 data visualization dashboard based on Multilayer Network (MLN) analysis underneath. With this tool users can flexibly analyze the effect of different events on the spread of the pandemic across geographical regions in the US in multiple time periods of varying lengths.

Salient Features of CoWiz:
- Interval Length: The user selects the desired length of the periods (in number of day(s)) that he/she wants to analyze. The comparison can range from a single day to 30 days.
- Periods for Analysis: Two periods are to be chosen based on the events of interest
  - Base Period: The user selects the period whose number of new cases forms the basis of comparison. Example: The lockdown period
  - Target Period: The user selects the period whose number of new cases are to be compared against the base period. Example: Period around the 4th of July long weekend
- Severity Rate: The user is free to choose the extend of spread that he/she wishes to visualize from Big Dip to Spike. 
- In-depth Study: Different capabilities have been provided for in-dept drill down analysis
  - Hover: On hovering onto specific counties, the exact change in new cases, population density, median household income, and average education qualifications are displayed.
  - Zoom and Pan: Users can zoom and pan onto different regions for a clearer view
  - Download: For post-visualization analysis, the generated maps can be downloaded.
- News Headlines: The top 10 Covid-19 related news headlines from the New York Times for the selected target period are fetched and displayed.
- WHO Update: The official latest cumulative confirmed cases and deaths for the World and the US are displayed.
- Automated Data Repository Updates: The server-side Covid-19 data set is scheduled to be updated each night. The users are free to analyze any period from February 1, 2020 to a date as recent as yesterday.
- Feedback: A feedback option has been provided for the users.

### Explore the Project
Dashboard Link: https://itlab.uta.edu/cowiz/
Tutorial Video: https://www.youtube.com/watch?v=4vJ56FYBSCg

**Comment by tiffehr** [comment]
Thank you for sharing this with us!  I have added it to our Project board, under Examples.
