### ISSUE TITLE
Iowa Death Counts

### ISSUE THREAD

**Issue by gellingson16** [nytimes/covid-19-data#513]
Looks like Iowa deaths haven't been picked up over the past couple of days. I know they changed how they reported this on the coronavirus.iowa.gov website this week.

**Comment by lwaananenjones** [comment]
Thank you for pointing this out. We're working on a fix, and I'll update here when it's resolved.

**Comment by lwaananenjones** [comment]
This should be resolved now. We corrected the data last week to reflect the correct counts on 12/10 and 12/11 and changes our notes to indicate that the state is now including probable deaths. If anyone finds this issue while looking for context later, Iowa changed its methodology to [report deaths only based on death certificates](https://idph.iowa.gov/News/ArtMID/646/ArticleID/158384).

**Comment by gellingson16** [comment]
Thanks, appreciate it!
