### ISSUE TITLE
Vaccination Counts

### ISSUE THREAD

**Issue by millerloppet** [nytimes/covid-19-data#516]
Will vaccination doses or rates be available at the state or county level in the near (or not so near) future?

**Comment by tiffehr** [comment]
We're evaluating that now. The few early reporting sources are all over the map in terms of the data they're providing.  I'll return here once we have an idea what we might collect.

**Comment by jadacyrus** [comment]
+1 Also interested in this!

**Comment by tiffehr** [comment]
Yep, thank you.  No need for further +1s.  We're tracking this.

**Comment by YiXu-Takeda** [comment]
Hi tiffehr,

Any plan regarding the vaccine data?

**Comment by tiffehr** [comment]
I'll update the thread when we are collecting enough to make a judgement.  In the meantime, I would point you to the CDC's data.

**Comment by sebsebmc** [comment]
Hi, the [NYT vaccine tracking page](https://www.nytimes.com/interactive/2020/us/covid-19-vaccine-doses.html) links to this repository but the data is not here. This is understandably a bit confusing, and it would be great if the data powering that page was available somehow.

**Comment by tiffehr** [comment]
@sebsebmc Where is the link you mentioned, in that page?  Our sourcing we list on that page is the CDC and the U.S. Census Bureau.  We do not use any internal vaccination data, because it is taking appropriate time for us to build it out to the rigor of our other data sets here.

**Comment by sebsebmc** [comment]
Its at the bottom of the page just above the comments, 
![image](https://user-images.githubusercontent.com/2250975/107172451-03cbf180-698b-11eb-9346-f8375cc94278.png)
the second link point to this repo.

**Comment by tiffehr** [comment]
Ah, thank you. I would take the actual Sourcing lines in the article above our cross-story generic Covid-19 data module.  The article says a half-dozen times that the data is from the CDC and/or the Census Bureau, under each specific chart.  But I can see where the generic module is unclear.

**Comment by chilinux** [comment]
History of vaccination data seems to be getting posted here:
https://github.com/govex/COVID-19/tree/master/data_tables/vaccine_data

The data doesn't seem to match always 1 for 1 with what NYT publishes.  However, if you are trying to track how many first doses are resulting in second doses some 3-4 weeks later, it is helpful to have the historical first dose numbers.

It would be nice if NYT was publishing their own historical numbers as well.

**Comment by tiffehr** [comment]
@chilinux Historical numbers for what?

**Comment by chilinux** [comment]
If you go to:
https://www.nytimes.com/interactive/2020/us/covid-19-vaccine-doses.html

You only get the most recent data.

There is no way to look at what percentage of first doses was given on 21 or 28 days earlier.

**Comment by tiffehr** [comment]
I'm sorry, I'm really not following what you expect to have from this repo, in terms of data.  Our Graphic is not meant to be a vaccines data set, but a public-facing measure of progress.  We are using a few sources for vaccine data (thread above) but have not added any of that here.

**Comment by xunhuang** [comment]
it seems like New York State already publishes county level vaccination data, but it's in a Tableau that's difficult to extract
https://covid19vaccine.health.ny.gov/covid-19-vaccine-tracker

If anyone have some idea on how to extract, I'd love to help automate

**Comment by sagransj** [comment]
I would also like to have vaccination data here, and would particularly be interested in seeing the racial disparities data as related to vaccination as presented in this NYT interactive: https://www.nytimes.com/interactive/2021/03/05/us/vaccine-racial-disparities.html 

It would be interesting to be able to see how these disparities change over time as vaccination continues to expand.

**Comment by tiffehr** [comment]
Update on this:  we won't be adding vaccination data to our files here.  

The [CDC's public, per-county vaccination feed](https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=vaccination_county_condensed_data) is our central source for our reader-facing visualizations, as well as their [state vaccination data](https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=vaccination_data).  We recommend these sources going forward.
