### ISSUE TITLE
Data Issue:  excess deaths data is not updated to Dec 2016

### ISSUE THREAD

**Issue by daliagachc** [nytimes/covid-19-data#517]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [x] Other

Thanks for the amazing work! 

When could I expect the next update on the excess death rate file located at covid-19-data/excess-deaths/

**Comment by Pedro-McM** [comment]
Agreed. It looks like the data hasn't been updated since yesterday.

**Comment by tiffehr** [comment]
This is not an automated update. It is periodic, as we collect and confirm data from the wide variety of sources listed in the [Excess deaths directory README](https://github.com/nytimes/covid-19-data/tree/master/excess-deaths) plus CDC estimates.

Our updates of this data are probably best indicated by when we update _the data_ for our [Graphic](https://www.nytimes.com/interactive/2020/us/covid-death-toll-us.html).  That last updated Dec. 16th, 2020.  The current dataset seems to max at `2020-09-22`.  We'll look into updating it in early 2021.

**Comment by albertsun** [comment]
Hi y'all, we've updated the excess deaths data set.

This is going to be the last update to that dataset for the time being.

**Comment by daliagachc** [comment]
Thanks for the update and the great work! again, this is the only source that is reporting on the excess death rate for Bolivia which makes it quite important given the numbers. I hope that you can consider to update it again in the future given the outstanding number of positive cases that Bolivia is showing for January.
