### ISSUE TITLE
Thank you! GIF that animates daily changes in US

### ISSUE THREAD

**Issue by insideout** [nytimes/covid-19-data#52]
![covid19in20s](https://user-images.githubusercontent.com/47407833/77814186-0623a680-706c-11ea-8563-3456ce455763.gif)

Twitter daily updates: https://twitter.com/hashtag/covid19in20s

**Comment by WeileiZeng** [comment]
https://public.flourish.studio/visualisation/1632510/embed?auto=1

a similar one here

**Comment by Zoooook** [comment]
I made one also:
https://github.com/Zoooook/CoronavirusTimelapse
https://www.youtube.com/watch?v=WiAFI5BwHKY
