### ISSUE TITLE
Data Issue: Us-counties/us-states updates for Dec. 29 

### ISSUE THREAD

**Issue by ddenenberg71** [nytimes/covid-19-data#520]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [X] Missing time-series information
- [ ] Other

### Fuller details
us-counties.csv, us-states.csv, and us.csv updates didn't occur around the 'normal' time.  Just a heads-up in case you're unaware.    Thanks.

**Comment by PatrickDRusk** [comment]
I need my daily fix!

**Comment by albertsun** [comment]
@ddenenberg71 data should be updated now.

**Comment by ddenenberg71** [comment]
Thanks @albertsun!
