### ISSUE TITLE
Data Issue:  US Counties/US State data not updated for Jan 01 2021

### ISSUE THREAD

**Issue by AZIQB** [nytimes/covid-19-data#522]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [x] Missing time-series information
- [ ] Other

### Fuller details
US Counties/US States data .csv files are not showing 01/01/2021 data. I see it in the code but it is not updated in the csv files.

**Comment by albertsun** [comment]
Hi @AZIQB are you still seeing this issue? The files do have data for that day as I see them.
