### ISSUE TITLE
Question:  URLs for Mumbai Burials Data

### ISSUE THREAD

**Issue by akarlinsky** [nytimes/covid-19-data#523]
The listing states the source of Mumbai burials data, but does not link to it. How and where can this data be obtained?

**Comment by akarlinsky** [comment]
Same for Bolivia.

**Comment by tiffehr** [comment]
This public dataset is about cases & deaths data, with nothing about burials.  May I ask for a URL where you are finding such data?

**Comment by akarlinsky** [comment]
I'm referring to the excess deaths portion of the dataset:
https://github.com/nytimes/covid-19-data/tree/master/excess-deaths

**Comment by albertsun** [comment]
@akarlinsky we will look into this

**Comment by albertsun** [comment]
@akarlinsky in instances where data is not linked, the named government has directly provided a data file to The New York Times. We've then cleaned and matched the data to the format here. If you'd like to use the data, the best way would be to use it directly from the data file published in this repo.

**Comment by akarlinsky** [comment]
Thanks, that's what I did. But I was trying to find more up to date data as the last update of excess deaths data was a couple of months ago.

Also, I found Quarterly Deaths data for Jakarta (Indonesia). The totals add up to much higher than the listed burials data you cite:
[](https://data.jakarta.go.id/dataset/data-penerbitan-akta-kematian-tahun-2020)
