### ISSUE TITLE
Data Issue:  New Jersey 1/03-1/04 case counts

### ISSUE THREAD

**Issue by Kaycegsd7** [nytimes/covid-19-data#525]
### Describe the issue:
- [x ] Incorrect number of cases or deaths
- [x] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
The January 3 2021 cases count was 494,063.  The cases count for January 4 2021 was 545,155.  New cases on January 4 would be 51,092.  About 9 to 10 times what it should be.  New Jersey should be in the 4400 to 5000 range.  Thank you.

**Comment by jestabil** [comment]
Same question.

**Comment by lwaananenjones** [comment]
On Jan. 4, New Jersey added probable cases identified through antigen testing, which resulted in a one-time increase. We have notes about anomalies like this one on the [state tracker pages](https://www.nytimes.com/interactive/2020/us/new-jersey-coronavirus-cases.html). There are now only a few states remaining that do not include probable cases identified through antigen testing: California, Maryland, Missouri and Nevada (though NV includes some from its prisons).

The [state's dashboard](https://covid19.nj.gov/) has a time series by date of illness onset under "Case and Mortality Summaries." Our methodology is using the date cases are announced to be consistent across all states, but that may be useful if you're looking for historical data. It shows the vast majority of probable cases have been reported in the past three months.
