### ISSUE TITLE
The last data point for Bolivia is missing in the data

### ISSUE THREAD

**Issue by dkobak** [nytimes/covid-19-data#526]
Thanks for your work. 

In the last update of the NYT article, Bolivia has one more data point (September), compared to the data here on Github. Would be great if you could fix it.

**Comment by tiffehr** [comment]
Which file in this data set?

**Comment by akarlinsky** [comment]
excess deaths data
[https://github.com/nytimes/covid-19-data/tree/master/excess-deaths](https://github.com/nytimes/covid-19-data/tree/master/excess-deaths)

**Comment by tiffehr** [comment]
Thank you. We're reviewing. As you probably saw, we just updated the Graphic, so Sept. would already be out of date.

**Comment by akarlinsky** [comment]
![image](https://user-images.githubusercontent.com/48435065/104773149-3feda700-577d-11eb-91f0-975aa15b9f33.png)
![image](https://user-images.githubusercontent.com/48435065/104773269-76c3bd00-577d-11eb-9202-3f52ecb6d3b8.png)

Bolivia still shows up to September in graphic :)
Also, an update of the excess-deaths data is now even more in order.

Thanks :)

**Comment by tiffehr** [comment]
We're aware of you interest, thank you. Not all country data sources can be updated at the same interval. The source material simply does not line up.

**Comment by dkobak** [comment]
Thanks @tiffehr, I understand that, but as you use the September value for Bolivia in your figures, I assumed it could be added to the CSV too...

**Comment by albertsun** [comment]
Hi y'all, we've updated the excess deaths data set with the latest in the published graphic. Thank you all for your interest and following up on this.

As an FYI, due to staffing priorities, we are going to be discontinuing future updates to our excess deaths tracker for the time being.

**Comment by dkobak** [comment]
Thanks!
