### ISSUE TITLE
Data Issue:  Jan. 21 us-states/us-counties updates missing

### ISSUE THREAD

**Issue by ddenenberg71** [nytimes/covid-19-data#529]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [X] Missing time-series information
- [ ] Other

### Fuller details
Just a heads-up if not already known... the us-*.csv files weren't updated in the normal timeframe this morning.  Thanks.

**Comment by albertsun** [comment]
@ddenenberg71 these should be coming within the hour.

**Comment by tiffehr** [comment]
@ddenenberg71 Confirm you see the latest files?

**Comment by ddenenberg71** [comment]
@tiffehr  Yes.  All good.  Thanks.
