### ISSUE TITLE
"True Cases" added to map

### ISSUE THREAD

**Issue by btgalush** [nytimes/covid-19-data#53]
Please display "True Cases" on your map!  Your map with only confirmed cases is giving citizens like those in Pacifica CA a false sense of security/calm.  Academic research from Wuhan data shows "True Cases" are at least 8x confirmed cases.  With failed testing in US where probably only 1 in 10 cases are confirmed "True Cases" could be 80x (8 times 10) confirmed cases or worse.  People must know how much danger they are in, many many are still not concerned.

Academic paper on Wuhan data showing 11 day lag between "True Cases" and confirmed cases:
https://jamanetwork.com/journals/jama/fullarticle/2762130

Key image I annotated:
https://www.dropbox.com/s/r1w632m82ao18xa/WuhanGraph_1_22_circled.png?dl=0

Tomas Pueyo Seminal, but long (26 minutes) medium post on subject:
https://medium.com/@tomaspueyo/coronavirus-act-today-or-people-will-die-f4d3d9cd99ca

Endorsements of medium post by experts:
https://medium.com/tomas-pueyo/coronavirus-articles-endorsements-fdc68614f8e3

Example expert who endorsed:
Anthony Costello, ex-Director at the World Health Organization. Professor, University College London (tweet)

People to contact to corroborate model to estimate "True Cases":
Scott Morrow, San Mateo Health (recent NYTimes interview: https://www.nytimes.com/2020/03/12/us/coronavirus-san-mateo-scott-morrow.html)
Anthony Costello, ex-Director at the World Health Organization. Professor, University College London

Nextdoor screenshots:
https://www.dropbox.com/s/pbyjwfmir7lhpoc/localPacficaNextDoor_1percent.png?dl=0
https://www.dropbox.com/s/z0rk643o9asl46t/localPacificaNextDoorPosts.png?dl=0

Nextdoor thread:
https://nextdoor.com/news_feed/?post=142178628

**Comment by albertsun** [comment]
Hi @btgalush,

You are correct that the true number of cases is higher than the number of positive confirmed cases reported.

We're keeping the GH issues to just discussion issues specific to the dataset released here.
