### ISSUE TITLE
Three SE Utah counties not up to date

### ISSUE THREAD

**Issue by kmgwalker** [nytimes/covid-19-data#530]
Grand, Emery and Carbon counties have results here: https://www.seuhealth.com/covid-19

But the NYT is not picking up these cases, as of a few days ago.  Perhaps the health dept. website changed its format?

**Comment by tiffehr** [comment]
Yes, they changed to a dashboard format we cannot easily read.  We programmatically and manually collect our data and this change moves these counties to manual collection, which takes us longer.  It will be updated today or tomorrow with their latest figures.
