### ISSUE TITLE
Enhancement: More frequent updates?

### ISSUE THREAD

**Issue by PatrickDRusk** [nytimes/covid-19-data#531]
Is there any chance you could run the update bot a bit more frequently? It would be really nice to see what updates there are by 8 or 9 PM EST, even if they aren't perfect. It seems like bot updates are timed to happen nearer to midnight.

**Comment by albertsun** [comment]
Thanks for the feedback. We'd like to publish faster but as the process that produces this data is mostly a human done process (the bot is merely the very last push) it is not simply a matter of turning up the frequency of bot updates. It's also our goal to publish data faster and we are always evaluating our workflow to see where we can improve.

**Comment by PatrickDRusk** [comment]
Thanks. The last few days seem to have been more frequent. You guys do a great job with this data.

Just wanted to know that there are some of us out here that go through withdrawals when there isn't a late evening drop of the data!

**Comment by nguyenhuyenchien85** [comment]
Vào 11:25, Th 7, 23 thg 1, 2021 Patrick Rusk <notifications@github.com> đã
viết:
