### ISSUE TITLE
Data Issue:  Missing New York Counties: Bronx, Kings, and Queens

### ISSUE THREAD

**Issue by davidjayjackson** [nytimes/covid-19-data#532]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- **_[ *] Missing data for a locality_**
- [ ] Missing time-series information
- [ ] Other

### Fuller details
Now I'm not that familiar New York State. But the counties listed in the subject line is missing?

Thanks,
David Jackson

**Comment by ddenenberg71** [comment]
Explained here: https://github.com/nytimes/covid-19-data#geographic-exceptions

**Comment by davidjayjackson** [comment]
Fantastic, Thanks so much.

David,

**Comment by davidjayjackson** [comment]
I understand now.
