### ISSUE TITLE
Data Issue:  New York Data? What happens if a county refuses a death?

### ISSUE THREAD

**Issue by davidjayjackson** [nytimes/covid-19-data#533]
### Describe the issue:
- [x] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
What happens if a county refuses a death that took place in another county, even if the dead person is from that county?

**Comment by lwaananenjones** [comment]
Is there a particular example you're looking at for this problem? In general, death certificates include both a person's location of residence and the location where the death occurred, so health departments have access to both locations. Most public data about Covid-19 deaths is reported by the location of residence, but New York is unique in categorizing deaths both ways on the [state's dashboard](https://covid19tracker.health.ny.gov/views/NYS-COVID19-Tracker/NYSDOHCOVID-19Tracker-Fatalities?%3Aembed=yes&%3Atoolbar=no&%3Atabs=n). 

We also know this is a reason it's fairly common for state and local health officials to report slightly different death counts for the same county. A person's location of residence is not always straightforward, or there are differences in how that information reaches state and local officials.

**Comment by Monesha67** [comment]
Incorrect on New York State cases and deaths toll. Cases:1444199   Deaths Toll: 43687 02/03/2021. Here’s the link to Worldometer website that have the correct information on Total Cases and Total Deaths. Thank You!
https://www.worldometers.info/coronavirus/usa/new-york/
