### ISSUE TITLE
Data Issue: Stay at home order easing date missing

### ISSUE THREAD

**Issue by corybaird** [nytimes/covid-19-data#534]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ &check;] Missing data for a locality
- [&check; ] Missing time-series information
- [ ] Other

### Python code to show missing data
`
url ="https://raw.githubusercontent.com/COVID19StatePolicy/SocialDistancing/master/data/USstatesCov19distancingpolicy.csv"
df_stayhome = pd.read_csv(url, encoding = "ISO-8859-1")
mask = (df_stayhome.StatePolicy=='StayAtHome') & (df_stayhome.StateWide==1)
df_stayhome = df_stayhome.loc[mask, ['StateName','StateWide','DateIssued', 'DateEnacted', 'DateExpiry', 'DateEased', 'DateEnded']]
df_stayhome['DateExpiry'] =df_stayhome.DateExpiry.combine_first(df_stayhome.DateEased).combine_first(df_stayhome.DateEnded)
df_stayhome.loc[df_stayhome.DateExpiry.isna(),:]
`

### Fuller details
- Missing dates for the DateExpiry, DateEased, DateEnded for a number of states that enacted statewide stay at home dummies.
- Kentucky, Maine, Nevada and Ohio do not have ending, expiring, or easing measures for statewide measures that were implemented in early spring.

**Comment by albertsun** [comment]
It looks like this issue would more properly directed to this repo https://github.com/COVID19StatePolicy/SocialDistancing/ as that is the file you are downloading and we are not publishing any data on stay at home orders.
