### ISSUE TITLE
Data Issue:  State of Indiana Deaths - large 1 day increase in Death Count

### ISSUE THREAD

**Issue by BAR-B-Q** [nytimes/covid-19-data#537]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [x] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources. Please check the README and recent commit messages for updates to see if your issue is addressed.
Total Deaths went from 10091 to 11637 (2/3/21 to 2/4/21).  Was there some reason for this large 1-day bump?  Or is the data suspect?

**Comment by BAR-B-Q** [comment]
Just saw this article that answers my own question:  https://www.indystar.com/story/news/health/2021/02/03/indiana-covid-19-deaths-cases-statewide-vaccine-appointment/4377868001/ 
Please close this issue.

**Comment by PatrickDRusk** [comment]
If it helps you at all, Indiana reports deaths by date of death at:
https://hub.mph.in.gov/dataset/6bcfb11c-6b9e-44b2-be7f-a2910d28949a/resource/7661f008-81b5-4ff2-8e46-f59ad5aad456/download/covid_report_death_date_agegrp.xlsx
Usual caveats that the most recent couple weeks are incomplete.

**Comment by albertsun** [comment]
Yep, we've noted this on our Indiana state page as well:
https://www.nytimes.com/interactive/2020/us/indiana-coronavirus-cases.html
