### ISSUE TITLE
Data Issue:  Yakima, WA showing large negative/positive cases for Feb 3 & Feb 4

### ISSUE THREAD

**Issue by charlesbrodhead3** [nytimes/covid-19-data#539]
### Describe the issue:
- [x] Suspicious number of cases or deaths

### Fuller details
The following is output from my code that processes your New York Times data.  Please note the large negative/positive cases for Feb 3 & Feb 4.
             state  county        date  population  **cases**  deaths  case_rate  death_rate     cases7d  deaths7d
919861  Washington  Yakima  2021-01-28      250873    184       1  10.097938    0.145891  100.857143  1.857143
919862  Washington  Yakima  2021-01-29      250873     82       2  10.130624    0.146688   94.857143  1.142857
919863  Washington  Yakima  2021-01-30      250873    152       0  10.191212    0.146688   97.285714  1.142857
919864  Washington  Yakima  2021-01-31      250873      0       0  10.191212    0.146688   97.285714  1.142857
919865  Washington  Yakima  2021-02-01      250873    235       0  10.284885    0.146688  114.571429  0.857143
919866  Washington  Yakima  2021-02-02      250873    120       0  10.332718    0.146688  119.428571  0.571429
919867  Washington  Yakima  **2021-02-03**      250873   **-866**       5   9.987524    0.148681  -13.285714  1.142857
919868  Washington  Yakima  **2021-02-04**      250873   **1138**       1  10.441140    0.149079  123.000000  1.142857

I didn't see any large changes on the following websites on those days:
https://www.yakimacounty.us/2404/Data-Summary
https://www.doh.wa.gov/Emergencies/COVID19/DataDashboard
(select Yakima county under the Epidemiologic Curves tab of the Dashboard)

Hope this helps!

**Comment by lwaananenjones** [comment]
Thank you for bringing this up. Our data for Yakima County comes from the county website, which had 25,056 cases displayed on Feb. 3. We think this is likely a typo that should instead be 26,056, and we're hoping county officials will confirm this. In the meantime, we've reverted the Feb. 3 count to match Feb. 2 to eliminate the decrease.
