### ISSUE TITLE
Question:  It looks that American Samoa now has COVID-19 Cases - but no Deaths.  When will American Samoa be added to the US States tables (as are Northern Mariana Islands, Guam,...) - or won't A. Samoa be added at all?  

### ISSUE THREAD

**Issue by BAR-B-Q** [nytimes/covid-19-data#541]
### Do you think there is an error in the data?
Please submit a Data Issue so it can be easily routed to the correct people.

### Do you have a question about the LICENSE or permission to use this data?
Please email us at covid-data@nytimes.com

### Your question
Please check to make sure your question is not answered in the README. It may have been updated since you first read it.

**Comment by tiffehr** [comment]
Thank you, we'll look into American Samoa's figures and sourcing.

**Comment by albertsun** [comment]
Hi @BAR-B-Q what source are you seeing those cases in? The cases we've seen reported so far have been reported among crew on container ships who have not been allowed to disembark their ships and we believe who are not residents of American Samoa.

**Comment by BAR-B-Q** [comment]
https://news.google.com/covid19/map?hl=en-US&mid=%2Fm%2F0h8d&gl=US&ceid=US%3Aen

**Comment by BAR-B-Q** [comment]
Also do a screen search "COVID-19 American Samoa" - added a PDF of the screen shot results - look at Cases Overview on right side of search/screen shot.
[American Samoa Screen Shot 2-11-21.pdf](https://github.com/nytimes/covid-19-data/files/5965365/American.Samoa.Screen.Shot.2-11-21.pdf)

**Comment by albertsun** [comment]
@BAR-B-Q thanks for those. It looks like Google is sourcing those cases to Wikipedia not us. We've seen the same reports but are not counting those cases because those crew members did not leave their ships, and they are not U.S. / American Samoa residents.

If there are cases on American Samoa itself among residents there, then those cases would be reported.
