### ISSUE TITLE
Can we trust the Covid19 Numbers?

### ISSUE THREAD

**Issue by davidjayjackson** [nytimes/covid-19-data#545]
### Do you think there is an error in the data?
Please submit a Data Issue so it can be easily routed to the correct people.

### Do you have a question about the LICENSE or permission to use this data?
Please email us at covid-data@nytimes.com

### Your question
Please check to make sure your question is not answered in the README. It may have been updated since you first read it.

**Comment by davidjayjackson** [comment]
The recent revelations about New York and Ohio shaving their death counts, raise the question can we trust the numbers?  TX David

**Comment by lwaananenjones** [comment]
Hi David, for the examples of New York and Ohio, do you mean how additional deaths have been announced recently, sometimes months after the deaths occurred? 

While the backlog from Ohio is the largest adjustment yet, we've seen lags and differences between states throughout the pandemic. We do watch carefully for unusual increases and decreases, and in most instances the causes are mundane. Most health records systems were not prepared for the volume or speed of data that has been required this year. There have been several large adjustments so far this year, which have mostly been related to end-of-the-year audits or officials catching up after holiday breaks.

The [National Center for Health Statistics](https://www.cdc.gov/nchs/nvss/covid-19.htm) will ultimately be the final source for the number of deaths, and though that system takes time, it is well-established with clear guidance for coroners and medical examiners about how to report cause of death. Most states have moved toward using death certificates as the primary source for the public counts. Public health researchers and officials also use "excess deaths" as another measure to check for underreporting, so we frequently [publish articles](https://www.nytimes.com/interactive/2021/01/14/us/covid-19-death-toll.html) with that data as well.

**Comment by davidjayjackson** [comment]
Thanks for your comments, they are very helpful.
