### ISSUE TITLE
Iowa Cases all going unknown

### ISSUE THREAD

**Issue by gellingson16** [nytimes/covid-19-data#546]
Iowa changed their case reporting again, and all new cases are hitting the unknown county.

**Comment by albertsun** [comment]
Iowa has changed to only report positive tests for each county, not unique individuals who have tested positive. Because they are not doing this de duplication we do not have a way to assign actual individual cases to counties at the moment.

**Comment by zshe3** [comment]
This note (https://www.nytimes.com/interactive/2020/us/iowa-coronavirus-cases.html#anomaly-notes) says that "Data on new cases by county for Iowa are missing from Feb. 20 to Feb. 24, 2021".

I infer that data reporting in Iowa is back to normal now.

**Comment by albertsun** [comment]
@zshe3 Ah yes, thank you for the reminder to update the note here as well.
