### ISSUE TITLE
Data Issue:  Missing data for Imperial County, California - week of 2/20

### ISSUE THREAD

**Issue by rpascua1** [nytimes/covid-19-data#547]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [X] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
Zero cases reported since 2/20/21.  Thank you!

**Comment by tiffehr** [comment]
Thank you.  Looking into it.  I do indeed see a discrepancy between the state's Tableau dashboard figures over that time and our CSV.

**Comment by tiffehr** [comment]
The county's dashboard has been reporting the same data for a few days now, `24.615` cases.
https://www.icphd.org/health-information-and-resources/healthy-facts/covid-19/covid-19-data/

Although the last-updated timestamp reports it was last changed 2/25/2021, in fact the county AND state's data stopped cumulating for Imperial on 2/20.  They may be changing to weekly updates, without much warning.  We'll know in a few days when we hit the one week mark, perhaps.
