### ISSUE TITLE
Data Issue:  Pueblo County

### ISSUE THREAD

**Issue by allisonletts** [nytimes/covid-19-data#548]
### Describe the issue:
- [X] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
Pueblo County, CO reports 63 cases for the week of February 12. NYT reports 266 cases for the **day** of February 12. 
Source:
https://county.pueblo.org/public-health/pueblo-county-covid-19-case-data

**Comment by allisonletts** [comment]
![image](https://user-images.githubusercontent.com/17914696/109231696-0a34d880-7795-11eb-9618-0fd1b52e83d0.png)

**Comment by tiffehr** [comment]
Thank you, looking into it.
