### ISSUE TITLE
Data Issue:  2/27/21

### ISSUE THREAD

**Issue by MntGoat76** [nytimes/covid-19-data#549]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [X] Other

### Fuller details
The risk level of Oregon is out of date. The state changed the levels of 16 counties this week including Washington, Clackamas, and Hood River.
The complete and official list for counties is published by the state here: https://public.tableau.com/profile/oregon.health.authority.covid.19#!/vizhome/OregonCountiesCOVID-19RiskLevelsSummaryTable/SummaryTable

**Comment by tiffehr** [comment]
Thank you for the heads up.  We are not using the state's own risk-level projections.  They will differ.

Mind providing the page on which you look for Oregon data?  We have a [state summary page](https://www.nytimes.com/interactive/2020/us/oregon-coronavirus-cases.html), but also the individual counties, e.g. [Umatilla](https://www.nytimes.com/interactive/2021/us/umatilla-oregon-covid-cases.html).  The per-county pages explain a lot more about our risk calculations:

![image](https://user-images.githubusercontent.com/60173/109399556-c363f180-7900-11eb-8833-db7647cb664e.png)

**Comment by MntGoat76** [comment]
I think this may be your best bet:

https://govstatus.egov.com/OR-OHA-COVID-19

It has a link to county data and also a link to Oregon's covid dashboards in Tableau.

If you need something different or more, I am happy to see what I can find for you.

Thank you for your valuable service during the public health crisis!

**Comment by tiffehr** [comment]
Thank you. Again, we're not using the state's own sources for our assessments.  But I'll relay this link to our team if they want to check their work.
