### ISSUE TITLE
REST API for CSV

### ISSUE THREAD

**Issue by desholmes** [nytimes/covid-19-data#55]
Thanks nytimes for gathering the data ❤️

I've created a simple REST API which loads the raw CSV files directly from this repo. The usage guide, hosted public API links and code is available here: [https://github.com/desholmes/covid-19-us-api](https://github.com/desholmes/covid-19-us-api).

I've also been [helping out](https://github.com/tomwhite/covid-19-uk-data/pull/7) with the automation of [tomwhite's](https://github.com/tomwhite) UK data gathering efforts, let me know if I can help nytimes out too.

**Comment by WeileiZeng** [comment]
https://covapi.herokuapp.com/

https://github.com/digiphilo/covid

a similar api project

**Comment by Kunal614** [comment]
> Thanks nytimes for gathering the data heart
> 
> I've created a simple REST API which loads the raw CSV files directly from this repo. The usage guide, hosted public API links and code is available here: https://github.com/desholmes/covid-19-us-api.
> 
> I've also been [helping out](https://github.com/tomwhite/covid-19-uk-data/pull/7) with the automation of [tomwhite's](https://github.com/tomwhite) UK data gathering efforts, let me know if I can help nytimes out too.

Sir what you api will return?

**Comment by desholmes** [comment]
> > Thanks nytimes for gathering the data heart
> > I've created a simple REST API which loads the raw CSV files directly from this repo. The usage guide, hosted public API links and code is available here: https://github.com/desholmes/covid-19-us-api.
> > I've also been [helping out](https://github.com/tomwhite/covid-19-uk-data/pull/7) with the automation of [tomwhite's](https://github.com/tomwhite) UK data gathering efforts, let me know if I can help nytimes out too.
> 
> Sir what your api will return?

Currently, the REST API returns the CSV files in this repo in JSON format with an optional `date` query string filter. There are links to the hosted API in the README.md of the [desholmes/covid-19-us-api](https://github.com/desholmes/covid-19-us-api) repo.

**Comment by Li357** [comment]
Just created a GraphQL API for the data as well, and joins with US Census data for county and state population estimates: https://github.com/Li357/covid-nyt-api
