### ISSUE TITLE
Enhancement: More data types.

### ISSUE THREAD

**Issue by Quantalabs** [nytimes/covid-19-data#552]
### Is your feature request related to a data problem?
Please submit a Data Issue so it can be easily routed to the correct people.

**No, it isn't a data issue.**

### Describe the feature you would like to see
A clear and concise description of what you want to see within our data sets

**I think that adding more statistics, such as the amount of recovered people, to the dataset is useful. Also adding additional cases rather than the total amount of cases is useful for dashboards being made with this data.**

### Describe alternatives you've considered
Please describe alternative solutions or features you've considered.

**None**

**Comment by tiffehr** [comment]
Recovered figures — from state or federal sources — is a highly imprecise figure. In most cases, it is reported as the difference between known positive tests and current cases.  There is no consistent methodology or way to check the numbers and it under-counts the number of people who caught covid-19 but never had tests or medical treatment.  

For these reasons, no data collection effort has used visible recovery figures.  We will not be adding it here.  And we have not routinely collected it either way.

We have a Project board with forks of this dataset, some of which offer additional cases broken out, if I recall correctly.  I recommend looking at the community resources on the Project board for a fork that has what you need.  A few past Issues also requested this figure and had discussion about the correct approach on your own calculation.
