### ISSUE TITLE
Data Issue:  

### ISSUE THREAD

**Issue by chem-geek** [nytimes/covid-19-data#554]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [X ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
New cases for Rhode Island on 3/5/21 seems anomalously high, increasing by a factor of 5 in a single day.

**Comment by lwaananenjones** [comment]
Could you share a little more about where you're seeing this problem and the numbers? I'm seeing 127,727 on 3/4 and 128,121 on 3/5, for an increase of 394, which is in line with the current 7-day average.

**Comment by chem-geek** [comment]
Yes I am unable to reproduce the error now. I downloaded the data and had over 500,000 for 3/5.

**Comment by tiffehr** [comment]
@chem-geek Downloaded the data from what source?
