### ISSUE TITLE
Data Issue:  Yakima County, WA no new cases for several days

### ISSUE THREAD

**Issue by khorton** [nytimes/covid-19-data#558]
### Describe the issue:
Suspicious number of cases or deaths

### Fuller details
The last increase for Yakima County,  WA in the data set is on 3/14.  The Yakima Herald newspaper has made several daily reports since then totally roughly 450 additional cases, so it seems quite unlikely that the NYT data is up to date.

**Comment by tiffehr** [comment]
The nitty-gritty is that they had a data-entry error that persisted for ~2 days.  The diagnostics on our end (a script that reads their HTML source) reported:
```
Integer "3,67" does not have the syntax for a number for confirmed cases
```

Earlier today they corrected the typo and our data-collection was able to resume.  We have had gaps in our data collection like this many times.  We cannot guess the missing digits, even in the trend-line.
