### ISSUE TITLE
Data Issue: Oklahoma no longer providing daily updates 

### ISSUE THREAD

**Issue by GhjNat** [nytimes/covid-19-data#559]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [x] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
The Oklahoma State Department of Health (OSDH) has moved to weekly reporting of data, and daily counts for counties may no longer be available for dates after March 16, 2021. The case counts by county here (https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html?name=styln-vaccines-combo&region=TOP_BANNER&block=storyline_menu_recirc&action=click&pgtype=Interactive&impression_id=&variant=1_Show) are therefore inaccurate.  

Here's the OSDH press release announcing the change:
https://oklahoma.gov/covid19/newsroom/2021/march/osdh-makes-updates-to-online-dashboard-of-covid-19-data.html

It is unclear at this point what kind of daily data will be available going forward in the weekly surveillance reports.

**Comment by tiffehr** [comment]
Yes, we're aware and working from alternative sources.  We'll only remove our OK county data if we cannot find another valid source, from a number of options.  Other states or counties are paced to be weekly, in which case we update our figures when they change.
