### ISSUE TITLE
Data Issue: TriCounty Utah (Uintah, Duchesne, Daggett) not updating

### ISSUE THREAD

**Issue by TomGoBravo** [nytimes/covid-19-data#560]
### Describe the issue:
- [X] Incorrect number of cases or deaths

### Fuller details
There are still cases every week (see https://tricountyhealth.com/local-covid-update/) but us-counties isn't changing:

<details>

```
$ csvgrep -c fips -r '49(009|013|047)' data/cases-nytimes/us-counties.csv  | csvgrep -c date -r '2021-03-(2|1)' |csvsort -c fips,date | csvlook 
|       date | county   | state |   fips | cases | deaths |
| ---------- | -------- | ----- | ------ | ----- | ------ |
| 2021-03-10 | Daggett  | Utah  | 49,009 |    37 |      0 |
| 2021-03-11 | Daggett  | Utah  | 49,009 |    37 |      0 |
| 2021-03-12 | Daggett  | Utah  | 49,009 |    37 |      0 |
| 2021-03-13 | Daggett  | Utah  | 49,009 |    37 |      0 |
| 2021-03-14 | Daggett  | Utah  | 49,009 |    37 |      0 |
| 2021-03-15 | Daggett  | Utah  | 49,009 |    37 |      0 |
| 2021-03-16 | Daggett  | Utah  | 49,009 |    37 |      0 |
| 2021-03-17 | Daggett  | Utah  | 49,009 |    37 |      0 |
| 2021-03-18 | Daggett  | Utah  | 49,009 |    37 |      0 |
| 2021-03-19 | Daggett  | Utah  | 49,009 |    37 |      0 |
| 2021-03-20 | Daggett  | Utah  | 49,009 |    37 |      0 |
| 2021-03-21 | Daggett  | Utah  | 49,009 |    37 |      0 |
| 2021-03-10 | Duchesne | Utah  | 49,013 | 1,217 |      9 |
| 2021-03-11 | Duchesne | Utah  | 49,013 | 1,217 |      9 |
| 2021-03-12 | Duchesne | Utah  | 49,013 | 1,217 |      9 |
| 2021-03-13 | Duchesne | Utah  | 49,013 | 1,217 |      9 |
| 2021-03-14 | Duchesne | Utah  | 49,013 | 1,217 |      9 |
| 2021-03-15 | Duchesne | Utah  | 49,013 | 1,217 |      9 |
| 2021-03-16 | Duchesne | Utah  | 49,013 | 1,217 |      9 |
| 2021-03-17 | Duchesne | Utah  | 49,013 | 1,217 |      9 |
| 2021-03-18 | Duchesne | Utah  | 49,013 | 1,217 |      9 |
| 2021-03-19 | Duchesne | Utah  | 49,013 | 1,217 |      9 |
| 2021-03-20 | Duchesne | Utah  | 49,013 | 1,217 |      9 |
| 2021-03-21 | Duchesne | Utah  | 49,013 | 1,217 |      9 |
| 2021-03-10 | Uintah   | Utah  | 49,047 | 1,757 |     17 |
| 2021-03-11 | Uintah   | Utah  | 49,047 | 1,757 |     17 |
| 2021-03-12 | Uintah   | Utah  | 49,047 | 1,757 |     17 |
| 2021-03-13 | Uintah   | Utah  | 49,047 | 1,757 |     17 |
| 2021-03-14 | Uintah   | Utah  | 49,047 | 1,757 |     17 |
| 2021-03-15 | Uintah   | Utah  | 49,047 | 1,757 |     17 |
| 2021-03-16 | Uintah   | Utah  | 49,047 | 1,757 |     17 |
| 2021-03-17 | Uintah   | Utah  | 49,047 | 1,757 |     17 |
| 2021-03-18 | Uintah   | Utah  | 49,047 | 1,757 |     17 |
| 2021-03-19 | Uintah   | Utah  | 49,047 | 1,757 |     17 |
| 2021-03-20 | Uintah   | Utah  | 49,047 | 1,757 |     17 |
| 2021-03-21 | Uintah   | Utah  | 49,047 | 1,757 |     17 |
```

</details>

I can't find anything about a known problem at https://www.nytimes.com/interactive/2021/us/uintah-utah-covid-cases.html or https://www.nytimes.com/interactive/2020/us/utah-coronavirus-cases.html or https://github.com/nytimes/covid-19-data#geographic-exceptions

**Comment by lwaananenjones** [comment]
Thank you for bringing this up. The TriCounty Health Department [stopped reporting cumulative county numbers on Feb. 12](https://tricountyhealth.com/changes-to-tchd-local-covid-19-update/). Many counties have stopped reporting updated counts as they transfer resources to vaccination efforts, but Utah is unique because the state dashboard includes cumulative counts by health district rather than by county. We've been in touch with the state and assessing other data sources, and right now we have a promising option for getting this data restored for these three counties and some others in Utah where the local health district is no longer updating as frequently. I'll post an update once we have that updated and reconciled with our existing data.

**Comment by lwaananenjones** [comment]
Circling back: We are now getting daily counts for Duchesne, Daggett and Uintah from the state, and we revised the time series for these states back to Feb. 13 for a clean transition. The state reports about the same total number as the health district did, but splits up the cases differently, so this results in a jump for Uintah on Feb. 13 and a decrease for Duchesne. We're assessing whether a similar change would be useful for other Utah counties now that some health districts aren't reporting as frequently as they used to.
