### ISSUE TITLE
Enhancement: Vaccine Information?

### ISSUE THREAD

**Issue by jegpeek** [nytimes/covid-19-data#563]
Could the data that went into the creation of this county-level map:

https://www.nytimes.com/interactive/2020/us/covid-19-vaccine-doses.html

be added to this repo? Or is it available elsewhere?

**Comment by tiffehr** [comment]
It's available here:  https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=vaccination_county_condensed_data
