### ISSUE TITLE
Data Issue:  Ohio is Missing Some Deaths between 2021-03-03 - 2021-02-27

### ISSUE THREAD

**Issue by davidjayjackson** [nytimes/covid-19-data#564]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [x] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
Ohio Didn't record any deaths for: 
3/04 - 0/04, 
3/06 - 03/08, 
03/10 - 03/11, 
03/13 - 03/15, 
03/17 - 03/18, 
03/20 - 03/22
03/24 - 03/25
03/27

**Comment by lwaananenjones** [comment]
That's correct — Ohio is no longer announcing deaths on a daily schedule. At the beginning of March, the state transitioned to a different system for tallying deaths based on death certificates. Here is a portion from the state's March 2 press release:

> In addition, mortality data will no longer be reported daily. Updated death certificate data is typically sent to the Ohio Department of Health twice per week, and may lag – often 1-2 months, but up to 6 months. On dates that data is not reported to the Ohio Department of Health, deaths will remain static on the COVID-19 dashboards. For the foreseeable future, mortality information will not be updated on specific days of the week. Case and other data will continue to be reported through ODRS on its current schedule.

**Comment by davidjayjackson** [comment]
Does that mean (for instance) that the 3/06 - 03/08, March 9 will be a total for Mar. 6 -9?
