### ISSUE TITLE
Splitting the main CSV data file

### ISSUE THREAD

**Issue by peterdaytx** [nytimes/covid-19-data#568]
I've kluged together a simple Win10 VBScript to split the giant CSV file into a user-selected CSV chunk... It's handling the current 47M file quite nicely... The input and output data filenames and location were left hard-coded to my desktop (sorry!), but all you need is a simple text editor to fix that...
[NYTExtract_v4.zip](https://github.com/nytimes/covid-19-data/files/6306494/NYTExtract_v4.zip)

**Comment by tiffehr** [comment]
@peterdaytx Thank you!  Adding to our Project board collection of public resources.
