### ISSUE TITLE
Data Issue:  us-counties/etc. not updated with April 16 data.

### ISSUE THREAD

**Issue by ddenenberg71** [nytimes/covid-19-data#569]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [X] Missing time-series information
- [ ] Other

### Fuller details
Just a heads-up in case you're not already aware: the us-counties/us-states/us files were not updated like they normally are around 2:20AM ET every day.  April 16 data is missing.  Thanks.

**Comment by cfhp1** [comment]
@albertsun, you have helped us in the past with late updates so I wanted to make you aware of this one. Thanks so much for continuing to provide an excellent data source.

**Comment by albertsun** [comment]
@ddenenberg71 @cfhp1 These are updated now, apologies, something went awry with the automation with the new files we added.

**Comment by cfhp1** [comment]
@albertsun, you are wonderful, thank you!

**Comment by ddenenberg71** [comment]
Thanks. I see the updates now.
