### ISSUE TITLE
Data contradicts other data sources?

### ISSUE THREAD

**Issue by achadwicklvs** [nytimes/covid-19-data#57]
Why is this data so incredibly skewed from other data sources such as https://www.worldometers.info/coronavirus/country/us/ or https://coronavirus.jhu.edu/map.html ? I'm not so certain of the data's correctness. If this data is to be believed, it's showing that there are 375007 cases in the United States, which directly contradicts the data sources listed above. Can we get confirmation on the accuracy of this data or at least a list of sources other than "journalists"?

**Comment by daveroush** [comment]
totally agree.  this data is not yet trustworthy

**Comment by stsievert** [comment]
Here are some numbers for March 25th:

* NYTimes: 35,450
* John Hopkins: 65,292
* Worldometers: 68,211

For March 24th:

* NYTimes: 28,273
* John Hopkins: 53,406
* Worldometers: 54,856

**Comment by daveroush** [comment]
those are big discrepancies!

**Comment by stsievert** [comment]
Whoops, I made a typo. I've updated https://github.com/nytimes/covid-19-data/issues/57#issuecomment-605470650 to reflect the numbers; the difference is a lot smaller now.

**Comment by albertsun** [comment]
@achadwicklvs @daveroush this data set is not intended to be an up to the moment count of the number of current cases in the U.S. like those pages. For that please see our map page on the nytimes.com web site here. https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html

This data is a periodic release of numbers for past days. I'm also not sure how are you getting 375007 cases. A sum over areas for the last day we have released data, 3/26, shows just about 85 thousand cases.

Small discrepancies between different data sources for the total summed number of cases are to be expected for any given day given different methodologies for counting and different schedules for updating numbers.

If there are specific instances of numbers where it appears we've made an error, please do raise those and we will investigate.

**Comment by dishserv** [comment]
FWIW, Johns Hopkins Center for Health Security stated in their Situation Reports on March 19, 20, 23, 24 and 25, "The New York Times is compiling national-level COVID-19 incidence data to track the epi curves in real time."  http://www.centerforhealthsecurity.org/resources/COVID-19/COVID-19-SituationReports.html

However, they stopped referencing the New York Times data beginning with their Situation Report on March 26.

**Comment by achadwicklvs** [comment]
@albertsun My apologies, I was not aware that the data shown was cumulative based off of the date. I assumed the data showed new cases per day.
