### ISSUE TITLE
Data Issue:  us/states/counties csv not updated, again

### ISSUE THREAD

**Issue by ddenenberg71** [nytimes/covid-19-data#570]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [X] Missing time-series information
- [ ] Other

### Fuller details
Heads-up: There haven't been any updates to any of the files (cumulative files, live files) since the manual updates around 11AM ET yesterday (Saturday April 17).

**Comment by cfhp1** [comment]
@albertsun, are you able to help us again?

**Comment by mikelehen** [comment]
Any ETA on today's data update?  Thanks!

**Comment by dawenx** [comment]
@albertsun Hope everything is good. I know it's weekend, appreciate very much if you could give an ETA on next update.

**Comment by albertsun** [comment]
Hi guys, our apologies, we're looking into this and will have an update shortly.

**Comment by Pedro-McM** [comment]
Thanks!

**Comment by cfhp1** [comment]
I appreciate your help, @albertsun. Glad to have the data.

**Comment by albertsun** [comment]
Today's update is done manually again.

To give everyone a bit of a heads up as well, starting today and going forward we're going to be changing the update schedule of this repo to move our daily update up by several hours to the late evening each day, before midnight. At that point the data for each day will be final.

**Comment by mikelehen** [comment]
Thanks @albertsun!
