### ISSUE TITLE
Vaccine reluctance data

### ISSUE THREAD

**Issue by rguttersohn** [nytimes/covid-19-data#571]
Will the county-level vaccine reluctance data synthesized from the Household Pulse Survey be shared in this repo? [First spotted here.](https://www.nytimes.com/interactive/2021/04/17/us/vaccine-hesitancy-politics.html)

**Comment by tiffehr** [comment]
Sorry, no it won't.  We recommend getting the figures from the [Household Pulse Survey](https://www.census.gov/programs-surveys/household-pulse-survey/data.html) itself.
