### ISSUE TITLE
This is probably what the state of MISSOURI is reporting, but cases went down from 4/16 (595,499) to 4/17 (588,373)

### ISSUE THREAD

**Issue by MirrorCola** [nytimes/covid-19-data#572]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources. Please check the README and recent commit messages for updates to see if your issue is addressed.

**Comment by albertsun** [comment]
Hi @MirrorCola, yep this is due to Missouri removing many duplicate cases. We are now noting this kind of anomaly in its own CSV file over here https://github.com/nytimes/covid-19-data/blob/master/rolling-averages/anomalies.csv#L422
