### ISSUE TITLE
Data Issue: St. Charles County, MO

### ISSUE THREAD

**Issue by chris-prener** [nytimes/covid-19-data#574]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [x] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
On 2021-04-23, there was a change in your data for St. Charles County, Missouri (GEOID 29183). The potentially anomalous change occurs on 2021-01-11. As of the 22nd, the NYTimes data reported 174 new cases for January 11th. However, on the 23rd the number of new cases reported on January 11th switched to 5175. The number of new cases for the following days also had a significant change.

**Comment by lwaananenjones** [comment]
That's correct. Our dataset includes probable cases where available, and St. Charles County [began reporting probable cases on Jan. 11](https://www.facebook.com/StCharlesCountyPublicHealth/photos/1582417201962649). It took us some time to put this in place, but we then revised the time series to include the probable cases as far back as available.

Our new [rolling averages data](https://github.com/nytimes/covid-19-data/tree/master/rolling-averages) also includes our list of anomalies, such as this one, to make those explanations easier to access.

**Comment by chris-prener** [comment]
Thanks for clarifying @lwaananenjones - and sorry I missed it on the anomalies list...
