### ISSUE TITLE
Data Issue:   Arkansas deaths drop by 174 on 2/28/2021

### ISSUE THREAD

**Issue by bradnemetski** [nytimes/covid-19-data#575]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [X ] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources. Please check the README and recent commit messages for updates to see if your issue is addressed.

It seems suspicious that the numbers drop from 5417 to 5243 on 2/28/2021

**Comment by tiffehr** [comment]
Arkansas posted about this at the time.  [Tweet, Feb 28th, afternoon ET](https://twitter.com/adhpio/status/1366163333225799682?s=21)
> A data clean-up is reflected in today's reports. Some deaths have been reclassified and duplicates were removed. 288 new cases are added today. The remaining 2,932 additional cases occurred prior to February 14, 2021
