### ISSUE TITLE
Enhancement:  Daily Case and Death Counts by County

### ISSUE THREAD

**Issue by dkeeshin** [nytimes/covid-19-data#578]
For the past year my company kDS, LLC has sourced  data from 

https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv  

to populate US County data for a COVID 19 data tracking solution that we built. For details see

http://keeshinds.com/blog/kDSBlog20200610.html

Recently we decided to the publish the data as CSV files on our github site at:

https://github.com/dkeeshin/covid19datavault/tree/master/data

Our version of the data are CSV files partitioned by month. The current year-month file is updated nightly. No changes are made to previous months.  You can tell what each year-month file contains by the year-month combination at the end of the file name. For example, the file name for April 2021 data looks like this:

002MonthlyUSCounTY202104.csv

Additionally, we enhanced the data . County names are checked against the US Census version of the name. We created a processes that assigns latitude and longitude to FIPS numbers per the US Census data. Another process assigns region, subregions and county populations per US Census data.  

The NYTIMES data does not provide a daily change number. As a result we created case_count_to_date and previous_case_count_to_date columns to store  tallies of the inception to date totals. The only way to find the daily case count is to subtract the previous_case_count_to_date total from the case_count_to_date total.  Same holds true for the previous_death_count_to_date and death_count_to_date. 

It would be helpful to have historical US county data that contains daily totals and not tallies of inception to date data. And perhaps also include the US Census data mentioned above.

Regards,

David Keeshin
Chief Database Architect
Keeshin Database Services, LLC

**Comment by dkeeshin** [comment]
update

**Comment by tiffehr** [comment]
Thank you for the information about your data set.  We are not expanding our cumulative counts to include the calculation of daily, stand-alone figures.  We'll share your data set with the community here, via our Project board, as one of the Alternative Formats the community has built.

**Comment by dkeeshin** [comment]
Thank you for the update.
