### ISSUE TITLE
Data Issue:  

### ISSUE THREAD

**Issue by JamesJohnCoyle** [nytimes/covid-19-data#579]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [x ] Other

### Fuller details
Was data discontinued on April 4? Also noted changes in text quality subsequent to March 14. Any explanation?

**Comment by albertsun** [comment]
Hi @JamesJohnCoyle data has not been discontinued. We are still updating regularly. I'm also a little unclear as to what you mean by changes in text quality. Could you say a little more about what you are looking at?

**Comment by JamesJohnCoyle** [comment]
Albert,
I was in error.  I believe the problem was a notepad limitation.  I was opening the download in notepad which had worked for until March without issue.  Downloading the link rather than opening up directly into notepad corrected the issue.
James Coyle


    On Tuesday, May 4, 2021, 04:42:56 PM EDT, Albert Sun ***@***.***> wrote:  
 
 


Hi @JamesJohnCoyle data has not been discontinued. We are still updating regularly. I'm also a little unclear as to what you mean by changes in text quality. Could you say a little more about what you are looking at?

**Comment by tiffehr** [comment]
@JamesJohnCoyle Thanks for clarifying what you were seeing!  Around March, our data set exceeded the limits of a number of apps folks use to view the files.  Can't be helped, given the source.  But some apps don't throw particularly clear errors.

I hope the full feed meets your expectations, now.

**Comment by JamesJohnCoyle** [comment]
Thanks for quick feedback.  This data has been enormously illuminating.  I am a geographer (formerly US Census Bureau, now unaffiliated).  I have been using this data to calculate location quotients at county and state level.  Location quotients (LQ) are geographical statistic that compares the local mean to a more universal mean.  With respect to covid, I am looking at 2 week case and death rates standardized per 100K and comparing both county rates to national mean and state means to national mean.  Today, Northampton County, North Carolina (FIPS 37131),  with 16 deaths over the past 2 weeks has 28x the national death rate. St. Clair County, Michigan, with a much larger population base (159,128) has 11.3 times the national mean. These are places where public health measures are failing.
Thanks again.
James Coyle



    On Wednesday, May 5, 2021, 12:36:51 AM EDT, Tiff Fehr ***@***.***> wrote:  
 
 


@JamesJohnCoyle Thanks for clarifying what you were seeing! Around March, our data set exceeded the limits of a number of apps folks use to view the files. Can't be helped, given the source. But some apps don't throw particularly clear errors.

I hope the full feed meets your expectations, now.
