### ISSUE TITLE
Maryland data does not fit with official state data

### ISSUE THREAD

**Issue by jaahumadap** [nytimes/covid-19-data#58]
According to the NYT file, there are 581 cummulative confirmed cases as of 3/26/20, but the official MD data [here](https://coronavirus.maryland.gov/#Resources) is reporting 992! The smaller number is also being reported in the JHU files, but it worries me about underlying errors in JHU's files. Is NYT using other sources?

**Comment by daveroush** [comment]
The data sources, all of them, should be documented and added to a data flow diagram

**Comment by jimAlabama** [comment]
It does fit.  Think about the number of cases per day, when the link you posted updates the number of cases, and when the data here are updated. When you posted your issue, the dates were off by more than a day.

**Comment by albertsun** [comment]
Hi @jaahumadap 

We do use the numbers from the official Maryland data, but this repo is not going to have the most up to date numbers.

The data we’re releasing on GitHub is a periodic release of cases and death numbers for full past days of reporting. For our most up-to-date published numbers, please instead see our maps page on The New York Times website: https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html

If you are interested in a specific place, local official sources are the most likely to have the latest numbers. We do not update our numbers instantaneously.
