### ISSUE TITLE
Data Issue:  Suspicious cases missing / drop-off for Essex County, NJ

### ISSUE THREAD

**Issue by mikelehen** [nytimes/covid-19-data#581]
### Describe the issue:
- [X] Incorrect number of cases or deaths
- [X] Suspicious number of cases or deaths

### Fuller details
![image](https://user-images.githubusercontent.com/206364/118017081-0849d280-b30b-11eb-8ae0-7e9b243ceacd.png)

Based on https://essexcountynj.org/covid-19-municipality/ it seems like they have at least 100 new cases, but maybe that'll come through in tonight's update?

**Comment by tiffehr** [comment]
Our source for NJ county data is (in part), their Tableau dashboard embedded here:  https://dashboards.doh.nj.gov/views/DailyConfirmedCaseSummary7_22_2020/PCRandAntigenPositives?:embed=y

Filtering to Essex, we see much the same slope as our graph that you screengrabbed.  We do not take their daily new-cases figures, but the cumulative total which remains slowly growing.  If the county has reported new cases, they have not yet relayed that to the state health department.

Please confirm tomorrow or the next day that the revised _cumulative_ total went up as you expect from the county's figures?

**Comment by mikelehen** [comment]
Thanks for looking into it.  It's pretty hard to compare but the trend seems stable at least.  I never did see 100 new cases come through in a single day, so I'm not sure what exactly was going on with the county-reported data, but since there's no timeseries / graph for the county-reported data it's hard to compare.  As of right now, the state-reported cumulative is 84121 vs the county-reported cumulative of 84059.  

But overall the trend looks stable and relatively credible, so I guess I'll assume it's right. 🤷
