### ISSUE TITLE
Data Issue: Daily us-counties/us-states/us updates missing for 5/13

### ISSUE THREAD

**Issue by ddenenberg71** [nytimes/covid-19-data#582]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [X] Missing time-series information
- [ ] Other

### Fuller details
Just a heads-up if not already known: the daily us-counties/us-states/us.csv updates for 5/13 haven't been committed yet.  Thanks.

**Comment by albertsun** [comment]
Should be updated now!

**Comment by ddenenberg71** [comment]
Thanks.  Yes, I see the new commit.
