### ISSUE TITLE
Question:  no more end of day update?

### ISSUE THREAD

**Issue by dawenx** [nytimes/covid-19-data#586]
Thanks for maintaining this great data product. It looks like recent updates are not regular and I'm wondering whether end of day update is provided daily.

**Comment by mikelehen** [comment]
From my perspective it has been pretty regular, but it looks like yesterday's EOD update hasn't happened yet.  cc/ @albertsun in case they can help.

**Comment by cfhp1** [comment]
> From my perspective it has been pretty regular, but it looks like yesterday's EOD update hasn't happened yet. cc/ @albertsun in case they can help.

A couple have been late. I was wondering the same. Thanks for tagging @albertsun, who has bailed us out many times after late updates.

**Comment by albertsun** [comment]
Hi folks. We've been running into some trouble with the size of the files in the update each day causing the automated `git push` to fail. We're looking into some solutions and will update in the meantime.

**Comment by dawenx** [comment]
@albertsun thanks for your help!!! feel free to close this issue if you want.

**Comment by dawenx** [comment]
@albertsun looks like there's no EOD update for 05/23 yet. can you help?

**Comment by cfhp1** [comment]
> @albertsun looks like there's no EOD update for 05/23 yet. can you help?

@dawenx, it's just been updated.

We really depend on NYT! Thanks NYT team and @albertsun in particular.

**Comment by dawenx** [comment]
@albertsun we need your help again for EOD update of 05/24, thanks

**Comment by dawenx** [comment]
Thanks for updating data for 05/24

**Comment by tiffehr** [comment]
Leaving this open for tomorrow, at least until we work out our improved data-uploading solution.

**Comment by dawenx** [comment]
@tiffehr @albertsun looks like EOD update for 05/25 was not successful

**Comment by albertsun** [comment]
It's coming shortly.

**Comment by tiffehr** [comment]
@dawenx Confirm you see the latest?

**Comment by dawenx** [comment]
Looks like EOD update for 05/26 was successful! @tiffehr @albertsun

**Comment by albertsun** [comment]
Hopefully this issue is settled now. Going to close this one for now. Thank you as always for your close watch.

**Comment by dawenx** [comment]
@albertsun there's no EOD update for 05/29

**Comment by dawenx** [comment]
need your help again, there's no EOD update for 06/01 @albertsun

**Comment by albertsun** [comment]
@dawenx it's coming within the hour

**Comment by dawenx** [comment]
Thanks @albertsun

Since it happened twice after the issue was closed, I'm wondering whether the underlying problem has been solved or not

**Comment by tiffehr** [comment]
@dawenx The underlying problem is an emergent ceiling on the size of file that we're trying to `git push` to GitHub, as @albertsun noted earlier in the thread.  Our file-creation pipeline is time-tested and performing fine.  We'll continue to figure out how to work around this new constraint.

**Comment by dawenx** [comment]
@albertsun looks like we need your help for EOD update for 06/03, thanks

**Comment by albertsun** [comment]
@dawenx it's updated now.

We're aware of those issue and will continue to monitor and try to make our updates as regular as possible.
