### ISSUE TITLE
Example: Movie of USA COVID-19 Trend 

### ISSUE THREAD

**Issue by peterdaytx** [nytimes/covid-19-data#588]
Attached is a RAR'ed MP4 movie showing how COVID evolved in the USA... [Original MP4 was over 10MB and couldn't be posted. ZIP didn't compress it significantly: RAR did...] To view the movie, the file [https://user-images.githubusercontent.com/64326612/119410014-c5dea900-bcad-11eb-929a-0ca1f0f95e51.mp4] needs to be downloaded, the .MP4 stripped from the file name, and replaced with .RAR -- then the file can be decompressed!

https://user-images.githubusercontent.com/64326612/119410014-c5dea900-bcad-11eb-929a-0ca1f0f95e51.mp4

The USA and each State/Territory is shown as a 3-bar "Flag":
- Top bar:
   - Name of the entity
   - Intensity of the color-bar indicates the population: dark-blue for the most populous
   - The "legend" at the bottom of the screen shows the color-scaling for each of the 3 bars: 
        The maximum and minimum values for the relevant property are shown in the first and last columns of the legend
        The entity (excl. USA) associated with each max/min is noted immediately above the actual property value for that entity
        The fixed points for the color-bars -- end-points for the top bar, end- and mid-points for the others -- are shown in the boxes with heavy surrounds
- Center bar:
   - Column-plot with a 60-day window of daily new-cases -- the date-range is given on either side of the USA flag
        The plot maximum is auto-scaled for the displayed data, the minimum is fixed at zero
   - The color-bar indicates the trend of the most recent 30 days of the column-plot [Right-half of column-plot]
        Red is bad (increasing), green is good (decreasing), yellow indicates stasis.
- Bottom bar:
   - Population-normalized most recent 7-day average of daily-new cases as Daily-cases per 100,000 [1 Lakh]
     [Right-most quarter of column-plot]

When this is all over the flags will all show blue/pale-yellow/pale-yellow bars and the numbers will all be zero!

There are some "transient artifacts" in the displays and numbers as "outlier" data passes through the window -- this is a particular problem with the sparse data early in the movie...

**Comment by tiffehr** [comment]
Thank you for sharing this!  I've added to our Project board, under Examples!  Nice solution around GitHub's limitations with the .rar file, too.
