### ISSUE TITLE
Use of Asymmetric Differential Logistic Equation to characterize COVID data

### ISSUE THREAD

**Issue by peterdaytx** [nytimes/covid-19-data#589]
From the very early days it appeared that an "Asymmetric Differential Logistic" equation would be a useful way to parameterize COVID data. 

The conventional logistic equation, has a simple "S" shape: 
   Logistic(x) = Final / (1 + exp(-ka * (x - x0)))

Its differential twin has a shape akin to a Gaussian curve with exponential rises and decays:
   DLogistic(x) = 4 * Peak * exp(ka * (x - x0)) / ((1 + exp(ka * (x - x0))) ^ 2) 
Where x0 and ka are constants; x is the date; Peak is the value of DLogistic at x = x0; Final is the value for the Logistic curve at x>>x0

In contrast, the Asymmetric Differential Logistic equation has asymmetric attack/decline rates (ka and kd):
   x<x0:  DALogistic = 4 * Peak * exp(ka * (x - x0)) / ((1 + exp(ka * (x - x0))) ^ 2)
   Else:    DALogistic = Peak * 4 * exp(kd * (x - x0)) / ((1 + exp(kd * (x - x0))) ^ 2)

Not surprisingly, the Asymmetric Logistic equation is slightly messier than its symmetric counterpart:
   x<x0:  ALogistic = Peak * (4 / ka) / (1 + exp(-ka * (x - x0)))
   Else:    ALogistic = Peak * (((2 / ka) - (2 / kd)) + (4 / kd) / (1 + exp(-kd * (x - x0))))

The attached chart shows how four Asymmetric Differential Logistic equations can be used to characterize the full-range of the NYT dataset for USA COVID 19 Daily Cases. The data has been plotted on a logarithmic axis for two reasons: to capture the range of the data; to demonstrate both the exponential attack and decline.

 It has not gone unnoticed that the Asymmetric Differential Logistic equation with relatively slow "attack" that peaks at around 12/27/2020 is actually "interfering" with the fit to the very early data...

![USA_CV_NYT](https://user-images.githubusercontent.com/64326612/119515090-2cf66f00-bd3b-11eb-9673-ec74f8f6d52b.png)

**Comment by albertsun** [comment]
Thanks for sharing! Interesting curve fitting.

**Comment by tiffehr** [comment]
@peterdaytx I added this to our collection of Examples!  Thank you very much for the write-up and chart!
