### ISSUE TITLE
TN Data is very off

### ISSUE THREAD

**Issue by EliBP** [nytimes/covid-19-data#59]
TN Data found [here](https://www.tn.gov/health/cedep/ncov.html) is quite different from your reporting. For example, Williamson county has over 90 cases, but according to the us-counties.csv file there are only 35 cases.

**Comment by jimAlabama** [comment]
It's very close.  The latest data here, just posted, are from yesterday.

**Comment by albertsun** [comment]
Hi @EliBP,

This dataset is generally not going to have the most recent numbers.

The data we’re releasing on GitHub is a periodic release of cases and death numbers for full past days of reporting. For our most up-to-date published numbers, please instead see our maps page on The New York Times website: https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html

If you are interested in a specific place, local official sources are the most likely to have the latest numbers. We do not update our numbers instantaneously.
