### ISSUE TITLE
Data Issue:  

### ISSUE THREAD

**Issue by fbtoc** [nytimes/covid-19-data#595]
It appears that today's update (6/4/2021 data) did not succeed.

**Comment by ghop02** [comment]
Taggin @albertsun for more visibility :)

**Comment by tiffehr** [comment]
Yep, we're still aware of the technical problem with pushing the growing file up to GitHub. It's currently a manual process and takes more time. We appreciate the attentiveness and your patience with it, as it is a more time-intensive step in our publishing processes.

**Comment by fbtoc** [comment]
Thanks - we appreciate you providing this service.
