### ISSUE TITLE
Data Issue: Unexplained net decrease in national deaths on April 21, 2021

### ISSUE THREAD

**Issue by memscribe** [nytimes/covid-19-data#599]
Suspicious number of cases or deaths — deaths decreased by 124 on April 21, 2021. 

The us.csv time series includes this data over a three-day stretch in April 2021. Note the totals in the third column, representing cumulative Covid-19 deaths in the United States: 

2021-04-20	31817925	569109
2021-04-21	31878030	568985
2021-04-22	31944272	569896

Deaths decreased by 124 on April 21, 2021. I have not yet seen any explanation for this decrease. April 21 is not listed among the anomalies on the [Latest Map and Case Count page](https://www.nytimes.com/interactive/2021/us/covid-cases.html?name=styln-coronavirus&region=TOP_BANNER&block=storyline_menu_recirc&action=click&pgtype=Interactive&variant=1_Show&is_new=false) for the U.S. 

I am not aware of any other date on which the nation sustained a net decrease in Covid-19 deaths.

**Comment by lwaananenjones** [comment]
Thank you for bringing this up. It looks like this is related to a one-day error with "unknown" deaths in Texas, which made the Texas total artificially high on April 20 before being corrected the following day. We'll revise that data point, which should resolve the decrease on April 21.
