### ISSUE TITLE
Coordinate by county with JHU.EDU?

### ISSUE THREAD

**Issue by ronaldgbennett** [nytimes/covid-19-data#60]
Is anyone coordinating with jhu to iron out discrepancies in the by-county data?  JHU has similar counts to yours, but their numbers tend to be higher (more recent?) and, unfortunately, they have different groupings of "Unknown" counties by state.  Perhaps coordination would address some of the individual county issues reported below where your sources are undercounting the local numbers...?  And of course, where is CDC in all of this?  Is the CDC able to provide any known good local sources?

**Comment by WeileiZeng** [comment]
CDC is fall behind, that is why groups like nytimes or 1point3ache step up for living data.

**Comment by cipriancraciun** [comment]
As a matter of fact, last week I have created a derived dataset from JHU (https://github.com/cipriancraciun/covid19-datasets), where my main goal was cleaning up the inconsistencies and providing summation and augmentation.

Today I have included in my derived dataset both the NY Times one and the ECDC (European CDC) one.

As an experiment I have "merged" the 5 datasets together in one file for easier comparison (look in the `dataset` column for the source):
* `jhu/daily` -- based on the `daily_reports` folder of the JHU repository;
* `jhu/series` -- based on the `time_series` files in the JHU repository;
* `nytimes/us-counties` -- based on the NY Times `us-counties.json`;
* `nytimes/us-states` -- based on the  NY Times `us-states.json`;
* `ecdc/worldwide` -- based on the ECDC dataset;
* https://github.com/cipriancraciun/covid19-datasets/blob/master/exports/combined/v1/values.tsv

(This is not just a simple copy-paste of the 5 datasets, but they use consistent location naming and dates, thus a comparison would be much more easy.)  (See the readme in the pointed repository for details.)

----

That being said, unfortunately the JHU team seems to be swamped, and issues keep piling (>900 unclosed already) on and left unattended.  (I've tried pointing people to duplicate issues, but new ones pop-up.)

Thus I don't know how efficient such a coordination would be, unless it is approached via a back-channel.

**Comment by cipriancraciun** [comment]
I have just opened an issue on the JHU repository about this coordination proposal:
* https://github.com/CSSEGISandData/COVID-19/issues/1732

**Comment by ronaldgbennett** [comment]
Thanks for your efforts to compare and improve consistency between the datasets.  I downloaded your merged dataset, but haven't really parsed it yet.
I'm not sure if this issue warrants much more work given the issues you've mentioned.
Best of luck.
