### ISSUE TITLE
Data Issue:  Decrease in total cases for us.csv on 2021-06-04

### ISSUE THREAD

**Issue by csubich** [nytimes/covid-19-data#600]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [X] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details

In us.csv, the total number of cases appears to drop between 2021-06-03 (33336460) and 2021-06-04 (33312467).  Since this is a cumulative total, this probably should not happen.

This discontinuity appears to have been introduced with commit 4c3b33858bda4d02b83b0bf640bb8818b62aa270, which revised 06-04 through 06-11.  If this was part of a larger data revision, it did not go back far enough.

**Comment by memscribe** [comment]
The New York Times’s [Coronavirus in the U.S.: Latest Map and Case Count](https://www.nytimes.com/interactive/2021/us/covid-cases.html?name=styln-coronavirus&region=TOP_BANNER&block=storyline_menu_recirc&action=click&pgtype=Interactive&variant=1_Show&is_new=false) page contains the following notation: 

“June 4, 2021: Florida stopped providing daily updates and removed many nonresident cases.”

**Comment by csubich** [comment]
Ah, thank you.  That's it, I had just missed the methodology note.

**Comment by tiffehr** [comment]
@csubich Yep, that's it.  @memscribe Thank you!
