### ISSUE TITLE
Data Issue: Polk County, MO

### ISSUE THREAD

**Issue by chris-prener** [nytimes/covid-19-data#601]
### Describe the issue:
- [x] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
The NYTimes data for Polk County, MO over the last week shows just 6 new cases over the last week. However, MO DHSS is reporting 45 new cases, and the local health department is reporting even more on their Facebook page. I check the `anamolies.csv` file and didn't see any notes about Polk County, so thought I would open this up to see if you all can check on those new case counts. Thanks so much for your help!

**Comment by lwaananenjones** [comment]
Thank you for bringing this up — we use both state and county data for Polk County, and it looks like we didn't get all the recent county updates. We'll revise that, so you should see the data match the county's numbers in our next update.

**Comment by chris-prener** [comment]
Great, thanks @lwaananenjones!

**Comment by tiffehr** [comment]
@chris-prener You see the updated figures yet?

**Comment by chris-prener** [comment]
Just took a look, thanks for checking in on this @tiffehr! Everything looks great now. Appreciate how responsive y'all are!
