### ISSUE TITLE
Data Issue:  cumulative deaths is nonmonotonic in us-counties.csv (6,160 errors)

### ISSUE THREAD

**Issue by batson** [nytimes/covid-19-data#602]
### Describe the issue:
- [X] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
The cumulative deaths column for Trinity County, California in [us-counties.csv](https://github.com/nytimes/covid-19-data/blob/master/us-counties.csv) is non-monotonic, meaning that the cumulative death count goes down on occasion. Here, the cumulative number of deaths goes from 0 up to 5, then down to 3. Judging from CA.gov [open data](https://data.ca.gov/dataset/covid-19-time-series-metrics-by-county-and-state1/resource/6a1aaf21-2a2c-466b-8738-222aaceaa168) portal, 3 is the correct current cumulative death count.

This error is reflected on the official Times dashboards, as there are 2 phantom deaths attributed to the county.
![Screen Shot 2021-06-16 at 5 14 26 PM](https://user-images.githubusercontent.com/1261162/122311785-c55dba80-cec7-11eb-9cf8-4747b48d6e0b.png)

There are 6,160 county-days on which the `deaths` column decreases in `us-counties.csv`, representing 0.4% of the dataset. See attached for the days/counties where that value drops. I believe (barring reincarnation events) that this represents some error upstream, perhaps due to revisions from the county/state which were not incorporated into the Times data.
[cumulative_death_decreases.csv](https://github.com/nytimes/covid-19-data/files/6666493/cumulative_death_decreases.csv)

This was generated via the following R code:

```
library(tidyverse)
df = read_csv('~/Desktop/us-counties.csv')
nonmon = df %>% group_by(county, state) %>% mutate(delta_deaths = deaths - lag(deaths)) %>% 
  filter(delta_deaths < 0 & county != 'Unknown')
nonmon %>%  write_csv('~/Desktop/cumulative_death_decreases.csv')
```

**Comment by batson** [comment]
There are also 24,923 such inconsistencies in the case data. See 
[cumulative_case_decreases.csv](https://github.com/nytimes/covid-19-data/files/6666538/cumulative_case_decreases.csv)

**Comment by albertsun** [comment]
Hi @batson these are due to after-the-fact data revisions by health departments, please see the section of the README on Declining Counts. Since this data set is by Report Date, we are not attempting to reconcile all instances of declining counts.

**Comment by batson** [comment]
Closed as known problem.

Note daily death totals displayed in nytimes graphics will not reflect revisions to cumulative counts.
