### ISSUE TITLE
Data Issue:  Today's file 7/2/2021 only has up to 6/30 (not 7/1) and US totals fro 6/29 & 6/30 have changed from yesterday's file

### ISSUE THREAD

**Issue by MirrorCola** [nytimes/covid-19-data#604]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources. Please check the README and recent commit messages for updates to see if your issue is addressed.

**Comment by cfhp1** [comment]
Also very eager to have the 7/1 data to meet earlier holiday weekend timing goals. @albertsun, are you able to help?

Thank you for continuing to provide this service!

**Comment by albertsun** [comment]
Looking into it

**Comment by MirrorCola** [comment]
To echo the comment above, thank you all very much for doing this.

**Comment by cfhp1** [comment]
> Looking into it

Thanks for the updated data!

**Comment by MirrorCola** [comment]
Indeed, thanks for the update.  Also looks like Florida data was added for 6/29 & 6/30.

**Comment by cfhp1** [comment]
> Also looks like Florida data was added for 6/29 & 6/30.

Florida has gone to weekly updates. If they don't change the schedule again, we should get new data tomorrow.

**Comment by MirrorCola** [comment]
Thanks again, I'm going to close this issue, but just a comment.  

State of Florida data has not been weekly, as I expected as well but seems to show up sporadically.  In June there were 8 days with zero changes in the new case totals.  All other days had some delta.  There were a few more days with zero deaths.

**Comment by lwaananenjones** [comment]
Hi everyone, I can clarify a bit about Florida data sources: The state has only been updating on Fridays, so county cases data updates weekly now. The state is no longer providing county-level deaths. 

For state totals, Florida has still been sending information to the CDC, so we get updated statewide cases and deaths on some days [from the CDC](https://covid.cdc.gov/covid-data-tracker/#cases_totalcases). So far, this has been _most_ but not all weekdays. It seems like sometimes the CDC data runs a day behind; for instance, there was new data on Monday of this week.

**Comment by MirrorCola** [comment]
Thank you for taking the time to add that explanation.
