### ISSUE TITLE
Data Issue:  San Francisco erratic data trends, negative numbers

### ISSUE THREAD

**Issue by durrettj** [nytimes/covid-19-data#606]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [X] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details

Cumulative case counts for San Francisco dropped by more than 300 between 6/29 and 6/30.

2021-06-29 37375
2021-06-30 37044
2021-07-01 37068
2021-07-02 37110
2021-07-03 37110
2021-07-04 37110
2021-07-05 37110
2021-07-06 37240
2021-07-07 37254
2021-07-08 37287
2021-07-09 37341
2021-07-10 37341
2021-07-11 37341
2021-07-12 37599
2021-07-13 37659

This causes erratic rolling averages:

2021-06-30 -331
2021-07-01 24
2021-07-02 42
2021-07-03 0
2021-07-04 0
2021-07-05 0
2021-07-06 130
2021-07-07 14
2021-07-08 33
2021-07-09 54
2021-07-10 0
2021-07-11 0
2021-07-12 258
2021-07-13 60

**Comment by lwaananenjones** [comment]
Thank you for asking about this. Our data for San Francisco County comes from the state health department. (We also monitor the county dashboard, but it has been consistently lower recently.) On June 30, California removed many cases and had this note:

> On June 30, there were 2013 newly reported confirmed cases of COVID-19 based on June 29 data. June 30's report includes 6372 fewer overall confirmed COVID-19 cases due to a routine audit of data that resulted in the removal of duplicate and reclassified cases.

We have anomalies this like one omitted from our rolling average and listed in the anomalies file with our relatively new [rolling averages dataset](https://github.com/nytimes/covid-19-data/tree/master/rolling-averages).

**Comment by durrettj** [comment]
Thank you for the explanation and pointing out the anomalies file.

Best regards, 

-- 
 
Jason Edward Durrett, GSTRT, GCUX, GCIA, GIAC Advisory Board
