### ISSUE TITLE
Data Issue: Independence, MO

### ISSUE THREAD

**Issue by chris-prener** [nytimes/covid-19-data#609]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [X] Other

### Fuller details
This is a heads up to your team - as of today, vaccination data for Missouri are being reported separately for Independence, MO. Independence had been reported as part of Jackson County before this. I would closely watch MO DHSS's dashboard for a switch with other county-level metrics where Jackson's numbers are reduced and Independence is reported separately.

**Comment by tiffehr** [comment]
@chris-prener Thank you for the heads up. We are not using local vaccination data fro Missouri, but instead the figures from the [CDC's vaccine data sets](https://covid.cdc.gov/covid-data-tracker/#vaccinations-county-view).  They do not have an entry for Independence, in their county list.  I don't see a decline within Jackson County, in MO, so I think they still roll Independence into it, with today's figure being `282,044`.
![image](https://user-images.githubusercontent.com/60173/127241682-b0a0f3ec-b7b3-469d-9a3e-8ad36cfcc4ce.png)

We _do_ see Independence within Missouri's own Tableau-displayed [vaccination data](https://results.mo.gov/t/COVID19/views/VaccinationsDashboard/Vaccinations?:embed=y&:showVizHome=no) and we do collect that figure.  But we are not using the state's source for our Missouri data in [our maps](https://www.nytimes.com/interactive/2020/us/covid-19-vaccine-doses.html).

**Comment by chris-prener** [comment]
Sorry @tiffehr for not being clear - I'm anticipating a change with case and mortality counts to mirror this! It has not happened yet, though.

**Comment by tiffehr** [comment]
@chris-prener Ah, gotcha, will re-open as we see what they do.

**Comment by chris-prener** [comment]
Sounds good. FWIW the change is because Independence has re-opened their city public health department instead of relying on Jackson County's department.

**Comment by chris-prener** [comment]
Wanted to give you a heads up @tiffehr that the change I had referenced was made today - you can see Independence separately being reported across all of DHSS's public dashboards.

From their [release notes](https://health.mo.gov/living/healthcondiseases/communicable/novel-coronavirus/data/public-health/data-methodology-and-documentation.php):

> Data Release Notes 8/31/21
> Addition of City of Independence-Tests, Cases and Death data.
> With the re-established City of Independence Health Department fully taking over COVID-19 response for their jurisdiction, MO DHSS has decided to provide COVID-19 data separately for the City of Independence and the service area of the Jackson County Health Department (the area not falling in either Kansas City or Independence). As such, the data by jurisdiction of residence on all public dashboards has been updated to include the City of Independence as a separate jurisdiction. This update moves approximately 12,000 total PCR cases, 2,500 Antigen cases, 200 Deaths, 100,000 PCR test and 41,000 Antigen test from Jackson County to the City of Independence.

**Comment by tiffehr** [comment]
@chris-prener Yep, I had to manually correct for it and hand that off to our reporting/data review process.  Thank you for the heads up!
