### ISSUE TITLE
Geographic Exceptions - Dukes and Nantucket

### ISSUE THREAD

**Issue by covid19viz** [nytimes/covid-19-data#61]
Your data files contains multiple records for Dukes and Nantucket (Massachusetts) with missing fips code. Please add a proper mention to Geographic Exceptions category in ReadMe.

**Comment by albertsun** [comment]
Hi, thank you for pointing this out. Those rows are duplicative of separate rows for Dukes and Nantucket for each date they appear. We'll be removing "Dukes and Nantucket" in the next revision.

**Comment by albertsun** [comment]
With the latest update these rows are now gone.
