### ISSUE TITLE
Data Issue:  death cases in san mateo county doesn't seems to be righ 

### ISSUE THREAD

**Issue by mkhanka** [nytimes/covid-19-data#611]
### Describe the issue: Incorrect death cases in san mateo county, CA in https://github.com/nytimes/covid-19-data/blob/master/us-counties.csv
- [ ] Incorrect number of deaths on 6th june 2021: 88 deaths 
- [ ]  Incorrect number of deaths on 15th june 2021: 39 deaths 

### Fuller details
As per Official California State Government Website 0 death on both dates.
sources: https://covid19.ca.gov/state-dashboard/#location-san_mateo

**Comment by lwaananenjones** [comment]
Both June 6 and 15 are days when California added many deaths in San Mateo that happened weeks or even months earlier. Our methodology is counting cases and deaths on the date they are announced. California shows deaths by date of death, so daily counts typically do not match. Our data should be interpreted as "X deaths were announced in this date."

When there are backlogs or anomalies that affect trends, such as these, they are listed in the anomalies file with our [rolling averages dataset](https://github.com/nytimes/covid-19-data/tree/master/rolling-averages).
