### ISSUE TITLE
This is paywall 

### ISSUE THREAD

**Issue by igmuska** [nytimes/covid-19-data#617]
I don't think the muckraker should host this here, if they do, they have to host the Covid  infection Dara without registering.. I will not do such
Thank you for your consideration

**Comment by virtadpt** [comment]
You can clone this repo without having a Github account.

`git clone https://github.com/nytimes/covid-19-data/`

**Comment by tiffehr** [comment]
A few clarifying questions:
1. what do you mean by muckraker?
2. As @virtadpt indicated, many of the files is this repository can be copied without requiring you sign up for GitHub -- you can save the "raw" file as if it were .csv or another file type just fine.

I hope this helps you get a copy of the data we are providing without needing to pay.

**Comment by Pedro-McM** [comment]
As a long-time and frequent user of the NYT data on github, I'd say that this issue can be closed, as two people have adequately addressed the concern.

* There is no paywall for this data.
* You don't need to be a github member to access it.
* @igmuska has had sufficient time to clarify their concerns beyond those addressed.

**Comment by tiffehr** [comment]
@Pedro-McM Yep, thank you!
