### ISSUE TITLE
what is the data source for hospitalization?

### ISSUE THREAD

**Issue by pdemarti** [nytimes/covid-19-data#619]
The Hospitalization data for Florida on the NYT website seems to have been stale since roughly August 17, 2021 (but it's hard to tell from the graph). I wanted to confirm the exact last available date by looking in this repo, but then I was surprised to find no hospitalization data at all.

**Comment by tiffehr** [comment]
We do not collect or publish hospitalization data here.  NYT's source for hospitalization figures the [U.S. Department of Health and Human Services](https://protect-public.hhs.gov/), as [cited on our published Hospitalization metrics](https://www.nytimes.com/interactive/2021/us/florida-covid-cases.html). Furthermore, our Florida page has a note at the top, indicating some unique constraints to Florida's reporting schedule, which we presume includes sending the latest hospitalization figures to HHS.

![image](https://user-images.githubusercontent.com/60173/130471023-ead701a8-97cb-4cc0-840f-6eaa9c379693.png)

**Comment by pdemarti** [comment]
Thank you for your prompt answer. More importantly: thank you for the work you and your colleagues do. It's been a beacon of knowledge and rigor for millions of people during this global pandemic.
