### ISSUE TITLE
Question:  will we get updates regarding college covid-19 data

### ISSUE THREAD

**Issue by shichenglu** [nytimes/covid-19-data#621]
Colleges are starting a new semester, will we have updates regarding their covid-19 data soon? It's a good time to have updates before a new semester starts.
Thanks!

**Comment by tiffehr** [comment]
I'll ask our team that focuses on manually collecting our college dataset.  Back to you soon.

**Comment by tiffehr** [comment]
@shichenglu We will not be updating our college data set anytime soon, I can report.  There are a number of methodological, staffing and logistic issues.
