### ISSUE TITLE
Question:  It would be possible to share some codes?

### ISSUE THREAD

**Issue by ravellom** [nytimes/covid-19-data#626]
Good Morning,
Congratulations on the great data analysis work you do, and the great utility for well-informed decision making.
It would be possible to share some codes with which you generate these excellent graphs and tables: https://www.nytimes.com/interactive/2021/us/covid-cases.html, or at least the libraries you use, etc.
It would be of great help for analysis in other countries.
Thanks in advance,
Raidell Avello 

### Do you think there is an error in the data?
Please submit a Data Issue so it can be easily routed to the correct people.

### Do you have a question about the LICENSE or permission to use this data?
Please email us at covid-data@nytimes.com

### Your question
Please check to make sure your question is not answered in the README. It may have been updated since you first read it.

**Comment by tiffehr** [comment]
@ravellom Our visualizations are often built with a combination of [Svelte](https://svelte.dev/) and [D3](https://d3js.org/).  We are unable to share more code than pointers to those libraries.  But many users of our public data set offered here have their own solutions that you may find interesting.  We've collected a number of them or our [Project board](https://github.com/nytimes/covid-19-data/projects/1), under Examples.  Some of those include using this data set with other online visualization libraries and tools.

**Comment by ravellom** [comment]
Thank you very much for your answer.
Very usefull examples!!
