### ISSUE TITLE
Just to register this, no update for 9/23 either

### ISSUE THREAD

**Issue by MirrorCola** [nytimes/covid-19-data#628]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources. Please check the README and recent commit messages for updates to see if your issue is addressed.

**Comment by joecascio** [comment]
Can we get an update from the NYTimes team?

**Comment by MirrorCola** [comment]
Just to amplify an earlier comment.  We really do appreciate the work all of you do on this.  So, thank you.

**Comment by tiffehr** [comment]
Primarily responding on this thread:  https://github.com/nytimes/covid-19-data/issues/627
