### ISSUE TITLE
Connecticut deaths do not match state government totals

### ISSUE THREAD

**Issue by dsubnet0** [nytimes/covid-19-data#629]
CT cumulative deaths in live/us-states.csv are listed as 8629, but ct.gov/coronavirus declares this to be 8,483. Looking back in the NYT data, something weird started to happen on or around 09-24. (Confusing the issue is the fact that CT only updates its death totals on Thursdays.)

**Comment by tiffehr** [comment]
We use [CT's data set and API queries](https://data.ct.gov/Health-and-Human-Services/COVID-19-Tests-Cases-Hospitalizations-and-Deaths-S/rf3k-f8fg) for our Connecticut figures.  For the state's deaths, we use their `totaldeaths` cumulative figure, which is a combination of confirmed deaths and probable deaths.

Here's the most recent dataset entries:
![image](https://user-images.githubusercontent.com/60173/135510293-13070c90-ebd0-4821-ab82-025a1ed350d1.png)

The `8,483` figure seems to line up with their figure from 9/23 -- the last weekly update, perhaps.

But the moment, I see the following on https://portal.ct.gov/coronavirus:
![image](https://user-images.githubusercontent.com/60173/135510181-d292fbec-dfb1-4312-81e7-df6f667ef8a8.png)

I think you caught it just before an update.

**Comment by tiffehr** [comment]
@dsubnet0 Let me know if you have further questions?  Re-open, if so!
