### ISSUE TITLE
No new data today for 9/30?

### ISSUE THREAD

**Issue by MirrorCola** [nytimes/covid-19-data#630]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources. Please check the README and recent commit messages for updates to see if your issue is addressed.

**Comment by albertsun** [comment]
We'll take a look

**Comment by dawenx** [comment]
Thanks @albertsun Appreciate you all's great work as always

**Comment by MirrorCola** [comment]
My thanks as well

**Comment by albertsun** [comment]
Most of the data is now updated. The update failed because this one file https://github.com/nytimes/covid-19-data/blob/master/rolling-averages/us-counties.csv grew over the Github file size limit and so we will no longer be able to continue updating that single file. If you were using that you should instead use this file https://github.com/nytimes/covid-19-data/blob/master/rolling-averages/us-counties-recent.csv which is truncated to just the most recent 30 days.

**Comment by cfhp1** [comment]
> [us-counties.csv](https://github.com/nytimes/covid-19-data/blob/master/rolling-averages/us-counties.csv) grew over the Github file size limit and so we will no longer be able to continue updating that single file.

Disappointing but understandable. Thanks very much for getting your data flowing again. It's very helpful.

Carolyn

**Comment by cfhp1** [comment]
> [us-counties-recent.csv](https://github.com/nytimes/covid-19-data/blob/master/rolling-averages/us-counties-recent.csv) which is truncated to just the most recent 30 days.

Will it always be possible to get all of the data? When data becomes older than 30 days but not old enough to be counties.csv, will it still be available?

Thanks,
Carolyn

**Comment by albertsun** [comment]
Yea, we're going to look into an alternate solution when we get there so that there will not be a gap.

**Comment by cfhp1** [comment]
Thanks again, @albertsun!
Carolyn

**Comment by MirrorCola** [comment]
again, thank you to you all!  Closing issue
