### ISSUE TITLE
Question:  PA data anomaly 11/13

### ISSUE THREAD

**Issue by jamie-spotlightpa** [nytimes/covid-19-data#639]
Hi - Trying to understand the data anomaly on Saturday, 11/13. Hoping to confirm whether this was a result of the state adding ~15k reinfections last week (they previously were not counted). Health department daily cases do not include the reinfections; they were simply added to the cumulative total. Thanks!

**Comment by tiffehr** [comment]
Yep, as you noted, PA's people had said they would be adding reinfections.  We thought the day they did it would be paired with a press release or something.  But we didn't find one to go with the ~15K cases anomaly they dropped on Saturday.  Internally, we marked it as such and discounted that day from our rolling averages.

Today, Monday, they did announce the reinfection number (`15,414`).  Need the source document(s)?  Happy to ask for that URL, if it would be helpful.

**Comment by lwaananenjones** [comment]
Here is [today's press release](https://www.media.pa.gov/pages/health-details.aspx?newsid=1667) confirming that this ws the cause of Saturday's increase, as well as the number of reinfection cases.

**Comment by jamie-spotlightpa** [comment]
Great, thank you both! I'm all set.
