### ISSUE TITLE
Case/day and death/day data woulkd be helpful

### ISSUE THREAD

**Issue by qudrcps** [nytimes/covid-19-data#64]
I started working with this, and incredibly helpful for the "armchair epidemiologist".  (In my case Maine, where our CDC does not send out graphics for case/day, only totals.)

It would be helpful for those not adept in manipulating the data to add two more columns, and clarify the two already there.  Clearly, "cases" are "Total_Cases" or "Cumulative_Cases (same for deaths). What is needed are "New_Cases" and "New Deaths".

Sure, I can do this programmatically, but not all can, and trying to get this information "out there" in  as simple a form as possible (and yes, I realize it does add to the file size).

Thanks to you all for making this available!!!

**Comment by albertsun** [comment]
In the interest of only maintaining a single version of the data, we're going to leave this computation to the users of the data.
