### ISSUE TITLE
MI hospital census data (11/16/21)

### ISSUE THREAD

**Issue by datagub** [nytimes/covid-19-data#640]
MI reports hospital census MWF.  NYT shows the latest reporting as of 11/9 (a week ago) but there have been several updates i think since then.  
https://www.michigan.gov/coronavirus/0,9753,7-406-98159-523641--,00.html

**Comment by albertsun** [comment]
Hi @datagub our data on hospitalizations (which is not included in this Github repo) is sourced centrally from the Department of Health and Human Services, not from state health departments. Sometimes the update there falls behind a little bit. We are looking into why it is behind by a few days right now.

**Comment by albertsun** [comment]
The hospitalization figures there are now updated through 11/15
