### ISSUE TITLE
Data Issue:  Drastic increase in COVID cases across Missouri counties 11/19/21

### ISSUE THREAD

**Issue by msimkins7** [nytimes/covid-19-data#641]
The data for Missouri on 11/19/2021 seems to have an abnormally high number of daily cases.  It increased from 1835 to 9548 in one day.  Is this a true increase or perhaps a data-dump for one day?

**Comment by tiffehr** [comment]
All the signs of a one-time data-dump:  https://www.stltoday.com/lifestyles/health-med-fit/coronavirus/missouri-reports-thousands-of-previously-unreleased-covid-19-deaths-infections/article_72750f11-f044-5873-9a81-a953f10064d7.html

> On Thursday, the Missouri Department of Health and Senior Services once again reconfigured the state’s COVID-19 data dashboard, adding thousands of previously unreported deaths and infections.
> 
> Some date back to the spring of 2020, and many are instances of illness or death now attributed to COVID-19 but that weren’t publicly tallied by the state at the time.

We have flagged it as an anomaly, but have to learn a bit more from the state until we know how to handle this data-dump correctly.

**Comment by tiffehr** [comment]
Here's the state's post about it:  https://health.mo.gov/living/healthcondiseases/communicable/novel-coronavirus/data/public-health/data-methodology-and-documentation.php

![image](https://user-images.githubusercontent.com/60173/142669960-0e0057f3-2dce-45e3-bb22-f2ce3969a297.png)

**Comment by msimkins7** [comment]
Thank you!
