### ISSUE TITLE
Data Issue: County data format change

### ISSUE THREAD

**Issue by cqcq42** [nytimes/covid-19-data#642]
Could you please decide on a data format for each file and stick to it?
County data has added additional columns from previous formats and the data for cases/deaths now seems to be cases/deaths PER DAY rather than the previous ACCUMULATED.

**Comment by ddenenberg71** [comment]
Perhaps you're accidentally looking at the files in the rolling-averages folder instead of the same-named files in the root folder?

**Comment by cqcq42** [comment]
Thanks. You are correct. Sorry.
