### ISSUE TITLE
Enhancement: Break rolling-averages/us-states.csv into additional by year files

### ISSUE THREAD

**Issue by SecretAgentKen** [nytimes/covid-19-data#647]
The `us-states.csv` file in `rolling-averages` has now exceeded the allowed size for an `IMPORTDATA` call in Google Sheets. Would it be possible to add additional `us-states-2020.csv` and `us-states-2021.csv` files similar to the current `county` level files? A `recent` file would be appreciated as well.

**Comment by tiffehr** [comment]
In discussion!

**Comment by K1118** [comment]
Hello, can i contribute to this issue please ?
