### ISSUE TITLE
Confirm definition of 'cases' - active or total?

### ISSUE THREAD

**Issue by paulmills-cd** [nytimes/covid-19-data#65]
Please clarify definition of 'cases'.  It's clear that it's total cumulative cases as of the date, but what's not clear is whether the cases field refers to ACTIVE cases (not including deaths and recovered), or TOTAL cases (including deaths and recovered).  

Also, repeating other's request for **recovered** counts, with fields as follows: 
- total cases cum
- deaths cum
**- recovered cum**
- open cases cum (total cases cum - deaths cum - recovered cum)

And, while queriable on our end by subtracting previous day's cases, it'd help many to also include incremental daily counts, with the following additional fields: 
- total cases daily
- deaths daily
- recovered daily
- open cases daily (total cases daily - deaths daily - recovered daily)

**Comment by albertsun** [comment]
Hi @paulmills-cd — cases is all cases, cumulative to that date, including past cases that are recovered. It is not active cases, and we are not currently publishing any count of recovered cases. There is not a standard definition of recovered and most counties and states are not providing reliable data on the number of recovered cases.

**Comment by paulmills-cd** [comment]
thanks for the explanation.
