### ISSUE TITLE
Data Issue: Cape Girardeau, MO 

### ISSUE THREAD

**Issue by chris-prener** [nytimes/covid-19-data#652]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [x] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
Similar to #650 - no data was reported in your data for the past week but MO DHSS reports > 100 new cases. Thanks for looking into it!

**Comment by tiffehr** [comment]
We're working on transitioning sources for this county, but haven't had time within the holidays to fully figure out the best source combination.  We'll reply here as we get to it.

**Comment by chris-prener** [comment]
Thanks @tiffehr!

**Comment by tiffehr** [comment]
@chris-prener Our last step will be to add a note about the change.  All good otherwise?

**Comment by chris-prener** [comment]
I believe so @tiffehr - things are looking good on my end!
