### ISSUE TITLE
Data Issue:  San Bernardino new cases on 28th Dec is inflated 

### ISSUE THREAD

**Issue by mkhanka** [nytimes/covid-19-data#653]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Missing time-series information

### Fuller details
There is huge difference in covid cases for 28 Dec 
Cases as per 
- [CA Department of Technology](https://public.tableau.com/app/profile/ca.open.data/viz/COVID-19CasesDashboardv2_0/CaseStatistics) :225  
- [NYTdashboard](https://www.nytimes.com/interactive/2021/us/san-bernardino-california-covid-cases.html) : 4474 
Also there are 0 cases reported from 25th to 27th, this might have spiked the cases on 28th, Please look into this and verify the data, if this is intended?

**Comment by lwaananenjones** [comment]
Our data includes cases on the date they are added to the county's total count, with the new cases each day calculated as the difference day-to-day in the cumulative count. The state instead displays cases by "episode date," which means the date someone was tested or first experienced symptoms. Even if cases are assigned to different dates, the cumulative counts should always match, such as 399,021 cases as of 1/2/21 matching the state's 386,278 [confirmed cases](https://public.tableau.com/app/profile/ca.open.data/viz/COVID-19CasesDashboardv2_0/CaseStatistics) plus 12,743 [probable cases](https://data.chhs.ca.gov/dataset/covid-19-probable-cases) based on antigen testing.

**Comment by tiffehr** [comment]
@mkhanka Re-open this if you'd like more details, please?
