### ISSUE TITLE
Data Issue: csv for 2022 not available [US Counties]

### ISSUE THREAD

**Issue by nickybisht** [nytimes/covid-19-data#654]
### Describe the issue:
- [ ] Missing data for a locality
- [ ] Missing time-series information

### Fuller details
Data for US counties not available for 2022. CSV missing for 2022: https://github.com/nytimes/covid-19-data/tree/master/rolling-averages
When can we expect data for this?

**Comment by albertsun** [comment]
Hi @nickybisht he 2022 file will be coming shortly.
