### ISSUE TITLE
Data Issue:  The most recent data in us-counties.csv is for 1-Mar-2022. 

### ISSUE THREAD

**Issue by SomervilleTom** [nytimes/covid-19-data#659]
### Describe the issue: ###

No `us-counties.csv` data after 1-Mar-2022

### Fuller details

Although the status says that `us-counties.csv` was updated 13 hours ago, it has no data after 1-Mar-2022.

Have the daily updates stopped?

**Comment by albertsun** [comment]
Hi @SomervilleTom I just checked that data file and I see data through 2022-03-03 as expected. Is it possible that you have not pulled down the latest version of the file or that whatever program you are using to open it has run into a row limit that is cutting off the end of the file?

**Comment by SomervilleTom** [comment]
Interesting. It does look fine now.

I attempted the download today, Here is an excerpt from the log:
```
--2022-03-04 12:17:15--  https://github.com/nytimes/covid-19-data/archive/master.zip
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/nytimes/covid-19-data/zip/refs/heads/master [following]
--2022-03-04 12:17:15--  https://codeload.github.com/nytimes/covid-19-data/zip/refs/heads/master
Resolving codeload.github.com (codeload.github.com)... 140.82.113.9
Connecting to codeload.github.com (codeload.github.com)|140.82.113.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘master.zip’
```
I appreciate the response, and I'll try the download again.

**Comment by SomervilleTom** [comment]
It appears that a stale copy of master.zip (from an earlier failure caused by an unrelated issue) confused the ingestor code on my end. All seems well now.

I apologize for the false alarm.

**Comment by tiffehr** [comment]
@SomervilleTom Thanks for checking!  We've been there, too. 😄
