### ISSUE TITLE
any chance to get the same data for death count from previous years?

### ISSUE THREAD

**Issue by asmirnov69** [nytimes/covid-19-data#66]
I assume that data are coming from official sources. Then it should be possible to have sample extended starting from e.g. 2015 for death counts.
Or there is something preventing the data team from doing that?

**Comment by amcdavid** [comment]
It appears these data are available with very high granularity here https://www.cdc.gov/nchs/nvss/mortality_public_use_data.htm . I don't see any reason why you couldn't join these, but i don't see how they would be necessarily comparable.

**Comment by FlashSheridan** [comment]
It would also provide perspective to include data on age and pre-existing conditions.

**Comment by albertsun** [comment]
I'm not sure what you would mean by this? No U.S. county would have any Covid-19 deaths in any year prior to 2020 as it is a novel disease. If you mean overall mortality rate, that is beyond the scope of this project and the data we are providing.
