### ISSUE TITLE
The worldwide Covid New cases and 7-day average data is not matching with WHO.

### ISSUE THREAD

**Issue by Saurabh0027** [nytimes/covid-19-data#661]
OWID Data: 

https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/jhu/full_data.csv 

New case statistics on OWID for worldwide on 2nd Mar, 3rd Mar, 4th Mar and 5th Mar are  1,651,874, 1,889,345, 1,702,615, 1,363,321 respectively.

WHO:  

https://covid19.who.int/

However, for 2nd, 3rd, 4th and 5th March, the data available on WHO are 1,602,527 1,617,490, 1,707,745, 1,636,595 respectively.

We would like you to please take a look at whether the statistics are correct or need to be corrected in reference with the source mentioned above like WHO.

**Comment by albertsun** [comment]
Hi @Saurabh0027 we do not publish any world level statistics in this data repository. On our pages our data for most countries comes from JHU and not either OWID or WHO.
