### ISSUE TITLE
Data Issue: Death cases of Arizona on 7th, 8th and 9th March are different from other sources. 

### ISSUE THREAD

**Issue by gauravjoshijo** [nytimes/covid-19-data#663]
### Describe the issue:

- [ ] Suspicious number of deaths

### Fuller details
Death cases of Arizona, US on 7th Mar, 8th Mar and 9th Mar are 0, 0, 150 respectively, whereas as per other sources:
- [**Worldometer**](https://www.worldometers.info/coronavirus/usa/arizona/): 
 Number of death cases on 7th, 8th and 9th March are  13, 13, 14 respectively.
- [***USFacts***](https://usafacts.org/visualizations/coronavirus-covid-19-spread-map/state/arizona):
 Number of death cases on 7th, 8th and 9th March are  0, 0, and 382 respectively.
- [***Ycharts:***](https://ycharts.com/indicators/arizona_coronavirus_deaths):
 Number of death cases on 7th, 8th and 9th March are  0, 0, and 382 respectively.

Please check the NYT source as data for the mentioned dates seem suspicious.

**Comment by tiffehr** [comment]
Arizona made some changes to their Tableau dashboard embeds [around the start of the month](https://directorsblog.health.azdhs.gov/the-adhs-covid-19-data-dashboard-is-changing-heres-why/), including dropping to "weekly updates"
