### ISSUE TITLE
Massachusetts deaths dropped by almost 4,000 on 3/14 is that what the state reported?

### ISSUE THREAD

**Issue by MirrorCola** [nytimes/covid-19-data#665]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources. Please check the README and recent commit messages for updates to see if your issue is addressed.

**Comment by albertsun** [comment]
Hi @MirrorCola yes this is what the state reported as part of a revision to their deaths count. We make note of anomalies like this in a file here which you can reference: https://github.com/nytimes/covid-19-data/blob/master/rolling-averages/anomalies.csv
