### ISSUE TITLE
For the US, as per the [NYT](https://www.nytimes.com/interactive/2021/us/covid-cases.html), daily Death cases on 14th March are showing 0.

### ISSUE THREAD

**Issue by Saurabh0027** [nytimes/covid-19-data#666]
For the US, as per the [NYT](https://www.nytimes.com/interactive/2021/us/covid-cases.html), daily Death cases on 14th March are showing 0.

But as per
[Corona Tracker](https://www.coronatracker.com/country/united-states/), cases were 936. 

[Worldometer](https://www.worldometers.info/coronavirus/country/us/), cases were 391.

[WHO](https://covid19.who.int/region/amro/country/us), cases were 117.

We also found a statement on [[NYT](https://screenshot.googleplex.com/Pbyo5eT3v2GCdUd)]

(https://www.nytimes.com/interactive/2021/us/covid-cases.html)  informing that the number of deaths decreased because Massachusetts removed many previously reported deaths on 14th March. 

Can you please confirm if this is the same reason for not getting updated data on 14th March? Please look into it and provide your insights.

**Comment by albertsun** [comment]
Yes, this is why we recommend people track the daily average number of deaths. Data is updated for all states individually as well.
