### ISSUE TITLE
MO Counties Missing Data starting April 1, 2022

### ISSUE THREAD

**Issue by msimkins7** [nytimes/covid-19-data#671]
My team does surveillance for counties in the St. Louis MSA and I noticed there is no updated data for the following Missouri counties starting 4/1/2022:  Warren, St. Louis City, Lincoln, Jefferson, Franklin.  Do you have any insights into why the other MSA counties (St. Louis, St. Charles) have updated data but the others don't?  I'm assuming it's related to some changes in the MO DHSS reporting or county-specific reporting frequency, but any additional information you can provide would be greatly appreciated!

**Comment by goodfeli** [comment]
Some other counties that quit updating on April 1, 2022 include: Santa Clara County, California; San Diego County, California; San Francisco County, California.

**Comment by msimkins7** [comment]
@albertsun Looks like we are getting data again on all Missouri counties.  Could someone speak to what changed, how the NYtimes is now getting the county-level data for Missouri?  I'm assuming you're relying on the state dashboard data? Thanks in advance!

**Comment by lwaananenjones** [comment]
Hi everyone: On Friday, April 1, Missouri [moved to a weekly data reporting schedule](https://governor.mo.gov/press-releases/archive/governor-parson-announces-end-covid-19-crisis-missouri) and stopped publishing cumulative counts for the state and counties. Here is the note that was on their data page at the time:
On Friday, April 1, 2022, Missouri will transition to a new phase of the COVID-19 pandemic response. The SARS-CoV-2 virus is expected to continue circulating in our communities and, therefore, will be considered endemic. The endemicity also means that surveillance priority will change from monitoring case numbers to monitoring disease severity and societal impact. To reflect these changes, the COVID-19 dashboard will transition to a new layout that will highlight specific data that will help public health leaders measure the impact and severity of COVID-19. Beginning April 1, 2022, the dashboard will be updated each Friday.

Some states that don't report cumulative counts on their own dashboards continue to report this data to the CDC. Missouri's weekly update to the CDC was lower than the state's March 30 update for the majority of counties, so we did not integrate that into our data until confirming that it was correct and followed the same methodology. Last week, we received confirmation from the state that the decreases were correct and the result of data cleaning, and the state also resumed publishing [cumulative data on its website](https://health.mo.gov/living/healthcondiseases/communicable/novel-coronavirus/data/public-health/data-download.php). We anticipate weekly Missouri updates on Friday going forward, and may implement a revision for the month of April using CDC data once we verify that this Friday's data comes in as expected.

When data is unavailable for unusual lengths of time, we include notes in our anomalies file that's included in the [rolling averages](https://github.com/nytimes/covid-19-data/tree/master/rolling-averages) dataset. Many states and local jurisdictions are reporting less frequently in 2022, so unfortunately there are sometimes unavoidable gaps between updates. That's the case for most California counties now that California updates only on Tuesdays and Fridays.
