### ISSUE TITLE
Data Issue:  us-counties-2022.csv is not updated daily

### ISSUE THREAD

**Issue by astrowonk** [nytimes/covid-19-data#674]
### Describe the issue:
 `us-counties-2022.csv` is not updating daily and it overlaps with regularly updated `us-counties-recent.csv`.

### Fuller details
 `us-counties-2022.csv` is not updating daily. It has data only through April 11th. Because this overlaps with `us-counties-recent.csv` this will create a de-duplication issues for anyone is trying to recreate a complete`us-counties.csv` dataset once that full file stops updating after hitting the 100MB github limit, per the README.

Can `us-counties-2022.csv` file please be updated daily with all 2022 data?

**Comment by albertsun** [comment]
Hi @astrowonk thanks for flagging this for us. We are taking a look.

**Comment by astrowonk** [comment]
> This file is now updating. For anyone following along, the original us-counties.csv file is now almost at or over the Github file limit and will soon stop updating.

Thank you! I updated my [repo](https://github.com/astrowonk/covid_dash) to use the yearly files when updating data for my [case dashboard](https://marcoshuerta.com/dash/covid/).

**Comment by astrowonk** [comment]
closing as @albertsun reports fixed!
