### ISSUE TITLE
Data Issue:  Stanislaus County, CA reporting 0 cases since March 25th.

### ISSUE THREAD

**Issue by mikelehen** [nytimes/covid-19-data#675]
### Describe the issue:
- [X] Incorrect number of cases or deaths
- [X] Suspicious number of cases or deaths

### Fuller details
Case data seems to have stopped updating since March 25 for [Stanislaus county](https://www.nytimes.com/interactive/2021/us/stanislaus-california-covid-cases.html):

![image](https://user-images.githubusercontent.com/206364/168382832-d602a0ba-be2d-438d-8cd4-6f332ba66011.png)

The [CA dashboard for Stanislaus](https://covid19.ca.gov/state-dashboard/#location-stanislaus) still shows cases:
![image](https://user-images.githubusercontent.com/206364/168382939-7b954b59-ff95-4e33-ae92-ee696a4632c3.png)

**Comment by tiffehr** [comment]
Yep, Stanislaus discontinued their reporting around 4/11, at `1,694` deaths and `119,328` confirmed cases.	

http://schsa.org/coronavirus/stats/
> COVID-19 Statistics
> Due to the wide use of at-home antigen tests (results unreported), local case data is a less valid tool for monitoring trends and will no longer be updated on this dashboard. For daily updates on confirmed cases and vaccine data, please visit [California COVID-19 Dashboard for Stanislaus County](https://covid19.ca.gov/state-dashboard/#location-stanislaus).

They now point to the state's data dashboard.  But they have not yet updated via the state, which is behind what Stanislaus last reported before they took their dashboard offline (`1,645` deaths, `118,586` confirmed cases).

https://public.tableau.com/views/COVID-19CasesDashboardv2_0/CaseStatistics?:embed=y&:showVizHome=no
![image](https://user-images.githubusercontent.com/60173/168500193-7164acf6-4f3c-41dd-9837-8c486a787fa4.png)

We don't have much control in this kind of situation, I'm afraid.

**Comment by mikelehen** [comment]
Thanks for the response!  What do you make of the fact that the CA dashboard is reporting new daily cases for Stanislaus County every day?  I hear you that it's strange that their total cumulative cases (118,586) is behind what the county dashboard used to show (136,645 I guess?), but is it possible the county dashboard had some methodology difference (including probably cases or a difference in using county of residence vs county of testing or something)?

Regardless, if the county is pointing people to use the state dashboard and the state dashboard is showing daily-updating data, wouldn't it make sense to just switch over to using the state dashboard data?  That probably means importing the historical timeseries so that there's not a disconnect, but that's hopefully doable?

Thanks for taking a look in any case.  Let me know if I'm not making sense.

**Comment by mikelehen** [comment]
Thanks again @tiffehr.  Sorry to keep nagging, but would it be possible to ingest the cumulative case timeseries data from https://data.ca.gov/dataset/covid-19-time-series-metrics-by-county-and-state (perhaps as a one-time backfill)?  Then you wouldn't need to do any math or change how you consider a "prior day."  You'd just need to do a one-time replacement of the previously-ingested county data cumulative case count timeseries with the state cumulative case count timeseries, and then you could go forward pulling the data from the state dashboard if that's the preferred mechanism.

Sorry if I'm missing something.  Also as a disclaimer, I haven't personally interacted with this CA dataset, but it seems to be official (from CA) and claims the data is from the state dashboard, so hopefully it's viable.

**Comment by tiffehr** [comment]
I'm afraid we can't ingest the state's cumulative timeseries data simply to clean up a week missing from Stanislaus. California's historical revisions to that timeseries may not match up with our day-by-day editorial decision-making process, where we needed to choose between multiple overlapping sources for each and every of CA's counties. Our (small) staff does a lot of manual methodology normalization that drives each day's review and approval of cumulative increases, including marking anomalous days and documenting the health department's state reason for them.

We do this for the entire country each day.

Our README has more about our methodology choosing to track cumulative figures _on the day announced_. We have to live with plateaus or staleness like Stanislaus is showing now.  Many counties now have this effect, as they change to weekly or bi-weekly updates to their counts. Full states, as well -- https://github.com/nytimes/covid-19-data/issues/671#issuecomment-1125125280

**Comment by mikelehen** [comment]
Thanks @tiffehr. I appreciate all the work NYT puts into this, which is why we are happy to rely on you and not have to replicate these efforts ourselves. 😁 

I'm confused by something you said though:

>  I'm afraid we can't ingest the state's cumulative timeseries data simply to clean up a week missing from Stanislaus.

I'm not sure what "a week" is referring to here. NYT has not had updated data for Stanislaus County for over 7 weeks (the last update was March 24th).  So this isn't an issue of weekly / biweekly reporting cadences, etc.  Did I misunderstand something?

**Comment by tiffehr** [comment]
No, I forgot to go back and lookup the length of the stall. But it would directly correspond to what the county itself reported, 4/11/22, in my original reply. The cadence of my tasks is often weekly, so I tend to only see the last 7 days of data in my diagnostics.

**Comment by mikelehen** [comment]
I'm not sure exactly what happened / changed, but it looks like NYT is reporting data again.

![image](https://user-images.githubusercontent.com/206364/168915430-9398b88c-d204-4bd4-86d8-b80184096c16.png)

Thanks very much for this!

**Comment by lwaananenjones** [comment]
Here's a little about this specific case, which was more complicated than a lot of our source transitions for a few reasons. If a county source announces that it's no longer reporting new data, we switch to the state data source — sometimes this is relatively seamless if the state is just a few days behind. In other cases when the county had a much higher cumulative count than the state, like this one, we then try to find out more about why (usually the reasons you described, like probable cases or how prison cases are allocated). 

In this case the county did continue to issue weekly reports through most of April, but the format didn't match up with the previously reported totals. At the same time, California decreased its cumulative counts for many counties (including Stanislaus) for several weeks in April, presumably from data cleaning related to the omicron surge earlier in the year. Since neither data source reported an increase in the county's cumulative count for most of April, we kept it on our watchlist and held off on changing sources. The state resumed more reliable updates during the last week of April, so we switched from county to state data at that time with a one-day decrease. We put that change into effect this week once we knew recent state data would reflect a reliable trend. We have a few ways to note on the tracker pages when a county is not reporting new data regularly, and in retrospect we would have done that in this situation if we'd known the issue would go on so long.

**Comment by mikelehen** [comment]
@lwaananenjones Thanks so much for the thorough explanation about what went on here and for getting it fully resolved.  It gives me added appreciation for all the work that goes on to maintain this data at a high quality.  Much appreciated! 🙏
