### ISSUE TITLE
I may have missed a note, but Data not updated for 5/14/2022?  

### ISSUE THREAD

**Issue by MirrorCola** [nytimes/covid-19-data#676]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources. Please check the README and recent commit messages for updates to see if your issue is addressed.

**Comment by MirrorCola** [comment]
Looks like live data may have been updated, but not 'base' files?

**Comment by albertsun** [comment]
@MirrorCola we will update this shortly. At this point the us-counties.csv file has grown too large for github so it will only be the year based county files from now on.

**Comment by dawenx** [comment]
@albertsun The nightly auto update failed for some reasons? Can you take a look? Thanks.

**Comment by mikelehen** [comment]
FWIW- us-counties-2022.csv doesn't have data for 5/14 either.  But live/us-counties.csv does.  Not sure if that's expected?

**Comment by albertsun** [comment]
Thanks all for raising these as you see them. Now that we aren't updating the us-counties.csv file any more we're hoping there will be no issue with tonight's update.
