### ISSUE TITLE
Announcement: Removing confirmed and probable data

### ISSUE THREAD

**Issue by albertsun** [nytimes/covid-19-data#678]
Hi all, or at least all who follow these issues.

We are planning to update our data format to remove the distinction between `confirmed` and `probable` cases and deaths since that distinction has become much much less meaningful in the data now being reported.

That would mean eliminating fields for `confirmed_cases`, `probable_cases`, `confirmed_deaths` and `probable_deaths`, and using only `cases` and `deaths` throughout.

We don't want to break backwards compatibility for people though, and are not sure all the current ways that people are using these sets of fields.

Are you using those fields?  Would this cause issues for you? Either way, please let us know here or in an email.

**Comment by albertsun** [comment]
This update has now been done.

**Comment by Playfrog4u** [comment]
I do use these fields.. I display them alongside the cases & death numbers in my app for local stats, state stats, and US stats.

**Comment by tiffehr** [comment]
@Playfrog4u Apologies, but we removed these more than a month ago.  You may need to update your app to our latest fields.
