### ISSUE TITLE
No update for June 16th?

### ISSUE THREAD

**Issue by MirrorCola** [nytimes/covid-19-data#679]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources. Please check the README and recent commit messages for updates to see if your issue is addressed.

**Comment by dawenx** [comment]
@albertsun Hi Albert, can you take a look on this? Many thanks as always.

**Comment by SomervilleTom** [comment]
Any status updates will be appreciated!

Looks like `us-counties-2022.csv` is stuck:
`
us-counties-2022.csv Updating data. 2 days ago
`

**Comment by tiffehr** [comment]
Sorry, for the delay, we are short-staffed this week and ran into an edge-case with internal publishing mechanisms.  Now resolved;  the `us-counties-2022.csv` is updated as of c39ce2032ca9c749d30e65a05111c4004d587d62.
