### ISSUE TITLE
Missing entry for 2020-03-26 Hancock County, West Virginia

### ISSUE THREAD

**Issue by behrman** [nytimes/covid-19-data#68]
You do not have an entry for 2020-03-26 for Hancock County West Virginia, though you have entries for 2020-03-25 and 2020-03-27. Assuming the data for those two dates are correct, we can infer the value for 2020-03-26 to be:

cases: 1
deaths: 0

**Comment by albertsun** [comment]
Hi @behrman thanks for flagging this. It appears the case originally announced on 3/25 for Hancock was reassigned to Jefferson County, Ohio (https://dhhr.wv.gov/News/2020/Pages/COVID-19-Daily-Update.aspx)

We'll remove the 1 case on 3/25 from Hancock in the next release.

**Comment by albertsun** [comment]
This is now corrected.
