### ISSUE TITLE
Data Issue: Connecticut completely revised their reporting and formats. No new data today.

### ISSUE THREAD

**Issue by joecascio** [nytimes/covid-19-data#683]
For whatever reason, Connecticut (where I live) revised their reporting formats. My scripts don't work anymore on their town data. I'm guessing this is why there is no new data from Connecticut at the state or county level..

**Comment by tiffehr** [comment]
Thank you for flagging this. We'd done a few manual updates, but failed to notice [a table-reorg message](https://data.ct.gov/Health-and-Human-Services/COVID-19-Tests-Cases-Hospitalizations-and-Deaths-S/rf3k-f8fg) on their OpenData portal.  
> Note: DPH is updating and streamlining the COVID-19 cases, deaths, and testing data. As of 6/27/2022, the data will be published in four tables instead of twelve.

It seems the prior [endpoints are still up](https://data.ct.gov/resource/bfnu-rgqt.json?$order=dateupdated%20desc&$limit=9), but now stale.  Just migrated our scraper to the new endpoints -- [like this one](https://data.ct.gov/resource/qmgw-5kp6.json?$order=report_date%20desc&$limit=1) -- and today's data should have the latest.  We'll discuss whether it's worth backdating that jump.
