### ISSUE TITLE
Data Issue: Negative deaths = resurrections?

### ISSUE THREAD

**Issue by LucCappellaro** [nytimes/covid-19-data#684]
### Describe the issue:
- [ x] Incorrect number of cases or deaths

### Fuller details
This file contains -2435 deaths on 2022-03-14.
https://github.com/nytimes/covid-19-data/blob/master/rolling-averages/us.csv#L785
It was introduced by commit f5da130de7b09e7efe6cb46f6f28e6290e4c423d.

**Comment by tiffehr** [comment]
@LucCappellaro Our README explains some of the potential complications that come with how states, counties and countries independently maintain their case counts. One source is historical revisions, as different health departments reassess backlogged tests, death certificates and other materials that inform their cumulative counts. 

Local health departments often report these revisions and we collect, assess and add them in our [living list of known anomalies](https://github.com/nytimes/covid-19-data/blob/master/rolling-averages/anomalies.csv).  I recommend checking any irregular counts you see against that list, to get a fully informed picture of changes.  

In this specific case, it looks like Massachussetts made a change that shows up in the anomalies.csv as well as on our national and state-specific pages:
https://www.nytimes.com/interactive/2021/us/massachusetts-covid-cases.html
![image](https://user-images.githubusercontent.com/60173/180665527-31ad2b38-d171-4a03-a742-a9c847ce930e.png)
