### ISSUE TITLE
Question:  0 Cases for weekends

### ISSUE THREAD

**Issue by nickybisht** [nytimes/covid-19-data#687]
![image](https://user-images.githubusercontent.com/90417853/183712330-aec3c5f4-1157-4070-adca-658557e07c03.png)

Seems like data for weekend is not getting updated. PTAL

**Comment by albertsun** [comment]
Hi @nickybisht yes that is due to the underlying reporting schedule from the public health agencies that data is sourced from and is expected. In other places data may be reported only certain days a week or even less frequently.
