### ISSUE TITLE
Data Issue:  Missing data from St. Louis County, MO since August 5th 2022.

### ISSUE THREAD

**Issue by luonglh** [nytimes/covid-19-data#688]
### Describe the issue:
Data from St. Louis County, MO has been missing since August 5th 2022. I checked the St. Louis County COVID-19 dashboard and noticed that data is still been updated there. Not sure why the data is not updated in the NYT dataset.

**Comment by lwaananenjones** [comment]
Thank you for writing to us about this — we're hoping to have an additional update for 8/5/22-8/15/22, but will have new data for St. Louis County as of 8/16/22.

**Comment by luonglh** [comment]
Thank you for fixing the data.
