### ISSUE TITLE
No data for 9/27/2022 at 7 am EDT?  

### ISSUE THREAD

**Issue by MirrorCola** [nytimes/covid-19-data#690]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources. Please check the README and recent commit messages for updates to see if your issue is addressed.

**Comment by tiffehr** [comment]
@MirrorCola A specific geography is missing, or an expected refresh of this GitHub repo's active files?

**Comment by MirrorCola** [comment]
An expected refresh, e.g. the us file does not include yesterday's data and I assume all daily files are similar.  Update is listed as "2 days ago."

**Comment by ddenenberg71** [comment]
us-counties-2022.csv and us-states.csv we’re not updated at all today as
they usually are.

**Comment by albertsun** [comment]
Thanks y'all for flagging this — we're looking into it.

**Comment by albertsun** [comment]
Should be resolved now!
