### ISSUE TITLE
Data Issue: San Francisco spike likely a data anomaly

### ISSUE THREAD

**Issue by bredcrumbs2** [nytimes/covid-19-data#691]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [x] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
The data for San Francisco County, CA, on Sept. 29 shows an increase of 1,415 from the previous week. During that week, the San Francisco County health department [announced](https://sf.gov/data/covid-19-cases-and-deaths) that it had added 1,400 cases from throughout September to its case totals after it identified a California Department of Public Health data processing error. That strongly suggests that the Sept. 29 increase should be marked as a data anomaly.

**Comment by albertsun** [comment]
@bredcrumbs2 thanks, we will take a look

**Comment by wmandrews** [comment]
Logged as an anomaly
