### ISSUE TITLE
Data Issue:  Missing Cases Data in Jefferson County, KY (FIPS: 21111)

### ISSUE THREAD

**Issue by BrettBoval** [nytimes/covid-19-data#692]
### Describe the issue:
- [X] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [X] Missing data for a locality
- [X] Missing time-series information
- [ ] Other

### Fuller details
Case data for Jefferson County, KY (fips 21111) appears to stop October 10th. Data for other counties in Kentucky continues to be reported. A quick google search in the news does not show anything that would easily explain the discrepancy.
<img width="772" alt="image" src="https://user-images.githubusercontent.com/20585842/199375967-37a2e8b5-99ee-43a9-8754-fd982f22e3c4.png">

That data, at least in weekly form, continues to be shown at the CDC Covid Tracker site.
<img width="812" alt="image" src="https://user-images.githubusercontent.com/20585842/199376020-46950e4c-2f0a-4aac-96d0-c5324703e543.png">

**Comment by mikelehen** [comment]
This seems to still be an issue.  https://www.nytimes.com/interactive/2021/us/jefferson-kentucky-covid-cases.html is showing no new cases since Oct 10, but https://covid.cdc.gov/covid-data-tracker/#county-view?list_select_state=Kentucky&data-type=CommunityLevels&list_select_county=21111 shows new cases as of Nov 5.

Is it possible to take a look?

**Comment by tiffehr** [comment]
@mikelehen We're continuing to look into it.  The county stopped updating their dashboard mid-October, which is why our data paused then.  Correcting the gap since is not an easy task.

**Comment by mikelehen** [comment]
Thanks for the update @tiffehr !

**Comment by tiffehr** [comment]
@mikelehen Thank you for your patience.  Alongside some other larger adjustments, we backfilled Jefferson County today:  https://www.nytimes.com/interactive/2021/us/jefferson-kentucky-covid-cases.html

Reopen if you still see issues!
