### ISSUE TITLE
Several states and counties appear to show a spike in the death count during the week from 11/6 to 11/12.  Is that an artifact in my calculations or is something else going on?

### ISSUE THREAD

**Issue by MirrorCola** [nytimes/covid-19-data#693]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources. Please check the README and recent commit messages for updates to see if your issue is addressed.

**Comment by MirrorCola** [comment]
Looks like you've noted 11/11/22 as anomalous for deaths in many counties.  Any comments on what the cause is?

**Comment by raagnew** [comment]
Bust in US death count is on Nov 11.
date | cases | deaths | daily deaths
11/7/2022 | 97515911 | 1068574 |  
11/8/2022 | 97537052 | 1068787 | 213
11/9/2022 | 97630738 | 1069707 | 920
11/10/2022 | 97718587 | 1070288 | 581
11/11/2022 | 97729911 | 1083006 | 12718 <<
11/12/2022 | 97732486 | 1083008 | 2
11/13/2022 | 97734440 | 1083009 | 1
11/14/2022 | 97785361 | 1083181 | 172
11/15/2022 | 97818425 | 1083484 | 303
11/16/2022 | 97903783 | 1084197 | 713
11/17/2022 | 97986304 | 1084623 | 426
11/18/2022 | 98038669 | 1085139 | 516
11/19/2022 | 98042166 | 1085150 | 11

**Comment by albertsun** [comment]
Hi all,

Yes, as noted in our [anomalies file](https://github.com/nytimes/covid-19-data/blob/master/rolling-averages/anomalies.csv#L1745) we started including deaths reported by a new source, the CDC's [NCHS](https://www.cdc.gov/nchs/nvss/covid-19.htm) which collects death certificates and now reports out the number of Covid deaths per-county by county of residence. This let us identify a large number of counties where it appeared the number of deaths reported by county and state officials were under counted. In those cases where they had reported fewer deaths than CDC we are now using the higher CDC reported number of deaths.

**Comment by MirrorCola** [comment]
Thanks for the explanation, I saw the anomalies file but didn't understand the cause.  As far as I'm concerned this item can now be closed.

Once again, I appreciate all of the work so many of you are doing to compile this and for you to be so responsive.

**Comment by raagnew** [comment]
I also appreciate the data y'all have compiled since the inception of this
pandemic.  Trendline distortion should be temporary.

Bob Agnew
