### ISSUE TITLE
Data Issue:  Snafu with us-counties data?

### ISSUE THREAD

**Issue by SomervilleTom** [nytimes/covid-19-data#697]
### Describe the issue: ###

The `us-counties-2022.csv` file is described as "updating". I find no `us-counties-2023.csv` file in the repo.

### Fuller details

Starting in 2022, the us-counties data was broken into a different file for each year. If this convention is to continue, then the data for 2023 should be added to a file named `us-counties-2023.csv`. I see no such file in the repo yet. The repo says that the `us-counties-2022.csv` file was last updated yesterday.

While it's not a big deal, my project ingests this data each day automatically using `cron`. I had configured the ingestor to use the filename for the new year and, not surprisingly, it failed.

I invite guidance as to whether this issue will correct itself tomorrow. If not, then I'll need to take other steps accordingly.

I appreciate all the effort the entire team has been investing in this during the pandemic. Please let me know if there's any way I can help.

**Comment by albertsun** [comment]
Hi @SomervilleTom yes, that us-counties-2023.csv file will be added shortly.

**Comment by tiffehr** [comment]
It's [here](https://github.com/nytimes/covid-19-data/blob/master/us-counties-2023.csv)!
