### ISSUE TITLE
Need total number of tests in each county, as well as total positive tests.

### ISSUE THREAD

**Issue by leerosenthalj** [nytimes/covid-19-data#70]
This is great, thank you! But the data isn't particularly useful without being able to compute the fraction of positive tests, which we can't do without the total number of tests. I know not all counties are supplying that data, but can you include it for the counties that do?

**Comment by laura03062** [comment]
I agree. Knowing if the virus is circulating in a specific county  important to public safety. Residents will take the stay at home order more seriously.

**Comment by albertsun** [comment]
@leerosenthalj For this data release we focused on consistent, nationwide county-level data for cases and deaths. As you point out, testing data is not consistently available.

There are other efforts to collect that data, which we hope will improve over time. In particular, the Covid Tracking Project https://covidtracking.com/ seems to be doing a good job of collecting data on testing at the state level and we’ve used their data in at least one of our articles here: https://www.nytimes.com/interactive/2020/03/17/us/coronavirus-testing-data.html
