### ISSUE TITLE
Data Issue:  Dates with negative case numbers and deaths.

### ISSUE THREAD

**Issue by Jonathan-Nyquist** [nytimes/covid-19-data#700]
### Describe the issue:
- [] Incorrect number of cases or deaths
- [X ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
In the data set rolling-averages/us.csv there are days with a negative number of cases, and what is more disturbing: negative deaths   (Reincarnation? Covid induced zombies?)  
![zombies](https://user-images.githubusercontent.com/103674665/214957544-28eabe6f-3ad7-4002-9cb5-aff6e670df98.jpg)

**Comment by tiffehr** [comment]
@Jonathan-Nyquist Thanks for the clear example here.  What you're seeing is probably the result of a downward-revised count of deaths from one or more of our sources, which often happens when local health departments or other officials realized they had duplication or other death-certification challenges. Our [README that lives alongside our rolling-average files](https://github.com/nytimes/covid-19-data/tree/master/rolling-averages#cases-and-deaths-rolling-averages-and-anomalous-days) has a deeper explanation of our methodology and [how we judge anomolous entries](https://github.com/nytimes/covid-19-data/tree/master/rolling-averages#anomalies-methodology) in our data set and its calculated figures.
> Identified anomalies are often because of officials making revisions to improve the overall quality of the data they have released. Many small anomalies due to backlogs of cases or minor revisions of previously announced numbers are not included here, particularly at the county level. There are no listed anomalies from very early in the pandemic. When deciding whether to list an anomaly, we judge whether a member of the public would need that note to understand and put in context that day’s case or death count.

You can search our [list of anomalies](https://github.com/nytimes/covid-19-data/blob/master/rolling-averages/anomalies.csv) here in GitHub for the dates in your example, using its filter mechanism.
![image](https://user-images.githubusercontent.com/60173/215167602-12d50522-0d71-438e-9435-fed3e0f42009.png)

**Comment by Jonathan-Nyquist** [comment]
Thanks, glad to hear the negative deaths don't herald the coming of the Covid 19 zombie apocalypse.
________________________________
From: Tiff Fehr ***@***.***>
Sent: Friday, January 27, 2023 1:37 PM
To: nytimes/covid-19-data ***@***.***>
Cc: Jonathan Nyquist ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [nytimes/covid-19-data] Data Issue: Dates with negative case numbers and deaths. (Issue #700)


@Jonathan-Nyquist<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJonathan-Nyquist&data=05%7C01%7Cjonathan.nyquist%40temple.edu%7C1f8700b5a196470dc99a08db009591a4%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C638104414646730121%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Ff1yWGjGhpIHSRtj4XaBzgCmfGEQDi41z4zMEmCPKzg%3D&reserved=0> Thanks for the clear example here. What you're seeing is probably the result of a downward-revised count of deaths from one or more of our sources, which often happens when local health departments or other officials realized they had duplication or other death-certification challenges. Our README that lives alongside our rolling-average files<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnytimes%2Fcovid-19-data%2Ftree%2Fmaster%2Frolling-averages%23cases-and-deaths-rolling-averages-and-anomalous-days&data=05%7C01%7Cjonathan.nyquist%40temple.edu%7C1f8700b5a196470dc99a08db009591a4%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C638104414646730121%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2B7%2BDk9%2BE8emZA0Nm%2F3WX87QVeF2%2BLVa2G9A7tElGFQU%3D&reserved=0> has a deeper explanation of our methodology and how we judge anomolous entries<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnytimes%2Fcovid-19-data%2Ftree%2Fmaster%2Frolling-averages%23anomalies-methodology&data=05%7C01%7Cjonathan.nyquist%40temple.edu%7C1f8700b5a196470dc99a08db009591a4%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C638104414646730121%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Jibvdk%2FmBzQ1mZa4MsNiSSO1eYlDcbddKEoeTa%2Ft%2Fk4%3D&reserved=0> in our data set and its calculated figures.

Identified anomalies are often because of officials making revisions to improve the overall quality of the data they have released. Many small anomalies due to backlogs of cases or minor revisions of previously announced numbers are not included here, particularly at the county level. There are no listed anomalies from very early in the pandemic. When deciding whether to list an anomaly, we judge whether a member of the public would need that note to understand and put in context that day’s case or death count.

You can search our list of anomalies<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnytimes%2Fcovid-19-data%2Fblob%2Fmaster%2Frolling-averages%2Fanomalies.csv&data=05%7C01%7Cjonathan.nyquist%40temple.edu%7C1f8700b5a196470dc99a08db009591a4%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C638104414646730121%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=clDx02xPWjODDLxQD4NIjHKuf0vRYrRFatjknMh6XxU%3D&reserved=0> here in GitHub for the dates in your example, using its filter mechanism.
[image]<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F60173%2F215167602-12d50522-0d71-438e-9435-fed3e0f42009.png&data=05%7C01%7Cjonathan.nyquist%40temple.edu%7C1f8700b5a196470dc99a08db009591a4%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C638104414646730121%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JBsy%2FTHitmW1Ud4SVlnUCQago9y6w6RyYXEwtRxcJR0%3D&reserved=0>
