### ISSUE TITLE
Data Issue: "Your connection is not private" message

### ISSUE THREAD

**Issue by vlad391** [nytimes/covid-19-data#703]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [X] Other

Hello, whenever I try to access the "https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv" link, I get an error message in both Chrome and Edge saying that "Your connection is not private" (NET::ERR_CERT_COMMON_NAME_INVALID). Perhaps this is just an issue on my end?

![image](https://user-images.githubusercontent.com/73789538/227639420-0b12793a-25a9-4aeb-8bf3-dc822777ef82.png)

**Comment by ddenenberg71** [comment]
This issue is affecting all repos, not just this one.

**Comment by tiffehr** [comment]
Yep, the issue was with GitHub's certificate, which I believe they have since updated.  We can do little about that.
