### ISSUE TITLE
SECURITY Data Issue:  

### ISSUE THREAD

**Issue by Ulfat3215** [nytimes/covid-19-data#706]
### Describe the issue:
- [x] Incorrect number of cases or deaths
- [x] Suspicious number of cases or deaths
- [x] Missing data for a locality
- [x] Missing time-series information
- [x] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources. Please check the README and recent commit messages for updates to see if your issue is addressed.

**Comment by tiffehr** [comment]
@Ulfat3215 Did you mean to open two new Issues on this repo (this and https://github.com/nytimes/covid-19-data/issues/705)?  

If so, it seems the link you provided is not working for me to better understand what data-related problem you want to report here.

**Comment by tiffehr** [comment]
Closing, since we're not sure what's being reported as a potential security issue here.
