### ISSUE TITLE
Mapping County FIPS Codes

### ISSUE THREAD

**Issue by openbrian** [nytimes/covid-19-data#71]
I started building a map of the cases by county per capita.  I get the population data from Census.  The FIPS county codes are not lining up well.  Any idea?

Here's the eastern half of the US https://raw.githubusercontent.com/openbrian/covid-19-map-by-region/master/us_east.png

**Comment by bohm0072** [comment]
FIPS codes have two components - state FIPS code (2 digit) and county FIPS code (3 digit).

"FIPS codes are numbers which uniquely identify geographic areas.  The number of 
digits in FIPS codes vary depending on the level of geography.  State-level FIPS
codes have two digits, county-level FIPS codes have five digits of which the 
first two are the FIPS code of the state to which the county belongs."
(see https://transition.fcc.gov/oet/info/maps/census/fips/fips.txt)

**Comment by openbrian** [comment]
The issue was, not every county is represented in the covid data.  Only the counties with cases or deaths are there.

This was leading to what looked like gaps, but really is just zeros.

Now the combining of 5 counties to form NYC, is a separate issue, along with the other exceptions.
