### ISSUE TITLE
break NYC data by county/borough

### ISSUE THREAD

**Issue by brambow** [nytimes/covid-19-data#73]
The "county" data for New York City is currently provided as a single NYC record, with no FIPS which causes problems for wanting to join this to county GIS data boundaries and demographics:

![image](https://user-images.githubusercontent.com/6227786/77850289-69622580-719f-11ea-9ce4-86beea48f48f.png)

![image](https://user-images.githubusercontent.com/6227786/77850296-78e16e80-719f-11ea-95e1-10bc80464e96.png)

Why not provide the individual counties and FIPS codes for NYC?

**Comment by InformationForHumans** [comment]
Followup question: is it NYC that is combining or is it the NYT? If NYT, agree, it would help to break this out.

**Comment by brambow** [comment]
The data NYC provides daily is broken into boroughs: https://www1.nyc.gov/assets/doh/downloads/pdf/imm/covid-19-daily-data-summary.pdf

Before I started using the NYT dataset, I was using county-level data from https://usafacts.org/visualizations/coronavirus-covid-19-spread-map/, which also broke it into the 5 boroughs.  NYT's data is in an easier format to ingest and update though, so it'd be nice if they also provided the detailed borough data.

**Comment by StevenLi-DS** [comment]
usafacts now have it:
https://usafacts.org/visualizations/coronavirus-covid-19-spread-map/
![image](https://user-images.githubusercontent.com/33796896/77855275-5b230200-71bd-11ea-905d-89d5568dfe24.png)

**Comment by arenn** [comment]
The data set is great and highly usable, but the lack of NYC borough/county values is a major problem for many toolchains. Would greatly appreciate a breakdown by NYC county. Thanks!

**Comment by StevenLi-DS** [comment]
Seems like nytimes has it. 

https://www.nytimes.com/interactive/2020/04/01/nyregion/nyc-coronavirus-cases-map.html?referringSource=articleShare
