### ISSUE TITLE
Specify timezone

### ISSUE THREAD

**Issue by kmatarese** [nytimes/covid-19-data#77]
First off thanks for putting this together.

I'm trying to join this together with other open data sources, but it's unclear whether the date in your time series file has any specific timezone associated. From the readme it sounds like it may be the timezone of the geographic location, meaning the dates are all different time zones depending on the time zone of the data source.

If it's possible to do everything in UTC (or if it already is) that would be great.

**Comment by albertsun** [comment]
Hi @kmatarese, the data for each date corresponds to the situation at the end of that day in the U.S. — we usually consider that to be around 4 a.m. ET. So far, states and counties only seem to update their cases count announcements during their local day, we haven't really been seeing any middle of the night updates that would change the numbers. Does that help?

**Comment by kmatarese** [comment]
Thanks for clarifying @albertsun . 

The differences in counts due to time zone issues will be pretty minor as you noted due to the way things are being reported. It would only cause issues when trying to roll your data up by date to less granular geos and comparing to numbers from other data sources (such as the JHU time series data which is in UTC). I'll ignore any discrepancies for now.
