### ISSUE TITLE
Discrepancy for NYC confirmed cases

### ISSUE THREAD

**Issue by albertc44** [nytimes/covid-19-data#78]
I've been tracking NYC data on a dashboard I've built and I've noticed that there are discrepancies between the number of positive cases for NYC county as reported by [New York State's Department of Health website](https://coronavirus.health.ny.gov/county-county-breakdown-positive-cases) and NYC's own [health reporting website](https://www1.nyc.gov/site/doh/covid/covid-19-providers.page) (see the "Daily Data Summary" PDF for "Total Cases"). 

I've been relying on the NYC health website to get daily case numbers, and then using the NY State's data for all other counties in NY State. I did a quick spot check on the NYC county number and noticed that sometimes it's consistent with NYC health's website but other times it was undercounting (presume it was using the NY State data). Are you relying on NY State or NYC's data for the confirmed cases for NYC county?

**Comment by albertsun** [comment]
Hi @albertc44 we're relying on New York State data for now.

New York State reports data for New York City as a single entity. The city has been reporting data by borough separately, but we are still checking to see that the way it reports cases is consistent with how cases are reported across the rest of the dataset before integrating borough-level numbers into our dataset.
