### ISSUE TITLE
If a county is not listed, can we assume it's 0 cases and 0 deaths

### ISSUE THREAD

**Issue by openbrian** [nytimes/covid-19-data#79]
If so, please update documentation.  I did not see that mentioned.

**Comment by albertsun** [comment]
Yes, that's correct. Counties with 0 cases and 0 deaths are not listed.

**Comment by wiredII** [comment]
This should be stated "known" cases... As there have been more untested yet.

**Comment by openbrian** [comment]
Let's keep this open until the readme is updated
