### ISSUE TITLE
Harris County Texas is too low

### ISSUE THREAD

**Issue by kbeckner24** [nytimes/covid-19-data#81]
Number shown for Harris County Texas is the same as what is on the county public health website.  However, that number does not include the testing done by the City of Houston.  That can be found on the City of Houston emergency website.

**Comment by albertsun** [comment]
@kbeckner24 Thanks for pointing this out. We have been adding the values for City of Houston and Harris County, but due to a data entry error we had the wrong value for 3/28. We'll amend this in the next release.

**Comment by albertsun** [comment]
This is now corrected.
