### ISSUE TITLE
County time series graphs

### ISSUE THREAD

**Issue by jlgallup** [nytimes/covid-19-data#85]
We have created a [website](https://sgallup.shinyapps.io/covidshiny/) to display COVID-19 County or State time series graphs selected by the user, using the NYT archive. Thanks to the Times for sharing it. Please have a look if you are interested and point out any problems you find. 

John Gallup

**Comment by aanand08** [comment]
@jlgallup, this is great and thanks for doing this. Not sure of backend programming you have done but i created a R and shiny flexdashboard to look at cases by state and county over time. Unfortunately dont have a way to post it online so let me and I can share the code with you. 

I would also suggest looking at new cases and deaths by date as its gives an accurate picture of the growth of the epidemic or the inflection point at which the curve changes direction.

**Comment by aanand08** [comment]
meant more specifically to put new cases in different chart than cumulative as will show trend better

**Comment by adriancotter** [comment]
Doing something similar, but using log scale, and then comparing that to state and the united states
http://www.nonsensical.com/covid-19/county-trendlines.html

**Comment by rscohn2** [comment]
Thanks for sharing.  Now I know to stop working on my version with boring PNG's: http://covid-county.appspot.com/

**Comment by John-Jackson99** [comment]
I created a Power BI dashboard with a few interesting views.
Combined with 2010 census data to a better understanding of transmission vs density.
https://app.powerbi.com/groups/me/reports/ece614d8-5b5f-4b57-8b15-c265603653cd/ReportSection97c53e279385689a4bca

**Comment by adriancotter** [comment]
Is there a public view of that, John-Jackson99? It was asking to login.

I saw this video today, which is leading me to do some reworking of my graphs (not plotting against time)
https://digg.com/video/coronavirus-exponential-growth-graph?utm_source=digg&utm_medium=email

**Comment by willson556** [comment]
Had a go at an interactive dashboard over the holiday weekend. It's live at https://data.thomasewillson.com. Source is at https://github.com/willson556/covid-dashboard.

**Comment by tiffehr** [comment]
@willson556 and others:  I'd recommend submitting separate `example` Issues for these independently, so we can make sure they're individually collected in our Examples area on the Project board.  Happy to see the thread here, too, but I want your work to shine on its own.
