### ISSUE TITLE
All death counts are zero

### ISSUE THREAD

**Issue by lsylvain** [nytimes/covid-19-data#87]
Do you plan to update and maintain the deaths column values?

**Comment by BrentBradburn** [comment]
@lsylvain, I don't think you're looking at the data correctly -- the deaths are there.
In the early data, the deaths are zero.  This changes as time goes forward.
In the county data, even now (thankfully), many/most counties have zero deaths.

**Comment by aanand08** [comment]
@lsylvain, the deaths like cases is cumulative in the column.

**Comment by albertsun** [comment]
Thanks @BrentBradburn @aanand08, you are correct.

@lsylvain please check again and if there are specific 0s you are concerned about re-open and let us know.
