### ISSUE TITLE
WA state changed the reporting format of their page

### ISSUE THREAD

**Issue by rainiernate** [nytimes/covid-19-data#89]
The scrapers might not report correctly with the new format starting around 9p on 3/29/2020. The cases / deaths table has now been embedded in a Microsoft Business Tools applet. Have a look:

https://www.doh.wa.gov/emergencies/coronavirus

<img width="802" alt="Screen Shot 2020-03-29 at 9 06 49 PM" src="https://user-images.githubusercontent.com/13302862/77876616-5899ca00-7208-11ea-96a2-8f0715b45ea0.png">

**Comment by albertsun** [comment]
Thanks for letting us know @rainiernate ! Our team is on it now.
