### ISSUE TITLE
Add hospitalizations

### ISSUE THREAD

**Issue by PhilMiller** [nytimes/covid-19-data#9]
Confirmed case counts are skewed by how many tests get run, and who gets tested, both of which differs wildly across the country.

The number of people in a place hospitalized for COVID is a steady estimator for the total number of active infections in that place that have progressed to severe symptoms, which is expected to be a steady fraction of total infections. This is very useful for finer-grained forecasting purposes, as is being done using https://github.com/CodeForPhilly/chime/

Under normal circumstances, we would expect the CDC to gather, collate, and release this kind of information, and even make the forecasts using an in-house team and distribute them. Instead, we see individual hospitals scrambling to pull something together themselves.

Please try to collect this data where possible, and use your connections and clout to get it more consistently released.

**Comment by brownrw8** [comment]
Was curious about this as well

**Comment by alexgenaud** [comment]
total tests (or negative) and ICU rates would be valuable as well.

**Comment by ronaldgbennett** [comment]
Agree.  Case counts need to be referenced to the percent of population that has been tested - at a minimum.  Hospitalizations is more solid.  But deaths are also a solid measure, although with limited numbers to date.  Deaths by date are already in the raw data, but difficult to extract.  Charts like that shown below, taken from the raw data today showing growth in the daily death rate by county, would be helpful:

![Deaths by County](https://user-images.githubusercontent.com/62771947/77797534-790e2c80-702e-11ea-857f-6abef1950cf1.jpg)

**Comment by ronaldgbennett** [comment]
Here is a more complete chart including the top twelve worst counties, all normalized to the first reported death.  Until the case numbers data can be normalized to the percent of population tested, these death charts are probably the best way to assess if mitigation strategies are working or not.

![Deaths by County](https://user-images.githubusercontent.com/62771947/77807688-d497e480-7045-11ea-88f9-4f417c3a7359.jpg)

**Comment by amcdavid** [comment]
> total tests (or negative) and ICU rates would be valuable as well.

This is one resource for numbers tested https://docs.google.com/spreadsheets/u/2/d/e/2PACX-1vRwAqp96T9sYYq2-i7Tj0pvTf6XVHjDSMIKBdZHXiCGGdNC0ypEU9NbngS8mxea55JuCFuua1MUeOj5/pubhtml#
