### ISSUE TITLE
Please add form of social distancing and dates enacted by county

### ISSUE THREAD

**Issue by sanielfishawy** [nytimes/covid-19-data#92]
That way we can determine the effectiveness of various forms of social distancing.

**Comment by nickblink** [comment]
I recommend looking at this source for social distancing measures: https://www.kff.org/report-section/state-data-and-policy-actions-to-address-coronavirus-sources/

For the above, I copied this into a plain text file and then processed them using the R script attached

[demo_curating_US_social_distancing.zip](https://github.com/nytimes/covid-19-data/files/4404882/demo_curating_US_social_distancing.zip)

**Comment by albertsun** [comment]
Hi @sanielfishawy,

We've published an article rounding up when different areas have issue stay at home orders.

We hope people will analyze this and other data in many ways, but at this time we’re not releasing other datasets.
