### ISSUE TITLE
Release the data under a free license

### ISSUE THREAD

**Issue by kaldari** [nytimes/covid-19-data#94]
Right now, this data is provided under a vague, custom-made, and rather restrictive license. If you want to help the world right now, the biggest thing you could do would be to release this data under a real free license such as Creative Commons Attribution, Creative Commons Zero, or Creative Commons Attribution-ShareAlike. That would allow it to be reused by places like Wikipedia, Wikidata, Google, Wolfram Alpha, etc. and reach a much larger audience.

**Comment by dlobo** [comment]
+1 to kaldari's comments. Please dont create yet another custom license.

**Comment by codypiersall** [comment]
Related to (duplicate of?) #12 and #10.

**Comment by albertsun** [comment]
@kaldari We've updated our README.md to clarify that we consider the LICENSE we posted this under to be co-extensive with and equivalent to the CC BY-NC license.

**Comment by kaldari** [comment]
@albertsun - Thanks for clarifying it!
