### ISSUE TITLE
Incremental Daily Totals by Discrete County & State

### ISSUE THREAD

**Issue by rcweinbe** [nytimes/covid-19-data#96]
It would be great to see incremental values (new cases by county and state) so the data was more usable in summary without needing data transformations to calculate growth rates.

**Comment by sdetweil** [comment]
its pretty easy to calculate one from the other..  I have two sources..
one gives incremental only, this one gives cumulative only.

**Comment by rcweinbe** [comment]
I added a measure to my Power BI dashboard so I’m all set. Really was just thinking of any rookie analysts out there that may be bringing the data into views and trying to do quick sums and the like. Thanks Sam!
