### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by dashdotdotdashdotdot** [nytimes/covid-19-data#99]
Would be great to get an update.  Possible to add county population to the data?

**Comment by Cryowatt** [comment]
This is available on Wikipedia if you need it. I don't think it's fair to ask the author of this repo to do all this unrelated research on your behalf.

**Comment by John-Jackson99** [comment]
I have posted a 2019 estimated population dataset.
Includes housing and pop density
data has been normalized to the NYT data.
State-County is used as the index key
John
https://github.com/John-Jackson99/COVID-19-Data

**Comment by albertsun** [comment]
Thanks @John-Jackson99.

@dashdotdotdashdotdot hope that works for you
